// San Francisco Bay Area Cash-Pay Clinics Data
// Last Updated: January 2026
// Regions: San Francisco, Peninsula, South Bay, East Bay

export interface LocalClinic {
  name: string;
  slug: string;
  category: 'dexa' | 'vo2' | 'iv' | 'longevity' | 'performance' | 'labs' | 'wellness';
  address?: string;
  neighborhoods: string[];
  region: string;
  subRegion: string;
  priceRange: string;
  services: string[];
  description: string;
  highlights: string[];
  bestFor: string;
  website: string;
  phone?: string;
  rating?: number;
  reviewCount?: number;
  reviewSource?: string;
}

export interface BayAreaRegion {
  name: string;
  slug: string;
  parentRegion: 'san-francisco' | 'peninsula' | 'south-bay' | 'east-bay';
  cities: string[];
  description: string;
  clinics: LocalClinic[];
}

// =============================================================================
// SAN FRANCISCO
// =============================================================================
export const sanFranciscoClinics: LocalClinic[] = [
  // DEXA & Body Composition
  {
    name: 'DexaFit San Francisco',
    slug: 'dexafit-sf',
    category: 'dexa',
    address: '2001 Union St, San Francisco, CA 94123',
    neighborhoods: ['Cow Hollow', 'Marina', 'Pacific Heights'],
    region: 'San Francisco',
    subRegion: 'Marina/Cow Hollow',
    priceRange: '$119-179/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', '3D body scan', 'Metabolic testing'],
    description: 'Premium body composition studio in Cow Hollow. Full metabolic testing suite with VO2 max and RMR available.',
    highlights: ['Full metabolic suite', 'Premium location', 'Detailed consultations', 'VO2 max available'],
    bestFor: 'SF residents wanting comprehensive metabolic testing',
    website: 'https://www.dexafit.com',
    rating: 4.9,
    reviewCount: 312,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - San Francisco',
    slug: 'bodyspec-sf',
    category: 'dexa',
    neighborhoods: ['SOMA', 'Mission', 'Marina', 'Potrero Hill'],
    region: 'San Francisco',
    subRegion: 'Multiple Locations',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat', 'Regional body fat'],
    description: 'The most affordable DEXA in SF. BodySpec mobile units visit gyms and wellness centers across the city weekly.',
    highlights: ['Lowest price in market', 'Package deals ($40/scan)', 'Multiple SF locations', 'Quick appointments'],
    bestFor: 'Budget-conscious fitness enthusiasts tracking body composition',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 567,
    reviewSource: 'Google',
  },
  {
    name: 'UCSF Human Performance Center',
    slug: 'ucsf-hpc',
    category: 'dexa',
    address: 'UCSF Mission Bay, San Francisco, CA',
    neighborhoods: ['Mission Bay', 'Dogpatch'],
    region: 'San Francisco',
    subRegion: 'Mission Bay',
    priceRange: '$100-200',
    services: ['DEXA scan', 'VO2 max', 'Lactate threshold', 'Research-grade testing'],
    description: 'University research facility offering clinical-grade body composition and performance testing. Research-quality Hologic equipment.',
    highlights: ['Research-grade accuracy', 'Academic pricing', 'Hologic machines', 'Clinical protocols'],
    bestFor: 'Those wanting maximum accuracy with research-grade equipment',
    website: 'https://www.ucsfhealth.org',
    rating: 4.7,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  // IV Therapy
  {
    name: 'The Hydration Room - San Francisco',
    slug: 'hydration-room-sf',
    category: 'iv',
    address: '2100 Union St, San Francisco, CA 94123',
    neighborhoods: ['Cow Hollow', 'Marina'],
    region: 'San Francisco',
    subRegion: 'Marina/Cow Hollow',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Athletic recovery', 'Immune boost', 'Beauty IVs'],
    description: 'Bay Area expansion of the popular OC-based IV therapy chain. Clean, clinical environment with medical oversight.',
    highlights: ['Medical oversight', 'Proven protocols', 'Walk-ins welcome', 'Membership options'],
    bestFor: 'SF residents wanting reliable IV therapy',
    website: 'https://www.thehydrationroom.com',
    rating: 4.8,
    reviewCount: 234,
    reviewSource: 'Google',
  },
  {
    name: 'Drip Hydration SF',
    slug: 'drip-hydration-sf',
    category: 'iv',
    neighborhoods: ['Mobile - All SF'],
    region: 'San Francisco',
    subRegion: 'Citywide Mobile',
    priceRange: '$199-599/treatment',
    services: ['In-home IV therapy', 'NAD+', 'Myers cocktail', 'Athletic recovery', 'Hangover recovery'],
    description: 'Concierge IV service that comes to your home, office, or hotel anywhere in SF. RN-administered.',
    highlights: ['Mobile service', 'Same-day appointments', 'RN-administered', 'No travel needed'],
    bestFor: 'Busy professionals, post-event recovery, convenience',
    website: 'https://www.driphydration.com',
    rating: 4.9,
    reviewCount: 456,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - SF Marina',
    slug: 'restore-sf-marina',
    category: 'iv',
    address: '2184 Union St, San Francisco, CA 94123',
    neighborhoods: ['Marina', 'Cow Hollow'],
    region: 'San Francisco',
    subRegion: 'Marina/Cow Hollow',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Hyperbaric oxygen', 'Red light therapy', 'Compression'],
    description: 'National wellness franchise offering IV therapy alongside recovery modalities. Consistent experience, membership options.',
    highlights: ['Multi-modality', 'National chain', 'Membership pricing', 'Consistent quality'],
    bestFor: 'Those wanting multiple recovery modalities in one visit',
    website: 'https://www.restore.com',
    rating: 4.7,
    reviewCount: 189,
    reviewSource: 'Google',
  },
  // Longevity
  {
    name: 'Function Health SF',
    slug: 'function-health-sf',
    category: 'longevity',
    neighborhoods: ['SOMA', 'Financial District'],
    region: 'San Francisco',
    subRegion: 'SOMA/FiDi',
    priceRange: '$499/year membership',
    services: ['100+ biomarker testing', 'Quarterly labs', 'AI-powered insights', 'Physician consultations'],
    description: 'Tech-forward longevity platform offering comprehensive biomarker testing. Founded by health-tech entrepreneurs.',
    highlights: ['100+ biomarkers', 'Quarterly testing', 'AI insights', 'Tech-forward approach'],
    bestFor: 'Tech workers wanting data-driven health optimization',
    website: 'https://www.functionhealth.com',
    rating: 4.6,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'Pacific Longevity Institute',
    slug: 'pacific-longevity-sf',
    category: 'longevity',
    address: 'Pacific Heights, San Francisco, CA',
    neighborhoods: ['Pacific Heights', 'Presidio Heights'],
    region: 'San Francisco',
    subRegion: 'Pacific Heights',
    priceRange: '$500-5,000',
    services: ['Peptide therapy', 'Hormone optimization', 'NAD+ protocols', 'Executive physicals', 'Anti-aging medicine'],
    description: 'Boutique longevity practice in Pacific Heights. Personalized anti-aging protocols with concierge service.',
    highlights: ['Concierge service', 'Peptide expertise', 'Discreet location', 'Personalized protocols'],
    bestFor: 'High-net-worth individuals seeking comprehensive longevity care',
    website: 'https://www.pacificlongevity.com',
    rating: 4.9,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  // Performance
  {
    name: 'SF Performance Lab',
    slug: 'sf-performance-lab',
    category: 'performance',
    address: 'SOMA, San Francisco, CA',
    neighborhoods: ['SOMA', 'South Beach'],
    region: 'San Francisco',
    subRegion: 'SOMA',
    priceRange: '$150-400',
    services: ['VO2 max testing', 'Lactate threshold', 'Running gait analysis', 'Cycling biomechanics'],
    description: 'Performance testing lab popular with triathletes and endurance athletes. Comprehensive metabolic and biomechanical analysis.',
    highlights: ['Endurance focus', 'Biomechanics analysis', 'Coach partnerships', 'Training zones'],
    bestFor: 'Triathletes and endurance athletes in SF',
    website: 'https://www.sfperformancelab.com',
    rating: 4.8,
    reviewCount: 134,
    reviewSource: 'Google',
  },
  // Labs
  {
    name: 'Any Lab Test Now - SF',
    slug: 'any-lab-test-sf',
    category: 'labs',
    address: 'Multiple SF locations',
    neighborhoods: ['Castro', 'SOMA', 'Marina'],
    region: 'San Francisco',
    subRegion: 'Multiple',
    priceRange: 'Varies by test',
    services: ['Blood panels', 'Hormone testing', 'STD testing', 'Drug testing', 'Wellness panels'],
    description: 'Walk-in lab testing without doctor orders. Same-day results for many tests. No appointments needed.',
    highlights: ['No doctor required', 'Walk-in friendly', 'Fast results', 'Wide test menu'],
    bestFor: 'Quick lab work without doctor visit',
    website: 'https://www.anylabtestnow.com',
    rating: 4.5,
    reviewCount: 123,
    reviewSource: 'Google',
  },
];

// =============================================================================
// PENINSULA
// =============================================================================
export const peninsulaClinics: LocalClinic[] = [
  {
    name: 'BodySpec - Peninsula',
    slug: 'bodyspec-peninsula',
    category: 'dexa',
    neighborhoods: ['Palo Alto', 'Menlo Park', 'Redwood City', 'San Mateo'],
    region: 'Peninsula',
    subRegion: 'Multiple Cities',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile units visit Peninsula gyms weekly. Popular stops include Palo Alto and Redwood City locations.',
    highlights: ['Affordable', 'Multiple locations', 'Package deals', 'Regular schedule'],
    bestFor: 'Peninsula fitness enthusiasts tracking body composition',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 345,
    reviewSource: 'Google',
  },
  {
    name: 'DexaFit Palo Alto',
    slug: 'dexafit-palo-alto',
    category: 'dexa',
    address: 'Palo Alto, CA',
    neighborhoods: ['Palo Alto', 'Stanford', 'Menlo Park'],
    region: 'Peninsula',
    subRegion: 'Palo Alto',
    priceRange: '$119-179/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', '3D body scan'],
    description: 'DexaFit\'s Peninsula location serving the Stanford/Palo Alto tech community. Full metabolic testing available.',
    highlights: ['Near Stanford', 'Full testing suite', 'Tech community', 'Premium experience'],
    bestFor: 'Tech workers and Stanford community',
    website: 'https://www.dexafit.com',
    rating: 4.8,
    reviewCount: 234,
    reviewSource: 'Google',
  },
  {
    name: 'Stanford Sports Medicine',
    slug: 'stanford-sports-med',
    category: 'performance',
    address: 'Stanford, CA',
    neighborhoods: ['Stanford', 'Palo Alto'],
    region: 'Peninsula',
    subRegion: 'Stanford',
    priceRange: '$200-500',
    services: ['VO2 max testing', 'Lactate threshold', 'Sports physicals', 'Movement analysis', 'Injury prevention'],
    description: 'World-class sports medicine at Stanford. Same facility that serves Stanford athletes, open to public.',
    highlights: ['World-class facility', 'Stanford expertise', 'Athlete-level care', 'Research-backed'],
    bestFor: 'Serious athletes wanting elite-level assessment',
    website: 'https://stanfordhealthcare.org',
    rating: 4.9,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'The Hydration Room - Burlingame',
    slug: 'hydration-room-burlingame',
    category: 'iv',
    address: 'Burlingame, CA',
    neighborhoods: ['Burlingame', 'San Mateo', 'Hillsborough'],
    region: 'Peninsula',
    subRegion: 'Mid-Peninsula',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Athletic recovery', 'Immune boost'],
    description: 'Peninsula location of the popular IV therapy chain. Convenient for mid-Peninsula residents.',
    highlights: ['Downtown Burlingame', 'Same quality as SF', 'Walk-ins welcome', 'Parking available'],
    bestFor: 'Mid-Peninsula residents wanting IV therapy',
    website: 'https://www.thehydrationroom.com',
    rating: 4.7,
    reviewCount: 156,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - San Mateo',
    slug: 'restore-san-mateo',
    category: 'iv',
    address: 'San Mateo, CA',
    neighborhoods: ['San Mateo', 'Foster City', 'Belmont'],
    region: 'Peninsula',
    subRegion: 'Mid-Peninsula',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy', 'Infrared sauna'],
    description: 'Full-service wellness franchise in San Mateo. All Restore modalities available.',
    highlights: ['Full wellness menu', 'Multiple modalities', 'Membership pricing', 'Easy parking'],
    bestFor: 'Peninsula residents wanting recovery services',
    website: 'https://www.restore.com',
    rating: 4.7,
    reviewCount: 134,
    reviewSource: 'Google',
  },
  {
    name: 'Sutter Health - Palo Alto Performance Medicine',
    slug: 'sutter-palo-alto-performance',
    category: 'performance',
    address: 'Palo Alto, CA',
    neighborhoods: ['Palo Alto', 'Mountain View'],
    region: 'Peninsula',
    subRegion: 'Palo Alto',
    priceRange: '$150-400',
    services: ['VO2 max testing', 'Sports physicals', 'Metabolic testing', 'Cardiac screening'],
    description: 'Hospital-backed performance testing with full medical oversight. Good for those wanting comprehensive screening.',
    highlights: ['Medical oversight', 'Comprehensive screening', 'Sutter network', 'Insurance options'],
    bestFor: 'Those wanting hospital-backed testing with specialist access',
    website: 'https://www.sutterhealth.org',
    rating: 4.6,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'Peninsula Longevity Center',
    slug: 'peninsula-longevity',
    category: 'longevity',
    address: 'Menlo Park, CA',
    neighborhoods: ['Menlo Park', 'Atherton', 'Palo Alto'],
    region: 'Peninsula',
    subRegion: 'Menlo Park',
    priceRange: '$500-5,000',
    services: ['Peptide therapy', 'Hormone optimization', 'NAD+ protocols', 'Executive physicals', 'Genetic testing'],
    description: 'Boutique longevity practice serving the Peninsula\'s tech executives. Comprehensive anti-aging protocols.',
    highlights: ['Tech executive focus', 'Comprehensive testing', 'Personalized protocols', 'Concierge service'],
    bestFor: 'Tech executives seeking longevity optimization',
    website: 'https://www.peninsulalongevity.com',
    rating: 4.8,
    reviewCount: 56,
    reviewSource: 'Google',
  },
  {
    name: 'Woodside Wellness',
    slug: 'woodside-wellness',
    category: 'wellness',
    address: 'Woodside, CA',
    neighborhoods: ['Woodside', 'Portola Valley', 'Atherton'],
    region: 'Peninsula',
    subRegion: 'Western Peninsula',
    priceRange: '$150-500',
    services: ['IV therapy', 'Vitamin injections', 'Wellness consultations', 'Detox programs'],
    description: 'Boutique wellness center in the hills of Woodside. Personalized care in a serene setting.',
    highlights: ['Scenic location', 'Personalized care', 'Boutique feel', 'Privacy focused'],
    bestFor: 'Western Peninsula residents wanting boutique wellness',
    website: 'https://www.woodsidewellness.com',
    rating: 4.7,
    reviewCount: 45,
    reviewSource: 'Google',
  },
];

// =============================================================================
// SOUTH BAY
// =============================================================================
export const southBayClinics: LocalClinic[] = [
  {
    name: 'BodySpec - South Bay',
    slug: 'bodyspec-south-bay',
    category: 'dexa',
    neighborhoods: ['San Jose', 'Santa Clara', 'Sunnyvale', 'Mountain View', 'Cupertino'],
    region: 'South Bay',
    subRegion: 'Multiple Cities',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile units visit South Bay gyms throughout the week. Most affordable DEXA option in Silicon Valley.',
    highlights: ['Lowest price', 'Multiple locations', 'Package deals', 'Tech community popular'],
    bestFor: 'South Bay tech workers tracking fitness progress',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 678,
    reviewSource: 'Google',
  },
  {
    name: 'DexaFit San Jose',
    slug: 'dexafit-san-jose',
    category: 'dexa',
    address: 'San Jose, CA',
    neighborhoods: ['Downtown San Jose', 'Willow Glen', 'Santana Row'],
    region: 'South Bay',
    subRegion: 'San Jose',
    priceRange: '$119-179/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', '3D body scan', 'Metabolic testing'],
    description: 'DexaFit\'s South Bay location. Full metabolic testing suite for Silicon Valley\'s health-conscious tech workers.',
    highlights: ['Full suite', 'Near Santana Row', 'VO2 available', 'Premium experience'],
    bestFor: 'South Bay residents wanting comprehensive testing',
    website: 'https://www.dexafit.com',
    rating: 4.8,
    reviewCount: 289,
    reviewSource: 'Google',
  },
  {
    name: 'San Jose State Sports Medicine',
    slug: 'sjsu-sports-med',
    category: 'performance',
    address: 'San Jose State University, San Jose, CA',
    neighborhoods: ['Downtown San Jose', 'Japantown'],
    region: 'South Bay',
    subRegion: 'San Jose',
    priceRange: '$100-300',
    services: ['VO2 max testing', 'Lactate threshold', 'Body composition', 'Sports physicals'],
    description: 'University sports medicine department offering testing to the public. Academic pricing with research-grade equipment.',
    highlights: ['Academic pricing', 'Research-grade', 'Clinical protocols', 'Student-friendly'],
    bestFor: 'Budget-conscious athletes wanting quality testing',
    website: 'https://www.sjsu.edu',
    rating: 4.5,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Los Gatos',
    slug: 'restore-los-gatos',
    category: 'iv',
    address: 'Los Gatos, CA',
    neighborhoods: ['Los Gatos', 'Saratoga', 'Campbell'],
    region: 'South Bay',
    subRegion: 'Los Gatos',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy', 'Infrared sauna'],
    description: 'Premium location in downtown Los Gatos. Full suite of recovery modalities popular with local athletes.',
    highlights: ['Downtown Los Gatos', 'Full menu', 'Affluent community', 'Easy parking'],
    bestFor: 'Los Gatos and Saratoga residents',
    website: 'https://www.restore.com',
    rating: 4.8,
    reviewCount: 198,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Cupertino',
    slug: 'restore-cupertino',
    category: 'iv',
    address: 'Cupertino, CA',
    neighborhoods: ['Cupertino', 'Sunnyvale', 'Santa Clara'],
    region: 'South Bay',
    subRegion: 'Cupertino',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy'],
    description: 'Convenient location for Apple and tech campus workers. Full recovery suite available.',
    highlights: ['Near Apple campus', 'Tech worker popular', 'Multiple modalities', 'Membership options'],
    bestFor: 'Cupertino tech workers wanting recovery services',
    website: 'https://www.restore.com',
    rating: 4.7,
    reviewCount: 167,
    reviewSource: 'Google',
  },
  {
    name: 'The Hydration Room - Campbell',
    slug: 'hydration-room-campbell',
    category: 'iv',
    address: 'Campbell, CA',
    neighborhoods: ['Campbell', 'Los Gatos', 'San Jose'],
    region: 'South Bay',
    subRegion: 'Campbell',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Athletic recovery', 'Hangover recovery'],
    description: 'South Bay location of popular IV therapy chain. Downtown Campbell location with easy access.',
    highlights: ['Downtown Campbell', 'Full IV menu', 'Walk-ins welcome', 'Consistent quality'],
    bestFor: 'South Bay residents wanting IV therapy',
    website: 'https://www.thehydrationroom.com',
    rating: 4.8,
    reviewCount: 189,
    reviewSource: 'Google',
  },
  {
    name: 'Silicon Valley Longevity',
    slug: 'sv-longevity',
    category: 'longevity',
    address: 'Los Gatos, CA',
    neighborhoods: ['Los Gatos', 'Saratoga', 'Monte Sereno'],
    region: 'South Bay',
    subRegion: 'Los Gatos',
    priceRange: '$500-10,000',
    services: ['Comprehensive biomarkers', 'Peptide therapy', 'Hormone optimization', 'NAD+ protocols', 'Executive physicals'],
    description: 'Premium longevity clinic serving Silicon Valley executives. Comprehensive testing and personalized protocols.',
    highlights: ['Tech executive focus', 'Comprehensive testing', 'Cutting-edge protocols', 'Concierge service'],
    bestFor: 'Tech executives seeking comprehensive longevity care',
    website: 'https://www.svlongevity.com',
    rating: 4.9,
    reviewCount: 78,
    reviewSource: 'Google',
  },
  {
    name: 'Optimal Health Medical',
    slug: 'optimal-health-sj',
    category: 'longevity',
    address: 'San Jose, CA',
    neighborhoods: ['Willow Glen', 'Rose Garden', 'Almaden'],
    region: 'South Bay',
    subRegion: 'San Jose',
    priceRange: '$300-3,000',
    services: ['Hormone optimization', 'Peptide therapy', 'IV therapy', 'Functional medicine'],
    description: 'Integrative medicine practice focusing on optimization and anti-aging. Accessible pricing for South Bay.',
    highlights: ['Functional medicine', 'Accessible pricing', 'Hormone expertise', 'Personalized care'],
    bestFor: 'Those seeking integrative medicine approach',
    website: 'https://www.optimalhealthmed.com',
    rating: 4.7,
    reviewCount: 123,
    reviewSource: 'Google',
  },
  {
    name: 'Any Lab Test Now - San Jose',
    slug: 'any-lab-test-sj',
    category: 'labs',
    address: 'Multiple San Jose locations',
    neighborhoods: ['Willow Glen', 'Almaden', 'Evergreen'],
    region: 'South Bay',
    subRegion: 'San Jose',
    priceRange: 'Varies by test',
    services: ['Blood panels', 'Hormone testing', 'STD testing', 'Drug testing', 'Wellness panels'],
    description: 'Walk-in lab testing without doctor orders. Multiple South Bay locations.',
    highlights: ['No doctor required', 'Walk-in friendly', 'Fast results', 'Multiple locations'],
    bestFor: 'Quick lab work without doctor visit',
    website: 'https://www.anylabtestnow.com',
    rating: 4.5,
    reviewCount: 156,
    reviewSource: 'Google',
  },
  {
    name: 'South Bay Performance Institute',
    slug: 'south-bay-performance',
    category: 'performance',
    address: 'Santa Clara, CA',
    neighborhoods: ['Santa Clara', 'Sunnyvale', 'Milpitas'],
    region: 'South Bay',
    subRegion: 'Santa Clara',
    priceRange: '$150-400',
    services: ['VO2 max testing', 'Lactate threshold', 'Running analysis', 'Cycling power testing'],
    description: 'Performance testing facility popular with Silicon Valley triathletes and cyclists. Comprehensive metabolic testing.',
    highlights: ['Triathlete focus', 'Cycling expertise', 'Training plans', 'Coach partnerships'],
    bestFor: 'Endurance athletes in South Bay',
    website: 'https://www.southbayperformance.com',
    rating: 4.8,
    reviewCount: 145,
    reviewSource: 'Google',
  },
];

// =============================================================================
// EAST BAY
// =============================================================================
export const eastBayClinics: LocalClinic[] = [
  {
    name: 'BodySpec - East Bay',
    slug: 'bodyspec-east-bay',
    category: 'dexa',
    neighborhoods: ['Oakland', 'Berkeley', 'Walnut Creek', 'Pleasanton', 'Dublin'],
    region: 'East Bay',
    subRegion: 'Multiple Cities',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec visits East Bay gyms regularly. Popular locations in Oakland, Berkeley, and Walnut Creek.',
    highlights: ['Affordable', 'Multiple locations', 'Package deals', 'Regular schedule'],
    bestFor: 'East Bay fitness enthusiasts tracking body composition',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 423,
    reviewSource: 'Google',
  },
  {
    name: 'DexaFit Walnut Creek',
    slug: 'dexafit-walnut-creek',
    category: 'dexa',
    address: 'Walnut Creek, CA',
    neighborhoods: ['Walnut Creek', 'Lafayette', 'Pleasant Hill'],
    region: 'East Bay',
    subRegion: 'Central Contra Costa',
    priceRange: '$119-179/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', '3D body scan'],
    description: 'DexaFit\'s East Bay location in downtown Walnut Creek. Full metabolic testing suite available.',
    highlights: ['Downtown location', 'Full suite', 'Premium experience', 'Easy BART access'],
    bestFor: 'Contra Costa residents wanting comprehensive testing',
    website: 'https://www.dexafit.com',
    rating: 4.8,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'UC Berkeley Sports Medicine',
    slug: 'ucb-sports-med',
    category: 'performance',
    address: 'UC Berkeley Campus, Berkeley, CA',
    neighborhoods: ['Berkeley', 'North Berkeley'],
    region: 'East Bay',
    subRegion: 'Berkeley',
    priceRange: '$150-400',
    services: ['VO2 max testing', 'Lactate threshold', 'Movement screening', 'Sports physicals'],
    description: 'Cal\'s sports medicine department offering public testing. Same facility serving Cal athletes.',
    highlights: ['Cal athletics facility', 'Research-grade', 'Academic pricing', 'Expert staff'],
    bestFor: 'Serious athletes wanting elite-level assessment',
    website: 'https://www.ucberkeleyrecreation.com',
    rating: 4.7,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Walnut Creek',
    slug: 'restore-walnut-creek',
    category: 'iv',
    address: 'Walnut Creek, CA',
    neighborhoods: ['Walnut Creek', 'Lafayette', 'Orinda'],
    region: 'East Bay',
    subRegion: 'Central Contra Costa',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy', 'Hyperbaric'],
    description: 'Full-service Restore location in downtown Walnut Creek. All modalities available.',
    highlights: ['Full wellness menu', 'Downtown location', 'Membership pricing', 'Lamorinda access'],
    bestFor: 'Contra Costa residents wanting recovery services',
    website: 'https://www.restore.com',
    rating: 4.7,
    reviewCount: 145,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Oakland',
    slug: 'restore-oakland',
    category: 'iv',
    address: 'Oakland, CA',
    neighborhoods: ['Rockridge', 'Temescal', 'Piedmont'],
    region: 'East Bay',
    subRegion: 'Oakland',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy'],
    description: 'Oakland location serving the Rockridge and Temescal communities. Full recovery suite.',
    highlights: ['Rockridge location', 'Urban convenience', 'Full menu', 'BART accessible'],
    bestFor: 'Oakland residents wanting recovery services',
    website: 'https://www.restore.com',
    rating: 4.6,
    reviewCount: 134,
    reviewSource: 'Google',
  },
  {
    name: 'IV Therapy Oakland',
    slug: 'iv-therapy-oakland',
    category: 'iv',
    address: 'Oakland, CA',
    neighborhoods: ['Lake Merritt', 'Grand Lake', 'Adams Point'],
    region: 'East Bay',
    subRegion: 'Oakland',
    priceRange: '$129-399/treatment',
    services: ['IV vitamin therapy', 'NAD+', 'Glutathione', 'Myers cocktail', 'Athletic recovery'],
    description: 'Local Oakland IV therapy clinic near Lake Merritt. Personalized care with medical oversight.',
    highlights: ['Local Oakland', 'Near Lake Merritt', 'Personalized care', 'Medical oversight'],
    bestFor: 'Oakland residents wanting local IV therapy',
    website: 'https://www.ivtherapyoakland.com',
    rating: 4.7,
    reviewCount: 98,
    reviewSource: 'Google',
  },
  {
    name: 'Berkeley Longevity Center',
    slug: 'berkeley-longevity',
    category: 'longevity',
    address: 'Berkeley, CA',
    neighborhoods: ['Downtown Berkeley', 'North Berkeley', 'Claremont'],
    region: 'East Bay',
    subRegion: 'Berkeley',
    priceRange: '$400-4,000',
    services: ['Peptide therapy', 'Hormone optimization', 'NAD+ protocols', 'Functional medicine', 'Genetic testing'],
    description: 'Integrative longevity practice with research connections to UC Berkeley. Evidence-based protocols.',
    highlights: ['Research connections', 'Evidence-based', 'Academic community', 'Integrative approach'],
    bestFor: 'Those seeking research-backed longevity treatments',
    website: 'https://www.berkeleylongevity.com',
    rating: 4.8,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  {
    name: 'Tri-Valley Performance',
    slug: 'tri-valley-performance',
    category: 'performance',
    address: 'Pleasanton, CA',
    neighborhoods: ['Pleasanton', 'Dublin', 'Livermore'],
    region: 'East Bay',
    subRegion: 'Tri-Valley',
    priceRange: '$150-350',
    services: ['VO2 max testing', 'Lactate threshold', 'Running analysis', 'Cycling testing'],
    description: 'Performance testing in the Tri-Valley. Popular with the running and triathlon community.',
    highlights: ['Tri-Valley location', 'Endurance focus', 'Training programs', 'Local community'],
    bestFor: 'Tri-Valley endurance athletes',
    website: 'https://www.trivalleyperformance.com',
    rating: 4.7,
    reviewCount: 78,
    reviewSource: 'Google',
  },
  {
    name: 'East Bay Wellness Center',
    slug: 'east-bay-wellness',
    category: 'wellness',
    address: 'Danville, CA',
    neighborhoods: ['Danville', 'San Ramon', 'Alamo'],
    region: 'East Bay',
    subRegion: 'San Ramon Valley',
    priceRange: '$100-400',
    services: ['IV therapy', 'Vitamin injections', 'Wellness consultations', 'Detox programs'],
    description: 'Boutique wellness center in the San Ramon Valley. Personalized care for families and professionals.',
    highlights: ['Family friendly', 'Boutique feel', 'San Ramon Valley', 'Personalized care'],
    bestFor: 'San Ramon Valley residents seeking wellness services',
    website: 'https://www.eastbaywellness.com',
    rating: 4.6,
    reviewCount: 89,
    reviewSource: 'Google',
  },
];

// =============================================================================
// REGION DEFINITIONS
// =============================================================================
export const BAYAREA_REGIONS: BayAreaRegion[] = [
  {
    name: 'San Francisco',
    slug: 'san-francisco',
    parentRegion: 'san-francisco',
    cities: ['San Francisco', 'Daly City', 'South San Francisco'],
    description: 'The city offers the densest concentration of wellness options in the Bay. DexaFit and BodySpec cover DEXA, while The Hydration Room and Restore lead IV therapy. Premium longevity clinics in Pacific Heights serve executives.',
    clinics: sanFranciscoClinics,
  },
  {
    name: 'Peninsula',
    slug: 'peninsula',
    parentRegion: 'peninsula',
    cities: ['Palo Alto', 'Menlo Park', 'Redwood City', 'San Mateo', 'Burlingame', 'Woodside', 'Atherton'],
    description: 'Home to Stanford sports medicine and the tech elite\'s longevity clinics. BodySpec and DexaFit offer DEXA, while boutique wellness centers serve the affluent Peninsula communities.',
    clinics: peninsulaClinics,
  },
  {
    name: 'South Bay',
    slug: 'south-bay',
    parentRegion: 'south-bay',
    cities: ['San Jose', 'Santa Clara', 'Sunnyvale', 'Cupertino', 'Mountain View', 'Los Gatos', 'Campbell', 'Saratoga'],
    description: 'Silicon Valley\'s health hub. Heavy concentration of tech workers drives demand for BodySpec DEXA, Restore recovery, and cutting-edge longevity clinics in Los Gatos serving executives.',
    clinics: southBayClinics,
  },
  {
    name: 'East Bay',
    slug: 'east-bay',
    parentRegion: 'east-bay',
    cities: ['Oakland', 'Berkeley', 'Walnut Creek', 'Pleasanton', 'Dublin', 'Danville', 'Lafayette', 'Orinda'],
    description: 'Diverse options from urban Oakland to suburban Walnut Creek. UC Berkeley offers performance testing, Restore has multiple locations, and the Tri-Valley has growing wellness infrastructure.',
    clinics: eastBayClinics,
  },
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================
export function getRegionBySlug(slug: string): BayAreaRegion | undefined {
  return BAYAREA_REGIONS.find(r => r.slug === slug);
}

export function getClinicsByCategory(category: LocalClinic['category']): LocalClinic[] {
  return BAYAREA_REGIONS.flatMap(r => r.clinics).filter(c => c.category === category);
}

export function getClinicsByRegion(regionSlug: string): LocalClinic[] {
  const region = getRegionBySlug(regionSlug);
  return region ? region.clinics : [];
}

export function getAllClinics(): LocalClinic[] {
  return BAYAREA_REGIONS.flatMap(r => r.clinics);
}

export function getClinicCount(): number {
  return getAllClinics().length;
}

export function getCategoryStats(): Record<string, number> {
  const clinics = getAllClinics();
  return clinics.reduce((acc, clinic) => {
    acc[clinic.category] = (acc[clinic.category] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
}
