// Destination photo credits — Unsplash (via API). Attribution per Unsplash API guidelines.
export interface PhotoCredit { slug: string; photographer: string; photographerUrl: string; photoUrl: string }
export const DESTINATION_PHOTO_CREDITS: PhotoCredit[] = [
  { slug: 'mexico', photographer: "Gerson Repreza", photographerUrl: 'https://unsplash.com/@gersonrepreza?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/aerial-photo-of-white-buildings-PW3tJkRkSy8?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'turkey', photographer: "Anna Berdnik", photographerUrl: 'https://unsplash.com/@aberdni?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/aerial-view-of-buildings-and-flying-birds-0n0AHB1fgTQ?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'south-korea', photographer: "NK Lee", photographerUrl: 'https://unsplash.com/@nlee02?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/a-city-with-mountains-in-the-background-z1UIZhrUYrE?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'thailand', photographer: "Alejandro Cartagena \ud83c\uddf2\ud83c\uddfd\ud83c\udff3\u200d\ud83c\udf08", photographerUrl: 'https://unsplash.com/@cartayen?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/orange-temples-during-daytime-B64B6-kAWlw?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'india', photographer: "Annie Spratt", photographerUrl: 'https://unsplash.com/@anniespratt?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/taj-mahal-india-wXZfbj-Ftbs?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'costa-rica', photographer: "Christina Victoria Craft", photographerUrl: 'https://unsplash.com/@victoriabcphotographer?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/brown-wooden-bridge-over-green-mountains-during-daytime-DFfNVwhOIWQ?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'spain', photographer: "Logan Armstrong", photographerUrl: 'https://unsplash.com/@loganstrongarms?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/aerial-view-of-city-buildings-during-daytime-hVhfqhDYciU?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'czech-republic', photographer: "Ouael Ben Salah", photographerUrl: 'https://unsplash.com/@benwksi?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/white-and-brown-boat-on-river-near-brown-concrete-building-during-daytime-S2Wek5-5oEc?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'panama', photographer: "JACQUELINE BRANDWAYN", photographerUrl: 'https://unsplash.com/@lajaxx?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/city-buildings-near-body-of-water-under-blue-sky-during-daytime-rhHIEtBPD5A?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'colombia', photographer: "Joel Duncan", photographerUrl: 'https://unsplash.com/@joelduncan?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/city-buildings-during-sunset-Iqa-WlbNjqs?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'cayman-islands', photographer: "Becky Vogel", photographerUrl: 'https://unsplash.com/@beckylovesbirds?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/green-palm-tree-on-white-sand-beach-during-daytime-29TXTmsCj7A?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'dubai', photographer: "David Rodrigo", photographerUrl: 'https://unsplash.com/@david__r?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/aerial-photo-of-city-highway-surrounded-by-high-rise-buildings-Fr6zexbmjmc?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'brazil', photographer: "Agustin Diaz Gargiulo", photographerUrl: 'https://unsplash.com/@agustindiazg?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/aerial-photography-of-cityscape-near-sea-7F65HDP0-E0?utm_source=vitalityscout&utm_medium=referral' },
  { slug: 'hungary', photographer: "Ervin Lukacs", photographerUrl: 'https://unsplash.com/@lukerv4?utm_source=vitalityscout&utm_medium=referral', photoUrl: 'https://unsplash.com/photos/brown-concrete-building-near-body-of-water-during-daytime-sMyQb3i9bNA?utm_source=vitalityscout&utm_medium=referral' },
];
