import { Provider } from './types';

// =============================================================================
// DRUG REGISTRIES & INFORMATION RESOURCES
// =============================================================================

export const drugRegistryProviders: Provider[] = [
  {
    slug: 'fda-drugs',
    name: 'FDA Drug Database (Drugs@FDA)',
    description: 'Official FDA database of approved prescription and over-the-counter drugs, including labeling, approval history, and safety information.',
    category: 'drug_registry',
    services: ['Drug approvals', 'Labeling information', 'Generic equivalents', 'Safety alerts', 'Approval letters'],
    pricingDisplay: 'Free',
    pricingNotes: 'Completely free government resource. No registration required.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['United States'],
    url: 'https://www.accessdata.fda.gov/scripts/cder/daf/',
    referralType: 'direct_link',
    ourTake: 'This is the authoritative source for US drug approvals. Before taking any medication, you can look up the official FDA labeling, see when it was approved, and check for safety alerts. Essential for informed patients.',
    bestFor: ['Researching new medications', 'Finding generic equivalents', 'Checking FDA approval status'],
    pros: ['Official government source', 'Complete approval history', 'Free and authoritative', 'Includes all FDA-approved drugs'],
    cons: ['Interface can be dated', 'Technical/medical language', 'US drugs only', 'No pricing information'],
    accreditations: ['US Government - FDA'],
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'fda-orange-book',
    name: 'FDA Orange Book',
    description: 'Official FDA publication identifying drug products approved for safety and effectiveness, including therapeutic equivalence ratings.',
    category: 'drug_registry',
    services: ['Therapeutic equivalence', 'Generic substitutes', 'Patent information', 'Exclusivity data'],
    pricingDisplay: 'Free',
    pricingNotes: 'Free government resource for generic drug information.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['United States'],
    url: 'https://www.accessdata.fda.gov/scripts/cder/ob/',
    referralType: 'direct_link',
    ourTake: 'The Orange Book is your key to understanding generic equivalents. If you want to know whether a generic is truly equivalent to a brand-name drug, this is where pharmacists and doctors look.',
    bestFor: ['Finding generic alternatives', 'Understanding therapeutic equivalence', 'Patent expiration research'],
    pros: ['Authoritative equivalence ratings', 'Patent expiration dates', 'Free', 'Updated regularly'],
    cons: ['Technical for lay users', 'Focused on generics only', 'No clinical guidance', 'Dense information'],
    accreditations: ['US Government - FDA'],
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'dailymed',
    name: 'DailyMed (NIH)',
    description: 'National Institutes of Health database providing official drug labeling (package inserts) submitted to the FDA.',
    category: 'drug_registry',
    services: ['Package inserts', 'Drug labeling', 'Medication guides', 'Prescribing information', 'NDC codes'],
    pricingDisplay: 'Free',
    pricingNotes: 'Free NIH/NLM resource. No registration required.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['United States'],
    url: 'https://dailymed.nlm.nih.gov/',
    referralType: 'direct_link',
    ourTake: 'DailyMed is the best place to find the actual package insert for any medication. Want to read the same information your doctor sees? This is it. More user-friendly than FDA\'s database.',
    bestFor: ['Reading package inserts', 'Checking drug interactions', 'Understanding side effects'],
    pros: ['Official labeling documents', 'User-friendly interface', 'Searchable database', 'Includes OTC drugs'],
    cons: ['Medical jargon heavy', 'No lay summaries', 'US products only', 'No pricing'],
    accreditations: ['NIH - National Library of Medicine'],
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'rxlist',
    name: 'RxList',
    description: 'Consumer-friendly drug information resource with easy-to-understand drug monographs, interactions, and pill identification.',
    category: 'drug_registry',
    services: ['Drug information', 'Interaction checker', 'Pill identifier', 'Medical dictionary', 'Dosage guides'],
    pricingDisplay: 'Free',
    pricingNotes: 'Free with ads. Part of WebMD network.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['United States'],
    url: 'https://www.rxlist.com',
    referralType: 'direct_link',
    ourTake: 'RxList translates complex drug information into plain English. Their pill identifier is particularly useful if you find an unknown medication. Good starting point before diving into official FDA resources.',
    bestFor: ['Understanding medications in plain language', 'Pill identification', 'Quick drug lookups'],
    pros: ['Easy to understand', 'Good pill identifier', 'Interaction checker', 'Free access'],
    cons: ['Ad-supported', 'Less authoritative than FDA', 'May lag on newest drugs', 'US-focused'],
    accreditations: ['WebMD network'],
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'drugs-com',
    name: 'Drugs.com',
    description: 'Comprehensive drug information portal with pricing, interactions, pill ID, and user reviews of medications.',
    category: 'drug_registry',
    services: ['Drug information', 'Price comparisons', 'Interaction checker', 'Pill identifier', 'User reviews', 'Coupons'],
    pricingDisplay: 'Free',
    pricingNotes: 'Free with ads. Premium features available.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['International'],
    url: 'https://www.drugs.com',
    referralType: 'direct_link',
    ourTake: 'Drugs.com is one of the most comprehensive consumer drug resources. Their price comparison tool and coupons can save real money. The interaction checker is particularly robust. Good for everyday medication questions.',
    bestFor: ['Price comparisons', 'Drug interactions', 'User experiences', 'Finding coupons'],
    pros: ['Price comparison tool', 'Comprehensive database', 'User reviews', 'Discount coupons', 'Interaction checker'],
    cons: ['Heavy advertising', 'User reviews vary in quality', 'Commercial relationships', 'Can be overwhelming'],
    accreditations: ['TRUSTe certified', 'HONcode certified'],
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'goodrx',
    name: 'GoodRx',
    description: 'Drug pricing comparison platform offering free coupons and discounts at pharmacies nationwide.',
    category: 'drug_registry',
    services: ['Price comparisons', 'Pharmacy coupons', 'Drug information', 'Telehealth', 'Mail-order pharmacy'],
    pricingDisplay: 'Free coupons',
    pricingNotes: 'Free to use. GoodRx makes money from pharmacy fees when you use their coupons.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['United States'],
    url: 'https://www.goodrx.com',
    referralType: 'affiliate_link',
    ourTake: 'GoodRx is essential for cash-pay patients. Even with insurance, sometimes GoodRx prices beat your copay. Always check GoodRx before filling a prescription - you might save hundreds.',
    bestFor: ['Finding lowest drug prices', 'Cash-pay patients', 'Comparing pharmacy prices'],
    pros: ['Significant savings possible', 'Free to use', 'Accepted at most pharmacies', 'Easy to use app'],
    cons: ['Not insurance', 'Prices can vary', 'Some pharmacies don\'t accept', 'Data privacy concerns'],
    accreditations: ['BBB accredited'],
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'medlineplus',
    name: 'MedlinePlus Drug Information',
    description: 'NIH resource providing consumer-friendly drug information written for patients, not medical professionals.',
    category: 'drug_registry',
    services: ['Patient drug information', 'Health topics', 'Medical encyclopedia', 'Drug images', 'Spanish translations'],
    pricingDisplay: 'Free',
    pricingNotes: 'Free government health resource.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['United States'],
    url: 'https://medlineplus.gov/druginformation.html',
    referralType: 'direct_link',
    ourTake: 'MedlinePlus is the NIH\'s patient-friendly resource. Unlike technical FDA documents, these drug monographs are written for regular people. Great starting point for understanding any medication.',
    bestFor: ['Patient-friendly explanations', 'Spanish speakers', 'General health information'],
    pros: ['Written for patients', 'Trustworthy NIH source', 'Available in Spanish', 'Links to clinical trials'],
    cons: ['Less detailed than FDA', 'May not have newest drugs', 'No pricing information', 'No interaction checker'],
    accreditations: ['NIH - National Library of Medicine'],
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'epocrates',
    name: 'Epocrates',
    description: 'Clinical drug reference used by healthcare professionals, with a free version available to patients.',
    category: 'drug_registry',
    services: ['Drug monographs', 'Interaction checker', 'Pill identifier', 'Dosing calculators', 'Clinical guidelines'],
    pricingDisplay: 'Free basic / $175/yr Pro',
    pricingNotes: 'Free version has core features. Epocrates+ subscription for advanced tools.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['United States'],
    url: 'https://www.epocrates.com',
    referralType: 'direct_link',
    ourTake: 'Epocrates is what many doctors actually use at the point of care. The free version gives you access to the same drug interaction checker your physician uses. More clinical than consumer sites.',
    bestFor: ['Healthcare professionals', 'Detailed clinical information', 'Drug interactions'],
    pros: ['Used by real clinicians', 'Robust interaction checker', 'Mobile app', 'Clinical depth'],
    cons: ['More technical', 'Full features require subscription', 'Designed for professionals', 'App-focused'],
    accreditations: ['Used by 1M+ healthcare providers'],
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'clinicaltrials-gov',
    name: 'ClinicalTrials.gov',
    description: 'NIH database of clinical studies conducted around the world, searchable by condition, drug, or location.',
    category: 'drug_registry',
    services: ['Clinical trial search', 'Study results', 'Recruiting studies', 'Trial locations'],
    pricingDisplay: 'Free',
    pricingNotes: 'Free government resource. Participation in trials may provide free treatment.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['International'],
    url: 'https://clinicaltrials.gov',
    referralType: 'direct_link',
    ourTake: 'If you have a condition with limited treatment options, ClinicalTrials.gov might show you experimental treatments you can access for free by participating in research. Worth checking for any serious diagnosis.',
    bestFor: ['Finding clinical trials', 'Accessing experimental treatments', 'Research participation'],
    pros: ['Access to cutting-edge treatments', 'Free participation possible', 'Comprehensive database', 'International coverage'],
    cons: ['Not guaranteed treatment', 'May receive placebo', 'Strict eligibility criteria', 'Requires commitment'],
    accreditations: ['NIH - National Library of Medicine'],
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'rxassist',
    name: 'RxAssist',
    description: 'Database of patient assistance programs offered by pharmaceutical companies for those who can\'t afford medications.',
    category: 'drug_registry',
    services: ['Patient assistance programs', 'Drug discount programs', 'State programs', 'Free medication resources'],
    pricingDisplay: 'Free',
    pricingNotes: 'Free resource to find assistance programs. Actual assistance varies by program.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['United States'],
    url: 'https://www.rxassist.org',
    referralType: 'direct_link',
    ourTake: 'RxAssist is the most comprehensive directory of patient assistance programs. If you can\'t afford a medication, search here first to find manufacturer programs, state programs, and other resources.',
    bestFor: ['Finding free/low-cost medications', 'Uninsured patients', 'Underinsured patients'],
    pros: ['Comprehensive PAP database', 'Free to use', 'Links to applications', 'State program listings'],
    cons: ['Programs have income limits', 'Applications can be complex', 'Not all drugs covered', 'Requires effort to apply'],
    accreditations: ['Non-profit resource'],
    featured: true,
    lastVerified: '2024-12-21',
  },
];

export default {
  drug_registry: drugRegistryProviders,
};
