import { Provider } from './types';

// =============================================================================
// PHARMACEUTICAL COMPANIES
// =============================================================================
// Focus: Patient assistance programs and how to afford medications
// This isn't just a list of big pharma - it's a guide to getting help paying
// for expensive medications through manufacturer programs.

export const pharmaProviders: Provider[] = [
  // -----------------------------------------------------------------------------
  // FEATURED: Top companies by 2024 performance + patient assistance quality
  // -----------------------------------------------------------------------------
  {
    slug: 'pfizer',
    name: 'Pfizer',
    description: 'Global pharmaceutical giant known for vaccines (COVID-19, pneumonia), oncology drugs, and cardiovascular medications. 175+ years in business.',
    category: 'pharma',
    services: ['Vaccines', 'Oncology', 'Cardiovascular', 'Immunology', 'Patient assistance programs'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'Pfizer RxPathways offers assistance programs for eligible patients. Many drugs covered by insurance.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.pfizer.com',
    referralType: 'direct_link',
    ourTake: 'Pfizer is a household name after COVID-19 vaccines. They have robust patient assistance programs through RxPathways. If you\'re prescribed a Pfizer drug and can\'t afford it, always check their assistance program first - they helped hundreds of thousands of patients in 2024.',
    bestFor: ['Vaccine access', 'Cancer treatment', 'Patient assistance needs'],
    pros: ['Extensive patient assistance (RxPathways)', 'Well-researched drugs', 'Global availability', 'Strong R&D pipeline'],
    cons: ['High list prices', 'Complex assistance applications', 'Some drugs have alternatives', 'COVID product revenue declining'],
    accreditations: ['FDA approved', 'WHO prequalified vaccines'],
    yearsInBusiness: 175,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'johnson-johnson',
    name: 'Johnson & Johnson (Janssen)',
    description: '#1 pharma company by 2024 Rx revenue ($53.5B). Janssen pharmaceutical division focuses on immunology, oncology, and neuroscience.',
    category: 'pharma',
    services: ['Immunology drugs', 'Oncology', 'Neuroscience', 'Infectious disease', 'Patient assistance'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'Janssen CarePath provides savings programs and patient assistance for eligible individuals.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.janssen.com',
    referralType: 'direct_link',
    ourTake: 'J&J\'s pharma arm Janssen dethroned Pfizer as #1 in 2024 Rx sales. They make critical drugs for autoimmune conditions (Stelara, Tremfya) and cancer. Their CarePath program can cut costs from thousands to near-zero for qualifying patients. Always ask about CarePath if you\'re prescribed a Janssen drug.',
    bestFor: ['Autoimmune conditions', 'Cancer treatment', 'Mental health medications'],
    pros: ['#1 pharma by Rx revenue (2024)', 'Strong patient support (CarePath)', 'Innovative biologics', 'Diversified portfolio'],
    cons: ['Complex specialty drugs', 'Requires specialty pharmacies for some', 'Insurance navigation can be tricky'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 138,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'novo-nordisk',
    name: 'Novo Nordisk',
    description: 'Danish pharmaceutical leader in diabetes care and obesity treatments. Makers of Ozempic, Wegovy, and Rybelsus. +26% revenue growth in 2024.',
    category: 'pharma',
    services: ['Diabetes medications', 'Obesity treatments', 'GLP-1 drugs (Ozempic, Wegovy)', 'Insulin', 'Patient assistance'],
    pricingDisplay: '$900-1,500/mo without help',
    pricingNotes: 'NovoCare offers patient assistance and savings cards. Wegovy/Ozempic can be $1,000+/month without assistance, but $0 savings cards available for eligible patients.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['Global'],
    url: 'https://www.novonordisk.com',
    referralType: 'direct_link',
    ourTake: 'If you\'re interested in GLP-1 medications, Novo Nordisk is THE company to know - they make Ozempic, Wegovy, and Rybelsus. Their NovoCare program is absolutely essential for affording these life-changing but expensive medications. Don\'t pay $1,000+/month without first checking if you qualify for $0 savings cards.',
    bestFor: ['Diabetes management', 'Weight loss (GLP-1)', 'Insulin needs'],
    pros: ['Leader in diabetes/obesity', 'Strong patient assistance (NovoCare)', 'Innovative GLP-1 drugs', '$0 savings cards for eligible patients', '+26% revenue growth shows drug demand'],
    cons: ['GLP-1 drugs very expensive without help', 'Supply shortages for popular drugs', 'Insurance coverage varies wildly', 'High demand = access challenges'],
    accreditations: ['FDA approved', 'EMA approved'],
    yearsInBusiness: 101,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'eli-lilly',
    name: 'Eli Lilly',
    description: 'Fastest-growing major pharma (+32% in 2024). Makers of Mounjaro, Zepbound, and affordable insulin. Industry leader in patient assistance.',
    category: 'pharma',
    services: ['Diabetes medications', 'Obesity treatments (Mounjaro, Zepbound)', 'Oncology', 'Immunology', 'Patient assistance'],
    pricingDisplay: '$35 insulin cap available',
    pricingNotes: 'Lilly Cares provides free medications to qualifying patients. Pioneered $35/month insulin cap. Mounjaro assistance available.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['Global'],
    url: 'https://www.lilly.com',
    referralType: 'direct_link',
    ourTake: 'Lilly is the pharma success story of 2024 - 32% revenue growth driven by Mounjaro/Zepbound for weight loss. They also made waves with their $35 insulin cap, proving patient affordability can coexist with profits. Their Lilly Cares program is among the best in the industry. If cost is a barrier, always check Lilly Cares first.',
    bestFor: ['Diabetes care', 'Weight loss (Mounjaro/Zepbound)', 'Affordable insulin'],
    pros: ['$35 insulin program (industry-leading)', 'Best patient assistance in industry', 'Innovative weight loss drugs', '+32% growth shows drug effectiveness', 'Transparent pricing initiatives'],
    cons: ['Mounjaro expensive without coverage ($1,000+/mo)', 'Supply issues for popular drugs', 'Some specialty drugs hard to access'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 148,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'abbvie',
    name: 'AbbVie',
    description: '#2 pharma by 2024 Rx revenue ($52.7B). Known for immunology blockbusters Humira, Skyrizi, Rinvoq. Best-in-class patient support for rheumatology.',
    category: 'pharma',
    services: ['Immunology (Humira, Skyrizi, Rinvoq)', 'Oncology', 'Neuroscience', 'Eye care', 'Patient assistance'],
    pricingDisplay: 'Biologics: $5,000-8,000/mo list',
    pricingNotes: 'myAbbVie Assist provides FREE medications to eligible patients. Ambassador nurses help navigate insurance. Helped 235,000+ patients in 2024.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.abbvie.com',
    referralType: 'direct_link',
    ourTake: 'AbbVie\'s Humira was the world\'s best-selling drug for years. Now facing biosimilar competition (which means cheaper alternatives!), but their newer drugs Skyrizi and Rinvoq are excellent. The real story: myAbbVie Assist helped 235,000+ people get FREE medications in 2024. Their nurse ambassador program is genuinely helpful for navigating the system.',
    bestFor: ['Autoimmune diseases', 'Rheumatoid arthritis', 'Psoriasis', 'Crohn\'s disease'],
    pros: ['myAbbVie Assist helped 235K+ patients (2024)', 'Nurse ambassador support included', 'Specialty pharmacy coordination', 'Copay assistance available', 'Humira biosimilars = cheaper options'],
    cons: ['Biologics are very expensive without help', 'Requires specialty pharmacy', 'Prior authorization often needed', 'Application process takes time'],
    accreditations: ['FDA approved', 'Best-in-class for Rheumatology, Gastro, Neurology (PURE 2024)'],
    yearsInBusiness: 11,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'astrazeneca',
    name: 'AstraZeneca',
    description: 'British-Swedish pharma with +18% growth in 2024 ($54.1B revenue). Strong in oncology, respiratory, and cardiovascular medications.',
    category: 'pharma',
    services: ['Oncology', 'Respiratory', 'Cardiovascular', 'Diabetes', 'Patient assistance'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'AZ&Me prescription savings program provides assistance to eligible patients. Covers most AstraZeneca medications.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.astrazeneca.com',
    referralType: 'direct_link',
    ourTake: 'AstraZeneca had one of the best 2024 performances among Big Pharma - 18% revenue growth. They\'re particularly strong in cancer drugs and respiratory treatments. Their AZ&Me program can help significantly with costs. If you have cancer, lung disease, or heart conditions, check if your medication qualifies for AZ&Me assistance.',
    bestFor: ['Cancer treatment', 'Respiratory conditions (asthma, COPD)', 'Heart disease'],
    pros: ['+18% revenue growth (2024) shows drug effectiveness', 'Strong oncology pipeline', 'Respiratory expertise', 'AZ&Me patient assistance program', 'Active R&D investment'],
    cons: ['Specialty drugs expensive without assistance', 'Complex insurance navigation', 'Some supply constraints', 'Less consumer brand awareness'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 25,
    featured: true,
    lastVerified: '2024-12-21',
  },

  // -----------------------------------------------------------------------------
  // ADDITIONAL MAJOR PHARMA COMPANIES
  // -----------------------------------------------------------------------------
  {
    slug: 'merck',
    name: 'Merck & Co.',
    description: 'Global pharmaceutical company. Makers of Keytruda (revolutionary cancer immunotherapy), Gardasil (HPV vaccine), and essential medications.',
    category: 'pharma',
    services: ['Vaccines (Gardasil, Pneumovax)', 'Oncology (Keytruda)', 'Infectious disease', 'Cardiovascular', 'Patient assistance'],
    pricingDisplay: 'Keytruda: $10,000+/mo list',
    pricingNotes: 'Merck Patient Assistance Program provides free medications to eligible patients. Covers Keytruda and most Merck products.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.merck.com',
    referralType: 'direct_link',
    ourTake: 'Merck is behind Keytruda - one of the most important cancer immunotherapy drugs ever developed. It\'s revolutionized treatment for many cancers but costs $10,000+/month. Their patient assistance program covers Keytruda and most products. Also makes Gardasil (HPV vaccine) and many essential medications.',
    bestFor: ['Cancer treatment (Keytruda)', 'Vaccines (Gardasil, flu)', 'HIV treatment'],
    pros: ['Keytruda leader in cancer immunotherapy', 'Strong vaccine portfolio', 'Patient assistance available for expensive drugs', 'Global access programs'],
    cons: ['Keytruda very expensive without help', 'Complex oncology navigation', 'Insurance approval can be slow', 'Specialty pharmacy required for some'],
    accreditations: ['FDA approved', 'WHO prequalified'],
    yearsInBusiness: 133,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'amgen',
    name: 'Amgen',
    description: 'Pioneer biotech company (+17% growth in 2024). Leaders in biologics for cancer, bone health, and inflammatory conditions.',
    category: 'pharma',
    services: ['Oncology', 'Bone health (Prolia, Evenity)', 'Inflammatory conditions', 'Cardiovascular', 'Biosimilars', 'Patient assistance'],
    pricingDisplay: 'Biologics: $1,000-3,000/mo',
    pricingNotes: 'Amgen Safety Net Foundation provides free medications to qualifying patients. AMGEN FIRST STEP program offers copay assistance.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.amgen.com',
    referralType: 'direct_link',
    ourTake: 'Amgen is a biotech pioneer with 17% revenue growth in 2024. They\'re particularly important for bone health (Prolia, Evenity for osteoporosis) and have a growing biosimilar portfolio offering cheaper alternatives to expensive drugs. Their Safety Net Foundation and FIRST STEP copay program can significantly reduce costs.',
    bestFor: ['Bone health/osteoporosis', 'Cancer treatment', 'Inflammatory conditions', 'Biosimilar alternatives'],
    pros: ['+17% revenue growth (2024)', 'Safety Net Foundation for free meds', 'FIRST STEP copay assistance', 'Strong biosimilar portfolio (cheaper alternatives)', 'Pioneer biotech with decades of experience'],
    cons: ['Biologics expensive without help', 'Specialty pharmacy often required', 'Some drugs have complex dosing', 'Insurance navigation needed'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 44,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'gilead',
    name: 'Gilead Sciences',
    description: 'Leader in HIV treatment and prevention (Biktarvy, Descovy for PrEP). Also strong in hepatitis C cures and oncology.',
    category: 'pharma',
    services: ['HIV treatment & prevention', 'Hepatitis C', 'Oncology', 'COVID-19 (Veklury)', 'Patient assistance'],
    pricingDisplay: 'HIV drugs: $2,000-4,000/mo list',
    pricingNotes: 'Gilead Advancing Access provides free medications and copay assistance. Covers HIV, Hep C, and other products. PrEP assistance available.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['Global'],
    url: 'https://www.gilead.com',
    referralType: 'direct_link',
    ourTake: 'If you or someone you know needs HIV treatment or prevention (PrEP), Gilead is the most important pharma company to know. Their Advancing Access program provides medications free or at low cost to qualifying patients. They also cured millions of Hepatitis C - literally cured, not just treated. Strong patient assistance programs.',
    bestFor: ['HIV treatment', 'HIV prevention (PrEP)', 'Hepatitis C cure', 'Affordable antiviral access'],
    pros: ['Leader in HIV (Biktarvy, Descovy)', 'Hepatitis C cures', 'Strong Advancing Access patient assistance', 'PrEP affordability programs', 'Copay assistance available'],
    cons: ['HIV drugs very expensive without help', 'Must navigate assistance programs', 'Some insurance gaps for PrEP', 'Specialty pharmacy may be required'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 37,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'regeneron',
    name: 'Regeneron Pharmaceuticals',
    description: 'Innovative biotech known for Eylea (eye disease), Dupixent (eczema/asthma, with Sanofi), and COVID-19 antibody treatments.',
    category: 'pharma',
    services: ['Eye disease (Eylea)', 'Eczema/asthma (Dupixent)', 'Allergies', 'Oncology', 'Patient assistance'],
    pricingDisplay: 'Dupixent: $3,000+/mo list',
    pricingNotes: 'EYLEA4U and Dupixent MyWay programs provide copay assistance and patient support. My Regeneron Support offers navigation help.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.regeneron.com',
    referralType: 'direct_link',
    ourTake: 'Regeneron makes game-changing drugs for conditions that used to have limited options. Eylea transformed treatment for macular degeneration. Dupixent (with Sanofi) has been life-changing for severe eczema and asthma patients. Their patient support programs - EYLEA4U and Dupixent MyWay - help with copays and access.',
    bestFor: ['Eye diseases (macular degeneration)', 'Severe eczema', 'Uncontrolled asthma', 'Allergies'],
    pros: ['Innovative drugs for underserved conditions', 'EYLEA4U copay assistance', 'Dupixent MyWay program', 'Strong R&D pipeline', 'Good patient support navigation'],
    cons: ['Dupixent expensive without coverage', 'Specialty drugs require specific access', 'Insurance coverage varies', 'Prior authorization common'],
    accreditations: ['FDA approved', 'Best-in-class for Dermatology (PURE 2024, with Sanofi)'],
    yearsInBusiness: 36,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'bristol-myers-squibb',
    name: 'Bristol Myers Squibb',
    description: 'Powerhouse in cancer treatment (Opdivo, Yervoy, Revlimid) and blood disorders. Strong patient access support programs.',
    category: 'pharma',
    services: ['Oncology (Opdivo, Yervoy)', 'Hematology (Revlimid)', 'Immunology', 'Cardiovascular', 'Patient assistance'],
    pricingDisplay: 'Cancer drugs: $10,000+/mo',
    pricingNotes: 'BMS Access Support provides patient assistance, copay help, and nurse support. Covers most oncology products.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.bms.com',
    referralType: 'direct_link',
    ourTake: 'BMS is a cancer treatment powerhouse - Opdivo and Yervoy are critical immunotherapy drugs, and Revlimid treats blood cancers. These drugs are expensive ($10,000+/month) but their Access Support program is comprehensive. If you\'re facing a BMS specialty drug cost, definitely explore their assistance. Includes nurse support for complex treatments.',
    bestFor: ['Cancer treatment', 'Blood disorders (multiple myeloma)', 'Heart conditions'],
    pros: ['Strong oncology portfolio', 'Comprehensive BMS Access Support', 'Copay assistance available', 'Nurse support programs', 'Covers most expensive drugs'],
    cons: ['Specialty drugs very expensive', 'Complex insurance navigation', 'Prior authorization barriers', 'Specialty pharmacy required'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 137,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'gsk',
    name: 'GSK (GlaxoSmithKline)',
    description: 'British pharmaceutical company leading in vaccines (Shingrix, flu), respiratory medications, and HIV treatments (ViiV Healthcare).',
    category: 'pharma',
    services: ['Vaccines (Shingrix, flu)', 'Respiratory (asthma, COPD)', 'HIV treatment (ViiV)', 'Oncology', 'Patient assistance'],
    pricingDisplay: 'Shingrix: ~$200/dose',
    pricingNotes: 'GSK For You offers patient assistance and savings programs. ViiV Healthcare (HIV) has separate assistance programs.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.gsk.com',
    referralType: 'direct_link',
    ourTake: 'GSK leads in vaccines - Shingrix (shingles prevention) is particularly important for adults 50+. If you\'re 50 or older, ask your doctor about Shingrix. They also have strong respiratory treatments for asthma/COPD. Through ViiV Healthcare (their HIV joint venture), they offer important HIV treatments with patient assistance.',
    bestFor: ['Vaccines (shingles is important for 50+)', 'Asthma/COPD', 'HIV treatment (via ViiV)'],
    pros: ['Strong vaccine portfolio', 'Shingrix highly effective (90%+ for shingles)', 'Respiratory expertise', 'GSK For You patient assistance', 'ViiV HIV programs'],
    cons: ['Shingrix can be pricey (~$200/dose x2)', 'Some products face generic competition', 'Customer service varies', 'Need to coordinate with ViiV for HIV drugs'],
    accreditations: ['FDA approved', 'WHO prequalified vaccines'],
    yearsInBusiness: 24,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'sanofi',
    name: 'Sanofi',
    description: 'French pharmaceutical company known for Dupixent (with Regeneron), diabetes care (Lantus), vaccines, and rare disease treatments.',
    category: 'pharma',
    services: ['Immunology (Dupixent)', 'Diabetes (Lantus)', 'Vaccines', 'Rare diseases', 'Patient assistance'],
    pricingDisplay: 'Dupixent: $3,000+/mo list',
    pricingNotes: 'Sanofi Patient Connection provides assistance for qualifying patients. Dupixent MyWay (with Regeneron) for eczema/asthma drugs.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.sanofi.com',
    referralType: 'direct_link',
    ourTake: 'Sanofi is a major player in diabetes (Lantus insulin), vaccines, and rare diseases. Their Dupixent (partnered with Regeneron) has been a game-changer for severe eczema and asthma. Patient assistance is available but can be complex to navigate - they have multiple programs for different drug categories.',
    bestFor: ['Diabetes management (Lantus)', 'Eczema/allergies (Dupixent)', 'Vaccines', 'Rare diseases'],
    pros: ['Diverse portfolio', 'Rare disease expertise', 'Global vaccine leader', 'Dupixent MyWay program', 'Patient assistance available'],
    cons: ['Dupixent expensive without coverage', 'Multiple programs = navigation complexity', 'Some insulin products facing competition', 'Application processes vary by drug'],
    accreditations: ['FDA approved', 'Best-in-class for Dermatology (PURE 2024, with Regeneron)'],
    yearsInBusiness: 20,
    featured: false,
    lastVerified: '2024-12-21',
  },
];

export default {
  pharma: pharmaProviders,
};
