import { MedicalTourismProvider } from './types';

export const medicalTourismProviders: MedicalTourismProvider[] = [
  // DENTAL MEXICO PROVIDERS
  {
    slug: 'sani-dental',
    name: 'Sani Dental Group',
    category: 'dental-mexico',
    type: 'medical-tourism',
    description: 'Largest dental clinic network in Los Algodones with state-of-the-art facilities.',
    pricingDisplay: 'Implants from $950, crowns from $180',
    pricingComparison: 'US equivalent: Implants $3,000-5,000, crowns $1,000-1,500',
    bestFor: ['Full mouth restorations', 'Multiple implants', 'Those wanting largest clinic'],
    pros: [
      'Largest and most established clinic',
      'Multiple specialists on staff',
      'In-house dental lab for fast turnaround',
      'Free shuttle from Yuma, AZ',
    ],
    cons: [
      'Can feel like a dental factory',
      'Popular times have wait times',
      'Some upselling of additional procedures',
    ],
    ourTake: 'The Costco of dental tourism—high volume, good quality, great prices. Best for major work where efficiency matters.',
    deliveryModel: 'In-person treatment at Los Algodones clinic',
    destinationCountry: 'Mexico',
    destinationCity: 'Los Algodones',
    typicalTripLength: '3-7 days depending on procedures',
    includesInPackage: [
      'Free consultation',
      'X-rays and imaging',
      'Shuttle from Yuma, AZ',
      'Treatment coordination',
    ],
    featured: true,
  },
  {
    slug: 'pacific-implant',
    name: 'Pacific Dental Implant Center',
    category: 'dental-mexico',
    type: 'medical-tourism',
    description: 'Premium implant-focused clinic in Tijuana with US-trained surgeons.',
    pricingDisplay: 'Implants from $1,200, All-on-4 from $9,500',
    pricingComparison: 'US All-on-4: $25,000-40,000',
    bestFor: ['Complex implant cases', 'All-on-4/6 procedures', 'Those wanting premium experience'],
    pros: [
      'Surgeons trained in US',
      'Focus on complex implant cases',
      'High-end facility and equipment',
      'Excellent patient communication',
    ],
    cons: [
      'Higher prices than budget options',
      'Located in Tijuana (requires more travel)',
      'May have longer wait for appointments',
    ],
    ourTake: 'When you need the best for complex cases. Worth the premium for All-on-4 and full-arch restorations.',
    deliveryModel: 'Premium in-person care at Tijuana clinic',
    destinationCountry: 'Mexico',
    destinationCity: 'Tijuana',
    typicalTripLength: '5-10 days for implant cases',
    includesInPackage: [
      '3D CT scan',
      'Surgical guide fabrication',
      'Temporary prosthetics',
      'Post-op care kit',
      'Ground transportation',
    ],
    featured: true,
  },
  {
    slug: 'dental-brush',
    name: 'Dental Brush Tijuana',
    category: 'dental-mexico',
    type: 'medical-tourism',
    description: 'Modern clinic in Tijuana known for cosmetic dentistry and smile makeovers.',
    pricingDisplay: 'Veneers from $350, crowns from $200',
    pricingComparison: 'US veneers: $1,500-2,500 each',
    bestFor: ['Cosmetic dentistry', 'Veneers', 'Smile makeovers'],
    pros: [
      'Excellent cosmetic results',
      'Modern, Instagram-worthy facility',
      'Strong before/after portfolio',
      'Bilingual staff throughout',
    ],
    cons: [
      'Focused more on cosmetic than restorative',
      'Can push cosmetic upgrades',
      'Tijuana location requires border crossing',
    ],
    ourTake: 'The go-to for cosmetic work. Their veneer results rival Beverly Hills dentists at a fraction of the cost.',
    deliveryModel: 'Cosmetic-focused care at modern Tijuana facility',
    destinationCountry: 'Mexico',
    destinationCity: 'Tijuana',
    typicalTripLength: '2-5 days for cosmetic work',
    includesInPackage: [
      'Digital smile design',
      'Temporary veneers same-day',
      'Hotel recommendations',
      'Transportation coordination',
    ],
    featured: false,
  },
  {
    slug: 'dental-destinations-cancun',
    name: 'Dental Destinations Cancun',
    category: 'dental-mexico',
    type: 'medical-tourism',
    description: 'Combine dental work with beach vacation in Cancun\'s hotel zone.',
    pricingDisplay: 'Implants from $1,100, crowns from $250',
    pricingComparison: 'Similar to other Mexico options plus vacation value',
    bestFor: ['Those wanting vacation combo', 'Snowbirds', 'Couples/families'],
    pros: [
      'Beach vacation destination',
      'All-inclusive resort options nearby',
      'Direct flights from most US cities',
      'English widely spoken',
    ],
    cons: [
      'Higher travel costs than border clinics',
      'More touristy area',
      'Slightly higher dental prices',
    ],
    ourTake: 'Perfect if you\'re going to Cancun anyway or want to make dental work feel like a vacation. The total trip cost can still beat US prices.',
    deliveryModel: 'Vacation-style dental tourism in resort area',
    destinationCountry: 'Mexico',
    destinationCity: 'Cancun',
    typicalTripLength: '5-7 days (includes beach time)',
    includesInPackage: [
      'Airport pickup',
      'Resort hotel partnerships',
      'Flexible scheduling around activities',
      'Concierge service',
    ],
    featured: false,
  },

  // HAIR TURKEY PROVIDERS
  {
    slug: 'vera-clinic',
    name: 'Vera Clinic',
    category: 'hair-turkey',
    type: 'medical-tourism',
    description: 'High-volume Istanbul clinic with proprietary techniques and strong results.',
    pricingDisplay: '$2,500-4,500 all-inclusive',
    pricingComparison: 'US/UK equivalent: $10,000-25,000',
    bestFor: ['First-time transplants', 'Those wanting proven results', 'Budget-conscious patients'],
    pros: [
      'Proprietary OxyCure technique',
      'High volume means lots of experience',
      'Strong before/after gallery',
      'All-inclusive packages',
    ],
    cons: [
      'High volume can feel impersonal',
      'Doctor may not do entire procedure',
      'Long days during procedure',
    ],
    ourTake: 'One of the most reliable choices for first-timers. Their volume means they\'ve seen every hair type and situation.',
    deliveryModel: 'All-inclusive medical tourism package',
    destinationCountry: 'Turkey',
    destinationCity: 'Istanbul',
    typicalTripLength: '3-4 days',
    includesInPackage: [
      'Airport VIP transfers',
      '5-star hotel accommodation',
      'All procedure costs',
      'PRP treatment',
      'Medications and aftercare products',
      'Translator services',
    ],
    featured: true,
  },
  {
    slug: 'asmed',
    name: 'ASMED Surgical Medical Center',
    category: 'hair-turkey',
    type: 'medical-tourism',
    description: 'Premium clinic led by Dr. Koray Erdogan, known for natural hairline design.',
    pricingDisplay: '$4,000-8,000 depending on grafts',
    pricingComparison: 'Premium Turkey pricing but still 50%+ savings vs US',
    bestFor: ['Those wanting premium experience', 'Difficult cases', 'Natural hairline priority'],
    pros: [
      'Dr. Erdogan personally involved',
      'Known for natural-looking hairlines',
      'Lower graft counts with high density',
      'Smaller patient volume, more attention',
    ],
    cons: [
      'Higher price than budget options',
      'Longer wait times for appointments',
      'More selective about candidates',
    ],
    ourTake: 'The premium choice when hairline design matters most. Worth the extra cost for front/facial work.',
    deliveryModel: 'Boutique medical tourism experience',
    destinationCountry: 'Turkey',
    destinationCity: 'Istanbul',
    typicalTripLength: '3-4 days',
    includesInPackage: [
      'Private transfers',
      'Luxury hotel accommodation',
      'Pre-op blood tests',
      'Procedure and medications',
      'Aftercare package',
      'Personal coordinator',
    ],
    featured: true,
  },
  {
    slug: 'smile-hair',
    name: 'Smile Hair Clinic',
    category: 'hair-turkey',
    type: 'medical-tourism',
    description: 'Large-scale clinic with competitive pricing and extensive graft capabilities.',
    pricingDisplay: '$1,800-3,500 all-inclusive',
    pricingComparison: 'Among the most affordable quality options',
    bestFor: ['Budget-focused patients', 'Large graft needs', 'Straightforward cases'],
    pros: [
      'Very competitive pricing',
      'Can handle large graft sessions',
      'Quick booking availability',
      'Comprehensive packages',
    ],
    cons: [
      'Very high volume operation',
      'Less personalized experience',
      'Quality can vary by technician',
    ],
    ourTake: 'Best value option for straightforward cases. If you\'re not a complex case, you can get great results at budget prices.',
    deliveryModel: 'High-volume all-inclusive packages',
    destinationCountry: 'Turkey',
    destinationCity: 'Istanbul',
    typicalTripLength: '2-3 days',
    includesInPackage: [
      'Airport transfers',
      '4-star hotel',
      'Procedure and PRP',
      'Medications',
      'Translator',
    ],
    featured: false,
  },
  {
    slug: 'dr-serkan-aygin',
    name: 'Dr. Serkan Aygin Clinic',
    category: 'hair-turkey',
    type: 'medical-tourism',
    description: 'Award-winning clinic with 25+ years experience and celebrity clientele.',
    pricingDisplay: '$3,500-6,000 all-inclusive',
    pricingComparison: 'Mid-premium pricing with strong reputation',
    bestFor: ['Those wanting established reputation', 'Complex cases', 'Beard/eyebrow transplants'],
    pros: [
      'Multi-award winning clinic',
      '25+ years of experience',
      'Excellent for facial hair transplants',
      'Strong international reputation',
    ],
    cons: [
      'Dr. Aygin oversees but technicians do work',
      'Premium pricing',
      'Busy schedule means less flexibility',
    ],
    ourTake: 'A safe, reputable choice with decades of proven results. Good for those who value established track record.',
    deliveryModel: 'Premium all-inclusive medical tourism',
    destinationCountry: 'Turkey',
    destinationCity: 'Istanbul',
    typicalTripLength: '3-4 days',
    includesInPackage: [
      'VIP airport transfers',
      '5-star hotel',
      'All procedure costs',
      'PRP and mesotherapy',
      'Aftercare products for 12 months',
      'Dedicated patient coordinator',
    ],
    featured: false,
  },

  // BARIATRIC MEXICO PROVIDERS
  {
    slug: 'mexico-bariatric-center',
    name: 'Mexico Bariatric Center',
    category: 'bariatric-mexico',
    type: 'medical-tourism',
    description: 'Leading bariatric surgery center in Tijuana with experienced surgeons and modern facilities.',
    pricingDisplay: 'Gastric sleeve from $4,500, bypass from $6,500',
    pricingComparison: 'US gastric sleeve: $15,000-25,000',
    bestFor: ['First-time bariatric patients', 'Those wanting established program', 'Comprehensive aftercare'],
    pros: [
      'Highly experienced surgeons',
      'Modern hospital facilities',
      'Strong aftercare program',
      'Large patient community for support',
    ],
    cons: [
      'High volume can reduce personalization',
      'Tijuana requires border crossing',
      'Some patients prefer smaller clinics',
    ],
    ourTake: 'The industry leader in Mexico bariatric surgery. Their volume means expertise, and their aftercare sets them apart.',
    deliveryModel: 'Comprehensive bariatric surgery package',
    destinationCountry: 'Mexico',
    destinationCity: 'Tijuana',
    typicalTripLength: '3-5 days',
    includesInPackage: [
      'Airport transportation',
      'Hospital stay (2-3 nights)',
      'All surgical fees',
      'Pre-op testing',
      'Nutritionist consultation',
      'Post-op vitamins and supplements',
      'Lifetime aftercare support',
    ],
    featured: true,
  },
  {
    slug: 'alo-bariatrics',
    name: 'ALO Bariatrics',
    category: 'bariatric-mexico',
    type: 'medical-tourism',
    description: 'Premium bariatric center in Guadalajara with luxury experience and comprehensive care.',
    pricingDisplay: 'Gastric sleeve from $5,900, bypass from $7,500',
    pricingComparison: 'Premium Mexico pricing but luxury experience',
    bestFor: ['Those wanting premium experience', 'Patients prioritizing comfort', 'Comprehensive program seekers'],
    pros: [
      'Luxury recovery facilities',
      'Comprehensive pre/post care',
      'Not on the border (feels less clinical)',
      'Strong online patient community',
    ],
    cons: [
      'Higher prices than budget options',
      'Guadalajara requires flight',
      'May have longer wait times',
    ],
    ourTake: 'The premium experience in Mexico bariatrics. Worth it if you want the best facilities and don\'t mind paying more.',
    deliveryModel: 'Luxury all-inclusive bariatric experience',
    destinationCountry: 'Mexico',
    destinationCity: 'Guadalajara',
    typicalTripLength: '4-6 days',
    includesInPackage: [
      'Private airport transfers',
      'Luxury recovery suites',
      'All surgical and hospital fees',
      'Nutritionist and psychologist consultations',
      'Post-op vitamins (6 months)',
      'Compression garments',
      '24/7 patient support line',
    ],
    featured: true,
  },
  {
    slug: 'renew-bariatrics',
    name: 'Renew Bariatrics',
    category: 'bariatric-mexico',
    type: 'medical-tourism',
    description: 'Patient-focused bariatric center in Tijuana with strong online presence and support groups.',
    pricingDisplay: 'Gastric sleeve from $4,200, bypass from $5,900',
    pricingComparison: 'Competitive pricing with strong community',
    bestFor: ['Budget-conscious patients', 'Those wanting community support', 'Social media active patients'],
    pros: [
      'Competitive pricing',
      'Active patient community',
      'Strong social media presence',
      'Transparent process',
    ],
    cons: [
      'Newer than some competitors',
      'Tijuana location',
      'Less luxurious facilities',
    ],
    ourTake: 'Great value option with an engaged community. The Facebook groups provide invaluable peer support.',
    deliveryModel: 'Value-focused bariatric packages',
    destinationCountry: 'Mexico',
    destinationCity: 'Tijuana',
    typicalTripLength: '3-4 days',
    includesInPackage: [
      'Ground transportation',
      'Hospital stay',
      'Surgery and anesthesia',
      'Pre-op labs',
      'Post-op care package',
      'Online support group access',
    ],
    featured: false,
  },

  // PLASTIC KOREA PROVIDERS
  {
    slug: 'jk-plastic-surgery',
    name: 'JK Plastic Surgery',
    category: 'plastic-korea',
    type: 'medical-tourism',
    description: 'Luxury plastic surgery center in Gangnam known for natural-looking results.',
    pricingDisplay: 'Rhinoplasty from $4,000, double eyelid from $2,000',
    pricingComparison: 'US rhinoplasty: $8,000-15,000',
    bestFor: ['Those wanting natural results', 'Facial procedures', 'Luxury experience seekers'],
    pros: [
      'Natural-looking aesthetic philosophy',
      'State-of-the-art facilities',
      'English-speaking coordinators',
      'Located in upscale Gangnam',
    ],
    cons: [
      'Premium pricing for Korea',
      'Can be busy with international patients',
      'Recovery support extra cost',
    ],
    ourTake: 'Among the best for facial work with natural results. Their philosophy avoids the overdone look.',
    deliveryModel: 'Premium medical tourism in Gangnam',
    destinationCountry: 'South Korea',
    destinationCity: 'Seoul',
    typicalTripLength: '7-14 days depending on procedures',
    includesInPackage: [
      'Airport pickup',
      'Consultation and imaging',
      'Surgery and anesthesia',
      'Post-op care visits',
      'Translation services',
    ],
    featured: true,
  },
  {
    slug: 'jw-plastic-surgery',
    name: 'JW Plastic Surgery',
    category: 'plastic-korea',
    type: 'medical-tourism',
    description: 'Large multi-specialty plastic surgery hospital with comprehensive services.',
    pricingDisplay: 'Facial contouring from $6,000, breast augmentation from $5,000',
    pricingComparison: 'US facial contouring: $15,000-30,000',
    bestFor: ['Multiple procedures', 'Facial bone surgery', 'Full transformation'],
    pros: [
      'Multi-specialty capabilities',
      'Can do complex combinations',
      'Large surgical team',
      'In-house recovery facilities',
    ],
    cons: [
      'Large hospital feel',
      'Less boutique experience',
      'High patient volume',
    ],
    ourTake: 'Best for those wanting multiple procedures done efficiently. Their scale allows complex combinations.',
    deliveryModel: 'Full-service plastic surgery hospital',
    destinationCountry: 'South Korea',
    destinationCity: 'Seoul',
    typicalTripLength: '10-21 days for complex work',
    includesInPackage: [
      'All consultations',
      'Surgery and hospital stay',
      'Recovery room (additional days available)',
      'Post-op treatments',
      'Translation throughout',
    ],
    featured: true,
  },
  {
    slug: 'banobagi',
    name: 'Banobagi Plastic Surgery',
    category: 'plastic-korea',
    type: 'medical-tourism',
    description: 'Established clinic known for anti-aging and facial rejuvenation procedures.',
    pricingDisplay: 'Facelift from $8,000, rhinoplasty from $3,500',
    pricingComparison: 'US facelift: $15,000-30,000',
    bestFor: ['Anti-aging procedures', 'Facial rejuvenation', 'Mature patients'],
    pros: [
      'Specializes in anti-aging',
      'Experienced with older patients',
      'Natural rejuvenation focus',
      'Long track record',
    ],
    cons: [
      'Less focus on dramatic transformations',
      'May not suit younger patients seeking changes',
      'Wait times for popular surgeons',
    ],
    ourTake: 'The go-to for natural anti-aging work. They understand what mature patients want.',
    deliveryModel: 'Premium anti-aging focused care',
    destinationCountry: 'South Korea',
    destinationCity: 'Seoul',
    typicalTripLength: '10-14 days',
    includesInPackage: [
      'Consultation and planning',
      'All surgical fees',
      'Post-op skincare treatments',
      'Recovery room option',
      'Bilingual coordinator',
    ],
    featured: false,
  },
  {
    slug: 'id-hospital',
    name: 'ID Hospital',
    category: 'plastic-korea',
    type: 'medical-tourism',
    description: 'Korea\'s largest plastic surgery hospital specializing in facial bone contouring.',
    pricingDisplay: 'Two-jaw surgery from $12,000, V-line from $5,000',
    pricingComparison: 'US two-jaw surgery: $40,000-80,000',
    bestFor: ['Facial bone surgery', 'Jaw surgery', 'Dramatic facial changes'],
    pros: [
      'World leaders in facial bone surgery',
      'Largest plastic surgery hospital in Korea',
      'Comprehensive facilities',
      'Excellent for complex cases',
    ],
    cons: [
      'Hospital environment, not boutique',
      'High volume means less personal attention',
      'Can push additional procedures',
    ],
    ourTake: 'The undisputed leaders for facial bone work. If you need jaw or facial contouring surgery, this is where to go.',
    deliveryModel: 'Major plastic surgery hospital experience',
    destinationCountry: 'South Korea',
    destinationCity: 'Seoul',
    typicalTripLength: '14-21 days for bone surgery',
    includesInPackage: [
      'Full facial analysis',
      'CT scans and imaging',
      'Surgery and ICU if needed',
      'Hospital stay',
      'Post-op care visits',
      'Patient coordinator',
    ],
    featured: false,
  },
  {
    slug: 'grand-plastic-surgery',
    name: 'GRAND Plastic Surgery',
    category: 'plastic-korea',
    type: 'medical-tourism',
    description: 'High-end clinic known for body contouring and breast procedures.',
    pricingDisplay: 'Breast augmentation from $5,500, liposuction from $3,000',
    pricingComparison: 'US breast augmentation: $8,000-15,000',
    bestFor: ['Body procedures', 'Breast surgery', 'Combined body/face work'],
    pros: [
      'Strong body contouring expertise',
      'Modern facilities',
      'Good for combination procedures',
      'Recovery care options',
    ],
    cons: [
      'Less known for facial work',
      'Premium pricing',
      'Less international patient experience',
    ],
    ourTake: 'Best Korean option for body work when combined with facial procedures. Good all-around clinic.',
    deliveryModel: 'Full-service plastic surgery clinic',
    destinationCountry: 'South Korea',
    destinationCity: 'Seoul',
    typicalTripLength: '7-14 days',
    includesInPackage: [
      'Consultation and planning',
      'Surgery and aftercare',
      'Compression garments',
      'Follow-up visits',
      'Translation services',
    ],
    featured: false,
  },

  // FERTILITY EUROPE PROVIDERS
  {
    slug: 'reprofit',
    name: 'Reprofit International',
    category: 'fertility-europe',
    type: 'medical-tourism',
    description: 'Leading Czech fertility clinic with high success rates and donor programs.',
    pricingDisplay: 'IVF from €3,500, egg donation IVF from €6,000',
    pricingComparison: 'US IVF: $15,000-25,000 per cycle',
    bestFor: ['Egg donation IVF', 'Those seeking high success rates', 'LGBTQ+ families'],
    pros: [
      'Excellent success rates',
      'Strong egg donor program',
      'LGBTQ+ friendly',
      'English widely spoken',
    ],
    cons: [
      'Czech Republic requires some travel',
      'Multiple trips often needed',
      'Anonymous donors only (Czech law)',
    ],
    ourTake: 'One of the best value propositions in fertility tourism. Their donor program is particularly strong.',
    deliveryModel: 'Comprehensive fertility treatment packages',
    destinationCountry: 'Czech Republic',
    destinationCity: 'Brno',
    typicalTripLength: '5-7 days per visit, 2-3 visits typical',
    includesInPackage: [
      'All consultations',
      'IVF procedure and monitoring',
      'Embryo transfer',
      'Medications guidance',
      'Airport transfers optional',
    ],
    featured: true,
  },
  {
    slug: 'helios-fertility',
    name: 'HELIOS Fertility Center',
    category: 'fertility-europe',
    type: 'medical-tourism',
    description: 'German precision meets fertility care at this modern Berlin clinic.',
    pricingDisplay: 'IVF from €4,500, ICSI from €5,500',
    pricingComparison: 'US IVF with ICSI: $18,000-30,000',
    bestFor: ['Those wanting German medical standards', 'Complex cases', 'PGT testing needs'],
    pros: [
      'German medical standards',
      'Advanced genetic testing',
      'Modern facilities',
      'Excellent lab technology',
    ],
    cons: [
      'Higher prices than Eastern Europe',
      'German bureaucracy',
      'Stricter regulations than some countries',
    ],
    ourTake: 'When you want the precision of German medicine. Best for complex cases requiring advanced diagnostics.',
    deliveryModel: 'Premium German fertility care',
    destinationCountry: 'Germany',
    destinationCity: 'Berlin',
    typicalTripLength: '7-10 days per visit',
    includesInPackage: [
      'Full diagnostic workup',
      'IVF/ICSI procedure',
      'Embryo freezing if applicable',
      'Follow-up consultations',
      'Detailed medical reports',
    ],
    featured: false,
  },
  {
    slug: 'clinica-tambre',
    name: 'Clinica Tambre',
    category: 'fertility-europe',
    type: 'medical-tourism',
    description: 'Madrid-based fertility clinic with personalized approach and strong success rates.',
    pricingDisplay: 'IVF from €5,000, donor egg IVF from €8,000',
    pricingComparison: 'US comparable treatment: $20,000-35,000',
    bestFor: ['Those wanting personalized care', 'Spanish-speaking patients', 'Destination treatment'],
    pros: [
      'Personalized treatment protocols',
      'Beautiful Madrid location',
      'Strong international reputation',
      'Known donor options available',
    ],
    cons: [
      'Higher prices than Czech/Greek options',
      'Spanish holidays affect scheduling',
      'Popular clinic can have waits',
    ],
    ourTake: 'Great choice if you want to combine treatment with time in Spain. Their personalized approach stands out.',
    deliveryModel: 'Boutique fertility care in Spain',
    destinationCountry: 'Spain',
    destinationCity: 'Madrid',
    typicalTripLength: '7-10 days',
    includesInPackage: [
      'Personalized treatment protocol',
      'All monitoring and procedures',
      'Embryo vitrification',
      'English-speaking care team',
      'Follow-up support',
    ],
    featured: true,
  },
  {
    slug: 'barcelona-ivf',
    name: 'Barcelona IVF',
    category: 'fertility-europe',
    type: 'medical-tourism',
    description: 'Innovative fertility clinic in Barcelona with focus on minimal stimulation IVF.',
    pricingDisplay: 'Mini IVF from €3,000, standard IVF from €4,500',
    pricingComparison: 'Mini IVF rarely available in US, when offered $8,000+',
    bestFor: ['Those wanting less medication', 'Natural/mini IVF seekers', 'Multiple cycle planners'],
    pros: [
      'Pioneering mini-IVF protocols',
      'Less medication burden',
      'Barcelona is excellent destination',
      'Innovative approaches',
    ],
    cons: [
      'Mini IVF has lower per-cycle success',
      'May need more cycles',
      'Less suitable for low ovarian reserve',
    ],
    ourTake: 'Unique option for those who want gentler protocols. The mini-IVF approach isn\'t right for everyone but transformative for some.',
    deliveryModel: 'Innovation-focused fertility care',
    destinationCountry: 'Spain',
    destinationCity: 'Barcelona',
    typicalTripLength: '5-7 days per cycle',
    includesInPackage: [
      'Protocol customization',
      'Monitoring and retrieval',
      'Embryo transfer',
      'Cryopreservation options',
      'Remote monitoring support',
    ],
    featured: false,
  },
];
