import { Provider } from './types';

// =============================================================================
// LABS (Telehealth)
// =============================================================================

export const labsProviders: Provider[] = [
  {
    slug: 'superpower',
    name: 'SuperPower',
    description: 'Annual membership offering 100+ biomarker testing with AI-powered insights and personalized health plans.',
    category: 'labs',
    services: ['100+ biomarkers', 'Annual comprehensive panel', 'AI-powered insights', 'Personalized health plans', 'Quest Diagnostics partnership'],
    pricingDisplay: '$17/month',
    pricingNotes: 'Billed annually at $199. One comprehensive 100+ biomarker test per year. Additional tests $179 each.',
    pricingComparison: 'vs $1,000+ for similar testing through traditional healthcare',
    savingsPercent: 80,
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National - 3,000+ Quest locations'],
    url: 'https://superpower.com',
    referralType: 'affiliate_link',
    ourTake: 'SuperPower is the most affordable comprehensive testing option at just $17/month (billed annually at $199). You get one massive 100+ biomarker panel annually through Quest Labs, plus AI-driven insights and actionable health plans. The catch: only one test per year unless you pay $179 for additional tests. Best for annual baseline tracking on a budget.',
    bestFor: ['Budget-conscious', 'Annual comprehensive baseline', 'AI-driven recommendations'],
    pros: ['Most affordable ($17/month)', '100+ biomarkers in one draw', 'Quest partnership (3,000 locations)', 'AI-powered personalized plans', 'HSA/FSA eligible'],
    cons: ['Only one test per year', 'Additional tests cost $179', 'No physician consultation included', 'Heavy supplement upselling reported ($400+/month)'],
    procedureVolume: 'New startup (2024 launch)',
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'rythm-health',
    name: 'Rythm Health',
    description: 'Innovative at-home blood testing using needle-free device with monthly tracking capability.',
    category: 'labs',
    services: ['Needle-free blood collection', 'Monthly tracking', 'AI coach', 'Comprehensive biomarkers'],
    pricingDisplay: '$79/month',
    pricingNotes: 'Per comprehensive test. Ideal for monthly tracking.',
    pricingComparison: 'Affordable option for frequent tracking',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://rythmhealth.com',
    referralType: 'direct_link',
    ourTake: 'Rythm Health stands out for their needle-free blood collection device—92% of users prefer it over traditional needlesticks. At $79 per month, it\'s affordable for monthly tracking. Results in 7 days with AI coach to interpret. The device has 95-99% concordance with traditional lab draws. Best for those who want frequent testing without the pain of venipuncture.',
    bestFor: ['Needle-phobic', 'Monthly tracking', 'Frequent testing', 'Prefer at-home collection'],
    pros: ['Needle-free device (pain-free)', '95-99% accuracy vs venipuncture', 'Fast results (7 days)', 'AI coach included', 'Free Uber pickup'],
    cons: ['Limited test panel vs competitors', 'No high-sensitivity CRP or A1c', 'No app (web-only)', 'New company (less established)'],
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'marek-health',
    name: 'Marek Health',
    description: 'Comprehensive blood panels with physician consultation and personalized optimization protocols. Nearly 300 biomarkers available.',
    category: 'labs',
    services: ['Comprehensive panels', 'Hormone testing', 'Metabolic markers', 'Genetic analysis', 'Physician consultation', 'Monthly coaching'],
    pricingDisplay: '$250-850/panel',
    pricingNotes: 'Includes physician review and consultation. Follow-up labs $200+',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National (except NY, NJ, RI)'],
    url: 'https://marekhealth.com',
    referralType: 'affiliate_link',
    ourTake: 'Marek is the gold standard for comprehensive hormone and health optimization. You pay more, but you get physician consultation, nearly 300 biomarkers to choose from, and ongoing coaching. Best for serious optimizers who want guidance, not just data.',
    bestFor: ['Comprehensive testing', 'Hormone optimization', 'Want physician guidance'],
    pros: ['Most comprehensive biomarker selection', 'Physician consultation included', 'Monthly coaching check-ins', '5-star Trustpilot (800+ reviews)'],
    cons: ['Higher price point', 'Not available in NY, NJ, RI', '14-day turnaround', 'Can be overkill for basic testing'],
    accreditations: ['LabCorp partnership'],
    procedureVolume: '10,000+ patients',
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'function-health',
    name: 'Function Health',
    description: 'Membership-based platform offering 100+ lab tests twice yearly with AI-powered insights and action plans.',
    category: 'labs',
    services: ['100+ biomarkers', 'Heart health', 'Hormones', 'Thyroid', 'Cancer markers', 'Nutrients', 'Aging factors'],
    pricingDisplay: '$499/year',
    pricingNotes: 'Includes 2 comprehensive assessments per year. Additional $99 for mobile blood draw.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National (except NY, NJ)'],
    url: 'https://functionhealth.com',
    referralType: 'affiliate_link',
    ourTake: 'Function Health is the buzzy longevity-focused option backed by celebrity investors. Great value at $499/year for 100+ tests twice yearly. The catch: no direct physician access - you get AI insights and need to bring results to your own doctor.',
    bestFor: ['Longevity-focused', 'Annual comprehensive testing', 'Self-directed health'],
    pros: ['100+ biomarkers for $499/year', '50,000+ members', 'Great UI and insights', 'Quest Diagnostics labs'],
    cons: ['No direct physician consultation', 'Not in NY, NJ (or pay extra)', 'Waitlist for new members', '7-10 day turnaround'],
    procedureVolume: '50,000+ members',
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'insidetracker',
    name: 'InsideTracker',
    description: 'AI-powered blood testing platform with personalized nutrition, supplement, and exercise recommendations.',
    category: 'labs',
    services: ['Blood panels (26-48 biomarkers)', 'DNA testing', 'AI recommendations', 'Fitness optimization'],
    pricingDisplay: '$249-589/test',
    pricingNotes: 'Foundation (26 markers) or Ultimate (48 markers). DNA test available.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://insidetracker.com',
    referralType: 'affiliate_link',
    ourTake: 'InsideTracker is the OG of consumer blood testing, popular with athletes and biohackers. Strong AI-driven recommendations for nutrition and fitness. Less comprehensive than Marek or Function, but more actionable for lifestyle optimization.',
    bestFor: ['Athletes', 'Fitness optimization', 'Actionable recommendations'],
    pros: ['Strong AI recommendations', 'Good for fitness-focused users', 'Quest partnership', 'DNA integration available'],
    cons: ['Fewer biomarkers than competitors', 'No physician consultation', 'Can get expensive with add-ons'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'everlywell',
    name: 'Everlywell',
    description: 'Convenient at-home testing for specific health concerns including food sensitivities, hormones, and STDs.',
    category: 'labs',
    services: ['Food sensitivity', 'Hormone testing', 'STD testing', 'Thyroid', 'Metabolism'],
    pricingDisplay: '$49-199/test',
    pricingNotes: 'Subscription available for lower per-test pricing.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National (limited in NY)'],
    url: 'https://everlywell.com',
    referralType: 'affiliate_link',
    ourTake: 'Everlywell is the mass-market option - great for specific concerns like food sensitivities or a quick hormone check. Not for comprehensive panels, but unbeatable convenience and price for targeted testing.',
    bestFor: ['Specific health concerns', 'Food sensitivities', 'Budget-conscious'],
    pros: ['Most affordable option', 'Wide retail availability', 'Quick turnaround (5-7 days)', 'Good for single-issue testing'],
    cons: ['Not comprehensive', 'No physician support', 'Limited biomarkers per test'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'letsgetchecked',
    name: 'LetsGetChecked',
    description: 'At-home lab testing with nurse consultation included for results review and guidance.',
    category: 'labs',
    services: ['STD testing', 'Hormone panels', 'Vitamin levels', 'Thyroid', 'Liver/kidney function'],
    pricingDisplay: '$69-149/test',
    pricingNotes: 'Nurse consultation included with all tests.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://letsgetchecked.com',
    referralType: 'affiliate_link',
    ourTake: 'LetsGetChecked stands out for including nurse phone consultations with every test - you actually get to talk to someone about your results. Best for STD testing and vitamin panels where you want guidance.',
    bestFor: ['Want to talk to someone', 'STD testing', 'Vitamin/mineral levels'],
    pros: ['Nurse consultation included', 'Fast turnaround (2-5 days)', 'CAP/ISO accredited', 'Good customer support'],
    cons: ['Smaller test menu', 'Pricier than Everlywell', 'No comprehensive panels'],
    accreditations: ['CLIA certified', 'CAP accredited', 'ISO certified'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {"slug": "siphox-health", "name": "SiPhox Health", "description": "At-home blood testing using a needle-free EasyDraw upper-arm collection kit covering up to 61 biomarkers. Memberships bundle multiple draws per year with AI-driven insights and a personalized action plan.", "category": "labs", "services": ["Up to 61 biomarkers", "Needle-free EasyDraw collection", "Heart & metabolic panel", "Hormone panel", "Thyroid panel", "Longevity essentials", "GLP-1 monitoring", "AI health assistant"], "pricingDisplay": "$124+ per kit", "pricingNotes": "Entry kit around $124 plus shipping. Membership plans bundle multiple tests per year (e.g. semiannual ~$99/mo for 4 tests, annual ~$83/mo for 8 tests). HSA/FSA accepted.", "pricingComparison": "vs hundreds-to-thousands for comparable panels through traditional care", "deliveryModel": "telehealth_national", "geographicCoverage": ["National (state coverage policy applies)"], "url": "https://siphoxhealth.com", "referralType": "affiliate_link", "ourTake": "SiPhox is the needle-free, at-home alternative for people who want frequent biomarker tracking without a phlebotomist or a clinic trip. The EasyDraw upper-arm kit collects in about 5 minutes and covers up to 61 biomarkers across nine categories, with AI insights and supplement suggestions. Best for self-directed trackers who value convenience over a physician consult.", "bestFor": ["Needle-averse", "Frequent at-home tracking", "Self-directed optimization"], "pros": ["Needle-free at-home collection", "Up to 61 biomarkers in one draw", "Membership bundles multiple tests/year", "AI insights and action plan", "HSA/FSA eligible"], "cons": ["No included physician consultation", "7-10 day turnaround", "Per-kit price higher than walk-in lab draws", "State coverage restrictions apply"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "labcorp-ondemand", "name": "Labcorp OnDemand", "description": "Labcorp's direct-to-consumer arm letting you buy your own lab tests online without a doctor's visit or insurance. Collection happens at 2,000+ Labcorp Patient Service Centers, 400+ Labcorp at Walgreens locations, or via at-home self-collection kits.", "category": "labs", "services": ["Comprehensive health screening", "Hormone panels", "Thyroid testing", "Men's and women's health", "Sexual health / STI panels", "Heart health", "At-home self-collection kits"], "pricingDisplay": "$49-619/test", "pricingNotes": "No insurance billed; you pay directly. Comprehensive metabolic panel around $49; custom men's health panel up to ~$619. HSA/FSA eligible on most tests.", "pricingComparison": "Transparent cash pricing direct from a national reference lab", "deliveryModel": "telehealth_national", "geographicCoverage": ["National - 2,000+ Patient Service Centers plus 400+ Labcorp at Walgreens"], "url": "https://www.ondemand.labcorp.com", "referralType": "direct_link", "ourTake": "Labcorp OnDemand is the source-of-truth option: you order directly from one of the two national reference labs that already run most U.S. bloodwork, at transparent cash prices. You can collect in-person at thousands of centers or order at-home kits for select tests. Best for people who want the same lab their doctor uses, without the insurance loop.", "bestFor": ["Want a national reference lab directly", "Transparent cash pricing", "In-person draw convenience"], "pros": ["Run by Labcorp itself (no middleman)", "2,000+ centers plus Walgreens locations", "Wide test menu", "At-home kit options", "HSA/FSA eligible"], "cons": ["No insurance accepted", "Comprehensive panels can run expensive", "Insights are lighter than membership platforms", "No included coaching"], "accreditations": ["CLIA certified"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "quest-health", "name": "Quest Health", "description": "Quest Diagnostics' consumer-initiated testing platform (operated by Quest Consumer Inc.) offering 150+ lab tests you can buy online without a doctor visit. Clinical oversight is included, with collection at 2,000+ Quest locations, mobile in-home draw, or at-home kits.", "category": "labs", "services": ["150+ lab tests", "Vitamin and nutrition", "Heart health and cholesterol", "Thyroid and hormone testing", "Men's and women's health", "Fitness and performance", "STD / sexual health", "In-home Quest Mobile draw"], "pricingDisplay": "$29-599/test", "pricingNotes": "Tests start around $29-44; comprehensive panels up to ~$599. Clinical support included. Quest Mobile in-home draw adds a ~$79 fee. FSA/HSA eligible; Klarna/Affirm payment plans available.", "pricingComparison": "Cash pricing direct from a national reference lab", "deliveryModel": "telehealth_national", "geographicCoverage": ["National - 2,000+ Quest Diagnostics locations"], "url": "https://www.questhealth.com", "referralType": "direct_link", "ourTake": "Quest Health is the Quest Diagnostics equivalent of Labcorp OnDemand: buy directly from a national reference lab, no doctor visit, transparent cash prices. The 150+ test menu and 2,000+ locations make it easy to get a draw almost anywhere, and clinical oversight is included. Best for people who want the lab their physician already uses without insurance friction.", "bestFor": ["Want a national reference lab directly", "Wide test menu", "Flexible collection options"], "pros": ["Run by Quest Diagnostics directly", "150+ tests", "2,000+ locations plus in-home option", "Clinical oversight included", "FSA/HSA eligible, payment plans"], "cons": ["No insurance accepted", "In-home draw costs extra (~$79)", "Comprehensive panels can be pricey", "Lighter insights than membership platforms"], "accreditations": ["CLIA certified"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "ulta-lab-tests", "name": "Ulta Lab Tests", "description": "Direct-access lab testing partnered exclusively with Quest Diagnostics, offering 2,000+ individual tests and panels with a doctor's order included in every purchase. Draws happen at 2,100 Quest locations nationwide, with most results in 24-48 hours.", "category": "labs", "services": ["2,000+ tests and panels", "Comprehensive metabolic and lipid panels", "Hormone and thyroid testing", "Micronutrient panels", "CBC", "STD screening", "Heavy metal testing"], "pricingDisplay": "From $9/test", "pricingNotes": "Individual markers start around $9; bundled wellness panels priced higher. Frequent promotional discounts. Doctor's order included in price. Direct-pay (no insurance); HSA/FSA accepted.", "pricingComparison": "Discounts of up to ~90% vs traditional retail lab pricing", "deliveryModel": "telehealth_national", "geographicCoverage": ["National - 2,100 Quest Diagnostics locations"], "url": "https://www.ultalabtests.com", "referralType": "affiliate_link", "ourTake": "Ulta Lab Tests is the price-leader for a la carte bloodwork: order any of 2,000+ tests, get a doctor's order bundled in, then walk into one of 2,100 Quest locations. Single markers start as low as $9 and most results land in 24-48 hours. Best for budget-conscious self-trackers who know exactly which tests they want.", "bestFor": ["Budget-conscious", "A la carte specific markers", "Fast turnaround"], "pros": ["Lowest entry pricing (from $9)", "Doctor's order included", "2,100 Quest locations", "Fast results (24-48 hrs)", "Physician-reviewed before release"], "cons": ["No insurance accepted", "Less hand-holding than membership platforms", "No bundled coaching or consult", "Pricing best with promo codes"], "accreditations": ["Quest Diagnostics partnership", "CLIA certified"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "walk-in-lab", "name": "Walk-In Lab", "description": "Direct-to-consumer lab testing with no doctor's order or insurance required, fulfilled through both Quest Diagnostics and LabCorp networks. Offers 300+ tests and panels with all-inclusive transparent pricing and most results in 24-48 hours.", "category": "labs", "services": ["300+ tests and panels", "Wellness and metabolic panels", "Thyroid panels", "Hormone panels", "STD screening", "Heavy metal testing", "Food sensitivity testing", "At-home test kits"], "pricingDisplay": "From ~$29/test", "pricingNotes": "All-inclusive pricing with no separate lab, order, physician, or processing fees (excluding home kits). Comprehensive metabolic panel ~$29-49; full thyroid panel ~$79. No insurance billed; HSA/FSA accepted.", "pricingComparison": "Savings of up to ~85% vs traditional retail lab pricing", "deliveryModel": "telehealth_national", "geographicCoverage": ["National - Quest Diagnostics and LabCorp locations"], "url": "https://www.walkinlab.com", "referralType": "affiliate_link", "ourTake": "Walk-In Lab is the rare direct-access service that draws from both Quest and LabCorp, so you can pick whichever network is closer. Pricing is genuinely all-inclusive (no surprise lab or order fees), with a comprehensive metabolic panel around $29 and results in 24-48 hours. Best for people who want maximum location flexibility and upfront pricing.", "bestFor": ["Want both Quest and LabCorp options", "Transparent all-inclusive pricing", "Specific panel ordering"], "pros": ["Uses both Quest and LabCorp networks", "All-inclusive pricing (no hidden fees)", "300+ tests and panels", "Fast results (24-48 hrs)", "No doctor's order needed"], "cons": ["No insurance accepted", "No bundled physician consult", "Home kits priced separately", "Insights lighter than membership platforms"], "accreditations": ["CLIA certified"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "healthlabs", "name": "HealthLabs.com", "description": "Direct-to-consumer lab testing across 22+ categories with no doctor's referral or insurance required, fulfilled through Quest Diagnostics' national network. Transparent flat pricing with no added shipping or taxes, and results typically in 1-3 business days.", "category": "labs", "services": ["Wellness panels", "Hormone testing", "Thyroid testing", "Cardiac panels", "Diabetes panels", "Allergy testing", "STD screening", "Comprehensive STD panels"], "pricingDisplay": "From ~$29/test", "pricingNotes": "Basic panels start around $29; comprehensive hormone or allergy testing $300+. Comprehensive 10-test STD panel ~$139. The price shown is the total - no shipping, taxes, or added fees. No insurance accepted; results submittable for reimbursement.", "pricingComparison": "Same Quest/LabCorp labs at roughly 60-80% lower than retail", "deliveryModel": "telehealth_national", "geographicCoverage": ["National - 4,000+ Quest Diagnostics locations"], "url": "https://www.healthlabs.com", "referralType": "affiliate_link", "ourTake": "HealthLabs.com is a clean, transparent direct-access option built on Quest's network, with flat all-in pricing and fast 1-3 day turnaround. Its comprehensive STD panels are among the cheaper full-coverage options. Best for people who want a no-frills order-and-go experience at a national reference lab.", "bestFor": ["No-frills direct ordering", "STD panels", "Transparent flat pricing"], "pros": ["Quest Diagnostics network (4,000+ locations)", "Flat all-in pricing (no added fees)", "Fast results (1-3 days)", "Affordable comprehensive STD panels", "No doctor's order needed"], "cons": ["No insurance accepted", "No bundled physician consult", "Comprehensive panels can be pricey", "Minimal insights vs membership platforms"], "accreditations": ["CLIA certified"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "personalabs", "name": "Personalabs", "description": "Direct-access lab testing with 400+ tests orderable online without a doctor's appointment, fulfilled through LabCorp's 4,000+ U.S. locations. A physician order is included with every test, and most results return in 24-48 hours.", "category": "labs", "services": ["400+ lab tests", "Wellness checkup panels", "Hormone panels", "Thyroid testing", "Cardiac and diabetes panels", "Cancer screening markers", "Autoimmune testing", "STD screening"], "pricingDisplay": "$27-320/test", "pricingNotes": "General health tests from ~$27; basic CBC/CMP ~$30-50; wellness checkups ~$97-130; comprehensive hormone profiles ~$291-293. Physician order included. No insurance needed; HSA/FSA eligible.", "pricingComparison": "Up to ~80% savings vs hospital retail pricing", "deliveryModel": "telehealth_national", "geographicCoverage": ["National - 4,000+ LabCorp locations"], "url": "https://www.personalabs.com", "referralType": "affiliate_link", "ourTake": "Personalabs is a LabCorp-based direct-access service with a deep 400+ test menu and a physician order bundled into every purchase. Pricing is transparent and HSA/FSA-eligible, with a dedicated under-$100 category for common panels. Best for people on the LabCorp network who want a broad menu and fast 24-48 hour results.", "bestFor": ["LabCorp network users", "Broad test menu", "Want a physician order included"], "pros": ["400+ tests via LabCorp (4,000+ locations)", "Physician order included with every test", "Fast results (24-48 hrs)", "Under-$100 category for common panels", "HSA/FSA eligible"], "cons": ["No insurance accepted", "No bundled coaching or consult", "Comprehensive profiles can run $290+", "Insights lighter than membership platforms"], "accreditations": ["CLIA certified"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "choose-health", "name": "Choose Health", "description": "At-home blood testing using a finger-prick dried blood spot card that you mail back in a prepaid envelope, processed by CLIA/CAP-accredited labs. Panels span liver, metabolic, thyroid/adrenal, and male/female hormone health across roughly 100 biomarkers.", "category": "labs", "services": ["~100 biomarkers", "Finger-prick dried blood spot collection", "Liver function panel", "Metabolic panels (7 and 14 markers)", "Thyroid and adrenal panel", "Male and female hormone panels"], "pricingDisplay": "From $68/kit", "pricingNotes": "Kits start around $68 on a quarterly subscription. Finger-prick dried blood spot; no phlebotomist needed. HSA/FSA commonly accepted.", "pricingComparison": "Lower-cost at-home alternative to clinic draws", "deliveryModel": "telehealth_national", "geographicCoverage": ["National (not available in NY, RI)"], "url": "https://www.choosehealth.io", "referralType": "affiliate_link", "ourTake": "Choose Health (operating since 2018) is a fully at-home, finger-prick option for people who want to avoid both needles and clinic trips entirely. Panels run from focused 4-marker thyroid/adrenal checks to 20+ marker liver panels, processed by CLIA/CAP labs with 90-99% correlation to venous draws. Best for budget at-home tracking of metabolic and hormone markers.", "bestFor": ["Fully at-home collection", "Metabolic and hormone tracking", "Budget-conscious"], "pros": ["Finger-prick dried blood spot (no needle, no clinic)", "Kits from $68 on subscription", "~100 biomarkers across panels", "CLIA/CAP-accredited labs", "Established since 2018"], "cons": ["Not available in NY, RI", "Dried blood spot has correlation limits vs venous", "No bundled physician consult", "3-5 day processing after lab receipt"], "accreditations": ["CLIA certified", "CAP accredited"], "yearsInBusiness": 8, "featured": false, "lastVerified": "2026-06-25"},
];

// =============================================================================
// GLP-1 PROGRAMS (Telehealth)
// =============================================================================

export const glp1Providers: Provider[] = [
  {
    slug: 'hims-hers-glp1',
    name: 'Hims / Hers',
    description: 'Popular telehealth platform offering compounded semaglutide at competitive prices, plus brand-name options.',
    category: 'glp1',
    services: ['Compounded semaglutide', 'Brand Wegovy/Ozempic', 'Provider consultations', 'Ongoing support'],
    pricingDisplay: '$199/mo (compound)',
    pricingNotes: 'Compounded: $199/mo with 6-month plan. Brand Wegovy: $1,799/mo. Brand Ozempic: $1,799/mo.',
    pricingComparison: 'vs $1,000+/mo for brand without insurance',
    savingsPercent: 80,
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://hims.com/weight-loss',
    referralType: 'affiliate_link',
    ourTake: 'Hims/Hers is the most recognizable name in telehealth GLP-1s. Their compounded semaglutide at $199/mo is competitive, and they now offer brand-name access too. Good for those who want a mainstream, well-funded platform.',
    bestFor: ['Budget compound option', 'Brand-name access', 'Mainstream platform'],
    pros: ['Recognizable brand', 'Both compound and brand options', 'Good mobile app', 'Fast shipping'],
    cons: ['No insurance accepted', 'Compounded = not FDA-approved', '6-month commitment for best price'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'ro-body',
    name: 'Ro Body Program',
    description: 'Telehealth weight loss program with access to brand-name GLP-1s through NovoCare pharmacy partnership.',
    category: 'glp1',
    services: ['Wegovy', 'Ozempic', 'Coaching', 'Provider support'],
    pricingDisplay: '$145/mo + meds',
    pricingNotes: 'First month $99, then $145/mo for program. Brand meds via NovoCare: $499/mo (reduced from $1,000+).',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://ro.co/weight-loss',
    referralType: 'affiliate_link',
    ourTake: 'Ro has a unique angle: partnership with NovoCare gives access to real Wegovy/Ozempic at $499/mo instead of $1,000+. If you want brand-name medications without insurance, this is currently the best path.',
    bestFor: ['Brand-name GLP-1 access', 'Cash-pay for real Wegovy', 'Established telehealth'],
    pros: ['Brand-name meds at reduced price', 'NovoCare partnership', 'Established platform', 'Good support'],
    cons: ['Still expensive ($499/mo for meds)', 'No compounded option', 'Program fee on top of meds'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'noom-med',
    name: 'Noom Med',
    description: 'Behavior change app now offering compounded GLP-1 medications with integrated coaching and tracking.',
    category: 'glp1',
    services: ['Compounded semaglutide', 'Noom app access', 'Behavior coaching', 'Food logging'],
    pricingDisplay: '$149-279/mo',
    pricingNotes: 'First month $149, increases to $279 as dose increases. Includes Noom app.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://noom.com/med',
    referralType: 'affiliate_link',
    ourTake: 'Noom Med combines their popular behavior-change app with GLP-1 access. The idea is that the app helps you build habits while the medication helps with appetite. Good if you want more than just a prescription.',
    bestFor: ['Behavior change focus', 'Want coaching + meds', 'App-based tracking'],
    pros: ['Integrated behavior coaching', 'Popular app platform', 'No insurance required', 'Holistic approach'],
    cons: ['Higher price as dose increases', 'Compounded = not FDA-approved', 'May be overkill if you just want meds'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'calibrate',
    name: 'Calibrate',
    description: 'Metabolic reset program with GLP-1 prescription, bi-weekly coaching, and long-term maintenance focus.',
    category: 'glp1',
    services: ['GLP-1 prescription', 'Bi-weekly coaching', 'Metabolic health focus', 'Long-term maintenance'],
    pricingDisplay: '$199/mo',
    pricingNotes: 'Requires 3-month commitment. Medication cost depends on insurance.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://calibrate.com',
    referralType: 'affiliate_link',
    ourTake: 'Calibrate is the premium, coaching-heavy option. They focus on metabolic health and long-term maintenance, not just weight loss. Requires insurance for the medication, so not a true cash-pay option for meds.',
    bestFor: ['Coaching-focused', 'Have insurance for meds', 'Long-term metabolic health'],
    pros: ['Strong coaching program', 'Metabolic health focus', 'Maintenance planning', 'Bi-weekly sessions'],
    cons: ['Requires insurance for meds', '3-month minimum', 'Premium pricing', 'Not fully cash-pay'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'found',
    name: 'Found',
    description: 'Weight loss membership with access to various medications including GLP-1s, plus app-based coaching.',
    category: 'glp1',
    services: ['GLP-1 prescriptions', 'Other weight loss meds', 'App-based coaching', 'Provider consultations'],
    pricingDisplay: '$99-149/mo + $189/mo meds',
    pricingNotes: 'Membership required ($99-149/mo). GLP-1 medications additional ($189+/mo).',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://joinfound.com',
    referralType: 'affiliate_link',
    ourTake: 'Found takes a membership approach - you pay for access, then pay separately for medications. Good if you want flexibility in medication options, but the costs add up. 4 provider consults first month.',
    bestFor: ['Flexibility in medications', 'App-based approach', 'Multiple med options'],
    pros: ['Multiple medication options', 'Unlimited online coach access', 'Good app experience', '4 consults first month'],
    cons: ['Membership + med costs add up', 'Medication not included in base price', 'Can get expensive'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {"slug": "henry-meds-glp1", "name": "Henry Meds", "description": "Membership-free telehealth platform offering compounded semaglutide, tirzepatide, and liraglutide in injectable, oral, and sublingual forms. One bundled monthly price covers the provider visit, medication, supplies, and ongoing support.", "category": "glp1", "services": ["Compounded semaglutide (injectable, oral, sublingual)", "Compounded tirzepatide (oral)", "Compounded liraglutide (daily injectable)", "Provider visits", "Ongoing support"], "pricingDisplay": "From $179/mo", "pricingNotes": "One bundled monthly price includes provider visit, medication, supplies, and ongoing care. No separate membership fee. Compounded liraglutide from $179/mo; compounded semaglutide injectable roughly $297-397/mo by dose; oral/sublingual and tirzepatide options priced higher. Multi-month prepay discounts available.", "pricingComparison": "vs $1,000+/mo for brand-name GLP-1s without insurance", "deliveryModel": "telehealth_national", "geographicCoverage": ["National"], "url": "https://henrymeds.com/treatments/weight-management/glp-1-weight-management/", "referralType": "affiliate_link", "ourTake": "Henry Meds is one of the cleanest pricing models in the space: no membership fee, one bundled monthly cost that includes the visit, medication, and supplies. The standout is delivery-form flexibility — injectable, oral tablet, or sublingual drops — useful if you dislike needles. Compounded only, so no brand-name access here.", "bestFor": ["No membership fee", "Needle-free options (oral/sublingual)", "Bundled all-in pricing"], "pros": ["No separate membership fee", "Bundled price (visit + meds + supplies)", "Multiple delivery forms incl. oral and sublingual", "No insurance required", "Multi-month prepay discounts"], "cons": ["Compounded only (not FDA-approved)", "No brand-name Wegovy/Zepbound", "Injectable tirzepatide not offered", "Price rises with higher doses"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "mochi-health", "name": "Mochi Health", "description": "Specialist-led telehealth weight clinic with a flat-rate compounding model and a required live video visit with a board-certified obesity-medicine provider. Membership includes provider access, dietitian coaching, and 24/7 support; medication is billed separately.", "category": "glp1", "services": ["Compounded semaglutide", "Compounded tirzepatide", "Brand Zepbound", "Board-certified obesity-medicine providers", "Registered dietitian coaching", "Insurance support"], "pricingDisplay": "$79/mo membership", "pricingNotes": "First month $39, then $79/mo membership (includes visits, messaging, RD coaching, 24/7 support). Medication billed separately: flat-rate compounded semaglutide ~$99/mo and compounded tirzepatide ~$199/mo regardless of dose, shipping included.", "pricingComparison": "Flat medication price regardless of dose titration", "deliveryModel": "telehealth_national", "geographicCoverage": ["National"], "url": "https://joinmochi.com/", "referralType": "affiliate_link", "ourTake": "Mochi differentiates on two things: a required live video visit with a board-certified obesity-medicine specialist (not just a questionnaire) and flat-rate compounded pricing that doesn't climb as your dose titrates up. Registered dietitian coaching is bundled into the $79/mo membership. Medication is a separate line item, so budget for membership plus meds.", "bestFor": ["Specialist-led care", "Flat-rate pricing through dose increases", "Want dietitian coaching included"], "pros": ["Board-certified obesity-medicine providers", "Required live video consult", "Flat compounded pricing by dose", "RD coaching included in membership", "Insurance support available"], "cons": ["Membership + medication priced separately", "Compounded options not FDA-approved", "$79/mo membership on top of meds"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "ivim-health", "name": "Ivim Health", "description": "Telehealth weight-loss program offering compounded semaglutide and tirzepatide with individualized dosing, unlimited provider visits, and 1-on-1 health coaching. Medication and program fee are bundled into one monthly price.", "category": "glp1", "services": ["Compounded semaglutide", "Compounded tirzepatide", "Compounded liraglutide", "Brand Ozempic/Wegovy/Mounjaro/Zepbound", "Unlimited provider visits", "1-on-1 health coaching"], "pricingDisplay": "From $149/mo", "pricingNotes": "Compounded semaglutide from $149/mo; compounded tirzepatide from $224/mo (medication + program fee included). Programs require 1, 2, 4, or 6-month commitments; cancellation not available once a program starts.", "pricingComparison": "Includes unlimited provider visits and coaching", "deliveryModel": "telehealth_national", "geographicCoverage": ["National"], "url": "https://www.ivimhealth.com/weightloss/", "referralType": "affiliate_link", "ourTake": "Ivim bundles medication, unlimited provider visits, and 1-on-1 coaching into a single monthly price, which simplifies budgeting versus membership-plus-meds models. Individualized dosing is the pitch. The catch worth knowing: programs lock into multi-month commitments and you cannot cancel once a program starts.", "bestFor": ["Bundled med + coaching pricing", "Unlimited provider visits", "Individualized dosing"], "pros": ["Medication + program fee bundled", "Unlimited provider visits", "1-on-1 health coaching included", "Both compounded and brand options"], "cons": ["No cancellation once program starts", "Multi-month commitment required", "Compounded options not FDA-approved"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "form-health", "name": "Form Health", "description": "Virtual obesity-medicine clinic that pairs you with an American Board of Obesity Medicine-certified physician and a registered dietitian alongside FDA-approved GLP-1 prescriptions. Built around insurance coverage, with a cash-pay program option.", "category": "glp1", "services": ["Board-certified obesity-medicine physician care", "Registered dietitian", "FDA-approved GLP-1 prescriptions (Wegovy, Zepbound, Mounjaro)", "Behavioral health support", "App-based tracking"], "pricingDisplay": "$299/mo cash-pay", "pricingNotes": "Cash-pay program is $299/mo for physician and dietitian visits, care-team messaging, and app tools; medication and lab costs are not included. Covered by most major private insurance and Medicare, in which case patients pay only copays or deductibles.", "pricingComparison": "Covered by most major private insurance and Medicare", "deliveryModel": "telehealth_national", "geographicCoverage": ["National"], "url": "https://www.formhealth.co/", "referralType": "affiliate_link", "ourTake": "Form Health is the most clinically credentialed option here: every care team is led by an American Board of Obesity Medicine-certified physician paired with a registered dietitian, and it prescribes FDA-approved brand GLP-1s rather than compounds. It is built insurance-first, so the cash-pay $299/mo (meds excluded) is steep relative to compound-focused platforms. Best when you have coverage or want true obesity-medicine specialist care.", "bestFor": ["Insurance-covered care", "Board-certified obesity-medicine physicians", "FDA-approved brand GLP-1s"], "pros": ["ABOM board-certified physicians", "Registered dietitian on every care team", "FDA-approved medications (no compounds)", "Covered by most private insurance and Medicare"], "cons": ["$299/mo cash-pay excludes medication", "Pricey without insurance", "No compounded low-cost option"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "lifemd-weight", "name": "LifeMD", "description": "50-state direct-to-patient telehealth company with a weight-management program offering both compounded and brand-name GLP-1s. Monthly program fee covers clinical oversight and insurance assistance; medication is priced separately.", "category": "glp1", "services": ["Compounded semaglutide", "Brand Wegovy/Ozempic/Zepbound/Saxenda", "Oral semaglutide", "Clinical oversight", "Metabolic testing", "Insurance assistance"], "pricingDisplay": "$149/mo program", "pricingNotes": "Program fee first month $39, then $149/mo (cancel anytime); medication not included. Cash-pay compounded semaglutide around $199/mo; Ozempic pen $349-499; brand Wegovy/Zepbound $500-1,500+/mo without insurance.", "pricingComparison": "Works with insurance for prior authorization on covered meds", "deliveryModel": "telehealth_national", "geographicCoverage": ["National (50 states)"], "url": "https://lifemd.com/weight-management/", "referralType": "affiliate_link", "ourTake": "LifeMD is a large, publicly traded 50-state telehealth operator, so the platform is mature and offers both compounded and brand-name GLP-1s plus insurance prior-authorization help. The trade-off is a two-part cost: a $149/mo program fee on top of separately priced medication. Useful if you want one platform that can flex between cash-pay compounds and insurance-routed brand meds.", "bestFor": ["Both compounded and brand options", "Insurance prior-authorization help", "Established 50-state platform"], "pros": ["Available in all 50 states", "Compounded and brand-name options", "Insurance prior-authorization assistance", "Cancel anytime", "Non-GLP-1 alternatives offered"], "cons": ["Program fee separate from medication", "Brand meds expensive without insurance", "Costs add up across program + meds"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "eden-glp1", "name": "Eden", "description": "Online weight-loss clinic prescribing compounded and brand-name GLP-1s with a same-price-at-every-dose model for compounds. Membership is required and billed separately from medication.", "category": "glp1", "services": ["Compounded semaglutide", "Compounded tirzepatide", "Brand Ozempic/Wegovy/Zepbound/Mounjaro", "24/7 provider messaging", "Nutritional guidance", "Community support"], "pricingDisplay": "$99/mo (compound semaglutide)", "pricingNotes": "Compounded semaglutide $99/mo, compounded tirzepatide $199/mo (same price at every dose). Requires Eden Membership: $39 first month, then $99/mo. Brand options: Ozempic/Zepbound/Mounjaro ~$1,399/mo, Wegovy ~$1,695/mo. Membership does not guarantee a prescription.", "pricingComparison": "Compounded price stays flat as dose titrates up", "deliveryModel": "telehealth_national", "geographicCoverage": ["National"], "url": "https://www.eden.health/weight-loss", "referralType": "affiliate_link", "ourTake": "Eden's hook is flat compounded pricing — $99/mo semaglutide or $199/mo tirzepatide that does not climb as your dose increases. The fine print is a separate Eden Membership ($39 then $99/mo) that does not guarantee a prescription, so factor both lines into your total. Brand-name access exists but at full retail. Domain note: tryeden.com now redirects to eden.health.", "bestFor": ["Flat compounded pricing", "Same price through dose increases", "24/7 provider messaging"], "pros": ["Same price at every dose (compounds)", "Both compounded and brand options", "24/7 provider messaging", "Nutritional guidance + community"], "cons": ["Separate membership fee ($99/mo after first month)", "Membership does not guarantee a prescription", "Compounded options not FDA-approved", "Brand meds at full retail"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "weightwatchers-clinic", "name": "WeightWatchers Clinic", "description": "GLP-1 medication program from WeightWatchers (formerly Sequence), delivered through its affiliated WeightWatchers Clinic medical group. Membership covers telehealth clinician care and behavior support; brand-name GLP-1 medication is routed through insurance and billed separately.", "category": "glp1", "services": ["Board-certified clinician telehealth visits", "FDA-approved GLP-1s (Wegovy, Zepbound, Saxenda)", "Non-GLP-1 alternatives (Metformin, naltrexone/bupropion)", "Insurance navigation", "Behavior-change program"], "pricingDisplay": "$20/mo first 3 months", "pricingNotes": "$20/mo for first three months on a 12-month plan, then $74/mo (a $49 first-month fee may apply). Membership excludes GLP-1 medication; care team works with commercial insurance on coverage. Out-of-pocket meds roughly $350-1,300/mo. Cash-pay Med+ members can prepay 3/6/12-month supplies.", "pricingComparison": "Insurance-first; works with commercial plans (not government or Kaiser)", "deliveryModel": "telehealth_national", "geographicCoverage": ["National"], "url": "https://www.weightwatchers.com/us/weight-loss-medication", "referralType": "affiliate_link", "ourTake": "This is the program formerly known as Sequence, now folded into WeightWatchers Clinic. It pairs a board-certified clinician with WW's behavior-change backbone and prescribes FDA-approved brand GLP-1s (no compounds), routing medication through commercial insurance. Strong fit if you have commercial coverage and want lifestyle support; weak fit if you need cash-pay compounded meds or are on a government/Kaiser plan.", "bestFor": ["Have commercial insurance", "Want behavior-change support with meds", "FDA-approved brand GLP-1s"], "pros": ["FDA-approved medications (no compounds)", "Board-certified clinicians", "Behavior-change program integrated", "Insurance navigation included", "Prepay supply lock-in for cash-pay"], "cons": ["Medication not included in membership", "Brand meds expensive without insurance", "No government or Kaiser plan support", "No compounded low-cost path"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "success-by-sesame", "name": "Success by Sesame", "description": "Direct-to-consumer weight-loss program on the Sesame marketplace where you choose your own provider and access compounded or brand-name GLP-1s without retail markup. Subscription covers telehealth and messaging; medication is priced separately.", "category": "glp1", "services": ["Compounded semaglutide", "Brand Wegovy/Zepbound and other GLP-1s", "Choose-your-own-provider", "Unlimited messaging", "Ongoing clinical care", "Costco member discount option"], "pricingDisplay": "From $59/mo", "pricingNotes": "Subscription from $59/mo with annual plan (telehealth visits, unlimited messaging, ongoing care). Medication billed separately; brand GLP-1s start around $149/mo without insurance. Costco members can access Wegovy/Ozempic at $349/mo via Costco Pharmacy.", "pricingComparison": "Costco-member pricing on Wegovy/Ozempic at $349/mo", "deliveryModel": "telehealth_national", "geographicCoverage": ["National"], "url": "https://sesamecare.com/service/online-weight-loss-program", "referralType": "affiliate_link", "ourTake": "Success by Sesame runs on a marketplace model: you browse and pick your own provider rather than getting assigned one, and medication is offered without retail markup. The $59/mo subscription is among the lowest entry points, and the Costco partnership ($349/mo Wegovy/Ozempic for members) is a genuine differentiator. Medication is a separate line, and provider quality varies because each sets their own practice.", "bestFor": ["Choosing your own provider", "Costco members", "Low subscription entry point"], "pros": ["Choose-your-own-provider model", "Low $59/mo subscription", "Compounded and brand options", "Costco member discount on brand meds", "Unlimited messaging"], "cons": ["Medication priced separately", "Provider quality varies (independent practices)", "Promo pricing has end dates"], "featured": false, "lastVerified": "2026-06-25"},
  {"slug": "plushcare-weight", "name": "PlushCare", "description": "Physician-led telehealth platform prescribing only FDA-approved brand-name GLP-1s, with board-certified MDs and same-day appointment availability. In-network with major insurers; cash-pay visits priced per appointment on top of a low membership.", "category": "glp1", "services": ["FDA-approved GLP-1s (Wegovy, Zepbound, Saxenda)", "Board-certified MD visits", "Same-day appointments", "Insurance billing", "Unlimited messaging"], "pricingDisplay": "$19.99/mo membership", "pricingNotes": "Membership $19.99/mo (or $149/year) after a free first month; visits not included. Provider visits $129 without insurance, or as low as $30 copay in-network. Brand GLP-1 medication priced separately (e.g., Zepbound vial $299-449, Wegovy $199-399).", "pricingComparison": "In-network with Cigna, Humana, Aetna, BCBS, UnitedHealthcare", "deliveryModel": "telehealth_national", "geographicCoverage": ["National"], "url": "https://plushcare.com/glp-1-prescription/", "referralType": "affiliate_link", "ourTake": "PlushCare is the insurance-friendly, MD-led pick: its network is board-certified physicians (not NPs), it takes major insurers, and it prescribes only FDA-approved brand GLP-1s — no compounds. The low $19.99/mo membership is misleading on its own because visits ($129 cash) and medication are separate. Best if you have in-network coverage and want a real doctor and brand-name meds rather than the cheapest compound.", "bestFor": ["In-network insurance users", "Board-certified MD visits", "FDA-approved brand GLP-1s only"], "pros": ["In-network with major insurers", "Board-certified MDs (not NPs)", "Same-day appointments", "FDA-approved medications only", "Low base membership"], "cons": ["Visits and medication priced separately", "No compounded low-cost option", "Cash-pay visit $129", "Brand meds expensive without coverage"], "featured": false, "lastVerified": "2026-06-25"},
];

// =============================================================================
// TRT (Telehealth)
// =============================================================================

export const trtProviders: Provider[] = [
  {
    slug: 'fountain-trt',
    name: 'Fountain TRT',
    description: 'Streamlined TRT telehealth platform specializing in testosterone creams and injections with minimal friction.',
    category: 'trt',
    services: ['Testosterone cream', 'Testosterone injections', 'Ongoing consultations', 'Lab monitoring'],
    pricingDisplay: '~$199/mo',
    pricingNotes: 'Includes medication, consultations, and medical team access. $30 onboarding blood test.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://fountaintrt.com',
    referralType: 'affiliate_link',
    ourTake: 'Fountain TRT is the "set it and forget it" option. Great for busy professionals who want straightforward TRT without extensive optimization. They favor creams, which some prefer over injections.',
    bestFor: ['Convenience', 'Prefer creams', 'Minimal hassle', 'Busy professionals'],
    pros: ['Simple onboarding', '4.8★ Trustpilot', 'Responsive support', 'Both cream and injection options'],
    cons: ['Less comprehensive than Marek', 'Limited customization', 'Focused solely on TRT'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'marek-health-trt',
    name: 'Marek Health (TRT)',
    description: 'Comprehensive hormone optimization with the most thorough testing and physician oversight in the industry.',
    category: 'trt',
    services: ['Full hormone panel', 'TRT protocols', 'Peptides', 'Nutritional support', 'Monthly coaching'],
    pricingDisplay: '$450-1,700 (labs) + treatment',
    pricingNotes: 'Initial labs $450-1,700 (with optional genetics). Treatment costs additional. Follow-up labs every 6 months.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National (except NY, NJ, RI)'],
    url: 'https://marekhealth.com',
    referralType: 'affiliate_link',
    ourTake: 'Marek is the premium choice for those who want complete hormone optimization, not just TRT. Most comprehensive testing available, physician oversight, and access to peptides. You pay significantly more, but get concierge-level care.',
    bestFor: ['Comprehensive optimization', 'Want full hormone panel', 'Willing to invest'],
    pros: ['Most thorough testing', 'Physician consultations', 'Peptide access', 'Holistic approach'],
    cons: ['Most expensive option', 'Not in NY, NJ, RI', 'May be overkill for simple TRT'],
    accreditations: ['LabCorp partnership'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'trt-nation',
    name: 'TRT Nation',
    description: 'Budget-friendly all-inclusive TRT program with straightforward pricing and solid results.',
    category: 'trt',
    services: ['Testosterone injections', 'Lab monitoring', 'Provider consultations'],
    pricingDisplay: '$99/mo',
    pricingNotes: 'All-inclusive pricing. Labs, medication, and consultations included.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://trtnation.com',
    referralType: 'affiliate_link',
    ourTake: 'TRT Nation is the best value in the market at $99/mo all-in. No frills, but effective TRT for those who know what they want and don\'t need extensive hand-holding or optimization beyond testosterone.',
    bestFor: ['Budget-conscious', 'Straightforward TRT', 'Know what you need'],
    pros: ['Best value at $99/mo', 'All-inclusive pricing', 'No surprise costs', 'Solid reputation'],
    cons: ['Less comprehensive testing', 'Basic service', 'Limited customization'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'henry-meds-trt',
    name: 'Henry Meds',
    description: 'Competitive TRT telehealth with labs included in the monthly price.',
    category: 'trt',
    services: ['Testosterone therapy', 'Labs included', 'Provider consultations'],
    pricingDisplay: '$129/mo',
    pricingNotes: 'Labs included in monthly price.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://henrymeds.com',
    referralType: 'affiliate_link',
    ourTake: 'Henry Meds hits a sweet spot - more comprehensive than TRT Nation, less expensive than Fountain. Labs included makes budgeting easy. Good middle-ground option.',
    bestFor: ['Want labs included', 'Mid-range budget', 'Straightforward service'],
    pros: ['Labs included in price', 'Competitive pricing', 'Good value proposition'],
    cons: ['Less known brand', 'Not as comprehensive as Marek'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {"slug": "hone-health-trt", "name": "Hone Health", "description": "Telehealth hormone clinic offering testosterone injections, cream, troches, clomiphene, and enclomiphene with membership-based ongoing care. Care is built around recurring lab testing of 40+ biomarkers and licensed-physician oversight.", "category": "trt", "services": ["Testosterone injections", "Testosterone cream", "Testosterone troches", "Clomiphene", "Enclomiphene", "Anastrozole", "40+ biomarker lab testing", "Physician consultations"], "pricingDisplay": "$135-155/mo + meds", "pricingNotes": "Plus membership $135/mo (hormone-only), Premium $155/mo (adds weight/metabolic). A $65 initial advanced lab test. Medications billed separately (e.g. testosterone injections from ~$28/mo).", "deliveryModel": "telehealth_national", "geographicCoverage": ["National"], "url": "https://honehealth.com/mens/testosterone-replacement-therapy/", "referralType": "affiliate_link", "ourTake": "Hone splits membership from medication, so the headline price looks low until you add the drug cost. Where it earns its keep is the recurring 40+ biomarker testing and physician follow-up baked into membership. Good for someone who wants structured monitoring, not just a prescription.", "bestFor": ["Want ongoing biomarker monitoring", "Multiple delivery formats", "Physician-guided care"], "pros": ["40+ biomarker testing included in membership", "Many delivery formats (injection, cream, troche, oral SERMs)", "Low $65 entry lab test", "Established telehealth brand"], "cons": ["Membership is separate from medication cost", "Total monthly cost can climb past $170-190", "Premium tier needed for combined metabolic care"], "lastVerified": "2026-06-25"},
  {"slug": "defy-medical", "name": "Defy Medical", "description": "Long-running physician-supervised hormone clinic offering the broadest range of testosterone formats: injections, topical gels/lotions, pellets, and nasal gel, plus HCG and ED support. Operates a cash-pay, a-la-carte model with no subscription, so patients pay only for what they use.", "category": "trt", "services": ["Testosterone injections", "Topical testosterone gels/lotions", "Testosterone pellets", "Testosterone nasal gel", "HCG", "Estrogen management", "ED treatments", "Physician consultations"], "pricingDisplay": "$149 consult + ~$200-350/mo", "pricingNotes": "Cash-pay a-la-carte, no subscription. Initial physician consultation $149. Basic TRT plus supplies and labs runs roughly $200-350/mo; adding peptides or HGH secretagogues can reach $400-650/mo.", "deliveryModel": "telehealth_national", "geographicCoverage": ["National (telehealth)", "Tampa, FL clinic"], "url": "https://www.defymedical.com/services/trt/", "referralType": "affiliate_link", "ourTake": "Defy is the format buffet of online TRT, offering injections, gels, pellets, and nasal gel under one roof. The a-la-carte cash-pay model rewards people who know what they want and dislike subscriptions. Costs add up fast once you stack peptides or HGH secretagogues.", "bestFor": ["Want the most delivery formats", "Prefer pay-per-service over subscription", "Complex or custom protocols"], "pros": ["Widest range of testosterone formats (injection, gel, pellet, nasal)", "No subscription or contract", "Established physician-led clinic", "Offers HCG, fertility, and ED support"], "cons": ["No upfront published monthly price", "Total cost higher than budget subscription clinics", "$149 initial consult fee", "A-la-carte billing can be hard to forecast"], "lastVerified": "2026-06-25"},
  {"slug": "maximus", "name": "Maximus", "description": "Telehealth men's optimization service whose flagship King Protocol uses enclomiphene, an oral SERM that raises the body's own testosterone instead of replacing it, preserving fertility and testicular function. Also offers testosterone cream and oral testosterone combination protocols, fully online with at-home labs.", "category": "trt", "services": ["Enclomiphene (King Protocol)", "Testosterone cream", "Oral testosterone protocols", "At-home lab testing", "Doctor consultations", "Coaching"], "pricingDisplay": "$199.99/mo (enclomiphene)", "pricingNotes": "King Protocol enclomiphene $199.99/mo including doctor consult and medication; drops to ~$99.99/mo on an annual commitment. Required labs in months 1 and 2 cost $72.50 each. Enclomiphene + Testosterone Cream from $189.99/mo.", "deliveryModel": "telehealth_national", "geographicCoverage": ["National (all states except Alaska and Washington, D.C.)"], "url": "https://www.maximustribe.com/testosterone", "referralType": "affiliate_link", "ourTake": "Maximus is the fertility-sparing alternative to traditional TRT. Enclomiphene stimulates your own production instead of replacing it, which appeals to younger men who want to protect fertility. The trade-off: it only works if your HPG axis still responds, and the annual commitment is where the real savings live.", "bestFor": ["Want to preserve fertility", "Prefer stimulating natural production over replacement", "Younger men with intact HPG axis"], "pros": ["Enclomiphene preserves fertility and testicular function", "Fully online with at-home labs", "Available in nearly all states", "Annual plan roughly halves monthly cost"], "cons": ["Enclomiphene is not for everyone (depends on responsive HPG axis)", "Best price requires 12-month commitment", "Labs in months 1-2 are an added cost", "Not classic exogenous TRT"], "lastVerified": "2026-06-25"},
  {"slug": "joi-blokes", "name": "Joi + Blokes", "description": "Men's and women's hormone telehealth platform (Blokes is the men's side) offering testosterone injections, capsules, creams, and enclomiphene on tiered subscriptions that include meds, clinician consults, quarterly labs, and coaching. Active members can add hair-loss or ED medications for $1/month each.", "category": "trt", "services": ["Testosterone injections", "Testosterone capsules", "Testosterone cream", "Enclomiphene", "Quarterly lab testing", "Clinician consultations", "1:1 health coaching", "Unlimited messaging"], "pricingDisplay": "$99-149/mo", "pricingNotes": "Flex $149/mo (3-mo), Commit & Save $129/mo (6-mo), Full Year $99/mo (12-mo, billed upfront). Initial lab fee ~$49. Meds, consults, and quarterly labs included. Hair-loss/ED add-ons $1/mo each.", "deliveryModel": "telehealth_state_limited", "geographicCoverage": ["National except AL, AR, CT, DE, GA, HI, LA, MN, MO, MS, NC, ND, OK, PA, RI, SC"], "url": "https://joiandblokes.com/product/testosterone-replacement-therapy/", "referralType": "affiliate_link", "ourTake": "Joi + Blokes bundles meds, consults, quarterly labs, and coaching into one subscription, so the $99/mo annual tier is genuinely all-in. The $1/mo hair-loss and ED add-ons are a nice touch for the typical TRT patient. The catch is the long list of excluded states, so confirm yours before committing.", "bestFor": ["Want one all-inclusive subscription", "Value coaching plus meds", "Cheap hair-loss/ED add-ons"], "pros": ["All-inclusive (meds + labs + consults + coaching)", "$99/mo on the annual plan", "$1/mo hair-loss and ED add-ons", "Multiple delivery formats plus enclomiphene"], "cons": ["Excluded in 16 states", "Best price requires annual upfront payment", "Initial lab fee on top of subscription", "Shorter plans cost meaningfully more"], "lastVerified": "2026-06-25"},
  {"slug": "petermd", "name": "PeterMD", "description": "Budget-focused online TRT clinic offering testosterone cypionate injection packages bundled with an aromatase inhibitor, supplies, shipping, and physician consultations. Positions itself on price with tiered monthly packages and a low-price guarantee.", "category": "trt", "services": ["Testosterone cypionate injections", "Aromatase inhibitor", "Injection supplies", "Physician consultations", "Lab coordination", "Home delivery"], "pricingDisplay": "$89-139/mo", "pricingNotes": "Tiered monthly packages reported at $89, $99, and $139/mo; entry pricing advertised from $95. Packages include testosterone cypionate, an aromatase inhibitor, syringes/swabs, shipping, and physician consults. Core plans may run higher ($159-229/mo) once added medications are stacked.", "deliveryModel": "telehealth_national", "geographicCoverage": ["National (North America)"], "url": "https://getpetermd.com/mens-trt/", "referralType": "affiliate_link", "ourTake": "PeterMD competes almost entirely on price, bundling testosterone, an aromatase inhibitor, supplies, and consults into a single low monthly fee. That makes it attractive for cost-sensitive men who already know they need TRT. The bare-bones model means less hand-holding and optimization than premium clinics.", "bestFor": ["Most cost-sensitive", "Know they need TRT already", "Want meds plus supplies bundled"], "pros": ["Among the lowest monthly prices", "Aromatase inhibitor and supplies included", "Physician consults included", "Simple injection-focused offering"], "cons": ["Minimal optimization or coaching", "Pricing climbs once add-ons are stacked", "Injection-centric (limited formats)", "Less comprehensive than premium clinics"], "lastVerified": "2026-06-25"},
  {"slug": "evolve-telemed", "name": "Evolve Telemed", "description": "Budget-conscious telehealth provider combining testosterone replacement with weight management, offering injectable and topical-cream testosterone via licensed providers. Programs bundle ongoing visits, provider messaging, lab support, and discounted prescriptions with no long-term contract.", "category": "trt", "services": ["Testosterone injections", "Topical testosterone cream", "Provider consultations", "Lab support", "Provider messaging", "Weight management add-on"], "pricingDisplay": "$129/mo (hormone program)", "pricingNotes": "Hormone Optimization Program $129/mo; Hormone + Weight Loss Program $179/mo. Includes ongoing visits, provider messaging, lab support, and discounted prescriptions with no long-term contract. Initial hormone-panel lab work can run higher (around $500).", "deliveryModel": "telehealth_national", "geographicCoverage": ["National"], "url": "https://evolvetelemed.com/trt-men/", "referralType": "affiliate_link", "ourTake": "Evolve pairs TRT with weight management in one no-contract subscription, which fits men chasing both at once. The $129 hormone program is mid-market and bundles messaging and lab support. Upfront lab panel pricing is the line item to confirm before enrolling.", "bestFor": ["Want TRT plus weight management", "Prefer no long-term contract", "Mid-range budget"], "pros": ["Combines TRT with weight loss", "No long-term contract", "Provider messaging and lab support included", "Discounted prescriptions"], "cons": ["Initial lab panel can be costly", "Fewer delivery formats (injection or cream)", "Less established brand", "Pricing varies by individual plan"], "lastVerified": "2026-06-25"},
];

// =============================================================================
// DEXA (Local)
// =============================================================================

export const dexaProviders: Provider[] = [
  {
    slug: 'bodyspec',
    name: 'BodySpec',
    description: 'Affordable DEXA scans through storefronts, mobile vans, and gym partnerships across major cities.',
    category: 'dexa',
    services: ['DEXA body composition', 'Body fat by region', 'Lean mass tracking', 'Visceral fat', 'Bone density'],
    pricingDisplay: '$40-45/scan',
    pricingNotes: 'Single scan ~$45. Membership drops to $40/scan. Credits never expire.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Austin', 'Los Angeles', 'San Francisco', 'Seattle', 'Dallas', 'New York'],
    url: 'https://bodyspec.com',
    referralType: 'affiliate_link',
    ourTake: 'BodySpec revolutionized DEXA pricing by partnering with gyms and using mobile vans. At $40-45/scan, there\'s no reason not to track your body composition quarterly. Best value in the market.',
    bestFor: ['Budget-conscious', 'Regular tracking', 'Major metro areas'],
    pros: ['Best pricing ($40-45)', '500,000+ scans performed', 'Mobile van convenience', 'Gym partnerships'],
    cons: ['Limited to select cities', 'Mobile vans = less scheduling flexibility', 'Basic service'],
    procedureVolume: '500,000+ scans',
    yearsInBusiness: 12,
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'dexafit',
    name: 'DexaFit',
    description: 'Full-service body composition testing including DEXA, VO2 max, and RMR at franchise locations nationwide.',
    category: 'dexa',
    services: ['DEXA scan', 'VO2 max testing', 'RMR (metabolic rate)', '3D body scan'],
    pricingDisplay: '$100-150/scan',
    pricingNotes: 'Packages available: 4 tests for $410, 8 tests for $660. Memberships from $58-83/mo.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['National (franchise locations)'],
    url: 'https://dexafit.com',
    referralType: 'affiliate_link',
    ourTake: 'DexaFit is the premium option with more locations and additional services like VO2 max. Pricier than BodySpec, but worth it if you want metabolic testing or don\'t have BodySpec nearby.',
    bestFor: ['Want VO2 max too', 'More locations', 'Comprehensive testing'],
    pros: ['Nationwide franchise network', 'VO2 max and RMR available', 'Package discounts', 'More locations'],
    cons: ['More expensive than BodySpec', 'Pricing varies by location', 'Franchise quality varies'],
    featured: false,
    lastVerified: '2024-12-01',
  },
];

export const vo2maxProviders: Provider[] = [
  {
    slug: 'pnoe',
    name: 'PNOĒ',
    description: 'Clinical-grade metabolic and VO2 max analysis delivered through a network of partner gyms, clinics, and longevity practices.',
    category: 'vo2max',
    services: ['VO2 max testing', 'Resting metabolic rate (RMR)', 'Metabolic efficiency', 'Cardiorespiratory fitness', 'Personalized training zones'],
    pricingDisplay: '$150-250/test',
    pricingNotes: 'Pricing set by the local partner facility; often bundled with coaching or nutrition.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['National (partner facilities)'],
    url: 'https://www.pnoe.com',
    referralType: 'direct_link',
    ourTake: 'PNOĒ runs a true clinical metabolic cart used by many performance and longevity clinics. If you want a detailed VO2 max plus fat/carb-burning breakdown and training zones, find a PNOĒ partner near you.',
    bestFor: ['Detailed metabolic data', 'Training-zone precision', 'Longevity & performance clients'],
    pros: ['Clinical-grade metabolic cart', 'Detailed fuel-utilization data', 'Wide partner network', 'Actionable training zones'],
    cons: ['Price varies by facility', 'Only via partner locations', 'Report depth depends on the operator'],
    lastVerified: '2026-06-13',
  },
  {
    slug: 'dexafit-vo2max',
    name: 'DexaFit (VO2 Max)',
    description: 'VO2 max and RMR testing alongside DEXA at DexaFit franchise studios nationwide — a one-stop body-composition and fitness picture.',
    category: 'vo2max',
    services: ['VO2 max testing', 'RMR (metabolic rate)', 'DEXA body composition', 'Fitness assessment'],
    pricingDisplay: '$100-175/test',
    pricingNotes: 'Often bundled with DEXA/RMR packages; pricing varies by franchise location.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['National (franchise locations)'],
    url: 'https://dexafit.com',
    referralType: 'affiliate_link',
    ourTake: 'If you already use DexaFit for DEXA, adding VO2 max in the same visit is convenient and gives you a fuller metabolic and cardio picture. Quality can vary by franchise — confirm equipment when you book.',
    bestFor: ['One-stop testing', 'Pairing with DEXA', 'Most metro areas'],
    pros: ['VO2 max + DEXA + RMR in one place', 'Nationwide franchise network', 'Package discounts'],
    cons: ['Franchise quality varies', 'Pricing varies by location', 'Booking required'],
    lastVerified: '2026-06-13',
  },
  {
    slug: 'fitnescity',
    name: 'Fitnescity',
    description: 'Books VO2 max, RMR, and DEXA testing through a national network of partner labs, often bundled for athletes and executives.',
    category: 'vo2max',
    services: ['VO2 max testing', 'RMR', 'DEXA body composition', 'Wellness testing concierge'],
    pricingDisplay: '$99-300/test',
    pricingNotes: 'Marketplace pricing varies by partner lab and city.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['National (partner-lab network)'],
    url: 'https://www.fitnescity.com',
    referralType: 'direct_link',
    ourTake: 'Fitnescity is the easiest way to find and book a VO2 max test in your city without calling around — it aggregates partner labs and standardizes the booking. Convenience is the draw; price depends on the lab.',
    bestFor: ['Finding a nearby lab fast', 'Bundling tests', 'No-hassle booking'],
    pros: ['Aggregates many partner labs', 'Simple online booking', 'Bundled test options'],
    cons: ['Quality varies by partner lab', 'Pricing not always upfront', 'Marketplace, not the provider'],
    lastVerified: '2026-06-13',
  },
];

export const ivProviders: Provider[] = [
  {
    slug: 'drip-hydration',
    name: 'Drip Hydration',
    description: 'Mobile IV therapy delivered to your home, hotel, or office in major US metros, plus telehealth-adjacent wellness services.',
    category: 'iv',
    services: ['Mobile IV hydration', 'Vitamin infusions', 'NAD+ drips', 'Myers cocktail', 'Hangover & recovery'],
    pricingDisplay: '$100-400/drip',
    pricingNotes: 'NAD+ and specialty drips cost more; mobile/travel fee may apply.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['National (mobile, major metros)'],
    url: 'https://driphydration.com',
    referralType: 'direct_link',
    ourTake: 'Drip Hydration is one of the largest mobile IV operators, so coverage is strong in big metros and the at-home convenience is real. IV vitamin therapy benefits are largely unproven beyond rehydration — go in with realistic expectations.',
    bestFor: ['At-home convenience', 'Travel/hotel visits', 'Major metros'],
    pros: ['Comes to you', 'Wide metro coverage', 'Broad drip menu'],
    cons: ['Pricier than walk-in clinics', 'Benefits beyond hydration unproven', 'Travel fees possible'],
    lastVerified: '2026-06-13',
  },
  {
    slug: 'restore-hyper-wellness',
    name: 'Restore Hyper Wellness',
    description: 'Walk-in wellness studios offering IV drips alongside cryotherapy, red-light therapy, and recovery services nationwide.',
    category: 'iv',
    services: ['IV drip therapy', 'Vitamin shots', 'Cryotherapy', 'Red-light therapy', 'Recovery services'],
    pricingDisplay: '$35-200/drip',
    pricingNotes: 'Membership lowers per-visit cost; specialty drips priced higher.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['National (studios)'],
    url: 'https://www.restore.com',
    referralType: 'direct_link',
    ourTake: 'Restore is a convenient one-stop for IV drips plus cryo and red light, with memberships that make regular visits cheaper. Treat it as wellness/recovery, not medicine — the evidence for most add-ons is still emerging.',
    bestFor: ['Walk-in convenience', 'Bundling recovery services', 'Members'],
    pros: ['Many studio locations', 'Bundles IV with recovery tech', 'Membership pricing'],
    cons: ['Wellness, not medical care', 'Add-on benefits unproven', 'Upsells common'],
    lastVerified: '2026-06-13',
  },
  {
    slug: 'hydreight',
    name: 'Hydreight',
    description: 'Nationwide mobile IV and telehealth platform connecting you with licensed nurses for in-home infusions.',
    category: 'iv',
    services: ['Mobile IV therapy', 'Vitamin infusions', 'Hydration', 'Injections', 'Nurse-administered care'],
    pricingDisplay: '$99-300/visit',
    pricingNotes: 'Pricing varies by market and drip; travel/booking fees may apply.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['National (mobile, licensed-nurse network)'],
    url: 'https://www.hydreight.com',
    referralType: 'direct_link',
    ourTake: 'Hydreight runs a large licensed-nurse network across many states, so availability is broad and care is nurse-administered. As with all IV vitamin therapy, the upside beyond hydration is limited — useful mainly for convenience.',
    bestFor: ['Nurse-administered at home', 'Wide state availability', 'On-demand booking'],
    pros: ['Licensed-nurse network', 'Broad coverage', 'In-home convenience'],
    cons: ['Benefits beyond hydration unproven', 'Pricing varies', 'Fees may apply'],
    lastVerified: '2026-06-13',
  },
  {"slug": "mobile-iv-medics", "name": "Mobile IV Medics", "description": "Mobile IV therapy delivered to your home or office by registered nurses across a dozen states. Packages cover hydration, immunity, hangover, NAD+, and energy, with build-your-own add-ons.", "category": "iv", "services": ["Mobile IV hydration", "Immune boost drip", "Hangover relief", "NAD+ infusion", "Myers cocktail", "Vitamin & medication add-ons"], "pricingDisplay": "$199-749/visit", "pricingNotes": "Hydration package starts at $199; vitamin add-ons $20 each (except NAD+). In-home treatment and travel fees included in service area. Group discounts 10-20% for 2-20+ patients.", "deliveryModel": "in_person_local", "geographicCoverage": ["California", "Colorado", "Florida", "Georgia", "Illinois", "Nevada", "New Jersey", "Nebraska", "Minnesota", "Pennsylvania", "Tennessee", "Texas"], "url": "https://mobileivmedics.com", "referralType": "direct_link", "ourTake": "Mobile IV Medics is a transparent, nurse-administered mobile option with travel fees baked into the package price, which makes budgeting clean. Like all IV vitamin therapy, the evidence beyond rehydration is thin, so treat the add-ons as convenience, not medicine.", "bestFor": ["At-home convenience", "Transparent flat pricing", "Group or event drips"], "pros": ["Travel fees included in price", "Registered-nurse administered", "Multi-state coverage", "Group discounts"], "cons": ["Benefits beyond hydration unproven", "Add-ons increase cost quickly", "Service limited to listed states"], "lastVerified": "2026-06-25"},
  {"slug": "the-iv-doc", "name": "The IV Doc", "description": "Long-running concierge mobile IV therapy bringing hydration and wellness drips to your home, office, or hotel in major US cities. Menu spans hangover relief, immunity, energy, NAD+, and beauty infusions.", "category": "iv", "services": ["In-home IV hydration", "Hangover relief drip", "Immunity boost", "Energy boost", "NAD+ infusion", "Glutathione", "Myers cocktail"], "pricingDisplay": "$249-399/drip", "pricingNotes": "Most menu drips $249-$399 (many at $349); specialty and NAD+ infusions priced higher. Delivered to home, office, or hotel.", "deliveryModel": "in_person_local", "geographicCoverage": ["New York City", "National (major metros, mobile concierge)"], "url": "https://www.theivdoc.com", "referralType": "direct_link", "ourTake": "The IV Doc is one of the older concierge mobile IV brands, strongest in NYC, with a published per-drip menu so you know the price before booking. Convenience and clean pricing are the draw; the clinical upside beyond rehydration remains unproven.", "bestFor": ["NYC home/hotel visits", "Upfront menu pricing", "Concierge convenience"], "pros": ["Published per-drip menu pricing", "Home, office, or hotel service", "Established operator", "Broad drip menu"], "cons": ["Pricier than walk-in clinics", "Benefits beyond hydration unproven", "Coverage concentrated in major metros"], "lastVerified": "2026-06-25"},
  {"slug": "liquivida", "name": "Liquivida", "description": "Clinic-based wellness centers offering IV vitamin therapy alongside aesthetics, hormone therapy, and weight-loss programs in Florida, New Jersey, Texas, and partner lounges. Membership pricing for regular visitors.", "category": "iv", "services": ["IV vitamin therapy", "NAD infusion", "Glutathione drip", "Performance hydration", "Vitamin injections", "Lab testing & metabolic health"], "pricingDisplay": "Memberships from $79/mo", "pricingNotes": "Essential, Advanced, and Ultimate membership tiers start at $79/month; individual drip and add-on pricing varies by location.", "deliveryModel": "in_person_local", "geographicCoverage": ["Florida", "New Jersey", "Texas", "Connecticut", "Arizona"], "url": "https://www.liquivida.com", "referralType": "direct_link", "ourTake": "Liquivida runs full wellness centers, so IV drips sit next to aesthetics, hormones, and lab testing under one roof, which suits people who want a one-stop optimization clinic. Memberships lower per-visit cost; as always, the IV vitamin benefits beyond hydration are not well established.", "bestFor": ["One-stop wellness center", "Members and regulars", "Pairing IV with aesthetics/HRT"], "pros": ["Membership pricing from $79/mo", "Broad wellness service menu", "Established multi-state footprint", "On-site lab and metabolic testing"], "cons": ["Clinic visit required (limited mobile)", "Heavy cross-sell of aesthetics/HRT", "Per-drip pricing varies by location"], "lastVerified": "2026-06-25"},
  {"slug": "reset-iv", "name": "Reset IV", "description": "Fully mobile IV therapy serving Las Vegas, Miami, Los Angeles, and Orange County with nurses dispatched to homes, hotels, and offices. Named drips range from basic hydration to high-dose NAD+ and longevity infusions.", "category": "iv", "services": ["Mobile IV hydration", "Hangover recovery drip", "Beauty/glow drip", "NAD+ 500mg infusion", "Longevity drip", "Custom add-ons"], "pricingDisplay": "$199-1,500/drip", "pricingNotes": "Revival from $199, Aftermath $249, Glow $289, Edge $329, Fortress $369, Longevity from $549, NAD+ 500mg $699, Gold Drip $1,500. No travel fees in service areas.", "deliveryModel": "in_person_local", "geographicCoverage": ["Las Vegas, NV", "Miami, FL", "Fort Lauderdale, FL", "Los Angeles, CA", "Orange County, CA"], "url": "https://www.resetiv.com", "referralType": "direct_link", "ourTake": "Reset IV publishes a clear per-drip menu with no travel fees and quick nurse arrival in its five markets, which makes it one of the more transparent mobile options. The high-dose NAD+ and longevity drips are premium-priced; the longevity claims outrun the current evidence, so set expectations accordingly.", "bestFor": ["No travel fees", "Las Vegas / Miami / LA visits", "Upfront per-drip pricing"], "pros": ["No travel fees in service areas", "Transparent named-drip menu", "Open 7 days, fast nurse dispatch", "NAD+ and longevity options"], "cons": ["Only five metro markets", "Premium drips get expensive ($699-$1,500)", "Longevity/NAD benefits unproven"], "lastVerified": "2026-06-25"},
  {"slug": "iv-nutrition", "name": "IV Nutrition", "description": "Self-pay IV and injection clinics concentrated in the Midwest, offering curated drips, vitamin shots, NAD+, and basic lab testing with transparent per-menu pricing. Mobile at-home service available for an added fee.", "category": "iv", "services": ["IV drip therapy", "Vitamin injections", "NAD+ therapy", "Blood testing", "Mobile at-home IV", "Wellness memberships"], "pricingDisplay": "Per-menu, self-pay", "pricingNotes": "Self-pay model with transparent per-menu pricing that varies by location; a mobile fee applies for at-home service. Member discounts and monthly specials offered.", "deliveryModel": "hybrid", "geographicCoverage": ["Kansas", "Missouri", "Iowa", "Tennessee", "Texas", "Arizona"], "url": "https://ivnutrition.com", "referralType": "direct_link", "ourTake": "IV Nutrition is a self-pay clinic chain with transparent menu pricing and the option to come to you for a mobile fee, which is a good fit for Midwest markets the national mobile brands skip. It positions itself as wellness support rather than medical treatment, which is the honest framing for IV vitamin therapy.", "bestFor": ["Midwest clinic access", "Self-pay transparent menu", "Members and regulars"], "pros": ["Transparent self-pay pricing", "Clinic plus mobile option", "Member discounts and specials", "Vitamin injections and NAD+ available"], "cons": ["Pricing varies by location", "Mobile service adds a fee", "Benefits beyond hydration unproven"], "lastVerified": "2026-06-25"},
];

export default {
  labs: labsProviders,
  glp1: glp1Providers,
  trt: trtProviders,
  dexa: dexaProviders,
  vo2max: vo2maxProviders,
  iv: ivProviders,
};
