import { Provider } from './types';

// =============================================================================
// DENTAL (Mexico - Medical Tourism)
// =============================================================================

export const dentalProviders: Provider[] = [
  // Los Algodones
  {
    slug: 'sani-dental-group',
    name: 'Sani Dental Group',
    description: 'Largest dental clinic in Los Algodones with 30+ years experience. High-volume operation with on-site lab for same-day work.',
    category: 'dental',
    services: ['Dental implants', 'Crowns', 'Veneers', 'Full-mouth restoration', 'Root canals', 'Dentures', 'All-on-4'],
    pricingDisplay: '$750-1,200/implant',
    pricingNotes: 'Implant with crown: ~$1,500. Full arch: $9,000-12,000.',
    pricingComparison: 'vs $3,000-5,000/implant in US',
    savingsPercent: 70,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Mexico'],
    destinationCountry: 'Mexico',
    destinationCity: 'Los Algodones',
    typicalTripLength: '3-7 days',
    includesInPackage: ['Free consultation', 'X-rays', 'Hotel recommendations', 'Free shuttle from border'],
    recoveryNotes: 'Most work completed same trip. Complex cases may require 2 visits.',
    accreditations: ['ADA affiliated dentists', 'MTA certified'],
    yearsInBusiness: 30,
    procedureVolume: '10,000+ patients/year',
    url: 'https://sanidentalgroup.com',
    referralType: 'affiliate_link',
    ourTake: 'Sani is THE name in Los Algodones - the go-to for Americans crossing from Arizona. Walking distance from the US border. High volume means efficiency but can feel like a factory. 98% implant success rate. Best for straightforward work where you want predictability.',
    bestFor: ['Budget-conscious', 'First-time dental tourists', 'Near AZ border', 'Quick turnaround'],
    pros: ['Walking distance from US border', '30+ years experience', 'On-site lab for same-day work', '98% implant success rate', 'English-speaking staff'],
    cons: ['High volume can feel impersonal', 'Los Algodones is a tiny town', 'Assembly-line feel', 'Long wait times reported'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  // Tijuana
  {
    slug: 'pacific-implant-center',
    name: 'Pacific Implant Center',
    description: 'Premium Tijuana clinic with US-trained surgeons from Harvard, Loma Linda, and USC. 5 minutes from San Diego border.',
    category: 'dental',
    services: ['Dental implants', 'All-on-4/6', 'Full-mouth reconstruction', 'Bone grafting', 'Cosmetic dentistry'],
    pricingDisplay: '$1,550-1,850/implant',
    pricingNotes: 'Full implant with crown. All-on-4: $12,000-15,000.',
    pricingComparison: 'vs $4,500+/implant in US',
    savingsPercent: 65,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Mexico'],
    destinationCountry: 'Mexico',
    destinationCity: 'Tijuana',
    typicalTripLength: '5-10 days',
    includesInPackage: ['Consultation', 'CT scan', 'All surgical components'],
    recoveryNotes: 'Full-mouth cases typically require 2 trips spaced 3-6 months apart.',
    accreditations: ['Surgeons trained at Harvard, Loma Linda, USC'],
    yearsInBusiness: 14,
    url: 'https://pacificimplantcenters.com',
    referralType: 'affiliate_link',
    ourTake: 'Pacific Implant is the quality-focused choice in Tijuana. US-trained surgeons and 14 years of experience. Slightly higher prices than budget options, but worth it for complex cases. Just 5 minutes from San Diego.',
    bestFor: ['Quality-focused', 'Complex cases', 'Near San Diego', 'Want US-trained surgeons'],
    pros: ['US-trained surgeons (Harvard, Loma Linda)', '14 years experience', '5 min from San Diego border', 'Good for complex cases'],
    cons: ['Higher prices than budget clinics', 'Complex cases need 2 trips', 'Tijuana location'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'dental-brush-tijuana',
    name: 'Dental Brush',
    description: 'ADA and BBB-rated Tijuana clinic with NYU-trained director. Uses CEREC and digital technology.',
    category: 'dental',
    services: ['Implants', 'Oral surgery', 'Full-mouth rehab', 'CEREC same-day crowns'],
    pricingDisplay: '$1,200-1,500/implant',
    pricingNotes: 'Same-day crowns with CEREC technology.',
    pricingComparison: 'vs $3,000-5,000 in US',
    savingsPercent: 65,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Mexico'],
    destinationCountry: 'Mexico',
    destinationCity: 'Tijuana',
    typicalTripLength: '3-7 days',
    includesInPackage: ['Digital X-rays', 'CEREC technology'],
    accreditations: ['ADA', 'BBB rated', 'NYU trained director'],
    url: 'https://dentalbrushtijuana.com',
    referralType: 'affiliate_link',
    ourTake: 'Dental Brush combines quality credentials (ADA, BBB, NYU-trained) with modern tech like CEREC for same-day crowns. Good middle-ground between budget and premium.',
    bestFor: ['Want same-day crowns', 'ADA/BBB credentialed', 'Modern technology'],
    pros: ['ADA and BBB rated', 'NYU-trained director', 'CEREC same-day crowns', 'Digital technology'],
    cons: ['Mid-range pricing', 'Less known than Sani'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  // Cancun
  {
    slug: 'dental-destinations-cancun',
    name: 'Dental Destinations Cancun',
    description: 'Boutique dental clinic in Cancun hotel zone. Premium experience combining vacation with dental work.',
    category: 'dental',
    services: ['All-on-4', 'Veneers', 'Implants', 'Cosmetic dentistry', 'Smile makeovers'],
    pricingDisplay: '$800-1,500/implant',
    pricingNotes: 'Higher-end pricing for Cancun location and experience.',
    pricingComparison: 'vs $3,000-5,000 in US',
    savingsPercent: 60,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Mexico'],
    destinationCountry: 'Mexico',
    destinationCity: 'Cancun',
    typicalTripLength: '5-10 days',
    includesInPackage: ['Airport pickup', 'Hotel partnerships', 'Concierge service', 'Beach recovery'],
    accreditations: ['AACD member'],
    yearsInBusiness: 15,
    url: 'https://dentaldestinationscancun.com',
    referralType: 'affiliate_link',
    ourTake: 'The premium option for those who want to combine dental work with a beach vacation. More personalized than border town clinics. Worth it for cosmetic cases where you want extra attention and a nicer recovery setting.',
    bestFor: ['Vacation + dental combo', 'Cosmetic focus', 'Premium experience', 'Smile makeovers'],
    pros: ['Beach resort location', 'Personalized boutique care', 'Good for cosmetic work', 'Concierge service'],
    cons: ['Higher prices than border towns', 'Flight required', 'Premium positioning'],
    featured: false,
    lastVerified: '2024-12-01',
  },
];

// =============================================================================
// HAIR TRANSPLANT (Turkey - Medical Tourism)
// =============================================================================

export const hairTransplantProviders: Provider[] = [
  {
    slug: 'vera-clinic',
    name: 'Vera Clinic',
    description: 'Award-winning Istanbul clinic with 30,000+ procedures. Known for OxyCure technique that boosts follicle survival.',
    category: 'hair_transplant',
    services: ['FUE', 'DHI', 'Sapphire FUE', 'OxyCure technique', 'Beard transplant', 'Eyebrow transplant', 'PRP'],
    pricingDisplay: '$2,900-5,900',
    pricingNotes: 'All-inclusive packages. OxyCure technique included.',
    pricingComparison: 'vs $10,000-20,000 in US',
    savingsPercent: 75,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Turkey'],
    destinationCountry: 'Turkey',
    destinationCity: 'Istanbul',
    typicalTripLength: '5-7 days',
    includesInPackage: ['Hotel (3 nights)', 'Airport VIP transfers', 'Translator', 'PRP treatment', 'Medications', 'Wash kit', '1-year guarantee'],
    recoveryNotes: 'Can fly home after 3 days. Avoid sun for 3 weeks. Full results visible at 12 months.',
    accreditations: ['JCI accredited', 'ISO 9001', 'European Award in Medicine 2021'],
    yearsInBusiness: 10,
    procedureVolume: '30,000+ procedures',
    url: 'https://veraclinic.net',
    referralType: 'affiliate_link',
    ourTake: 'Vera is the prestige choice in Istanbul. JCI accredited, European Award winner, and their OxyCure technique (oxygen therapy for follicles) is unique. Higher-end pricing for Turkey, but you get what you pay for. 4.8★ on Trustpilot with 1,700+ reviews.',
    bestFor: ['Premium experience', 'Natural results', 'First-time patients', 'Want top accreditation'],
    pros: ['JCI accredited (rare in Turkey)', 'European Award 2021', 'Proprietary OxyCure technique', '4.8★ Trustpilot (1,700+ reviews)', 'All-inclusive packages'],
    cons: ['Higher priced for Turkey market', 'Popular = busy', '10+ hour flight from US', 'Premium pricing'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'asmed-clinic',
    name: 'ASMED',
    description: 'Research-driven clinic led by Dr. Koray Erdogan, pioneer of robotic FUE in Turkey. 97% graft survival rate.',
    category: 'hair_transplant',
    services: ['FUE', 'Robotic FUE', 'Stem cell adjuncts', 'Custom planning'],
    pricingDisplay: '~$3,500',
    pricingNotes: 'Bespoke treatment plans. Premium positioning.',
    pricingComparison: 'vs $10,000-20,000 in US',
    savingsPercent: 75,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Turkey'],
    destinationCountry: 'Turkey',
    destinationCity: 'Istanbul',
    typicalTripLength: '5-7 days',
    includesInPackage: ['Detailed consultation', 'Custom surgical plan', 'Follow-up protocol'],
    accreditations: ['International Society of Dermatology awards'],
    procedureVolume: 'Limited volume (quality focus)',
    url: 'https://asmed.com',
    referralType: 'affiliate_link',
    ourTake: 'ASMED is for those who want cutting-edge technique over volume. Dr. Erdogan pioneered robotic FUE in Turkey and publishes research. Limited patient volume means more personalized attention. 97% graft survival rate is industry-leading.',
    bestFor: ['Technology-forward', 'Research-driven approach', 'Want named surgeon', 'Precision focus'],
    pros: ['Pioneered robotic FUE in Turkey', '97% graft survival rate', 'Research-driven', 'Named surgeon (Dr. Erdogan)', 'VIP treatment'],
    cons: ['Limited availability', 'Premium pricing', 'Less all-inclusive than competitors'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'smile-hair-clinic',
    name: 'Smile Hair Clinic',
    description: 'High-volume Istanbul clinic with competitive pricing. 4.9★ Trustpilot with 3,500+ reviews. Micro Sapphire FUE technique.',
    category: 'hair_transplant',
    services: ['FUE', 'Sapphire FUE', 'Micro Sapphire FUE', 'DHI'],
    pricingDisplay: '$1,800-2,500',
    pricingNotes: 'All-inclusive packages. Budget-friendly for Turkey.',
    pricingComparison: 'vs $10,000-20,000 in US',
    savingsPercent: 85,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Turkey'],
    destinationCountry: 'Turkey',
    destinationCity: 'Istanbul',
    typicalTripLength: '4-6 days',
    includesInPackage: ['Hotel (2 nights)', 'Airport transfers', 'Medications', 'Translator'],
    recoveryNotes: 'Can fly home after 2-3 days.',
    accreditations: ['Best Clinic Istanbul 2021-2024'],
    procedureVolume: '15,000+ procedures',
    url: 'https://smilehairclinic.com',
    referralType: 'affiliate_link',
    ourTake: 'Smile Hair is the value champion. At $1,800-2,500, it\'s one of the most affordable options with genuinely good results. High volume operation but 4.9★ Trustpilot with 3,500+ reviews speaks to consistent quality. Best for budget-conscious with realistic expectations.',
    bestFor: ['Budget-conscious', 'Value-focused', 'Straightforward cases', 'Best price-to-quality'],
    pros: ['Very competitive pricing', '4.9★ Trustpilot (3,500+ reviews)', 'Best Clinic awards 2021-2024', 'Micro Sapphire FUE', 'Good value'],
    cons: ['High volume = less personal', 'Shorter hotel stay included', 'Less premium experience'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'dr-serkan-aygin',
    name: 'Dr. Serkan Aygin Clinic',
    description: 'Celebrity surgeon with 25+ years experience. Known for high-profile patients and natural-looking results.',
    category: 'hair_transplant',
    services: ['FUE', 'DHI', 'Sapphire FUE', 'Celebrity clients'],
    pricingDisplay: '$2,500-4,000',
    pricingNotes: 'Named surgeon performs procedures.',
    pricingComparison: 'vs $10,000-20,000 in US',
    savingsPercent: 75,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Turkey'],
    destinationCountry: 'Turkey',
    destinationCity: 'Istanbul',
    typicalTripLength: '5-7 days',
    includesInPackage: ['Hotel', 'Transfers', 'Consultation with Dr. Aygin'],
    yearsInBusiness: 25,
    procedureVolume: '10,000+ procedures',
    url: 'https://drserkanaygin.com',
    referralType: 'affiliate_link',
    ourTake: 'Dr. Serkan Aygin is one of the most recognized names in Turkish hair transplants. Celebrity clients and 25+ years experience. Good for those who want a named surgeon and strong before/after portfolio.',
    bestFor: ['Want named surgeon', 'Celebrity portfolio', 'Natural results'],
    pros: ['25+ years experience', 'Celebrity clientele', 'Strong before/after gallery', 'Named surgeon'],
    cons: ['Premium pricing', 'Busy schedule', 'May not perform every procedure personally'],
    featured: false,
    lastVerified: '2024-12-01',
  },
];

// =============================================================================
// BARIATRIC SURGERY (Mexico - Medical Tourism)
// =============================================================================

export const bariatricProviders: Provider[] = [
  {
    slug: 'mexico-bariatric-center',
    name: 'Mexico Bariatric Center',
    description: 'Leading bariatric surgery center in Tijuana with 27,000+ procedures. Own state-of-the-art Hospital Azar.',
    category: 'bariatric',
    services: ['Gastric sleeve', 'Gastric bypass', 'Duodenal switch', 'Revision surgery', 'LAP-BAND', 'Endoscopic sleeve'],
    pricingDisplay: '$4,500-6,500',
    pricingNotes: 'Gastric sleeve from $4,500. Bypass from $5,995. Duodenal switch from $5,995.',
    pricingComparison: 'vs $15,000-25,000 in US',
    savingsPercent: 75,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Mexico'],
    destinationCountry: 'Mexico',
    destinationCity: 'Tijuana',
    typicalTripLength: '3-5 days',
    includesInPackage: ['Hospital stay', 'Surgeon fees', 'Anesthesia', 'Ground transportation', 'Pre-op tests', 'Nutritionist consultation'],
    recoveryNotes: 'Can fly home 2-3 days post-op. Full recovery 2-4 weeks. Aftercare program included.',
    accreditations: ['Hospital Azar (opened 2024)'],
    yearsInBusiness: 12,
    procedureVolume: '27,000+ surgeries',
    url: 'https://mexicobariatriccenter.com',
    referralType: 'affiliate_link',
    ourTake: 'MBC is the most established name in Mexican bariatric surgery. Their new Hospital Azar (opened 2024) is state-of-the-art. Strong aftercare program is a differentiator - they stay with you post-surgery. 27,000+ procedures and easy access from San Diego.',
    bestFor: ['Most established option', 'Strong aftercare', 'Near San Diego', 'First-time bariatric'],
    pros: ['27,000+ procedures', 'New Hospital Azar (2024)', 'Comprehensive aftercare program', 'Easy access from San Diego', '5 surgeons on staff'],
    cons: ['Tijuana location perception', 'Not luxury experience', 'Must qualify medically'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'alo-bariatrics',
    name: 'ALO Bariatrics',
    description: 'Multi-location bariatric center with all-inclusive flat-fee pricing. Locations in Tijuana, Guadalajara, and Puerto Vallarta.',
    category: 'bariatric',
    services: ['Gastric sleeve', 'Gastric bypass', 'Duodenal switch', 'Revision surgery', 'LAP-BAND'],
    pricingDisplay: '$4,700+',
    pricingNotes: 'All-inclusive flat fee. Includes hospital, hotel, chauffeur, exams, prescriptions. No surprise charges.',
    pricingComparison: 'vs $15,000-25,000 in US',
    savingsPercent: 75,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Mexico'],
    destinationCountry: 'Mexico',
    destinationCity: 'Tijuana',
    typicalTripLength: '3-5 days',
    includesInPackage: ['Hospital stay', 'Hotel', 'Chauffeur', 'Exams', 'Prescription drugs', 'Follow-up'],
    recoveryNotes: 'Puerto Vallarta option for beach recovery.',
    accreditations: ['Dreams Hospital', 'Mayo Clinic affiliations'],
    procedureVolume: '10,000+ surgeries (Dr. Lopez)',
    url: 'https://alobariatrics.com',
    referralType: 'affiliate_link',
    ourTake: 'ALO stands out for truly all-inclusive pricing - no surprise charges. Three locations let you choose your setting (Tijuana for convenience, Puerto Vallarta for beach recovery). Dr. Lopez has 10,000+ surgeries. Good for those who want predictable costs.',
    bestFor: ['All-inclusive pricing', 'Multiple location options', 'Want beach recovery (PV)', 'No surprise costs'],
    pros: ['Truly all-inclusive pricing', 'Three locations to choose', 'Mayo Clinic affiliations', 'Dr. Lopez: 10,000+ surgeries', 'Puerto Vallarta beach option'],
    cons: ['Slightly higher starting price', 'Quality varies by location', 'Less known than MBC'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'renew-bariatrics',
    name: 'Renew Bariatrics',
    description: 'Budget-friendly Tijuana option with solid results and good reviews.',
    category: 'bariatric',
    services: ['Gastric sleeve', 'Gastric bypass', 'Revision surgery'],
    pricingDisplay: '$4,200-5,500',
    pricingNotes: 'Budget option with good outcomes.',
    pricingComparison: 'vs $15,000-25,000 in US',
    savingsPercent: 80,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Mexico'],
    destinationCountry: 'Mexico',
    destinationCity: 'Tijuana',
    typicalTripLength: '3-5 days',
    includesInPackage: ['Surgery', 'Hospital stay', 'Transportation'],
    url: 'https://renewbariatrics.com',
    referralType: 'affiliate_link',
    ourTake: 'Renew is the budget option in Tijuana bariatric. Lower price point with decent outcomes. Good for those prioritizing savings over bells and whistles.',
    bestFor: ['Budget-focused', 'Straightforward cases', 'Maximum savings'],
    pros: ['Most affordable option', 'Good reviews', 'Straightforward process'],
    cons: ['Less comprehensive than MBC/ALO', 'Fewer included services', 'Less premium experience'],
    featured: false,
    lastVerified: '2024-12-01',
  },
];

// =============================================================================
// PLASTIC SURGERY (South Korea - Medical Tourism)
// =============================================================================

export const plasticSurgeryProviders: Provider[] = [
  {
    slug: 'jk-plastic-surgery',
    name: 'JK Plastic Surgery Center',
    description: 'Longstanding Apgujeong clinic recognized for foreign-patient systems. 1:1 interpreter from consultation to discharge.',
    category: 'plastic_surgery',
    services: ['Rhinoplasty', 'Double eyelid', 'Facial contouring', 'Breast surgery', 'Body contouring'],
    pricingDisplay: 'Varies by procedure',
    pricingNotes: 'Consultation required for pricing. 50-75% savings vs US typical.',
    pricingComparison: 'vs US prices',
    savingsPercent: 60,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['South Korea'],
    destinationCountry: 'South Korea',
    destinationCity: 'Seoul (Apgujeong)',
    typicalTripLength: '7-14 days',
    includesInPackage: ['1:1 interpreter', 'Consultation', 'Follow-up care'],
    recoveryNotes: 'Facial procedures: 1-2 weeks before flying. Body: 2-3 weeks.',
    accreditations: ['JCI accredited'],
    url: 'https://jkplastic.com',
    referralType: 'affiliate_link',
    ourTake: 'JK is one of the most established names for foreign patients in Korea. Located on "Medical Street" in Apgujeong. Their 1:1 interpreter system from consultation through discharge is a major differentiator for English speakers.',
    bestFor: ['Foreign patients', 'English support needed', 'Full-service experience'],
    pros: ['Longstanding reputation', '1:1 interpreter throughout', 'Medical Street location', 'Full service for foreigners', 'JCI accredited'],
    cons: ['Premium pricing for Korea', 'Busy/high volume', 'Language still challenging'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'jw-plastic-surgery',
    name: 'JW Plastic Surgery',
    description: '22 years with zero complications reported. Known for safety and 3D virtual surgery simulation.',
    category: 'plastic_surgery',
    services: ['Rhinoplasty', 'Facial contouring', 'Eye surgery', 'Breast surgery'],
    pricingDisplay: 'Varies by procedure',
    pricingNotes: '3D simulation included in consultation.',
    savingsPercent: 55,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['South Korea'],
    destinationCountry: 'South Korea',
    destinationCity: 'Seoul (Gangnam)',
    typicalTripLength: '7-14 days',
    includesInPackage: ['3D virtual simulation', 'CT imaging', 'Consultation'],
    accreditations: ['Zero complications in 22 years (reported)'],
    yearsInBusiness: 22,
    url: 'https://jwplasticsurgery.com',
    referralType: 'affiliate_link',
    ourTake: 'JW\'s safety record is their headline: 22 years, zero complications reported. Their 3D virtual surgery simulation lets you see results before committing. Best for safety-conscious patients who want to preview outcomes.',
    bestFor: ['Safety-focused', 'Want 3D preview', 'Natural results', 'Conservative approach'],
    pros: ['22 years, zero complications', '3D virtual simulation', 'High-resolution CT imaging', 'Safety-focused culture'],
    cons: ['Conservative approach may limit dramatic changes', 'Premium pricing'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'banobagi',
    name: 'Banobagi Plastic Surgery',
    description: 'Known as "The Detailist" - meticulous attention to detail. High volume of overseas patients with full English support.',
    category: 'plastic_surgery',
    services: ['Facial contouring', 'Rhinoplasty', 'Eye surgery', 'Anti-aging', 'Body contouring'],
    pricingDisplay: 'Varies by procedure',
    pricingNotes: 'Known for not recommending unnecessary procedures.',
    savingsPercent: 55,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['South Korea'],
    destinationCountry: 'South Korea',
    destinationCity: 'Seoul (Gangnam)',
    typicalTripLength: '7-14 days',
    includesInPackage: ['English support', 'Multiple language interpreters', 'Detailed consultation'],
    url: 'https://banobagi.com',
    referralType: 'affiliate_link',
    ourTake: 'Banobagi\'s "Detailist" philosophy means they obsess over every detail. Notably, they\'re known for NOT recommending unnecessary procedures for financial gain - refreshing in an industry with lots of upselling. High overseas patient volume.',
    bestFor: ['Detail-oriented', 'Don\'t want to be upsold', 'Natural subtle results'],
    pros: ['Meticulous attention to detail', 'Won\'t upsell unnecessary procedures', 'Full English support', 'High overseas patient volume'],
    cons: ['May be too conservative for dramatic changes', 'Gangnam location (busy)'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'id-hospital',
    name: 'ID Hospital',
    description: 'Hospital-scale facility widely known for facial contouring and bone surgery. Comprehensive offerings.',
    category: 'plastic_surgery',
    services: ['Facial bone contouring', 'Two-jaw surgery', 'Rhinoplasty', 'Eye surgery', 'Body contouring'],
    pricingDisplay: 'Varies by procedure',
    pricingNotes: 'Hospital-scale facility with OR suites.',
    savingsPercent: 55,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['South Korea'],
    destinationCountry: 'South Korea',
    destinationCity: 'Seoul (Gangnam)',
    typicalTripLength: '10-14 days',
    includesInPackage: ['Hospital facilities', 'Post-op care', 'Interpreter services'],
    recoveryNotes: 'Bone surgery requires longer recovery - plan 2+ weeks.',
    url: 'https://idhospital.com',
    referralType: 'affiliate_link',
    ourTake: 'ID Hospital is the go-to for serious facial bone work (V-line, jaw reduction, two-jaw surgery). Hospital-scale facility with proper OR suites. Best for those wanting structural changes, not just soft tissue.',
    bestFor: ['Facial bone surgery', 'V-line/jaw work', 'Two-jaw surgery', 'Major structural changes'],
    pros: ['Hospital-scale facility', 'Known for bone surgery', 'Comprehensive surgical suites', 'Can handle complex cases'],
    cons: ['Bone surgery = longer recovery', 'Can feel clinical', 'High volume'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'grand-plastic-surgery',
    name: 'GRAND Plastic Surgery',
    description: 'Large center with 30,000+ patients from 100+ countries since 2004. One-stop system with coordinated aftercare.',
    category: 'plastic_surgery',
    services: ['Rhinoplasty', 'Facial contouring', 'Breast surgery', 'Body contouring', 'Anti-aging'],
    pricingDisplay: 'Varies by procedure',
    pricingNotes: 'One-stop system for international patients.',
    savingsPercent: 55,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['South Korea'],
    destinationCountry: 'South Korea',
    destinationCity: 'Seoul (Apgujeong/Cheongdam)',
    typicalTripLength: '7-14 days',
    includesInPackage: ['Coordinated care', 'Aftercare program', 'International patient services'],
    yearsInBusiness: 20,
    procedureVolume: '30,000+ patients',
    url: 'https://grandplasticsurgery.com',
    referralType: 'affiliate_link',
    ourTake: 'GRAND has the volume and experience with international patients - 30,000+ from 100+ countries. Their one-stop system is designed for medical tourists who need coordinated care. Good for first-timers who want hand-holding.',
    bestFor: ['First-time medical tourists', 'Want coordinated care', 'International patient focus'],
    pros: ['30,000+ international patients', '20 years experience', 'One-stop coordinated system', 'Multiple procedure capability'],
    cons: ['High volume', 'Can feel like a factory', 'Premium positioning'],
    featured: false,
    lastVerified: '2024-12-01',
  },
];

// =============================================================================
// FERTILITY / IVF (Europe - Medical Tourism)
// =============================================================================

export const fertilityProviders: Provider[] = [
  // Czech Republic
  {
    slug: 'reprofit-international',
    name: 'Reprofit International',
    description: 'One of Europe\'s most advanced fertility centers. First specialist donor-egg IVF center in Czech Republic.',
    category: 'fertility',
    services: ['IVF', 'Egg donation', 'Sperm donation', 'Embryo freezing', 'PGD/PGS'],
    pricingDisplay: '€2,700-5,700/cycle',
    pricingNotes: 'Own-egg IVF from €2,700. Donor egg from €5,500.',
    pricingComparison: 'vs $12,000-20,000/cycle in US',
    savingsPercent: 65,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Czech Republic'],
    destinationCountry: 'Czech Republic',
    destinationCity: 'Brno',
    typicalTripLength: '7-10 days (own eggs) or 2-3 days (donor eggs)',
    includesInPackage: ['Consultations', 'Monitoring', 'Egg retrieval/transfer', 'Lab work'],
    accreditations: ['First donor-egg IVF center in Czech Republic'],
    yearsInBusiness: 18,
    url: 'https://reprofit.com',
    referralType: 'affiliate_link',
    ourTake: 'Reprofit pioneered donor-egg IVF in Czech Republic and remains one of Europe\'s most advanced centers. Czech pricing is 50% lower than Western Europe. Anonymous donation only per Czech law. English spoken.',
    bestFor: ['Donor egg IVF', 'Budget-conscious', 'European destination'],
    pros: ['Pioneer in Czech fertility', 'Advanced technology', 'Significantly cheaper than US', 'English-speaking staff'],
    cons: ['Anonymous donation only (Czech law)', 'No same-sex couples (Czech law)', 'Brno is smaller city'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'sanatorium-helios',
    name: 'Sanatorium HELIOS',
    description: '25 years experience in infertility treatment. Partners with Genea (Australian fertility research leader).',
    category: 'fertility',
    services: ['IVF', 'ICSI', 'Egg donation', 'Embryo freezing', 'Assisted hatching'],
    pricingDisplay: '€2,100-3,500/cycle',
    pricingNotes: 'Own-egg IVF from €2,100. One of the most affordable in Europe.',
    pricingComparison: 'vs $12,000-20,000/cycle in US',
    savingsPercent: 75,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Czech Republic'],
    destinationCountry: 'Czech Republic',
    destinationCity: 'Brno',
    typicalTripLength: '7-10 days',
    includesInPackage: ['All IVF procedures', 'Monitoring', 'Lab work'],
    accreditations: ['Genea partnership (Australian research)'],
    yearsInBusiness: 25,
    url: 'https://sanatoriumhelios.com',
    referralType: 'affiliate_link',
    ourTake: 'HELIOS is one of the most affordable quality IVF options in Europe. 25 years experience and partnership with Genea (Australian research leader) gives them access to cutting-edge protocols. Best value in Czech Republic.',
    bestFor: ['Maximum savings', 'Research-backed protocols', '25 years experience'],
    pros: ['Most affordable quality option', '25 years experience', 'Genea partnership', 'Research-driven'],
    cons: ['Anonymous donation only', 'No same-sex couples', 'Less known internationally'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  // Spain
  {
    slug: 'clinica-tambre',
    name: 'Clinica Tambre',
    description: 'One of the oldest fertility units in Spain with high success rates. Locations in Madrid and Alicante.',
    category: 'fertility',
    services: ['IVF', 'Egg donation', 'ROPA (reciprocal IVF)', 'Embryo donation', 'Fertility preservation'],
    pricingDisplay: '€4,100-7,100/cycle',
    pricingNotes: 'Higher than Czech but higher success rates reported.',
    pricingComparison: 'vs $12,000-20,000/cycle in US',
    savingsPercent: 55,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Spain'],
    destinationCountry: 'Spain',
    destinationCity: 'Madrid',
    typicalTripLength: '7-10 days',
    includesInPackage: ['Consultations', 'Monitoring', 'Procedures', 'Initial follow-up'],
    accreditations: ['One of oldest fertility units in Spain'],
    url: 'https://clinicatambre.com',
    referralType: 'affiliate_link',
    ourTake: 'Tambre is a top-tier Spanish clinic with high success rates (50-60% for IVF). Spain allows single women and same-sex couples, which Czech doesn\'t. Pricier than Czech but more inclusive and often better outcomes.',
    bestFor: ['High success rates', 'Single women', 'Same-sex couples (ROPA)', 'Premium experience'],
    pros: ['High success rates (50-60%)', 'Single women & same-sex welcome', 'ROPA for lesbian couples', 'Madrid location'],
    cons: ['Higher than Czech pricing', 'Spain is more expensive overall', 'Flights from US longer'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'barcelona-ivf',
    name: 'Centro de Fertilidad Barcelona',
    description: 'Affordable IVF in Barcelona with strong support for international patients.',
    category: 'fertility',
    services: ['IVF', 'Egg donation', 'Sperm donation', 'Embryo freezing'],
    pricingDisplay: '€4,000-6,000/cycle',
    pricingNotes: 'Strong support for international patients.',
    pricingComparison: 'vs $12,000-20,000/cycle in US',
    savingsPercent: 60,
    deliveryModel: 'in_person_destination',
    geographicCoverage: ['Spain'],
    destinationCountry: 'Spain',
    destinationCity: 'Barcelona',
    typicalTripLength: '7-10 days',
    includesInPackage: ['Full IVF treatment', 'International patient support'],
    url: 'https://barcelonaivf.com',
    referralType: 'affiliate_link',
    ourTake: 'Barcelona IVF offers the Spanish quality and inclusivity at slightly lower prices than Madrid clinics. Barcelona is also a more appealing destination for many. Good middle-ground option.',
    bestFor: ['Barcelona location', 'International support', 'Slightly lower Spain pricing'],
    pros: ['Barcelona destination appeal', 'Strong international support', 'Single & same-sex welcome', 'Good value for Spain'],
    cons: ['Slightly less established than Tambre', 'Spanish pricing still higher than Czech'],
    featured: false,
    lastVerified: '2024-12-01',
  },
];

export default {
  dental: dentalProviders,
  hair_transplant: hairTransplantProviders,
  bariatric: bariatricProviders,
  plastic_surgery: plasticSurgeryProviders,
  fertility: fertilityProviders,
};
