import { Provider } from './types';

// =============================================================================
// PHARMACEUTICAL COMPANIES
// =============================================================================

export const pharmaProviders: Provider[] = [
  {
    slug: 'pfizer',
    name: 'Pfizer',
    description: 'Global pharmaceutical giant known for vaccines (COVID-19, pneumonia), oncology drugs, and cardiovascular medications.',
    category: 'pharma',
    services: ['Vaccines', 'Oncology', 'Cardiovascular', 'Immunology', 'Patient assistance programs'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'Pfizer RxPathways offers assistance programs for eligible patients. Many drugs covered by insurance.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.pfizer.com',
    referralType: 'direct_link',
    ourTake: 'Pfizer is a household name after COVID-19 vaccines. They have robust patient assistance programs through RxPathways. If you\'re prescribed a Pfizer drug and can\'t afford it, always check their assistance program first.',
    bestFor: ['Vaccine access', 'Cancer treatment', 'Patient assistance needs'],
    pros: ['Extensive patient assistance', 'Well-researched drugs', 'Global availability', 'Strong R&D pipeline'],
    cons: ['High list prices', 'Complex assistance applications', 'Some drugs have alternatives'],
    accreditations: ['FDA approved', 'WHO prequalified vaccines'],
    yearsInBusiness: 175,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'johnson-johnson',
    name: 'Johnson & Johnson (Janssen)',
    description: 'Diversified healthcare company with pharmaceutical division (Janssen) focusing on immunology, oncology, and neuroscience.',
    category: 'pharma',
    services: ['Immunology drugs', 'Oncology', 'Neuroscience', 'Infectious disease', 'Patient assistance'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'Janssen CarePath provides savings programs and patient assistance for eligible individuals.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.janssen.com',
    referralType: 'direct_link',
    ourTake: 'J&J\'s pharma arm Janssen makes important drugs for autoimmune conditions (Stelara, Tremfya) and cancer. Their CarePath program can significantly reduce costs. Worth exploring if you\'re on a Janssen drug.',
    bestFor: ['Autoimmune conditions', 'Cancer treatment', 'Mental health medications'],
    pros: ['Strong patient support programs', 'Innovative biologics', 'Diversified portfolio', 'CarePath savings'],
    cons: ['Complex specialty drugs', 'Requires specialty pharmacies for some', 'Insurance navigation can be tricky'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 138,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'novo-nordisk',
    name: 'Novo Nordisk',
    description: 'Danish pharmaceutical company leading in diabetes care and obesity treatments, including popular GLP-1 medications.',
    category: 'pharma',
    services: ['Diabetes medications', 'Obesity treatments', 'GLP-1 drugs', 'Insulin', 'Patient assistance'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'NovoCare offers patient assistance and savings cards. Wegovy/Ozempic can be $1,000+/month without assistance.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['Global'],
    url: 'https://www.novonordisk.com',
    referralType: 'direct_link',
    ourTake: 'If you\'re interested in GLP-1 medications (Ozempic, Wegovy, Rybelsus), Novo Nordisk is the company to know. Their NovoCare program is essential for affording these expensive but effective medications.',
    bestFor: ['Diabetes management', 'Weight loss (GLP-1)', 'Insulin needs'],
    pros: ['Leader in diabetes/obesity', 'Strong patient assistance (NovoCare)', 'Innovative GLP-1 drugs', '$0 savings cards available'],
    cons: ['GLP-1 drugs very expensive without help', 'Supply shortages for popular drugs', 'Insurance coverage varies'],
    accreditations: ['FDA approved', 'EMA approved'],
    yearsInBusiness: 101,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'eli-lilly',
    name: 'Eli Lilly',
    description: 'Major pharmaceutical company known for diabetes drugs (insulin, Mounjaro), oncology, and immunology treatments.',
    category: 'pharma',
    services: ['Diabetes medications', 'Obesity treatments', 'Oncology', 'Immunology', 'Patient assistance'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'Lilly Cares provides free medications to qualifying patients. Insulin capped at $35/month for many.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['Global'],
    url: 'https://www.lilly.com',
    referralType: 'direct_link',
    ourTake: 'Lilly made waves with their $35 insulin cap and Mounjaro (tirzepatide) for weight loss. Their patient assistance is among the best in the industry. Always check Lilly Cares if cost is a barrier.',
    bestFor: ['Diabetes care', 'Weight loss (Mounjaro/Zepbound)', 'Affordable insulin'],
    pros: ['$35 insulin program', 'Strong patient assistance', 'Innovative weight loss drugs', 'Transparent pricing initiatives'],
    cons: ['Mounjaro expensive without coverage', 'Supply issues for popular drugs', 'Some specialty drugs hard to access'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 148,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'abbvie',
    name: 'AbbVie',
    description: 'Biopharmaceutical company known for immunology blockbusters (Humira, Skyrizi, Rinvoq) and oncology drugs.',
    category: 'pharma',
    services: ['Immunology', 'Oncology', 'Neuroscience', 'Eye care', 'Patient assistance'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'myAbbVie Assist provides free medications to eligible patients. Ambassador program helps with insurance navigation.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.abbvie.com',
    referralType: 'direct_link',
    ourTake: 'AbbVie\'s Humira was the world\'s best-selling drug for years. Now facing biosimilar competition, but their newer drugs (Skyrizi, Rinvoq) are gaining ground. Their patient support programs are comprehensive.',
    bestFor: ['Autoimmune diseases', 'Rheumatoid arthritis', 'Psoriasis'],
    pros: ['Strong patient assistance', 'Nurse ambassador support', 'Specialty pharmacy coordination', 'Copay assistance'],
    cons: ['Biologics are very expensive', 'Requires specialty pharmacy', 'Prior authorization often needed'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 11,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'merck',
    name: 'Merck & Co.',
    description: 'Global pharmaceutical company known for vaccines, oncology (Keytruda), and infectious disease treatments.',
    category: 'pharma',
    services: ['Vaccines', 'Oncology', 'Infectious disease', 'Cardiovascular', 'Patient assistance'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'Merck Patient Assistance Program provides free medications to eligible patients.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.merck.com',
    referralType: 'direct_link',
    ourTake: 'Merck is behind Keytruda (revolutionary cancer immunotherapy), Gardasil (HPV vaccine), and many essential medications. Their patient assistance covers most products. Worth checking for cancer patients.',
    bestFor: ['Cancer treatment (Keytruda)', 'Vaccines', 'HIV treatment'],
    pros: ['Keytruda leader in oncology', 'Strong vaccine portfolio', 'Patient assistance available', 'Global access programs'],
    cons: ['Keytruda very expensive', 'Complex oncology navigation', 'Insurance approval can be slow'],
    accreditations: ['FDA approved', 'WHO prequalified'],
    yearsInBusiness: 133,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'bristol-myers-squibb',
    name: 'Bristol Myers Squibb',
    description: 'Biopharmaceutical company specializing in oncology, hematology, immunology, and cardiovascular medications.',
    category: 'pharma',
    services: ['Oncology', 'Hematology', 'Immunology', 'Cardiovascular', 'Patient assistance'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'BMS Access Support provides patient assistance, copay help, and nurse support.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.bms.com',
    referralType: 'direct_link',
    ourTake: 'BMS is a powerhouse in cancer treatment (Opdivo, Yervoy) and blood disorders. Their Access Support program is comprehensive. If you\'re facing a BMS specialty drug cost, definitely explore their assistance.',
    bestFor: ['Cancer treatment', 'Blood disorders', 'Heart conditions'],
    pros: ['Strong oncology portfolio', 'Comprehensive patient support', 'Copay assistance', 'Nurse support programs'],
    cons: ['Specialty drugs very expensive', 'Complex insurance navigation', 'Prior authorization barriers'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 137,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'gsk',
    name: 'GSK (GlaxoSmithKline)',
    description: 'British pharmaceutical company known for vaccines, respiratory medications, and HIV treatments.',
    category: 'pharma',
    services: ['Vaccines', 'Respiratory', 'HIV treatment', 'Oncology', 'Patient assistance'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'GSK For You offers patient assistance and savings programs.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.gsk.com',
    referralType: 'direct_link',
    ourTake: 'GSK leads in vaccines (Shingrix, flu vaccines) and respiratory treatments (asthma, COPD). Their Shingrix vaccine is particularly important for 50+ adults. Patient assistance available for most products.',
    bestFor: ['Vaccines (shingles, flu)', 'Asthma/COPD', 'HIV treatment'],
    pros: ['Strong vaccine portfolio', 'Respiratory expertise', 'Patient assistance available', 'Global presence'],
    cons: ['Shingrix can be pricey without insurance', 'Some products face generic competition', 'Customer service varies'],
    accreditations: ['FDA approved', 'WHO prequalified vaccines'],
    yearsInBusiness: 24,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'sanofi',
    name: 'Sanofi',
    description: 'French pharmaceutical company known for diabetes care, vaccines, and rare disease treatments.',
    category: 'pharma',
    services: ['Diabetes', 'Vaccines', 'Rare diseases', 'Immunology', 'Patient assistance'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'Sanofi Patient Connection provides assistance for qualifying patients.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.sanofi.com',
    referralType: 'direct_link',
    ourTake: 'Sanofi is a major player in diabetes (Lantus insulin), vaccines, and rare diseases. Their Dupixent for eczema/asthma has been a game-changer. Patient assistance is available but can be complex to navigate.',
    bestFor: ['Diabetes management', 'Eczema/allergies (Dupixent)', 'Vaccines'],
    pros: ['Diverse portfolio', 'Rare disease expertise', 'Global vaccine leader', 'Patient assistance available'],
    cons: ['Dupixent expensive without coverage', 'Navigation can be complex', 'Some insulin products facing competition'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 20,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'astrazeneca',
    name: 'AstraZeneca',
    description: 'British-Swedish pharmaceutical company known for oncology, respiratory, and cardiovascular medications.',
    category: 'pharma',
    services: ['Oncology', 'Respiratory', 'Cardiovascular', 'Diabetes', 'Patient assistance'],
    pricingDisplay: 'Varies by drug',
    pricingNotes: 'AZ&Me prescription savings program provides assistance to eligible patients.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Global'],
    url: 'https://www.astrazeneca.com',
    referralType: 'direct_link',
    ourTake: 'AstraZeneca made headlines with their COVID vaccine and has a strong oncology pipeline. Their AZ&Me program can help with costs for many medications. Worth checking for cancer and respiratory patients.',
    bestFor: ['Cancer treatment', 'Respiratory conditions', 'Heart disease'],
    pros: ['Strong oncology drugs', 'Respiratory expertise', 'Patient assistance program', 'Active R&D'],
    cons: ['Specialty drugs expensive', 'Complex insurance navigation', 'Some supply constraints'],
    accreditations: ['FDA approved'],
    yearsInBusiness: 25,
    featured: false,
    lastVerified: '2024-12-21',
  },
];

export default {
  pharma: pharmaProviders,
};
