import { Provider } from './types';

// =============================================================================
// LABS (Telehealth)
// =============================================================================

export const labsProviders: Provider[] = [
  {
    slug: 'superpower',
    name: 'SuperPower',
    description: 'Annual membership offering 100+ biomarker testing with AI-powered insights and personalized health plans.',
    category: 'labs',
    services: ['100+ biomarkers', 'Annual comprehensive panel', 'AI-powered insights', 'Personalized health plans', 'Quest Diagnostics partnership'],
    pricingDisplay: '$17/month',
    pricingNotes: 'Billed annually at $199. One comprehensive 100+ biomarker test per year. Additional tests $179 each.',
    pricingComparison: 'vs $1,000+ for similar testing through traditional healthcare',
    savingsPercent: 80,
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National - 3,000+ Quest locations'],
    url: 'https://superpower.com',
    referralType: 'affiliate_link',
    ourTake: 'SuperPower is the most affordable comprehensive testing option at just $17/month (billed annually at $199). You get one massive 100+ biomarker panel annually through Quest Labs, plus AI-driven insights and actionable health plans. The catch: only one test per year unless you pay $179 for additional tests. Best for annual baseline tracking on a budget.',
    bestFor: ['Budget-conscious', 'Annual comprehensive baseline', 'AI-driven recommendations'],
    pros: ['Most affordable ($17/month)', '100+ biomarkers in one draw', 'Quest partnership (3,000 locations)', 'AI-powered personalized plans', 'HSA/FSA eligible'],
    cons: ['Only one test per year', 'Additional tests cost $179', 'No physician consultation included', 'Heavy supplement upselling reported ($400+/month)'],
    procedureVolume: 'New startup (2024 launch)',
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'rythm-health',
    name: 'Rythm Health',
    description: 'Innovative at-home blood testing using needle-free device with monthly tracking capability.',
    category: 'labs',
    services: ['Needle-free blood collection', 'Monthly tracking', 'AI coach', 'Comprehensive biomarkers'],
    pricingDisplay: '$79/month',
    pricingNotes: 'Per comprehensive test. Ideal for monthly tracking.',
    pricingComparison: 'Affordable option for frequent tracking',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://rythmhealth.com',
    referralType: 'direct_link',
    ourTake: 'Rythm Health stands out for their needle-free blood collection device—92% of users prefer it over traditional needlesticks. At $79 per month, it\'s affordable for monthly tracking. Results in 7 days with AI coach to interpret. The device has 95-99% concordance with traditional lab draws. Best for those who want frequent testing without the pain of venipuncture.',
    bestFor: ['Needle-phobic', 'Monthly tracking', 'Frequent testing', 'Prefer at-home collection'],
    pros: ['Needle-free device (pain-free)', '95-99% accuracy vs venipuncture', 'Fast results (7 days)', 'AI coach included', 'Free Uber pickup'],
    cons: ['Limited test panel vs competitors', 'No high-sensitivity CRP or A1c', 'No app (web-only)', 'New company (less established)'],
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'marek-health',
    name: 'Marek Health',
    description: 'Comprehensive blood panels with physician consultation and personalized optimization protocols. Nearly 300 biomarkers available.',
    category: 'labs',
    services: ['Comprehensive panels', 'Hormone testing', 'Metabolic markers', 'Genetic analysis', 'Physician consultation', 'Monthly coaching'],
    pricingDisplay: '$250-850/panel',
    pricingNotes: 'Includes physician review and consultation. Follow-up labs $200+',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National (except NY, NJ, RI)'],
    url: 'https://marekhealth.com',
    referralType: 'affiliate_link',
    ourTake: 'Marek is the gold standard for comprehensive hormone and health optimization. You pay more, but you get physician consultation, nearly 300 biomarkers to choose from, and ongoing coaching. Best for serious optimizers who want guidance, not just data.',
    bestFor: ['Comprehensive testing', 'Hormone optimization', 'Want physician guidance'],
    pros: ['Most comprehensive biomarker selection', 'Physician consultation included', 'Monthly coaching check-ins', '5-star Trustpilot (800+ reviews)'],
    cons: ['Higher price point', 'Not available in NY, NJ, RI', '14-day turnaround', 'Can be overkill for basic testing'],
    accreditations: ['LabCorp partnership'],
    procedureVolume: '10,000+ patients',
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'function-health',
    name: 'Function Health',
    description: 'Membership-based platform offering 100+ lab tests twice yearly with AI-powered insights and action plans.',
    category: 'labs',
    services: ['100+ biomarkers', 'Heart health', 'Hormones', 'Thyroid', 'Cancer markers', 'Nutrients', 'Aging factors'],
    pricingDisplay: '$499/year',
    pricingNotes: 'Includes 2 comprehensive assessments per year. Additional $99 for mobile blood draw.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National (except NY, NJ)'],
    url: 'https://functionhealth.com',
    referralType: 'affiliate_link',
    ourTake: 'Function Health is the buzzy longevity-focused option backed by celebrity investors. Great value at $499/year for 100+ tests twice yearly. The catch: no direct physician access - you get AI insights and need to bring results to your own doctor.',
    bestFor: ['Longevity-focused', 'Annual comprehensive testing', 'Self-directed health'],
    pros: ['100+ biomarkers for $499/year', '50,000+ members', 'Great UI and insights', 'Quest Diagnostics labs'],
    cons: ['No direct physician consultation', 'Not in NY, NJ (or pay extra)', 'Waitlist for new members', '7-10 day turnaround'],
    procedureVolume: '50,000+ members',
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'insidetracker',
    name: 'InsideTracker',
    description: 'AI-powered blood testing platform with personalized nutrition, supplement, and exercise recommendations.',
    category: 'labs',
    services: ['Blood panels (26-48 biomarkers)', 'DNA testing', 'AI recommendations', 'Fitness optimization'],
    pricingDisplay: '$249-589/test',
    pricingNotes: 'Foundation (26 markers) or Ultimate (48 markers). DNA test available.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://insidetracker.com',
    referralType: 'affiliate_link',
    ourTake: 'InsideTracker is the OG of consumer blood testing, popular with athletes and biohackers. Strong AI-driven recommendations for nutrition and fitness. Less comprehensive than Marek or Function, but more actionable for lifestyle optimization.',
    bestFor: ['Athletes', 'Fitness optimization', 'Actionable recommendations'],
    pros: ['Strong AI recommendations', 'Good for fitness-focused users', 'Quest partnership', 'DNA integration available'],
    cons: ['Fewer biomarkers than competitors', 'No physician consultation', 'Can get expensive with add-ons'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'everlywell',
    name: 'Everlywell',
    description: 'Convenient at-home testing for specific health concerns including food sensitivities, hormones, and STDs.',
    category: 'labs',
    services: ['Food sensitivity', 'Hormone testing', 'STD testing', 'Thyroid', 'Metabolism'],
    pricingDisplay: '$49-199/test',
    pricingNotes: 'Subscription available for lower per-test pricing.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National (limited in NY)'],
    url: 'https://everlywell.com',
    referralType: 'affiliate_link',
    ourTake: 'Everlywell is the mass-market option - great for specific concerns like food sensitivities or a quick hormone check. Not for comprehensive panels, but unbeatable convenience and price for targeted testing.',
    bestFor: ['Specific health concerns', 'Food sensitivities', 'Budget-conscious'],
    pros: ['Most affordable option', 'Wide retail availability', 'Quick turnaround (5-7 days)', 'Good for single-issue testing'],
    cons: ['Not comprehensive', 'No physician support', 'Limited biomarkers per test'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'letsgetchecked',
    name: 'LetsGetChecked',
    description: 'At-home lab testing with nurse consultation included for results review and guidance.',
    category: 'labs',
    services: ['STD testing', 'Hormone panels', 'Vitamin levels', 'Thyroid', 'Liver/kidney function'],
    pricingDisplay: '$69-149/test',
    pricingNotes: 'Nurse consultation included with all tests.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://letsgetchecked.com',
    referralType: 'affiliate_link',
    ourTake: 'LetsGetChecked stands out for including nurse phone consultations with every test - you actually get to talk to someone about your results. Best for STD testing and vitamin panels where you want guidance.',
    bestFor: ['Want to talk to someone', 'STD testing', 'Vitamin/mineral levels'],
    pros: ['Nurse consultation included', 'Fast turnaround (2-5 days)', 'CAP/ISO accredited', 'Good customer support'],
    cons: ['Smaller test menu', 'Pricier than Everlywell', 'No comprehensive panels'],
    accreditations: ['CLIA certified', 'CAP accredited', 'ISO certified'],
    featured: false,
    lastVerified: '2024-12-01',
  },
];

// =============================================================================
// GLP-1 PROGRAMS (Telehealth)
// =============================================================================

export const glp1Providers: Provider[] = [
  {
    slug: 'hims-hers-glp1',
    name: 'Hims / Hers',
    description: 'Popular telehealth platform offering compounded semaglutide at competitive prices, plus brand-name options.',
    category: 'glp1',
    services: ['Compounded semaglutide', 'Brand Wegovy/Ozempic', 'Provider consultations', 'Ongoing support'],
    pricingDisplay: '$199/mo (compound)',
    pricingNotes: 'Compounded: $199/mo with 6-month plan. Brand Wegovy: $1,799/mo. Brand Ozempic: $1,799/mo.',
    pricingComparison: 'vs $1,000+/mo for brand without insurance',
    savingsPercent: 80,
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://hims.com/weight-loss',
    referralType: 'affiliate_link',
    ourTake: 'Hims/Hers is the most recognizable name in telehealth GLP-1s. Their compounded semaglutide at $199/mo is competitive, and they now offer brand-name access too. Good for those who want a mainstream, well-funded platform.',
    bestFor: ['Budget compound option', 'Brand-name access', 'Mainstream platform'],
    pros: ['Recognizable brand', 'Both compound and brand options', 'Good mobile app', 'Fast shipping'],
    cons: ['No insurance accepted', 'Compounded = not FDA-approved', '6-month commitment for best price'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'ro-body',
    name: 'Ro Body Program',
    description: 'Telehealth weight loss program with access to brand-name GLP-1s through NovoCare pharmacy partnership.',
    category: 'glp1',
    services: ['Wegovy', 'Ozempic', 'Coaching', 'Provider support'],
    pricingDisplay: '$145/mo + meds',
    pricingNotes: 'First month $99, then $145/mo for program. Brand meds via NovoCare: $499/mo (reduced from $1,000+).',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://ro.co/weight-loss',
    referralType: 'affiliate_link',
    ourTake: 'Ro has a unique angle: partnership with NovoCare gives access to real Wegovy/Ozempic at $499/mo instead of $1,000+. If you want brand-name medications without insurance, this is currently the best path.',
    bestFor: ['Brand-name GLP-1 access', 'Cash-pay for real Wegovy', 'Established telehealth'],
    pros: ['Brand-name meds at reduced price', 'NovoCare partnership', 'Established platform', 'Good support'],
    cons: ['Still expensive ($499/mo for meds)', 'No compounded option', 'Program fee on top of meds'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'noom-med',
    name: 'Noom Med',
    description: 'Behavior change app now offering compounded GLP-1 medications with integrated coaching and tracking.',
    category: 'glp1',
    services: ['Compounded semaglutide', 'Noom app access', 'Behavior coaching', 'Food logging'],
    pricingDisplay: '$149-279/mo',
    pricingNotes: 'First month $149, increases to $279 as dose increases. Includes Noom app.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://noom.com/med',
    referralType: 'affiliate_link',
    ourTake: 'Noom Med combines their popular behavior-change app with GLP-1 access. The idea is that the app helps you build habits while the medication helps with appetite. Good if you want more than just a prescription.',
    bestFor: ['Behavior change focus', 'Want coaching + meds', 'App-based tracking'],
    pros: ['Integrated behavior coaching', 'Popular app platform', 'No insurance required', 'Holistic approach'],
    cons: ['Higher price as dose increases', 'Compounded = not FDA-approved', 'May be overkill if you just want meds'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'calibrate',
    name: 'Calibrate',
    description: 'Metabolic reset program with GLP-1 prescription, bi-weekly coaching, and long-term maintenance focus.',
    category: 'glp1',
    services: ['GLP-1 prescription', 'Bi-weekly coaching', 'Metabolic health focus', 'Long-term maintenance'],
    pricingDisplay: '$199/mo',
    pricingNotes: 'Requires 3-month commitment. Medication cost depends on insurance.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://calibrate.com',
    referralType: 'affiliate_link',
    ourTake: 'Calibrate is the premium, coaching-heavy option. They focus on metabolic health and long-term maintenance, not just weight loss. Requires insurance for the medication, so not a true cash-pay option for meds.',
    bestFor: ['Coaching-focused', 'Have insurance for meds', 'Long-term metabolic health'],
    pros: ['Strong coaching program', 'Metabolic health focus', 'Maintenance planning', 'Bi-weekly sessions'],
    cons: ['Requires insurance for meds', '3-month minimum', 'Premium pricing', 'Not fully cash-pay'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'found',
    name: 'Found',
    description: 'Weight loss membership with access to various medications including GLP-1s, plus app-based coaching.',
    category: 'glp1',
    services: ['GLP-1 prescriptions', 'Other weight loss meds', 'App-based coaching', 'Provider consultations'],
    pricingDisplay: '$99-149/mo + $189/mo meds',
    pricingNotes: 'Membership required ($99-149/mo). GLP-1 medications additional ($189+/mo).',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://joinfound.com',
    referralType: 'affiliate_link',
    ourTake: 'Found takes a membership approach - you pay for access, then pay separately for medications. Good if you want flexibility in medication options, but the costs add up. 4 provider consults first month.',
    bestFor: ['Flexibility in medications', 'App-based approach', 'Multiple med options'],
    pros: ['Multiple medication options', 'Unlimited online coach access', 'Good app experience', '4 consults first month'],
    cons: ['Membership + med costs add up', 'Medication not included in base price', 'Can get expensive'],
    featured: false,
    lastVerified: '2024-12-01',
  },
];

// =============================================================================
// TRT (Telehealth)
// =============================================================================

export const trtProviders: Provider[] = [
  {
    slug: 'fountain-trt',
    name: 'Fountain TRT',
    description: 'Streamlined TRT telehealth platform specializing in testosterone creams and injections with minimal friction.',
    category: 'trt',
    services: ['Testosterone cream', 'Testosterone injections', 'Ongoing consultations', 'Lab monitoring'],
    pricingDisplay: '~$199/mo',
    pricingNotes: 'Includes medication, consultations, and medical team access. $30 onboarding blood test.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://fountaintrt.com',
    referralType: 'affiliate_link',
    ourTake: 'Fountain TRT is the "set it and forget it" option. Great for busy professionals who want straightforward TRT without extensive optimization. They favor creams, which some prefer over injections.',
    bestFor: ['Convenience', 'Prefer creams', 'Minimal hassle', 'Busy professionals'],
    pros: ['Simple onboarding', '4.8★ Trustpilot', 'Responsive support', 'Both cream and injection options'],
    cons: ['Less comprehensive than Marek', 'Limited customization', 'Focused solely on TRT'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'marek-health-trt',
    name: 'Marek Health (TRT)',
    description: 'Comprehensive hormone optimization with the most thorough testing and physician oversight in the industry.',
    category: 'trt',
    services: ['Full hormone panel', 'TRT protocols', 'Peptides', 'Nutritional support', 'Monthly coaching'],
    pricingDisplay: '$450-1,700 (labs) + treatment',
    pricingNotes: 'Initial labs $450-1,700 (with optional genetics). Treatment costs additional. Follow-up labs every 6 months.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National (except NY, NJ, RI)'],
    url: 'https://marekhealth.com',
    referralType: 'affiliate_link',
    ourTake: 'Marek is the premium choice for those who want complete hormone optimization, not just TRT. Most comprehensive testing available, physician oversight, and access to peptides. You pay significantly more, but get concierge-level care.',
    bestFor: ['Comprehensive optimization', 'Want full hormone panel', 'Willing to invest'],
    pros: ['Most thorough testing', 'Physician consultations', 'Peptide access', 'Holistic approach'],
    cons: ['Most expensive option', 'Not in NY, NJ, RI', 'May be overkill for simple TRT'],
    accreditations: ['LabCorp partnership'],
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'trt-nation',
    name: 'TRT Nation',
    description: 'Budget-friendly all-inclusive TRT program with straightforward pricing and solid results.',
    category: 'trt',
    services: ['Testosterone injections', 'Lab monitoring', 'Provider consultations'],
    pricingDisplay: '$99/mo',
    pricingNotes: 'All-inclusive pricing. Labs, medication, and consultations included.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://trtnation.com',
    referralType: 'affiliate_link',
    ourTake: 'TRT Nation is the best value in the market at $99/mo all-in. No frills, but effective TRT for those who know what they want and don\'t need extensive hand-holding or optimization beyond testosterone.',
    bestFor: ['Budget-conscious', 'Straightforward TRT', 'Know what you need'],
    pros: ['Best value at $99/mo', 'All-inclusive pricing', 'No surprise costs', 'Solid reputation'],
    cons: ['Less comprehensive testing', 'Basic service', 'Limited customization'],
    featured: false,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'henry-meds-trt',
    name: 'Henry Meds',
    description: 'Competitive TRT telehealth with labs included in the monthly price.',
    category: 'trt',
    services: ['Testosterone therapy', 'Labs included', 'Provider consultations'],
    pricingDisplay: '$129/mo',
    pricingNotes: 'Labs included in monthly price.',
    deliveryModel: 'telehealth_national',
    geographicCoverage: ['National'],
    url: 'https://henrymeds.com',
    referralType: 'affiliate_link',
    ourTake: 'Henry Meds hits a sweet spot - more comprehensive than TRT Nation, less expensive than Fountain. Labs included makes budgeting easy. Good middle-ground option.',
    bestFor: ['Want labs included', 'Mid-range budget', 'Straightforward service'],
    pros: ['Labs included in price', 'Competitive pricing', 'Good value proposition'],
    cons: ['Less known brand', 'Not as comprehensive as Marek'],
    featured: false,
    lastVerified: '2024-12-01',
  },
];

// =============================================================================
// DEXA (Local)
// =============================================================================

export const dexaProviders: Provider[] = [
  {
    slug: 'bodyspec',
    name: 'BodySpec',
    description: 'Affordable DEXA scans through storefronts, mobile vans, and gym partnerships across major cities.',
    category: 'dexa',
    services: ['DEXA body composition', 'Body fat by region', 'Lean mass tracking', 'Visceral fat', 'Bone density'],
    pricingDisplay: '$40-45/scan',
    pricingNotes: 'Single scan ~$45. Membership drops to $40/scan. Credits never expire.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['Austin', 'Los Angeles', 'San Francisco', 'Seattle', 'Dallas', 'New York'],
    url: 'https://bodyspec.com',
    referralType: 'affiliate_link',
    ourTake: 'BodySpec revolutionized DEXA pricing by partnering with gyms and using mobile vans. At $40-45/scan, there\'s no reason not to track your body composition quarterly. Best value in the market.',
    bestFor: ['Budget-conscious', 'Regular tracking', 'Major metro areas'],
    pros: ['Best pricing ($40-45)', '500,000+ scans performed', 'Mobile van convenience', 'Gym partnerships'],
    cons: ['Limited to select cities', 'Mobile vans = less scheduling flexibility', 'Basic service'],
    procedureVolume: '500,000+ scans',
    yearsInBusiness: 12,
    featured: true,
    lastVerified: '2024-12-01',
  },
  {
    slug: 'dexafit',
    name: 'DexaFit',
    description: 'Full-service body composition testing including DEXA, VO2 max, and RMR at franchise locations nationwide.',
    category: 'dexa',
    services: ['DEXA scan', 'VO2 max testing', 'RMR (metabolic rate)', '3D body scan'],
    pricingDisplay: '$100-150/scan',
    pricingNotes: 'Packages available: 4 tests for $410, 8 tests for $660. Memberships from $58-83/mo.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['National (franchise locations)'],
    url: 'https://dexafit.com',
    referralType: 'affiliate_link',
    ourTake: 'DexaFit is the premium option with more locations and additional services like VO2 max. Pricier than BodySpec, but worth it if you want metabolic testing or don\'t have BodySpec nearby.',
    bestFor: ['Want VO2 max too', 'More locations', 'Comprehensive testing'],
    pros: ['Nationwide franchise network', 'VO2 max and RMR available', 'Package discounts', 'More locations'],
    cons: ['More expensive than BodySpec', 'Pricing varies by location', 'Franchise quality varies'],
    featured: false,
    lastVerified: '2024-12-01',
  },
];

export default {
  labs: labsProviders,
  glp1: glp1Providers,
  trt: trtProviders,
  dexa: dexaProviders,
};
