import { Provider } from './types';

// =============================================================================
// INSURANCE COMPANIES
// =============================================================================
// Organized into Traditional (established) and Innovator (tech-first) categories
// to help consumers understand different approaches to health coverage.

// =============================================================================
// TRADITIONAL INSURERS
// =============================================================================
// The established giants - massive networks, decades of experience, but often
// bureaucratic. These companies cover the majority of Americans.

export const traditionalInsurers: Provider[] = [
  {
    slug: 'united-healthcare',
    name: 'UnitedHealthcare',
    description: 'Largest health insurer in the US by revenue ($189B+), offering employer-sponsored, individual, Medicare, and Medicaid plans nationwide.',
    category: 'insurance',
    services: ['Employer plans', 'Individual & family plans', 'Medicare Advantage', 'Medicaid', 'Short-term plans', 'Dental & vision'],
    pricingDisplay: 'Varies by plan',
    pricingNotes: 'Pricing depends on plan type, location, age, and coverage level. ACA plans available through Healthcare.gov.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['National - All 50 states'],
    url: 'https://www.uhc.com',
    referralType: 'direct_link',
    ourTake: 'UnitedHealthcare is the 800-lb gorilla of health insurance with 15% market share. Massive network and strong digital tools, but reviews are mixed on claims processing and prior authorization delays. Good for employer plans where you don\'t have a choice. For individual plans, shop around.',
    bestFor: ['Employer-sponsored coverage', 'Large network needs', 'Medicare Advantage'],
    pros: ['Largest provider network in the US', 'Available nationwide', 'Strong digital tools and app', 'Multiple plan types for every situation'],
    cons: ['Mixed customer service reviews', 'Prior authorization can be frustratingly slow', 'Premium pricing in some markets', 'Corporate bureaucracy'],
    accreditations: ['NCQA accredited plans'],
    yearsInBusiness: 47,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'elevance-anthem',
    name: 'Elevance Health (Anthem Blue Cross Blue Shield)',
    description: 'Second-largest health insurer ($124B revenue), operating as Anthem Blue Cross Blue Shield in 14 states with access to the national BCBS network.',
    category: 'insurance',
    services: ['Individual & family plans', 'Employer plans', 'Medicare', 'Medicaid', 'Dental', 'Vision', 'Behavioral health'],
    pricingDisplay: 'Varies by state/plan',
    pricingNotes: 'ACA-compliant plans available. Pricing varies significantly by state and coverage level.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['CA', 'CO', 'CT', 'GA', 'IN', 'KY', 'ME', 'MO', 'NV', 'NH', 'NY', 'OH', 'VA', 'WI'],
    url: 'https://www.anthem.com',
    referralType: 'direct_link',
    ourTake: 'Anthem carries the trusted Blue Cross Blue Shield brand and has strong networks in its 14 operating states. The BCBS network means you can often use providers across state lines. Worth comparing if you\'re in their territory, especially for PPO options.',
    bestFor: ['Blue Cross Blue Shield network access', 'PPO plan seekers', 'Multi-state employers', 'Cross-state coverage needs'],
    pros: ['Blue Cross Blue Shield network (84% of metro areas have BCBS as top insurer)', 'Strong regional presence', 'Good PPO options', 'Robust mobile app'],
    cons: ['Only operates in 14 states directly', 'Customer service varies by region', 'Some narrow networks on ACA marketplace plans'],
    accreditations: ['NCQA accredited'],
    yearsInBusiness: 80,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'kaiser-permanente',
    name: 'Kaiser Permanente',
    description: 'Unique integrated health system combining insurance with its own hospitals, doctors, and pharmacies. Known for coordinated care and preventive focus.',
    category: 'insurance',
    services: ['Individual & family plans', 'Employer plans', 'Medicare', 'Medicaid', 'Integrated care', 'Mental health'],
    pricingDisplay: '$300-800/mo individual',
    pricingNotes: 'Pricing varies by region. Often competitive due to integrated model eliminating middlemen. Limited to Kaiser facilities only.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['CA', 'CO', 'GA', 'HI', 'MD', 'OR', 'VA', 'WA', 'DC'],
    url: 'https://www.kaiserpermanente.org',
    referralType: 'direct_link',
    ourTake: 'Kaiser is fundamentally different: they\'re both insurer AND provider. If you like one-stop-shop healthcare where your doctor, specialists, pharmacy, and insurer are all connected, it\'s often the best value. The catch: you MUST use Kaiser facilities. No out-of-network flexibility whatsoever. Love it or hate it - no middle ground.',
    bestFor: ['Coordinated care preference', 'Cost-conscious consumers', 'Kaiser service areas', 'People who want one system'],
    pros: ['Integrated care model - everyone talks to each other', 'Often lower premiums than competitors', 'Excellent preventive care focus', 'Top-rated for member satisfaction', 'No claims to file'],
    cons: ['Must use Kaiser facilities exclusively', 'Limited to 9 states/regions', 'Zero out-of-network coverage', 'Can feel restrictive if you want choice'],
    accreditations: ['NCQA highest ratings', 'JD Power awards for member satisfaction'],
    yearsInBusiness: 79,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'centene-ambetter',
    name: 'Centene (Ambetter Health)',
    description: 'Largest ACA marketplace insurer (5.8M members) and largest Medicaid managed care organization. Known for affordable options for lower and middle-income families.',
    category: 'insurance',
    services: ['ACA marketplace plans', 'Medicaid managed care', 'Medicare (Wellcare)', 'CHIP', 'Correctional healthcare'],
    pricingDisplay: 'Often lowest ACA premiums',
    pricingNotes: 'Ambetter frequently offers the lowest or second-lowest cost ACA plans in markets where they operate. Strong for subsidy-eligible consumers.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['29 states via Ambetter', '31 states Medicaid'],
    url: 'https://www.ambetterhealth.com',
    referralType: 'direct_link',
    ourTake: 'Centene\'s Ambetter is the #1 ACA marketplace insurer for a reason: they specialize in serving people who qualify for subsidies. If you\'re shopping on Healthcare.gov and want the lowest premium, Ambetter will likely be in your top options. The trade-off: networks can be narrower than premium carriers, and customer service reviews are mixed. But for budget-conscious coverage, they\'re hard to beat.',
    bestFor: ['ACA marketplace shoppers', 'Subsidy-eligible individuals', 'Medicaid recipients', 'Budget-conscious families'],
    pros: ['Often lowest ACA premiums', '#1 marketplace carrier by enrollment', 'Strong Medicaid experience', 'Expanding to 60 new counties in 2025', 'Good for those with subsidies'],
    cons: ['Narrower provider networks', 'Customer service can be inconsistent', 'Less name recognition than BCBS', 'Some markets have limited specialist access'],
    accreditations: ['NCQA accredited in multiple states'],
    yearsInBusiness: 40,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'aetna-cvs',
    name: 'Aetna (CVS Health)',
    description: 'Major national insurer now part of CVS Health, offering unique integration with CVS pharmacies, MinuteClinic, and HealthHUB locations.',
    category: 'insurance',
    services: ['Individual & family plans', 'Employer plans', 'Medicare', 'Medicaid', 'CVS integration', 'Behavioral health', 'Dental'],
    pricingDisplay: 'Varies by plan',
    pricingNotes: 'Competitive pricing especially for those using CVS pharmacy benefits. CVS Caremark PBM integration.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['National - All 50 states'],
    url: 'https://www.aetna.com',
    referralType: 'direct_link',
    ourTake: 'The CVS acquisition (2018) gives Aetna a unique angle: deep pharmacy integration. If you use CVS for prescriptions, the savings and convenience add up. MinuteClinic visits, HealthHUB services, and pharmacy sync all work together. Good Medicare options and solid employer plans. The downside: still has big-insurer bureaucracy and prior auth headaches.',
    bestFor: ['CVS pharmacy users', 'Medicare shoppers', 'Employer plan members', 'Those who want pharmacy + insurance integration'],
    pros: ['CVS pharmacy integration benefits', 'MinuteClinic access', 'Strong behavioral health coverage', 'Good digital experience', 'Nationwide availability'],
    cons: ['Customer service complaints common', 'Prior authorization requirements', 'Some narrow networks on marketplace plans', 'CVS benefits less valuable if you prefer other pharmacies'],
    accreditations: ['NCQA accredited'],
    yearsInBusiness: 170,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'cigna',
    name: 'Cigna',
    description: 'Global health services company (11% US market share) known for strong employer plans and unique international coverage options.',
    category: 'insurance',
    services: ['Employer plans', 'Individual plans', 'Medicare', 'International coverage', 'Behavioral health', 'Dental', 'Pharmacy (Express Scripts)'],
    pricingDisplay: 'Varies by plan',
    pricingNotes: 'Often competitive for employer plans. Individual market presence varies by state. Owns Express Scripts PBM.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['National - All 50 states', 'International - 30+ countries'],
    url: 'https://www.cigna.com',
    referralType: 'direct_link',
    ourTake: 'Cigna shines in two areas: employer plans and international coverage. If you\'re an expat, travel frequently, or work for a multinational company, Cigna\'s global network is genuinely useful. They own Express Scripts, one of the largest PBMs. Less competitive in the individual ACA market - they\'ve pulled out of many states.',
    bestFor: ['Employer-sponsored coverage', 'International coverage needs', 'Expats and frequent travelers', 'Global companies'],
    pros: ['Strong employer plan options', 'International coverage in 30+ countries', 'Good behavioral health programs', '24/7 nurse line', 'Express Scripts pharmacy integration'],
    cons: ['Limited ACA marketplace presence', 'Customer service varies', 'Some network limitations', 'PBM ownership raises conflict of interest concerns'],
    accreditations: ['NCQA accredited'],
    yearsInBusiness: 230,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'humana',
    name: 'Humana',
    description: 'Major insurer (6.6% market share) with dominant strength in Medicare Advantage plans and senior healthcare services.',
    category: 'insurance',
    services: ['Medicare Advantage', 'Medicare Supplement', 'Prescription drug plans (Part D)', 'Dental', 'Vision', 'Home health', 'Employer plans'],
    pricingDisplay: 'Varies by plan',
    pricingNotes: 'Known for competitive Medicare Advantage pricing with strong supplemental benefits. Individual/employer plans vary by market.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['National - Most states', 'Medicare focus'],
    url: 'https://www.humana.com',
    referralType: 'direct_link',
    ourTake: 'If you\'re 65+, Humana absolutely should be on your Medicare comparison list. They\'ve invested heavily in senior-focused care coordination, home health services, and wellness programs. Many of their Medicare Advantage plans earn 4+ star ratings from CMS. For under-65 coverage, they\'re less notable - Medicare is their bread and butter.',
    bestFor: ['Medicare beneficiaries', 'Seniors', 'Prescription drug coverage', 'Home health needs'],
    pros: ['Strong Medicare Advantage options', 'Good supplemental benefits (dental, vision, fitness)', 'CenterWell home health integration', 'Wellness and prevention programs', 'CMS 4+ star ratings on many plans'],
    cons: ['Weaker in under-65 market', 'Network varies significantly by region', 'Some prior authorization delays', 'Less competitive for employer plans'],
    accreditations: ['CMS 4+ star ratings on many MA plans'],
    yearsInBusiness: 63,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'hcsc',
    name: 'Health Care Service Corporation (HCSC)',
    description: 'Largest customer-owned health insurer in the US, operating Blue Cross Blue Shield plans in 5 major states: IL, MT, NM, OK, and TX.',
    category: 'insurance',
    services: ['Individual & family plans', 'Employer plans', 'Medicare', 'Medicaid', 'Federal Employee Program', 'Dental', 'Vision'],
    pricingDisplay: 'Varies by state/plan',
    pricingNotes: 'Pricing varies by state. Often the dominant or sole BCBS option in their operating states.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['IL', 'MT', 'NM', 'OK', 'TX'],
    url: 'https://www.hcsc.com',
    referralType: 'direct_link',
    ourTake: 'HCSC is massive but flies under the radar because they operate as Blue Cross Blue Shield in their states, not under their corporate name. In Illinois and Texas especially, they\'re often THE dominant insurer. Customer-owned structure (mutual company) means they\'re not driven by stock price. If you\'re in their states, you\'re likely already considering them via the BCBS brand.',
    bestFor: ['IL, TX, MT, NM, OK residents', 'BCBS network access', 'Federal employees', 'Large employer plans'],
    pros: ['Customer-owned (not stockholder-driven)', 'Blue Cross Blue Shield network access', '7% national market share', 'Dominant in their operating states', 'Strong employer relationships'],
    cons: ['Only 5 states', 'Operates under BCBS brand (confusing)', 'Customer experience varies by state', 'Can be bureaucratic'],
    accreditations: ['NCQA accredited', 'BCBS Association member'],
    yearsInBusiness: 88,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'molina-healthcare',
    name: 'Molina Healthcare',
    description: 'Major Medicaid and ACA marketplace insurer specializing in affordable coverage for lower-income individuals and families.',
    category: 'insurance',
    services: ['Medicaid managed care', 'ACA marketplace plans', 'Medicare', 'Dual-eligible (Medicare + Medicaid)', 'CHIP'],
    pricingDisplay: 'Often lowest-cost option',
    pricingNotes: 'Frequently the most affordable ACA marketplace option in their markets. Specializes in government-sponsored coverage.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['CA', 'FL', 'IL', 'MI', 'NM', 'NY', 'OH', 'SC', 'TX', 'UT', 'WA', 'WI'],
    url: 'https://www.molinahealthcare.com',
    referralType: 'direct_link',
    ourTake: 'Molina knows their lane: affordable coverage for people who qualify for government programs or subsidies. If you\'re shopping for the lowest premium on Healthcare.gov, Molina and Ambetter are often your top choices. They also acquired Bright Health\'s remaining plans in 2024. Networks are smaller but functional. Not trying to compete with the UnitedHealthcares of the world on employer plans.',
    bestFor: ['Subsidy-eligible individuals', 'Medicaid recipients', 'Budget-focused ACA shoppers', 'Dual-eligible members'],
    pros: ['Often lowest premiums', 'Decades of Medicaid experience', 'Good care coordination', 'Understands low-income healthcare needs', 'Acquired Bright Health plans'],
    cons: ['Smaller provider networks', 'Customer service can lag', 'Limited presence in some markets', 'Not competitive for employer plans'],
    accreditations: ['NCQA accredited'],
    yearsInBusiness: 44,
    featured: false,
    lastVerified: '2024-12-21',
  },
];

// =============================================================================
// INSURANCE INNOVATORS
// =============================================================================
// Tech-first startups trying to modernize health insurance with better apps,
// virtual care, and transparent pricing. Some are thriving, others struggling.
// We include honest assessments of their financial challenges.

export const insuranceInnovators: Provider[] = [
  {
    slug: 'oscar-health',
    name: 'Oscar Health',
    description: 'Tech-first health insurance startup focused on user experience, virtual care, and a modern approach to health coverage. Founded 2012.',
    category: 'insurance',
    services: ['Individual & family ACA plans', 'Small business plans', 'Free 24/7 virtual care', 'Concierge care team', '+Oscar technology licensing'],
    pricingDisplay: '$350-700/mo individual',
    pricingNotes: 'Competitive ACA marketplace pricing in select markets. Virtual care included at no extra cost. Expanding technology licensing to other insurers.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['AZ', 'FL', 'GA', 'KS', 'MI', 'MO', 'NJ', 'NY', 'OH', 'PA', 'TN', 'TX', 'VA'],
    url: 'https://www.hioscar.com',
    referralType: 'direct_link',
    ourTake: 'Oscar represents what health insurance SHOULD feel like: a great app, free virtual care, and a concierge team that actually helps navigate the system. They\'ve faced real financial challenges though - $610M loss in 2022 and exited California\'s individual market in 2024. They expect profitability in 2024 and are pivoting to also license their technology to other insurers (+Oscar). If you\'re in their markets and value user experience over maximum network size, Oscar is worth considering. Just know they\'re still proving they can survive long-term.',
    bestFor: ['Tech-savvy consumers', 'Virtual care users', 'ACA marketplace shoppers who value UX', 'People frustrated with traditional insurance'],
    pros: ['Best-in-class app and digital experience', 'Free 24/7 virtual care included', 'Dedicated concierge care team', 'Transparent, easy-to-understand pricing', 'Modern approach to member experience'],
    cons: ['Now in 13 states (exited CA individual market)', 'Narrower networks in some areas', 'Financial losses in past years (improving)', 'No Medicare yet', 'Still proving long-term viability'],
    accreditations: ['NCQA accredited'],
    yearsInBusiness: 12,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'clover-health',
    name: 'Clover Health',
    description: 'Medicare Advantage-focused insurtech using AI-powered Clover Assistant to help doctors make better care decisions. Heavy technology focus.',
    category: 'insurance',
    services: ['Medicare Advantage (PPO and HMO)', 'Prescription drug coverage', 'Clover Assistant AI for providers', 'Supplemental benefits'],
    pricingDisplay: 'Medicare Advantage pricing',
    pricingNotes: 'Premium varies by plan and county. Many $0 premium MA plans available. Focus on keeping healthcare costs down through better data.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['AL', 'GA', 'MS', 'NJ', 'PA', 'SC', 'TN', 'TX'],
    url: 'https://www.cloverhealth.com',
    referralType: 'direct_link',
    ourTake: 'Clover\'s pitch is interesting: use AI (their Clover Assistant) to help primary care doctors make better decisions, reducing unnecessary costs and improving outcomes. They went public via SPAC in 2021 at $3.7B valuation, then faced reality - $339M loss in 2022. They\'ve narrowed focus to 8 states and are slowly improving financials. If you\'re in their markets and like the idea of tech-enabled Medicare, worth a look. But they\'re still in turnaround mode.',
    bestFor: ['Medicare beneficiaries in their states', 'Seniors interested in tech-enabled care', 'Those who want AI-assisted primary care'],
    pros: ['AI-powered care insights (Clover Assistant)', '$0 premium MA plans available', 'Focus on preventive care', 'Some unique supplemental benefits', 'Improving financial trajectory'],
    cons: ['Limited to 8 states', 'SPAC-era company still finding footing', 'Past financial struggles', 'Smaller than traditional MA insurers', 'Network size varies by market'],
    accreditations: ['CMS-approved Medicare Advantage insurer'],
    yearsInBusiness: 10,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'devoted-health',
    name: 'Devoted Health',
    description: 'Medicare Advantage startup founded by former Athenahealth leaders, focusing on concierge-style service for seniors.',
    category: 'insurance',
    services: ['Medicare Advantage (HMO and PPO)', 'Prescription drug coverage', 'Devoted Guides (personal care coordinators)', 'Transportation', 'Dental & vision'],
    pricingDisplay: 'Medicare Advantage pricing',
    pricingNotes: 'Many $0 premium MA plans with rich benefits. Focus on service quality over pure cost.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['AZ', 'FL', 'IL', 'OH', 'TX', 'and expanding'],
    url: 'https://www.devoted.com',
    referralType: 'direct_link',
    ourTake: 'Devoted Health takes a different approach to Medicare Advantage: white-glove service. Every member gets a "Devoted Guide" - a real person who helps navigate care, schedule appointments, and solve problems. Founded by the former Athenahealth CEO, they\'ve raised over $1.5B and are expanding steadily. Less splashy than Oscar but arguably more sustainable. If you\'re a senior who values personal service over app features, Devoted is worth considering.',
    bestFor: ['Seniors who want personal attention', 'Medicare beneficiaries frustrated with call centers', 'Those who value service over tech', 'Members in their expansion states'],
    pros: ['Devoted Guides provide personal care coordination', 'Strong supplemental benefits', 'Transportation services included', 'Founded by healthcare veterans', 'Well-funded and expanding carefully'],
    cons: ['Limited to 6 states currently', 'Newer company (founded 2017)', 'Still growing network relationships', 'Not available in all counties within states'],
    accreditations: ['CMS-approved Medicare Advantage insurer'],
    yearsInBusiness: 7,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'alignment-healthcare',
    name: 'Alignment Healthcare',
    description: 'Value-based Medicare Advantage company using proprietary AVA technology platform to coordinate care for complex patients.',
    category: 'insurance',
    services: ['Medicare Advantage', 'D-SNP (dual eligible) plans', 'Care management', 'AVA technology platform', 'Home-based care'],
    pricingDisplay: 'Medicare Advantage pricing',
    pricingNotes: 'Focus on coordinated care for high-need seniors. Many $0 premium options with strong supplemental benefits.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['AZ', 'CA', 'NC', 'NV', 'TX'],
    url: 'https://www.alignmenthealthcare.com',
    referralType: 'direct_link',
    ourTake: 'Alignment Healthcare focuses on the hardest population to serve well: seniors with multiple chronic conditions. Their AVA platform tracks patient data to intervene before problems become emergencies. They went public in 2021 and have been growing steadily, now covering 170K+ members. Less focused on flashy consumer tech, more on actually coordinating complex care. A solid choice if you have multiple health conditions and want an insurer actively managing your care.',
    bestFor: ['Seniors with multiple chronic conditions', 'Medicare beneficiaries wanting care coordination', 'Dual-eligible members', 'Those who value proactive care management'],
    pros: ['Specialized in complex patient care', 'AVA technology for care coordination', 'Strong outcomes for high-need members', 'Public company (financial transparency)', 'Growing steadily'],
    cons: ['Limited to 5 states', 'Less consumer-facing tech focus', 'Newer brand with less recognition', 'Not ideal for healthy seniors who want minimal insurer involvement'],
    accreditations: ['CMS-approved Medicare Advantage insurer'],
    yearsInBusiness: 11,
    featured: false,
    lastVerified: '2024-12-21',
  },
];

// Combined exports
export const insuranceProviders: Provider[] = [
  ...traditionalInsurers,
  ...insuranceInnovators,
];

export default {
  insurance: insuranceProviders,
  traditional: traditionalInsurers,
  innovators: insuranceInnovators,
};
