import { TelehealthProvider } from './types';

export const telehealthProviders: TelehealthProvider[] = [
  // LABS PROVIDERS
  {
    slug: 'marek-health-labs',
    name: 'Marek Health',
    category: 'labs',
    type: 'telehealth',
    description: 'Comprehensive lab testing with physician consultations focused on optimization and longevity.',
    pricingDisplay: '$250-500 for comprehensive panels',
    pricingComparison: 'Similar panels cost $1,500+ through traditional healthcare',
    bestFor: ['Biohackers', 'Those wanting physician guidance', 'Comprehensive hormone panels'],
    pros: [
      'Detailed physician consultations included',
      'Focus on optimization, not just "normal" ranges',
      'Can prescribe treatments based on results',
      'Extensive hormone and metabolic panels',
    ],
    cons: [
      'Higher price point than basic services',
      'May be overkill for simple testing needs',
      'Requires membership for ongoing care',
    ],
    ourTake: 'Best for those who want actionable insights and physician guidance, not just raw numbers. The consultations alone are worth the premium.',
    deliveryModel: 'Lab orders sent to local Quest/Labcorp, results reviewed via telehealth',
    featured: true,
  },
  {
    slug: 'function-health',
    name: 'Function Health',
    category: 'labs',
    type: 'telehealth',
    description: 'Premium membership offering 100+ biomarkers tested twice yearly with an intuitive dashboard.',
    pricingDisplay: '$499/year membership',
    pricingComparison: 'Testing these biomarkers individually would cost $10,000+/year',
    bestFor: ['Health optimizers', 'Data-driven individuals', 'Those wanting longitudinal tracking'],
    pros: [
      '100+ biomarkers in one draw',
      'Beautiful, actionable dashboard',
      'Twice-yearly testing included',
      'Early disease detection focus',
    ],
    cons: [
      'Annual commitment required',
      'No physician consultations included',
      'Limited availability in some areas',
    ],
    ourTake: 'The best value for comprehensive testing if you want data and can interpret it yourself or with your own doctor.',
    deliveryModel: 'Lab draws at partner locations, results via app dashboard',
    featured: true,
  },
  {
    slug: 'insidetracker',
    name: 'InsideTracker',
    category: 'labs',
    type: 'telehealth',
    description: 'Science-backed blood testing with personalized nutrition and lifestyle recommendations.',
    pricingDisplay: '$189-589 per test',
    pricingComparison: '40-60% less than ordering through a doctor',
    bestFor: ['Athletes', 'Those wanting nutrition guidance', 'Performance optimizers'],
    pros: [
      'AI-powered personalized recommendations',
      'Integrates with fitness wearables',
      'Strong focus on actionable nutrition advice',
      'Founded by aging researchers',
    ],
    cons: [
      'Recommendations can feel generic',
      'No prescription capability',
      'Upsells additional products',
    ],
    ourTake: 'Great for athletes and those who want specific food and supplement recommendations based on their results.',
    deliveryModel: 'Mobile blood draw or lab visit, results via web platform',
    featured: false,
  },
  {
    slug: 'everlywell',
    name: 'Everlywell',
    category: 'labs',
    type: 'telehealth',
    description: 'Consumer-friendly at-home test kits for common health concerns.',
    pricingDisplay: '$49-299 per test',
    pricingComparison: '30-50% less than traditional lab visits',
    bestFor: ['Beginners to lab testing', 'Specific single-issue testing', 'Those wanting convenience'],
    pros: [
      'True at-home collection (finger prick)',
      'Wide variety of targeted tests',
      'Available at major retailers',
      'Quick turnaround times',
    ],
    cons: [
      'Less comprehensive than blood draw tests',
      'Some tests have accuracy limitations',
      'No physician guidance included',
    ],
    ourTake: 'Best entry point for those new to self-directed lab testing. Good for specific concerns, not comprehensive health pictures.',
    deliveryModel: 'At-home collection kits shipped to you, mail back for results',
    featured: false,
  },
  {
    slug: 'letsgetchecked',
    name: 'LetsGetChecked',
    category: 'labs',
    type: 'telehealth',
    description: 'At-home health testing with nurse support and treatment options.',
    pricingDisplay: '$69-349 per test',
    pricingComparison: 'Comparable to Everlywell with added nurse support',
    bestFor: ['Those wanting clinical support', 'STI testing', 'Hormone testing'],
    pros: [
      'Nurse available for result questions',
      'Can connect to treatment if needed',
      'Discreet packaging and process',
      'HSA/FSA eligible',
    ],
    cons: [
      'Limited test menu compared to lab draws',
      'Finger prick limitations on some markers',
      'Processing time can vary',
    ],
    ourTake: 'The added nurse support makes this a good middle ground between basic at-home tests and full telehealth services.',
    deliveryModel: 'At-home collection kits with optional nurse consultations',
    featured: false,
  },

  // GLP-1 PROVIDERS
  {
    slug: 'hims-hers',
    name: 'Hims/Hers',
    category: 'glp1',
    type: 'telehealth',
    description: 'Popular telehealth platform offering compounded semaglutide with subscription model.',
    pricingDisplay: '$199-299/month',
    pricingComparison: 'Brand-name Wegovy costs $1,000-1,500/month without insurance',
    bestFor: ['Those new to GLP-1s', 'Budget-conscious patients', 'Those wanting simple process'],
    pros: [
      'Lower cost compounded options',
      'Well-designed app and experience',
      'Fast prescription process',
      'Includes provider consultations',
    ],
    cons: [
      'Compounded, not brand-name medication',
      'Subscription model locks you in',
      'Variable compounding pharmacy quality',
    ],
    ourTake: 'Best mainstream option for those who want affordability and a polished experience. The compounded medication works well for most.',
    deliveryModel: 'Telehealth consultation, medication shipped monthly',
    featured: true,
  },
  {
    slug: 'ro',
    name: 'Ro',
    category: 'glp1',
    type: 'telehealth',
    description: 'Established telehealth company offering GLP-1 programs with body program coaching.',
    pricingDisplay: '$145-399/month',
    pricingComparison: '70-85% less than retail Wegovy/Ozempic',
    bestFor: ['Those wanting coaching support', 'Comprehensive weight loss approach', 'Brand-name seekers'],
    pros: [
      'Offers both compounded and brand-name',
      'Metabolic health coaching included',
      'Strong clinical protocols',
      'Insurance billing support for brand-name',
    ],
    cons: [
      'Brand-name availability can be limited',
      'Higher price for coaching tiers',
      'Requires ongoing subscription',
    ],
    ourTake: 'Best for those who want more than just medication—the coaching and support make a real difference in outcomes.',
    deliveryModel: 'Telehealth visits, monthly medication delivery, app-based coaching',
    featured: true,
  },
  {
    slug: 'noom-med',
    name: 'Noom Med',
    category: 'glp1',
    type: 'telehealth',
    description: 'Psychology-based weight loss app now offering GLP-1 prescriptions with behavior change program.',
    pricingDisplay: '$149-299/month (medication) + $59/month (program)',
    pricingComparison: 'Combined cost still 60% less than brand-name alone',
    bestFor: ['Those who struggled with willpower alone', 'Behavior change focus', 'Long-term habit building'],
    pros: [
      'Proven behavior change curriculum',
      'Addresses psychological aspects of eating',
      'Medication + lifestyle combination',
      'Human coaching available',
    ],
    cons: [
      'Two separate subscriptions to manage',
      'App can feel repetitive over time',
      'Medication is add-on to existing program',
    ],
    ourTake: 'Uniquely positioned to help you maintain weight loss after stopping GLP-1s. The behavior change component is the secret weapon.',
    deliveryModel: 'App-based program with telehealth prescriptions, medication shipped',
    featured: false,
  },
  {
    slug: 'calibrate',
    name: 'Calibrate',
    category: 'glp1',
    type: 'telehealth',
    description: 'Metabolic health company focused on GLP-1 therapy with intensive 1-year program.',
    pricingDisplay: '$1,650 program fee + medication costs',
    pricingComparison: 'Premium program but comprehensive metabolic reset',
    bestFor: ['Those committed to long-term change', 'Metabolic health focus', 'Comprehensive support seekers'],
    pros: [
      'Year-long structured program',
      'Focus on metabolic health, not just weight',
      'Intensive coaching and support',
      'Works with insurance for medication',
    ],
    cons: [
      'High upfront program cost',
      'One-year commitment required',
      'Medication costs are additional',
    ],
    ourTake: 'The most comprehensive program available. Worth it if you can afford it and want the best chance of long-term success.',
    deliveryModel: 'Intensive telehealth program with insurance medication coordination',
    featured: false,
  },
  {
    slug: 'found',
    name: 'Found',
    category: 'glp1',
    type: 'telehealth',
    description: 'Weight care platform offering personalized medication protocols including GLP-1s.',
    pricingDisplay: '$99-349/month',
    pricingComparison: 'Mid-range pricing with personalized approach',
    bestFor: ['Those wanting personalized protocols', 'Multiple medication options', 'Flexible approach'],
    pros: [
      'Personalized medication matching',
      'Multiple medication options beyond GLP-1',
      'Board-certified obesity medicine doctors',
      'Flexible program structure',
    ],
    cons: [
      'Can take time to find right protocol',
      'Less polished app experience',
      'Variable medication availability',
    ],
    ourTake: 'Good choice if you want a doctor who specializes in obesity medicine to customize your treatment, not just prescribe what\'s popular.',
    deliveryModel: 'Telehealth consultations with personalized medication protocols',
    featured: false,
  },

  // TRT PROVIDERS
  {
    slug: 'fountain-trt',
    name: 'Fountain TRT',
    category: 'trt',
    type: 'telehealth',
    description: 'Specialized TRT clinic with focus on optimization and comprehensive hormone panels.',
    pricingDisplay: '$195-350/month',
    pricingComparison: 'Traditional endocrinologist + pharmacy often $400-600/month',
    bestFor: ['Men seeking optimization', 'Those wanting comprehensive protocols', 'Experienced TRT users'],
    pros: [
      'Comprehensive hormone optimization approach',
      'Includes ancillary medications (AI, HCG)',
      'Regular lab monitoring included',
      'Experienced TRT-focused physicians',
    ],
    cons: [
      'Premium pricing',
      'May be aggressive for beginners',
      'Some states not covered',
    ],
    ourTake: 'One of the best options for men serious about optimization. Their protocols are thorough and physicians actually understand TRT.',
    deliveryModel: 'Telehealth consultations, medications shipped from licensed pharmacy',
    featured: true,
  },
  {
    slug: 'marek-health-trt',
    name: 'Marek Health',
    category: 'trt',
    type: 'telehealth',
    description: 'Founded by fitness industry experts, offering evidence-based TRT with optimization focus.',
    pricingDisplay: '$250-500/month',
    pricingComparison: 'Premium service but comprehensive care included',
    bestFor: ['Fitness enthusiasts', 'Those wanting deep expertise', 'Optimization-focused individuals'],
    pros: [
      'Deep expertise in performance optimization',
      'Thorough intake and monitoring',
      'Transparent, education-focused approach',
      'Community and resources included',
    ],
    cons: [
      'Higher price point',
      'Waitlists during busy periods',
      'May be too detailed for simple needs',
    ],
    ourTake: 'The gold standard for those who want physicians that truly understand optimization, not just getting you to "normal" ranges.',
    deliveryModel: 'Comprehensive telehealth with detailed protocols and monitoring',
    featured: true,
  },
  {
    slug: 'trt-nation',
    name: 'TRT Nation',
    category: 'trt',
    type: 'telehealth',
    description: 'Affordable TRT clinic with straightforward pricing and no-nonsense approach.',
    pricingDisplay: '$99-199/month',
    pricingComparison: 'One of the most affordable legitimate TRT options',
    bestFor: ['Budget-conscious patients', 'Those wanting simplicity', 'Straightforward TRT needs'],
    pros: [
      'Very competitive pricing',
      'Transparent, simple process',
      'Quick prescription turnaround',
      'No hidden fees',
    ],
    cons: [
      'Less comprehensive than premium options',
      'Basic ancillary medication options',
      'Less hand-holding in process',
    ],
    ourTake: 'Best value option for straightforward TRT. If you know what you need and don\'t require extensive optimization, this delivers.',
    deliveryModel: 'Streamlined telehealth, medications shipped monthly',
    featured: false,
  },
  {
    slug: 'henry-meds',
    name: 'Henry Meds',
    category: 'trt',
    type: 'telehealth',
    description: 'Multi-service telehealth platform offering TRT alongside other treatments.',
    pricingDisplay: '$150-250/month',
    pricingComparison: 'Competitive mid-range pricing',
    bestFor: ['Those wanting multiple services', 'Convenient all-in-one platform', 'Moderate pricing seekers'],
    pros: [
      'Multiple health services available',
      'Good balance of price and service',
      'User-friendly platform',
      'Regular monitoring included',
    ],
    cons: [
      'Less specialized than TRT-focused clinics',
      'Newer to TRT market',
      'Protocol customization more limited',
    ],
    ourTake: 'Solid middle-ground option, especially if you might use their other services. Good for those who don\'t need boutique-level TRT care.',
    deliveryModel: 'Telehealth platform with integrated pharmacy fulfillment',
    featured: false,
  },

  // DEXA PROVIDERS
  {
    slug: 'bodyspec',
    name: 'BodySpec',
    category: 'dexa',
    type: 'telehealth',
    description: 'Mobile DEXA scanning service bringing scans to convenient locations.',
    pricingDisplay: '$45-65 per scan',
    pricingComparison: 'Hospital DEXA scans often $200-400',
    bestFor: ['Fitness enthusiasts', 'Those tracking body composition', 'Athletes monitoring progress'],
    pros: [
      'Very affordable pricing',
      'Mobile locations for convenience',
      'Detailed body composition reports',
      'Tracking over time features',
    ],
    cons: [
      'Limited to certain metro areas',
      'Scheduling can be limited',
      'Basic scan without extensive consultation',
    ],
    ourTake: 'The most accessible and affordable way to get accurate body composition data. Perfect for regular tracking.',
    deliveryModel: 'Mobile DEXA trucks at scheduled locations, walk-in appointments',
    featured: true,
  },
  {
    slug: 'dexafit',
    name: 'DexaFit',
    category: 'dexa',
    type: 'telehealth',
    description: 'Comprehensive body composition testing centers with DEXA, VO2 max, and RMR testing.',
    pricingDisplay: '$75-150 per DEXA scan',
    pricingComparison: 'Premium pricing but full-service facilities',
    bestFor: ['Serious athletes', 'Those wanting full metabolic picture', 'Comprehensive testing seekers'],
    pros: [
      'Fixed locations with full equipment',
      'Additional tests available (VO2, RMR)',
      'More detailed consultations',
      'Consistent, professional experience',
    ],
    cons: [
      'Higher pricing than mobile options',
      'Requires traveling to location',
      'May be overkill for basic needs',
    ],
    ourTake: 'Worth the premium if you want the full picture—combine DEXA with VO2 max and RMR for complete metabolic understanding.',
    deliveryModel: 'Brick-and-mortar testing centers in major cities',
    featured: false,
  },
];
