import { Provider } from './types';

// =============================================================================
// INSURANCE COMPANIES
// =============================================================================

export const insuranceProviders: Provider[] = [
  {
    slug: 'united-healthcare',
    name: 'UnitedHealthcare',
    description: 'Largest health insurer in the US by revenue, offering employer-sponsored, individual, Medicare, and Medicaid plans nationwide.',
    category: 'insurance',
    services: ['Employer plans', 'Individual & family plans', 'Medicare Advantage', 'Medicaid', 'Short-term plans', 'Dental & vision'],
    pricingDisplay: 'Varies by plan',
    pricingNotes: 'Pricing depends on plan type, location, age, and coverage level. ACA plans available through Healthcare.gov.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['National - All 50 states'],
    url: 'https://www.uhc.com',
    referralType: 'direct_link',
    ourTake: 'UnitedHealthcare is the 800-lb gorilla of health insurance. Massive network, but reviews are mixed on claims processing. Good for employer plans where you don\'t have a choice. For individual plans, shop around.',
    bestFor: ['Employer-sponsored coverage', 'Large network needs', 'Medicare Advantage'],
    pros: ['Largest provider network', 'Available nationwide', 'Strong digital tools', 'Multiple plan types'],
    cons: ['Mixed customer service reviews', 'Prior authorization can be slow', 'Premium pricing in some markets'],
    accreditations: ['NCQA accredited plans'],
    yearsInBusiness: 47,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'anthem-blue-cross',
    name: 'Anthem Blue Cross Blue Shield',
    description: 'Major Blue Cross Blue Shield affiliate serving 14 states with comprehensive health coverage options.',
    category: 'insurance',
    services: ['Individual & family plans', 'Employer plans', 'Medicare', 'Medicaid', 'Dental', 'Vision'],
    pricingDisplay: 'Varies by state/plan',
    pricingNotes: 'ACA-compliant plans available. Pricing varies significantly by state and coverage level.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['CA', 'CO', 'CT', 'GA', 'IN', 'KY', 'ME', 'MO', 'NV', 'NH', 'NY', 'OH', 'VA', 'WI'],
    url: 'https://www.anthem.com',
    referralType: 'direct_link',
    ourTake: 'Anthem carries the trusted Blue Cross Blue Shield brand and has strong networks in its operating states. Worth comparing if you\'re in their territory, especially for PPO options.',
    bestFor: ['Blue Cross network access', 'PPO plan seekers', 'Multi-state employers'],
    pros: ['Blue Cross Blue Shield network', 'Strong regional presence', 'Good PPO options', 'Robust app'],
    cons: ['Only in 14 states', 'Customer service varies by region', 'Some narrow networks on ACA plans'],
    accreditations: ['NCQA accredited'],
    yearsInBusiness: 80,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'kaiser-permanente',
    name: 'Kaiser Permanente',
    description: 'Integrated health system combining insurance with its own hospitals, doctors, and pharmacies. Known for coordinated care.',
    category: 'insurance',
    services: ['Individual & family plans', 'Employer plans', 'Medicare', 'Medicaid', 'Integrated care'],
    pricingDisplay: '$300-800/mo individual',
    pricingNotes: 'Pricing varies by region. Often competitive due to integrated model. Limited to Kaiser facilities.',
    deliveryModel: 'in_person_local',
    geographicCoverage: ['CA', 'CO', 'GA', 'HI', 'MD', 'OR', 'VA', 'WA', 'DC'],
    url: 'https://www.kaiserpermanente.org',
    referralType: 'direct_link',
    ourTake: 'Kaiser is different: they\'re both insurer and provider. If you like one-stop-shop healthcare and are in their region, it\'s often the best value. But you must use Kaiser facilities - no out-of-network flexibility.',
    bestFor: ['Coordinated care preference', 'Cost-conscious consumers', 'Kaiser service areas'],
    pros: ['Integrated care model', 'Often lower premiums', 'Excellent preventive care', 'Top-rated for member satisfaction'],
    cons: ['Must use Kaiser facilities', 'Limited geographic availability', 'No out-of-network coverage', 'Can feel restrictive'],
    accreditations: ['NCQA highest ratings', 'JD Power awards'],
    yearsInBusiness: 79,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'aetna',
    name: 'Aetna (CVS Health)',
    description: 'Major national insurer now part of CVS Health, offering integration with CVS pharmacies and MinuteClinic.',
    category: 'insurance',
    services: ['Individual & family plans', 'Employer plans', 'Medicare', 'Medicaid', 'CVS integration', 'Behavioral health'],
    pricingDisplay: 'Varies by plan',
    pricingNotes: 'Competitive pricing especially for those using CVS pharmacy benefits.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['National - All 50 states'],
    url: 'https://www.aetna.com',
    referralType: 'direct_link',
    ourTake: 'The CVS acquisition gives Aetna unique pharmacy integration. If you\'re a frequent CVS customer, the savings add up. Good Medicare options and employer plans.',
    bestFor: ['CVS pharmacy users', 'Medicare shoppers', 'Employer plans'],
    pros: ['CVS integration benefits', 'Strong behavioral health coverage', 'Good digital experience', 'Nationwide availability'],
    cons: ['Customer service complaints', 'Prior auth requirements', 'Some narrow networks'],
    accreditations: ['NCQA accredited'],
    yearsInBusiness: 170,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'cigna',
    name: 'Cigna',
    description: 'Global health services company known for strong employer plans and international coverage options.',
    category: 'insurance',
    services: ['Employer plans', 'Individual plans', 'Medicare', 'International coverage', 'Behavioral health', 'Dental'],
    pricingDisplay: 'Varies by plan',
    pricingNotes: 'Often competitive for employer plans. Individual market presence varies by state.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['National - All 50 states', 'International'],
    url: 'https://www.cigna.com',
    referralType: 'direct_link',
    ourTake: 'Cigna shines in employer plans and has unique strengths in global coverage for expats and travelers. Less competitive in the individual ACA market in many states.',
    bestFor: ['Employer-sponsored coverage', 'International coverage needs', 'Expats'],
    pros: ['Strong employer plans', 'International coverage options', 'Good behavioral health', '24/7 nurse line'],
    cons: ['Limited ACA presence in some states', 'Customer service varies', 'Some network limitations'],
    accreditations: ['NCQA accredited'],
    yearsInBusiness: 230,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'humana',
    name: 'Humana',
    description: 'Major insurer with particular strength in Medicare Advantage plans and senior healthcare services.',
    category: 'insurance',
    services: ['Medicare Advantage', 'Medicare supplement', 'Prescription drug plans', 'Individual plans', 'Employer plans'],
    pricingDisplay: 'Varies by plan',
    pricingNotes: 'Known for competitive Medicare Advantage pricing. Individual/employer plans vary by market.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['National - Most states'],
    url: 'https://www.humana.com',
    referralType: 'direct_link',
    ourTake: 'If you\'re 65+, Humana should be on your Medicare comparison list. They\'ve invested heavily in senior-focused care coordination. Less notable for under-65 coverage.',
    bestFor: ['Medicare beneficiaries', 'Seniors', 'Prescription drug coverage'],
    pros: ['Strong Medicare options', 'Good supplemental benefits', 'Home health integration', 'Wellness programs'],
    cons: ['Weaker in under-65 market', 'Network varies by region', 'Some prior auth delays'],
    accreditations: ['CMS 4+ star ratings on many plans'],
    yearsInBusiness: 63,
    featured: false,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'oscar-health',
    name: 'Oscar Health',
    description: 'Tech-first health insurance startup focused on user experience and virtual care integration.',
    category: 'insurance',
    services: ['Individual & family plans', 'Small business plans', 'Virtual care', 'Concierge team'],
    pricingDisplay: '$350-700/mo individual',
    pricingNotes: 'Competitive ACA marketplace pricing in select markets. Strong virtual care included.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['AZ', 'CA', 'CO', 'FL', 'GA', 'KS', 'MI', 'MO', 'NJ', 'NY', 'OH', 'PA', 'TN', 'TX', 'VA'],
    url: 'https://www.hioscar.com',
    referralType: 'direct_link',
    ourTake: 'Oscar is what health insurance should feel like in 2024. Great app, free virtual care, and a concierge team that actually helps. The catch: limited markets and sometimes narrower networks.',
    bestFor: ['Tech-savvy consumers', 'Virtual care users', 'ACA marketplace shoppers'],
    pros: ['Best-in-class app', 'Free 24/7 virtual care', 'Concierge team included', 'Transparent pricing'],
    cons: ['Limited to 15 states', 'Narrower networks in some areas', 'Newer company (est. 2012)', 'No Medicare yet'],
    accreditations: ['NCQA accredited'],
    yearsInBusiness: 12,
    featured: true,
    lastVerified: '2024-12-21',
  },
  {
    slug: 'molina-healthcare',
    name: 'Molina Healthcare',
    description: 'Major Medicaid and ACA marketplace insurer known for affordable options for lower-income individuals.',
    category: 'insurance',
    services: ['Medicaid', 'Medicare', 'ACA marketplace plans', 'Dual-eligible plans'],
    pricingDisplay: 'Often lowest-cost',
    pricingNotes: 'Frequently the most affordable ACA option. Strong Medicaid presence.',
    deliveryModel: 'hybrid',
    geographicCoverage: ['CA', 'FL', 'IL', 'MI', 'NM', 'NY', 'OH', 'SC', 'TX', 'UT', 'WA', 'WI'],
    url: 'https://www.molinahealthcare.com',
    referralType: 'direct_link',
    ourTake: 'If you qualify for subsidies and want the lowest premium, Molina is often the answer. They specialize in serving lower-income populations. Networks can be limited.',
    bestFor: ['Subsidy-eligible individuals', 'Medicaid recipients', 'Budget-focused shoppers'],
    pros: ['Often lowest premiums', 'Strong Medicaid experience', 'Good for subsidy users', 'Care coordination'],
    cons: ['Smaller networks', 'Customer service can lag', 'Limited presence outside target markets'],
    accreditations: ['NCQA accredited'],
    yearsInBusiness: 44,
    featured: false,
    lastVerified: '2024-12-21',
  },
];

export default {
  insurance: insuranceProviders,
};
