// Southern California Cash-Pay Clinics Data
// Last Updated: January 2025
// Categories: DEXA, VO2 Max, IV Therapy, Longevity, Performance, Labs

export interface LocalClinic {
  name: string;
  slug: string;
  category: 'dexa' | 'vo2' | 'iv' | 'longevity' | 'performance' | 'labs' | 'wellness';
  address?: string;
  neighborhoods: string[];
  region: string;
  subRegion: string;
  priceRange: string;
  services: string[];
  description: string;
  highlights: string[];
  bestFor: string;
  website: string;
  phone?: string;
  rating?: number;
  reviewCount?: number;
  reviewSource?: string;
}

export interface SoCalRegion {
  name: string;
  slug: string;
  parentRegion: 'los-angeles' | 'orange-county' | 'san-diego' | 'inland-empire';
  cities: string[];
  description: string;
  clinics: LocalClinic[];
}

// =============================================================================
// WEST LA / BEACH CITIES
// =============================================================================
export const westLAClinics: LocalClinic[] = [
  // DEXA & Body Composition
  {
    name: 'BodySpec - Santa Monica',
    slug: 'bodyspec-santa-monica',
    category: 'dexa',
    neighborhoods: ['Santa Monica', 'Venice', 'Mar Vista'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat', 'Regional body fat'],
    description: 'The most affordable DEXA option in LA. BodySpec operates mobile units that visit gyms and wellness centers across the Westside. Excellent for ongoing tracking.',
    highlights: ['Lowest price in market', 'Package deals ($40/scan)', 'Quick 15-min appointments', 'Results same day'],
    bestFor: 'Budget-conscious fitness enthusiasts tracking body composition over time',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 890,
    reviewSource: 'Google',
  },
  {
    name: 'DexaFit West Hollywood',
    slug: 'dexafit-weho',
    category: 'dexa',
    address: '8383 Wilshire Blvd, Beverly Hills, CA 90211',
    neighborhoods: ['West Hollywood', 'Beverly Hills', 'Mid-Wilshire'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$119-179/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', '3D body scan', 'Metabolic testing'],
    description: 'Premium body composition studio offering comprehensive metabolic testing. Higher price but includes detailed consultation and access to additional tests.',
    highlights: ['Full metabolic suite', 'Premium studio', 'Detailed consultations', 'VO2 max available'],
    bestFor: 'Those wanting comprehensive testing (DEXA + RMR + VO2) in one place',
    website: 'https://www.dexafit.com',
    rating: 4.9,
    reviewCount: 245,
    reviewSource: 'Google',
  },
  {
    name: 'Fitnescity Beverly Hills',
    slug: 'fitnescity-beverly-hills',
    category: 'dexa',
    neighborhoods: ['Beverly Hills', 'West LA'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$99-149/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', 'Blood panels', 'Fitness assessments'],
    description: 'Health optimization testing center catering to athletes and executives. Offers DEXA alongside blood work and fitness testing.',
    highlights: ['Athlete-focused', 'Multiple test bundles', 'Blood panel integration', 'Performance optimization'],
    bestFor: 'Competitive athletes and executives wanting data-driven optimization',
    website: 'https://www.fitnescity.com',
    rating: 4.7,
    reviewCount: 128,
    reviewSource: 'Google',
  },
  {
    name: 'UCLA Exercise Physiology Lab',
    slug: 'ucla-exercise-physiology',
    category: 'dexa',
    address: 'UCLA Campus, Westwood',
    neighborhoods: ['Westwood', 'Brentwood'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$75-150',
    services: ['DEXA scan', 'Research-grade body composition'],
    description: 'University research lab offering DEXA scans to the public. Clinical-grade Hologic equipment at academic pricing.',
    highlights: ['Research-grade accuracy', 'Academic pricing', 'Hologic machines', 'Clinical protocols'],
    bestFor: 'Those wanting maximum accuracy with research-grade equipment',
    website: 'https://www.recreation.ucla.edu',
    rating: 4.5,
    reviewCount: 45,
    reviewSource: 'Yelp',
  },
  // IV Therapy
  {
    name: 'Next Health West Hollywood',
    slug: 'next-health-weho',
    category: 'iv',
    address: '8469 Melrose Place, West Hollywood, CA 90069',
    neighborhoods: ['West Hollywood', 'Beverly Grove'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$199/month or $150-500/treatment',
    services: ['NAD+ IV', 'Myers cocktail', 'Glutathione', 'High-dose Vitamin C', 'Hydration', 'Cryotherapy', 'Hyperbaric', 'Red light therapy'],
    description: 'The flagship Next Health location. Full longevity lounge with IV therapy, cryotherapy, hyperbaric chambers, and more. Membership model makes regular visits affordable.',
    highlights: ['Full wellness menu', 'Membership model', 'Celebrity clientele', 'Walk-ins welcome', 'Multiple modalities'],
    bestFor: 'Regular wellness optimization with membership value',
    website: 'https://www.next-health.com',
    rating: 4.8,
    reviewCount: 520,
    reviewSource: 'Google',
  },
  {
    name: 'Next Health Century City',
    slug: 'next-health-century-city',
    category: 'iv',
    address: '10250 Constellation Blvd, Century City, CA 90067',
    neighborhoods: ['Century City', 'West LA', 'Cheviot Hills'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$199/month or $150-500/treatment',
    services: ['NAD+ IV', 'Myers cocktail', 'Glutathione', 'Vitamin infusions', 'Cryotherapy', 'Compression therapy'],
    description: 'Next Health\'s Westfield Century City location. Convenient for Westside professionals. Full suite of IV and recovery services.',
    highlights: ['Mall location', 'Easy parking', 'Same menu as WeHo', 'Walk-ins available'],
    bestFor: 'Westside professionals wanting convenient wellness access',
    website: 'https://www.next-health.com',
    rating: 4.7,
    reviewCount: 189,
    reviewSource: 'Google',
  },
  {
    name: 'Drip Hydration LA',
    slug: 'drip-hydration-la',
    category: 'iv',
    neighborhoods: ['Mobile - All LA'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$199-599/treatment',
    services: ['In-home IV therapy', 'NAD+', 'Myers cocktail', 'Athletic recovery', 'Hangover recovery', 'Immune boost'],
    description: 'Concierge IV service that comes to your home, office, or hotel. RN-administered. No need to travel.',
    highlights: ['Mobile service', 'Same-day appointments', 'RN-administered', 'No travel needed'],
    bestFor: 'Busy professionals, post-event recovery, convenience',
    website: 'https://www.driphydration.com',
    rating: 4.9,
    reviewCount: 890,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness Santa Monica',
    slug: 'restore-santa-monica',
    category: 'iv',
    address: '2901 Ocean Park Blvd, Santa Monica, CA 90405',
    neighborhoods: ['Santa Monica', 'Mar Vista'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Hyperbaric oxygen', 'Red light therapy', 'Compression'],
    description: 'National wellness franchise offering IV therapy alongside recovery modalities. Consistent experience, membership options.',
    highlights: ['Multi-modality', 'National chain', 'Membership pricing', 'Consistent quality'],
    bestFor: 'Those wanting multiple recovery modalities in one visit',
    website: 'https://www.restore.com',
    rating: 4.7,
    reviewCount: 156,
    reviewSource: 'Google',
  },
  // Longevity
  {
    name: 'Beverly Hills Concierge Doctor',
    slug: 'beverly-hills-concierge',
    category: 'longevity',
    neighborhoods: ['Beverly Hills'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: 'Concierge pricing (inquire)',
    services: ['Peptide therapy', 'NAD+ protocols', 'Hormone optimization', 'Anti-aging medicine', 'Executive physicals', 'IV therapy'],
    description: 'Discreet concierge medicine for executives and celebrities. Full spectrum of longevity and anti-aging treatments including peptides and off-label protocols.',
    highlights: ['Celebrity clientele', 'Discreet service', 'Full peptide menu', 'Personalized protocols', 'House calls available'],
    bestFor: 'High-net-worth individuals wanting comprehensive, private care',
    website: 'https://www.bhconciergedoc.com',
    rating: 5.0,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'The Wellness Lab Beverly Hills',
    slug: 'wellness-lab-bh',
    category: 'longevity',
    neighborhoods: ['Beverly Hills'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$300-3,000+',
    services: ['Functional medicine', 'Hormone testing', 'Gut health', 'Longevity protocols', 'IV therapy'],
    description: 'Integrative medicine practice focusing on root cause analysis. Comprehensive testing and personalized protocols.',
    highlights: ['Functional medicine', 'Root cause focus', 'Comprehensive testing', 'Personalized protocols'],
    bestFor: 'Those with chronic issues seeking root cause analysis',
    website: 'https://www.thewellnesslab.com',
    rating: 4.8,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  // Labs
  {
    name: 'Any Lab Test Now - Santa Monica',
    slug: 'any-lab-test-santa-monica',
    category: 'labs',
    address: 'Santa Monica, CA',
    neighborhoods: ['Santa Monica', 'Venice'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: 'Varies by test',
    services: ['Blood panels', 'Hormone testing', 'STD testing', 'Drug testing', 'Wellness panels'],
    description: 'Walk-in lab testing without doctor orders. Same-day results for many tests. No appointments needed.',
    highlights: ['No doctor required', 'Walk-in friendly', 'Fast results', 'Wide test menu'],
    bestFor: 'Quick lab work without doctor visit',
    website: 'https://www.anylabtestnow.com',
    rating: 4.5,
    reviewCount: 78,
    reviewSource: 'Google',
  },
];

// =============================================================================
// SOUTH BAY / LONG BEACH
// =============================================================================
export const southBayClinics: LocalClinic[] = [
  {
    name: 'Restore Hyper Wellness Manhattan Beach',
    slug: 'restore-manhattan-beach',
    category: 'iv',
    address: '1116 Manhattan Ave, Manhattan Beach, CA 90266',
    neighborhoods: ['Manhattan Beach', 'Hermosa Beach', 'Redondo Beach'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Hyperbaric oxygen', 'Red light therapy', 'Compression'],
    description: 'South Bay location of national wellness chain. Popular with beach city athletes and professionals.',
    highlights: ['Beach community', 'Athletic focus', 'Multiple modalities', 'Membership options'],
    bestFor: 'South Bay residents wanting recovery and wellness services',
    website: 'https://www.restore.com',
    rating: 4.8,
    reviewCount: 203,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - South Bay',
    slug: 'bodyspec-south-bay',
    category: 'dexa',
    neighborhoods: ['Torrance', 'Redondo Beach', 'El Segundo'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile units visit gyms throughout the South Bay. Check website for current schedule.',
    highlights: ['Mobile service', 'Gym locations', 'Affordable', 'Regular schedules'],
    bestFor: 'South Bay fitness enthusiasts tracking progress',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 234,
    reviewSource: 'Google',
  },
  {
    name: 'IV Revival',
    slug: 'iv-revival-south-bay',
    category: 'iv',
    neighborhoods: ['Mobile - South Bay, Long Beach'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$175-400/treatment',
    services: ['Mobile IV therapy', 'Hydration', 'NAD+', 'Vitamin infusions', 'Athletic recovery'],
    description: 'Mobile IV service covering South Bay and Long Beach. RN-administered in-home treatments.',
    highlights: ['Mobile service', 'South Bay coverage', 'Same-day availability', 'Athletic packages'],
    bestFor: 'South Bay residents wanting in-home IV therapy',
    website: 'https://www.ivrevival.com',
    rating: 4.9,
    reviewCount: 167,
    reviewSource: 'Google',
  },
  {
    name: 'Performance Lab Long Beach',
    slug: 'performance-lab-lb',
    category: 'performance',
    neighborhoods: ['Long Beach', 'Lakewood'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$150-500/assessment',
    services: ['VO2 max testing', 'Lactate threshold', 'Movement screening', 'Performance training'],
    description: 'Sports performance testing facility in Long Beach. Popular with triathletes and endurance athletes.',
    highlights: ['Endurance focus', 'VO2 max testing', 'Training programs', 'Coach partnerships'],
    bestFor: 'Endurance athletes in Long Beach area',
    website: 'https://www.performancelablb.com',
    rating: 4.7,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  // New additions for South Bay
  {
    name: 'Beach Cities Longevity',
    slug: 'beach-cities-longevity',
    category: 'longevity',
    address: '1200 Highland Ave, Manhattan Beach, CA 90266',
    neighborhoods: ['Manhattan Beach', 'Hermosa Beach', 'El Segundo'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$400-3,500',
    services: ['Peptide therapy', 'Hormone optimization', 'NAD+ protocols', 'Executive physicals', 'Anti-aging consults'],
    description: 'Boutique longevity practice serving the South Bay professional community. Personalized anti-aging protocols with concierge service.',
    highlights: ['Boutique practice', 'Peptide expertise', 'Concierge service', 'Beach city location'],
    bestFor: 'South Bay professionals seeking comprehensive longevity care',
    website: 'https://www.beachcitieslongevity.com',
    rating: 4.9,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  {
    name: 'Torrance DEXA & Metabolic Testing',
    slug: 'torrance-dexa',
    category: 'dexa',
    address: 'Torrance, CA',
    neighborhoods: ['Torrance', 'Carson', 'Gardena'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$95-175/scan',
    services: ['DEXA body composition', 'RMR testing', 'Bone density', 'Metabolic panels'],
    description: 'Dedicated body composition facility in Torrance. More affordable than DexaFit but more comprehensive than BodySpec.',
    highlights: ['Mid-price option', 'RMR included', 'Flexible scheduling', 'Detailed reports'],
    bestFor: 'Those wanting more than basic DEXA at reasonable prices',
    website: 'https://www.torrancedexa.com',
    rating: 4.6,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'Any Lab Test Now - Long Beach',
    slug: 'any-lab-test-long-beach',
    category: 'labs',
    address: 'Long Beach, CA',
    neighborhoods: ['Long Beach', 'Signal Hill', 'Lakewood'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: 'Varies by test',
    services: ['Blood panels', 'Hormone testing', 'STD testing', 'Wellness panels', 'Drug testing'],
    description: 'Walk-in lab testing without doctor orders in Long Beach. Convenient for South Bay residents.',
    highlights: ['No doctor required', 'Walk-in friendly', 'Fast results', 'Full test menu'],
    bestFor: 'Quick lab work without doctor visit',
    website: 'https://www.anylabtestnow.com',
    rating: 4.5,
    reviewCount: 134,
    reviewSource: 'Google',
  },
  {
    name: 'South Bay Cryo & Recovery',
    slug: 'south-bay-cryo',
    category: 'wellness',
    address: 'Redondo Beach, CA',
    neighborhoods: ['Redondo Beach', 'Hermosa Beach', 'Torrance'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$35-250/session',
    services: ['Cryotherapy', 'Infrared sauna', 'Compression therapy', 'Red light therapy', 'Normatec'],
    description: 'Recovery-focused wellness center for athletes and fitness enthusiasts. Multiple modalities under one roof.',
    highlights: ['Multi-modality', 'Athletic focus', 'Membership deals', 'Walk-ins available'],
    bestFor: 'Athletes wanting comprehensive recovery options',
    website: 'https://www.southbaycryo.com',
    rating: 4.7,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'Palos Verdes Integrative Medicine',
    slug: 'pv-integrative',
    category: 'longevity',
    address: 'Palos Verdes Estates, CA',
    neighborhoods: ['Palos Verdes Estates', 'Rancho Palos Verdes', 'Rolling Hills'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$300-2,500',
    services: ['Functional medicine', 'Hormone testing', 'Gut health', 'IV therapy', 'Nutrient testing'],
    description: 'Integrative medicine practice in the Peninsula. Root cause approach to chronic conditions and optimization.',
    highlights: ['Root cause focus', 'Functional medicine', 'Peninsula location', 'Personalized protocols'],
    bestFor: 'PV residents seeking integrative health solutions',
    website: 'https://www.pvintegrative.com',
    rating: 4.8,
    reviewCount: 56,
    reviewSource: 'Google',
  },
  {
    name: 'El Segundo Sports Medicine',
    slug: 'el-segundo-sports-med',
    category: 'vo2',
    address: 'El Segundo, CA',
    neighborhoods: ['El Segundo', 'Manhattan Beach', 'Hawthorne'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$175-400',
    services: ['VO2 max testing', 'Lactate threshold', 'Movement screening', 'Sports physicals', 'Injury prevention'],
    description: 'Sports medicine facility near LAX. Popular with aerospace workers and South Bay athletes.',
    highlights: ['Near LAX', 'VO2 max testing', 'Convenient hours', 'Athletic focus'],
    bestFor: 'South Bay athletes and aerospace professionals',
    website: 'https://www.elsegundosportsmed.com',
    rating: 4.6,
    reviewCount: 98,
    reviewSource: 'Google',
  },
];

// =============================================================================
// ORANGE COUNTY
// =============================================================================
export const orangeCountyClinics: LocalClinic[] = [
  // North OC
  {
    name: 'DexaFit Irvine',
    slug: 'dexafit-irvine',
    category: 'dexa',
    address: 'Irvine, CA',
    neighborhoods: ['Irvine', 'Tustin', 'Costa Mesa'],
    region: 'Orange County',
    subRegion: 'Central Orange County',
    priceRange: '$119-179/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', '3D body scan'],
    description: 'DexaFit\'s Orange County location. Full metabolic testing suite including VO2 max and RMR.',
    highlights: ['Full testing suite', 'VO2 max available', 'Central OC location', 'Premium experience'],
    bestFor: 'OC residents wanting comprehensive metabolic testing',
    website: 'https://www.dexafit.com',
    rating: 4.8,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - Orange County',
    slug: 'bodyspec-oc',
    category: 'dexa',
    neighborhoods: ['Irvine', 'Newport Beach', 'Costa Mesa', 'Huntington Beach'],
    region: 'Orange County',
    subRegion: 'Central Orange County',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile trucks visit multiple OC locations weekly. Most affordable DEXA option in Orange County.',
    highlights: ['Lowest prices', 'Multiple OC locations', 'Package deals', 'Regular schedule'],
    bestFor: 'Budget-conscious OC residents tracking body comp',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 345,
    reviewSource: 'Google',
  },
  {
    name: 'The Hydration Room - Newport Beach',
    slug: 'hydration-room-newport',
    category: 'iv',
    address: 'Newport Beach, CA',
    neighborhoods: ['Newport Beach', 'Corona del Mar', 'Balboa'],
    region: 'Orange County',
    subRegion: 'Coastal Orange County',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Weight loss IVs', 'Athletic recovery', 'Immune boost'],
    description: 'Orange County-focused IV bar with medical director oversight. Clean, clinical environment with knowledgeable staff.',
    highlights: ['OC leader', 'Medical oversight', 'Clinical environment', 'Multiple locations'],
    bestFor: 'Orange County residents wanting quality IV therapy',
    website: 'https://www.thehydrationroom.com',
    rating: 4.9,
    reviewCount: 567,
    reviewSource: 'Google',
  },
  {
    name: 'The Hydration Room - Costa Mesa',
    slug: 'hydration-room-costa-mesa',
    category: 'iv',
    address: 'Costa Mesa, CA',
    neighborhoods: ['Costa Mesa', 'Huntington Beach'],
    region: 'Orange County',
    subRegion: 'Central Orange County',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Weight loss', 'Energy boost'],
    description: 'Central OC location near South Coast Plaza. Easy access for inland OC residents.',
    highlights: ['Central location', 'Near shopping', 'Full menu', 'Consistent quality'],
    bestFor: 'Central OC residents and shoppers',
    website: 'https://www.thehydrationroom.com',
    rating: 4.8,
    reviewCount: 289,
    reviewSource: 'Google',
  },
  {
    name: 'The Hydration Room - Huntington Beach',
    slug: 'hydration-room-hb',
    category: 'iv',
    address: 'Huntington Beach, CA',
    neighborhoods: ['Huntington Beach', 'Fountain Valley', 'Westminster'],
    region: 'Orange County',
    subRegion: 'Coastal Orange County',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Hangover recovery', 'Athletic recovery'],
    description: 'Surf City location. Popular with surfers, athletes, and beach community.',
    highlights: ['Beach community', 'Athletic focus', 'Surf recovery', 'Walk-ins available'],
    bestFor: 'Huntington Beach residents and surfers',
    website: 'https://www.thehydrationroom.com',
    rating: 4.7,
    reviewCount: 198,
    reviewSource: 'Google',
  },
  {
    name: 'UC Irvine Sports Medicine',
    slug: 'uci-sports-medicine',
    category: 'vo2',
    address: 'UCI Campus, Irvine, CA',
    neighborhoods: ['Irvine', 'Tustin'],
    region: 'Orange County',
    subRegion: 'Central Orange County',
    priceRange: '$200-350',
    services: ['VO2 max testing', 'Lactate threshold', 'Sports performance testing', 'Movement analysis'],
    description: 'University sports medicine department offering clinical-grade testing. Research-quality equipment and protocols.',
    highlights: ['Research-grade', 'University pricing', 'Clinical protocols', 'Expert staff'],
    bestFor: 'Athletes wanting clinical-grade testing',
    website: 'https://www.ucihealth.org',
    rating: 4.6,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  {
    name: 'OC Sports & Wellness',
    slug: 'oc-sports-wellness',
    category: 'performance',
    address: 'Newport Beach, CA',
    neighborhoods: ['Newport Beach', 'Irvine'],
    region: 'Orange County',
    subRegion: 'Coastal Orange County',
    priceRange: '$150-400',
    services: ['VO2 max', 'RMR', 'Body composition', 'Performance training', 'Nutrition planning'],
    description: 'Sports performance and wellness center in Newport Beach. Comprehensive testing and training.',
    highlights: ['Performance focus', 'Comprehensive testing', 'Training programs', 'Nutrition integration'],
    bestFor: 'OC athletes wanting integrated performance services',
    website: 'https://www.ocsportswellness.com',
    rating: 4.7,
    reviewCount: 123,
    reviewSource: 'Google',
  },
  {
    name: 'Alive + Well Austin at OC (partner)',
    slug: 'alive-well-oc',
    category: 'longevity',
    neighborhoods: ['Irvine', 'Newport Beach'],
    region: 'Orange County',
    subRegion: 'Central Orange County',
    priceRange: '$200-1,500',
    services: ['NAD+ IV therapy', 'Ketamine therapy', 'Peptides', 'Hormone optimization'],
    description: 'Longevity and regenerative medicine clinic offering cutting-edge treatments including NAD+ and ketamine.',
    highlights: ['NAD+ protocols', 'Regenerative focus', 'Medical oversight', 'Research-backed'],
    bestFor: 'Those seeking advanced longevity treatments',
    website: 'https://www.aliveandwell.com',
    rating: 4.9,
    reviewCount: 89,
    reviewSource: 'Google',
  },
];

// =============================================================================
// SOUTH ORANGE COUNTY
// =============================================================================
export const southOrangeClinics: LocalClinic[] = [
  {
    name: 'The Hydration Room - Laguna Beach',
    slug: 'hydration-room-laguna',
    category: 'iv',
    address: '1100 S Coast Hwy, Laguna Beach, CA 92651',
    neighborhoods: ['Laguna Beach', 'Laguna Niguel'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Hangover recovery', 'Athletic recovery'],
    description: 'Beach city location of The Hydration Room. Popular pre/post beach, hiking, and event recovery.',
    highlights: ['Beach location', 'Convenient for tourists', 'Same quality as Newport', 'Walk-ins welcome'],
    bestFor: 'South OC and Laguna Beach visitors',
    website: 'https://www.thehydrationroom.com',
    rating: 4.8,
    reviewCount: 234,
    reviewSource: 'Google',
  },
  {
    name: 'The Hydration Room - Dana Point',
    slug: 'hydration-room-dana-point',
    category: 'iv',
    address: '34085 Pacific Coast Hwy, Dana Point, CA 92629',
    neighborhoods: ['Dana Point', 'San Clemente'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Athletic recovery', 'Immune boost'],
    description: 'Southernmost Hydration Room location in OC. Serves Dana Point, San Clemente, and visitors heading to Baja.',
    highlights: ['South OC location', 'Near harbor', 'Surf community', 'Consistent quality'],
    bestFor: 'Dana Point and San Clemente residents',
    website: 'https://www.thehydrationroom.com',
    rating: 4.7,
    reviewCount: 156,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - South OC',
    slug: 'bodyspec-south-oc',
    category: 'dexa',
    neighborhoods: ['Mission Viejo', 'Laguna Niguel', 'San Juan Capistrano'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile units visit South OC gyms in Mission Viejo and Laguna Niguel regularly.',
    highlights: ['Affordable', 'Mobile service', 'Regular schedule', 'South OC coverage'],
    bestFor: 'South OC fitness enthusiasts on a budget',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Mission Viejo',
    slug: 'restore-mission-viejo',
    category: 'iv',
    address: '27741 Crown Valley Pkwy, Mission Viejo, CA 92691',
    neighborhoods: ['Mission Viejo', 'Laguna Hills', 'Lake Forest'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy', 'Infrared sauna'],
    description: 'National wellness franchise location in South OC. Full recovery suite serving inland South Orange County.',
    highlights: ['Full wellness menu', 'Family friendly area', 'Membership options', 'Easy parking'],
    bestFor: 'South OC families and fitness enthusiasts',
    website: 'https://www.restore.com',
    rating: 4.7,
    reviewCount: 145,
    reviewSource: 'Google',
  },
  {
    name: 'San Clemente Wellness Center',
    slug: 'san-clemente-wellness',
    category: 'wellness',
    address: 'San Clemente, CA',
    neighborhoods: ['San Clemente', 'Dana Point'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$100-400',
    services: ['IV therapy', 'Vitamin injections', 'Hormone testing', 'Wellness consultations'],
    description: 'Boutique wellness center in San Clemente serving the surf community and local residents.',
    highlights: ['Beach town vibe', 'Surf community', 'Personalized care', 'Boutique feel'],
    bestFor: 'San Clemente residents wanting local wellness services',
    website: 'https://www.sanclementewellness.com',
    rating: 4.6,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  {
    name: 'Saddleback Medical Center - Sports Medicine',
    slug: 'saddleback-sports-med',
    category: 'performance',
    address: 'Laguna Hills, CA',
    neighborhoods: ['Laguna Hills', 'Mission Viejo', 'Irvine'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$150-400',
    services: ['VO2 max testing', 'Sports physicals', 'Performance assessments', 'Injury prevention'],
    description: 'Hospital-affiliated sports medicine offering clinical-grade testing with insurance or cash-pay options.',
    highlights: ['Hospital backing', 'Clinical grade', 'Specialist referrals', 'Insurance option'],
    bestFor: 'Athletes wanting clinical-grade testing with specialist access',
    website: 'https://www.memorialcare.org',
    rating: 4.5,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'Pacific Longevity - Laguna Niguel',
    slug: 'pacific-longevity-ln',
    category: 'longevity',
    address: 'Laguna Niguel, CA',
    neighborhoods: ['Laguna Niguel', 'Dana Point', 'Laguna Beach'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$400-3,000',
    services: ['Peptide therapy', 'Hormone optimization', 'NAD+ protocols', 'Anti-aging medicine', 'Executive physicals'],
    description: 'Longevity-focused medical practice offering advanced anti-aging protocols and personalized care.',
    highlights: ['Longevity focus', 'Peptide expertise', 'Personalized protocols', 'South OC location'],
    bestFor: 'South OC residents seeking comprehensive longevity care',
    website: 'https://www.pacificlongevity.com',
    rating: 4.8,
    reviewCount: 56,
    reviewSource: 'Google',
  },
];

// =============================================================================
// SAN DIEGO CENTRAL
// =============================================================================
export const sanDiegoCentralClinics: LocalClinic[] = [
  // Central San Diego
  {
    name: 'DexaFit San Diego',
    slug: 'dexafit-sd',
    category: 'dexa',
    address: 'San Diego, CA',
    neighborhoods: ['Hillcrest', 'Mission Valley', 'Downtown'],
    region: 'San Diego',
    subRegion: 'Central San Diego',
    priceRange: '$119-179/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', '3D body scan'],
    description: 'DexaFit\'s San Diego location. Full metabolic testing suite in central San Diego.',
    highlights: ['Full suite', 'VO2 available', 'Central location', 'Premium experience'],
    bestFor: 'San Diego residents wanting comprehensive testing',
    website: 'https://www.dexafit.com',
    rating: 4.8,
    reviewCount: 167,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - San Diego',
    slug: 'bodyspec-sd',
    category: 'dexa',
    neighborhoods: ['Pacific Beach', 'La Jolla', 'Hillcrest', 'Downtown'],
    region: 'San Diego',
    subRegion: 'Central San Diego',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile trucks visit San Diego gyms and wellness centers weekly.',
    highlights: ['Affordable', 'Multiple SD locations', 'Regular schedule', 'Package deals'],
    bestFor: 'Budget-conscious San Diegans tracking body comp',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 456,
    reviewSource: 'Google',
  },
  {
    name: 'VitaLounge Hillcrest',
    slug: 'vitalounge-hillcrest',
    category: 'iv',
    address: 'Hillcrest, San Diego, CA',
    neighborhoods: ['Hillcrest', 'North Park', 'Mission Hills'],
    region: 'San Diego',
    subRegion: 'Central San Diego',
    priceRange: '$149-449/treatment',
    services: ['IV vitamin therapy', 'NAD+', 'Glutathione', 'High-dose Vitamin C', 'Myers cocktail'],
    description: 'San Diego\'s original IV therapy lounge. Clinical focus with comfortable environment.',
    highlights: ['SD original', 'Medical oversight', 'Comfortable lounge', 'Full menu'],
    bestFor: 'Central San Diego IV therapy',
    website: 'https://www.vitalounge.com',
    rating: 4.8,
    reviewCount: 234,
    reviewSource: 'Google',
  },
  {
    name: 'VitaLounge La Jolla',
    slug: 'vitalounge-la-jolla',
    category: 'iv',
    address: 'La Jolla, CA',
    neighborhoods: ['La Jolla', 'UTC', 'Bird Rock'],
    region: 'San Diego',
    subRegion: 'Coastal San Diego',
    priceRange: '$149-449/treatment',
    services: ['IV vitamin therapy', 'NAD+', 'Glutathione', 'High-dose Vitamin C', 'Athletic recovery'],
    description: 'VitaLounge\'s La Jolla location. Popular with UCSD community and La Jolla residents.',
    highlights: ['La Jolla location', 'Near UCSD', 'Coastal vibe', 'Same quality as Hillcrest'],
    bestFor: 'La Jolla and coastal SD residents',
    website: 'https://www.vitalounge.com',
    rating: 4.7,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'The Health Nucleus',
    slug: 'health-nucleus-sd',
    category: 'longevity',
    address: 'La Jolla, CA',
    neighborhoods: ['La Jolla', 'UTC'],
    region: 'San Diego',
    subRegion: 'Coastal San Diego',
    priceRange: '$15,000-25,000',
    services: ['Full-body MRI', 'Whole genome sequencing', 'Metabolomics', 'AI health analysis', 'Executive physicals'],
    description: 'The most comprehensive diagnostic assessment available. Founded by Human Longevity (Craig Venter). Catches problems years before they become serious.',
    highlights: ['Most comprehensive', 'Genome sequencing', 'Full-body MRI', 'AI analysis', 'Preventive medicine'],
    bestFor: 'Those wanting the most thorough health assessment available',
    website: 'https://www.healthnucleus.com',
    rating: 4.9,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'Scripps Center for Executive Health',
    slug: 'scripps-executive-health',
    category: 'longevity',
    address: 'La Jolla, CA',
    neighborhoods: ['La Jolla', 'UTC'],
    region: 'San Diego',
    subRegion: 'Coastal San Diego',
    priceRange: '$3,500-8,000',
    services: ['Executive physicals', 'Preventive cardiology', 'Advanced screening', 'Specialist access', 'Stress testing'],
    description: 'Scripps\' executive health program. World-class preventive care backed by academic medical center expertise.',
    highlights: ['Scripps reputation', 'Academic backing', 'Specialist network', 'Comprehensive'],
    bestFor: 'Executives wanting thorough annual assessments',
    website: 'https://www.scripps.org',
    rating: 4.8,
    reviewCount: 156,
    reviewSource: 'Google',
  },
  // Peptide Therapy Clinics - San Diego Central
  {
    name: 'VitaLab Wellness',
    slug: 'vitalab-wellness-la-jolla',
    category: 'longevity',
    address: 'La Jolla, CA',
    neighborhoods: ['La Jolla', 'UTC', 'Del Mar'],
    region: 'San Diego',
    subRegion: 'Coastal San Diego',
    priceRange: '$300-2,000',
    services: ['Peptide therapy', 'BPC-157', 'Anti-aging protocols', 'Regenerative medicine', 'Hormone optimization'],
    description: 'La Jolla peptide therapy clinic offering regenerative treatments to improve health and rejuvenate wellbeing. Specializes in anti-aging and performance optimization.',
    highlights: ['Peptide specialists', 'La Jolla location', 'Regenerative focus', 'Anti-aging expertise'],
    bestFor: 'Those seeking peptide-based regenerative medicine in coastal San Diego',
    website: 'https://vitalabwellness.com',
    rating: 4.8,
    reviewCount: 134,
    reviewSource: 'Google',
  },
  {
    name: 'Aesthetica Medical Spa',
    slug: 'aesthetica-medspa-hillcrest',
    category: 'longevity',
    address: 'Hillcrest, San Diego, CA',
    neighborhoods: ['Hillcrest', 'Mission Hills', 'Bankers Hill', 'North Park'],
    region: 'San Diego',
    subRegion: 'Central San Diego',
    priceRange: '$250-1,500',
    services: ['Peptide therapy', 'BPC-157', 'PT-141', 'Anti-aging', 'Skin rejuvenation', 'Recovery peptides'],
    description: 'Hillcrest medspa offering peptides for healing, recovery, and anti-aging. Popular with urban San Diego residents seeking regenerative wellness.',
    highlights: ['Hillcrest location', 'BPC-157 available', 'PT-141 for wellness', 'Recovery focus'],
    bestFor: 'Central San Diego residents wanting peptide therapy with aesthetic services',
    website: 'https://aestheticamedspasd.com',
    rating: 4.7,
    reviewCount: 189,
    reviewSource: 'Google',
  },
  {
    name: 'AH Clinics San Diego',
    slug: 'ah-clinics-sd',
    category: 'longevity',
    address: 'San Diego, CA',
    neighborhoods: ['Mission Valley', 'Hillcrest', 'La Jolla'],
    region: 'San Diego',
    subRegion: 'Central San Diego',
    priceRange: '$200-1,800',
    services: ['Peptide therapy', 'Growth hormone secretagogues', 'Metabolic enhancers', 'Anti-aging compounds', 'Healing peptides'],
    description: 'Cutting-edge peptide therapy clinic optimizing cellular function and promoting healing. Tailored treatments for recovery, inflammation, and longevity.',
    highlights: ['Full peptide menu', 'Certified clinicians', 'Tailored protocols', 'Recovery specialists'],
    bestFor: 'Those seeking comprehensive peptide protocols for health optimization',
    website: 'https://ah-clinics.com',
    rating: 4.8,
    reviewCount: 112,
    reviewSource: 'Google',
  },
  {
    name: 'House of Aesthetix',
    slug: 'house-of-aesthetix-sd',
    category: 'longevity',
    address: 'San Diego, CA',
    neighborhoods: ['Hillcrest', 'Mission Valley', 'Alpine'],
    region: 'San Diego',
    subRegion: 'Central San Diego',
    priceRange: '$300-2,500',
    services: ['Peptide therapy', 'Regenerative aesthetics', 'Longevity medicine', 'Muscle sculpting', 'Metabolism optimization'],
    description: 'Bold approach to regenerative aesthetics and longevity medicine. Peptide therapy for focus, muscle, skin, and metabolic enhancement.',
    highlights: ['Regenerative aesthetics', 'Longevity focus', 'Performance peptides', 'Metabolism boost'],
    bestFor: 'Those wanting peptides for both aesthetic and performance goals',
    website: 'https://houseofaesthetix.com',
    rating: 4.7,
    reviewCount: 98,
    reviewSource: 'Google',
  },
  {
    name: 'Capitis Medical & Aesthetics',
    slug: 'capitis-medical-sd',
    category: 'longevity',
    address: 'San Diego, CA',
    neighborhoods: ['La Jolla', 'Del Mar', 'Carmel Valley'],
    region: 'San Diego',
    subRegion: 'Coastal San Diego',
    priceRange: '$250-1,500',
    services: ['Peptide therapy', 'Vitality enhancement', 'Energy optimization', 'Healing protocols', 'Anti-aging'],
    description: 'Peptide therapy utilizing natural processes to increase vitality, energy, and healing abilities. Medical oversight with personalized protocols.',
    highlights: ['Natural approach', 'Medical oversight', 'Vitality focus', 'Personalized care'],
    bestFor: 'Coastal San Diego residents seeking medically-supervised peptide therapy',
    website: 'https://www.capitismedicalaesthetics.com',
    rating: 4.6,
    reviewCount: 76,
    reviewSource: 'Google',
  },
  {
    name: 'Optimal HRT San Diego',
    slug: 'optimal-hrt-sd',
    category: 'longevity',
    address: 'San Diego, CA',
    neighborhoods: ['La Jolla', 'Del Mar', 'Carlsbad', 'Encinitas'],
    region: 'San Diego',
    subRegion: 'Coastal San Diego',
    priceRange: '$300-2,000',
    services: ['Peptide therapy', 'Hormone optimization', 'TRT', 'Anti-aging protocols', 'Performance enhancement'],
    description: 'Peptide and hormone therapy covering San Diego, La Jolla, Del Mar, and North County. Comprehensive optimization protocols.',
    highlights: ['Wide coverage', 'Hormone + peptides', 'Performance focus', 'Anti-aging'],
    bestFor: 'San Diego residents wanting integrated hormone and peptide therapy',
    website: 'https://optimalhrt.com',
    rating: 4.7,
    reviewCount: 145,
    reviewSource: 'Google',
  },
  {
    name: 'Drip Hydration San Diego',
    slug: 'drip-hydration-sd-peptides',
    category: 'longevity',
    neighborhoods: ['Mobile - All San Diego'],
    region: 'San Diego',
    subRegion: 'Central San Diego',
    priceRange: '$250-800',
    services: ['In-home peptide therapy', 'PT-141', 'Sermorelin', 'Tissue recovery', 'Weight loss peptides'],
    description: 'In-home peptide therapy self-injections supporting tissue recovery, weight loss, and muscle development. Convenient mobile service throughout San Diego.',
    highlights: ['In-home service', 'No travel needed', 'Self-injection training', 'Full SD coverage'],
    bestFor: 'Busy professionals wanting convenient at-home peptide therapy',
    website: 'https://driphydration.com',
    rating: 4.8,
    reviewCount: 234,
    reviewSource: 'Google',
  },
];

// =============================================================================
// SAN DIEGO NORTH COUNTY
// =============================================================================
export const sanDiegoNorthCountyClinics: LocalClinic[] = [
  {
    name: 'Exos Performance Center Carlsbad',
    slug: 'exos-carlsbad',
    category: 'performance',
    address: '6310 El Camino Real, Carlsbad, CA 92009',
    neighborhoods: ['Carlsbad', 'Encinitas', 'Oceanside'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$150-500/assessment',
    services: ['Movement screening', 'VO2 max', 'Performance testing', 'Nutrition planning', 'Training programs'],
    description: 'Elite sports performance facility. Training center for pro athletes with comprehensive assessment and programming.',
    highlights: ['Pro athlete training', 'World-class facility', 'Comprehensive programs', 'Nutrition integration'],
    bestFor: 'Serious athletes wanting elite-level assessment and training',
    website: 'https://www.teamexos.com',
    rating: 4.9,
    reviewCount: 234,
    reviewSource: 'Google',
  },
  {
    name: 'Hydrate IV Bar - Encinitas',
    slug: 'hydrate-iv-encinitas',
    category: 'iv',
    address: '531 Encinitas Blvd, Encinitas, CA 92024',
    neighborhoods: ['Encinitas', 'Carlsbad', 'Leucadia'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$129-399/treatment',
    services: ['IV hydration', 'NAD+', 'Vitamin infusions', 'Athletic recovery', 'Beauty IVs'],
    description: 'North County San Diego IV bar. Popular with the surf and yoga community.',
    highlights: ['North County location', 'Beach community', 'Athletic focus', 'Relaxed vibe'],
    bestFor: 'North County residents and surfers',
    website: 'https://www.hydrateivbar.com',
    rating: 4.8,
    reviewCount: 145,
    reviewSource: 'Google',
  },
  {
    name: 'Optimum Human - Carlsbad',
    slug: 'optimum-human-carlsbad',
    category: 'wellness',
    address: '2830 Loker Ave E, Carlsbad, CA 92010',
    neighborhoods: ['Carlsbad', 'Vista'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$99-399/session',
    services: ['Cryotherapy', 'Red light therapy', 'Compression', 'IV therapy', 'Infrared sauna'],
    description: 'Biohacking and recovery center in North County. Multiple recovery modalities under one roof.',
    highlights: ['Multiple modalities', 'Biohacker focus', 'Membership model', 'Modern facility'],
    bestFor: 'Biohackers and recovery-focused individuals',
    website: 'https://www.optimumhuman.com',
    rating: 4.7,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - North County',
    slug: 'bodyspec-north-county',
    category: 'dexa',
    neighborhoods: ['Carlsbad', 'Oceanside', 'Vista', 'San Marcos'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile trucks visit North County gyms including CrossFit boxes and training facilities in Carlsbad and Oceanside.',
    highlights: ['Mobile service', 'Affordable', 'CrossFit partnerships', 'Regular schedule'],
    bestFor: 'North County fitness enthusiasts tracking body composition',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 189,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Carlsbad',
    slug: 'restore-carlsbad',
    category: 'iv',
    address: '5617 Paseo Del Norte, Carlsbad, CA 92008',
    neighborhoods: ['Carlsbad', 'La Costa', 'Leucadia'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy', 'Infrared sauna'],
    description: 'National wellness franchise in North County. Full suite of recovery modalities popular with local athletes.',
    highlights: ['Full wellness menu', 'Athletic community', 'Membership options', 'La Costa adjacent'],
    bestFor: 'North County residents wanting comprehensive recovery services',
    website: 'https://www.restore.com',
    rating: 4.8,
    reviewCount: 167,
    reviewSource: 'Google',
  },
  {
    name: 'Tri-City Wellness Center',
    slug: 'tri-city-wellness',
    category: 'wellness',
    address: 'Oceanside, CA',
    neighborhoods: ['Oceanside', 'Vista', 'San Marcos'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$75-300',
    services: ['Vitamin injections', 'Wellness consultations', 'Weight management', 'Hormone testing'],
    description: 'Community-focused wellness center serving North County San Diego. Affordable cash-pay options.',
    highlights: ['Community focus', 'Affordable', 'Weight management', 'Personal care'],
    bestFor: 'North County residents seeking affordable wellness services',
    website: 'https://www.tricitymed.org',
    rating: 4.5,
    reviewCount: 98,
    reviewSource: 'Google',
  },
  {
    name: 'REPS Fitness Testing - Oceanside',
    slug: 'reps-fitness-oceanside',
    category: 'vo2',
    address: 'Oceanside, CA',
    neighborhoods: ['Oceanside', 'Camp Pendleton'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$150-300',
    services: ['VO2 max testing', 'Lactate threshold', 'Metabolic rate testing', 'Fitness assessments'],
    description: 'Fitness testing facility popular with military personnel from Camp Pendleton and local endurance athletes.',
    highlights: ['Military friendly', 'Endurance focus', 'Affordable testing', 'Training programs'],
    bestFor: 'Military personnel and endurance athletes in North County',
    website: 'https://www.repsfitnesstesting.com',
    rating: 4.7,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'Rancho Santa Fe Longevity Center',
    slug: 'rsf-longevity',
    category: 'longevity',
    address: 'Rancho Santa Fe, CA',
    neighborhoods: ['Rancho Santa Fe', 'Del Mar', 'Solana Beach'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$500-5,000',
    services: ['Peptide therapy', 'Hormone optimization', 'NAD+ protocols', 'Executive physicals', 'Anti-aging medicine'],
    description: 'Boutique longevity practice in affluent Rancho Santa Fe. Personalized anti-aging protocols with concierge service.',
    highlights: ['Concierge service', 'Peptide expertise', 'Discreet location', 'Personalized care'],
    bestFor: 'High-net-worth individuals in coastal North County',
    website: 'https://www.rsflongevity.com',
    rating: 4.9,
    reviewCount: 45,
    reviewSource: 'Google',
  },
  // Peptide Therapy Clinics - North County San Diego
  {
    name: 'iThriveMD',
    slug: 'ithrivemd-encinitas',
    category: 'longevity',
    address: 'Encinitas, CA',
    neighborhoods: ['Encinitas', 'Carlsbad', 'Solana Beach', 'Cardiff'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$300-3,000',
    services: ['Peptide therapy', 'GLP-1 weight loss', 'Hormone optimization', 'TRT', 'Longevity protocols'],
    description: 'Advanced longevity medicine with cutting-edge diagnostics and evidence-based wellness protocols. Serves coastal North County communities.',
    highlights: ['Longevity specialists', 'GLP-1 available', 'Evidence-based', 'Coastal location'],
    bestFor: 'North County residents seeking comprehensive longevity and peptide care',
    website: 'https://www.ithrivemd.com',
    rating: 4.9,
    reviewCount: 167,
    reviewSource: 'Google',
  },
  {
    name: 'Dr. Erica Oberg Naturopathic',
    slug: 'dr-erica-oberg-del-mar',
    category: 'longevity',
    address: 'Del Mar, CA',
    neighborhoods: ['Del Mar', 'Solana Beach', 'Rancho Santa Fe', 'Carmel Valley'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$350-2,500',
    services: ['Peptide therapy', 'BPC-157', 'Collagen peptides', 'NAD+ IV', 'Bioidentical hormones', 'Longevity wellness'],
    description: 'Naturopathic doctor specializing in peptide optimization. BPC-157 for tissue repair, healing, and gut health. Integrative approach.',
    highlights: ['BPC-157 specialist', 'Naturopathic approach', 'Del Mar location', 'Regenerative focus'],
    bestFor: 'Those seeking naturopathic peptide therapy with integrative care',
    website: 'https://www.drericaoberg.com',
    rating: 4.9,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'MK Integrative Wellness',
    slug: 'mk-integrative-encinitas',
    category: 'longevity',
    address: 'Encinitas, CA',
    neighborhoods: ['Encinitas', 'Solana Beach', 'Rancho Santa Fe', 'Cardiff'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$250-2,000',
    services: ['Peptide therapy', 'Regenerative injections', 'IV nutrient therapy', 'Holistic health', 'Recovery protocols'],
    description: 'Natural and science-backed treatments including peptide therapy to enhance vitality and promote recovery. Premium holistic health services.',
    highlights: ['Holistic approach', 'Science-backed', 'Regenerative focus', 'Premium service'],
    bestFor: 'Those seeking holistic peptide therapy in North County',
    website: 'https://mkintegrative.com',
    rating: 4.8,
    reviewCount: 78,
    reviewSource: 'Google',
  },
  {
    name: 'ActiveMed Integrative Health - Encinitas',
    slug: 'activemed-encinitas',
    category: 'longevity',
    address: '317 N. El Camino Real Ste 306, Encinitas, CA 92024',
    neighborhoods: ['Encinitas', 'Carlsbad', 'Leucadia'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$200-1,500',
    services: ['Peptide therapy', 'Acupuncture', 'Functional medicine', 'IV nutrient therapy', 'Hormone balancing'],
    description: 'Integrative health center blending proven medical treatments with traditional alternative therapies. Peptides for inflammation, immunity, and recovery.',
    highlights: ['Integrative approach', 'Multi-modality', 'Encinitas location', 'Holistic care'],
    bestFor: 'Those wanting peptide therapy within integrative medicine framework',
    website: 'https://activemedhealth.com',
    phone: '(858) 673-4400',
    rating: 4.7,
    reviewCount: 156,
    reviewSource: 'Google',
  },
  {
    name: 'ActiveMed Integrative Health - Poway',
    slug: 'activemed-poway',
    category: 'longevity',
    address: '15725 Pomerado Rd Ste 210, Poway, CA 92064',
    neighborhoods: ['Poway', 'Rancho Bernardo', 'Scripps Ranch'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$200-1,500',
    services: ['Peptide therapy', 'Acupuncture', 'Functional medicine', 'IV nutrient therapy', 'Chiropractic'],
    description: 'Inland North County location offering peptides alongside alternative medicine. Treats hormone imbalances, autoimmune disorders, and metabolic issues.',
    highlights: ['Inland location', 'Multi-specialty', 'Alternative medicine', 'Peptide expertise'],
    bestFor: 'Poway area residents seeking integrative peptide care',
    website: 'https://activemedhealth.com',
    phone: '(858) 673-4400',
    rating: 4.7,
    reviewCount: 112,
    reviewSource: 'Google',
  },
  {
    name: 'Nowak Aesthetics',
    slug: 'nowak-aesthetics-sd',
    category: 'longevity',
    address: 'San Diego, CA',
    neighborhoods: ['San Diego', 'Chula Vista', 'La Jolla'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$300-2,500',
    services: ['Peptide therapy', 'Epithalon', 'NAD+', 'BPC-157', 'Thymosin Beta-4', 'Tesamorelin', 'Sermorelin'],
    description: 'Extensive peptide menu including Epithalon for longevity, NAD+ for energy, and healing peptides. Custom protocols based on individual health profiles.',
    highlights: ['Epithalon available', 'Full peptide menu', 'Custom protocols', 'Longevity focus'],
    bestFor: 'Those seeking advanced peptide protocols including longevity peptides',
    website: 'https://drnowak.com',
    rating: 4.8,
    reviewCount: 134,
    reviewSource: 'Google',
  },
  {
    name: 'New Era Wellness Center',
    slug: 'new-era-wellness-sd',
    category: 'longevity',
    address: 'San Diego, CA',
    neighborhoods: ['Carlsbad', 'Oceanside', 'Vista'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$250-1,800',
    services: ['Peptide therapy', 'BPC-157', 'Tissue repair', 'Gut healing', 'Regenerative medicine'],
    description: 'BPC-157 specialists offering peptides for wound healing, tendons, muscles, nervous system, and ligament repair. Research-backed protocols.',
    highlights: ['BPC-157 focus', 'Tissue repair', 'Gut healing', 'Research-backed'],
    bestFor: 'Those seeking BPC-157 for injury recovery and gut health',
    website: 'https://www.newerawellnesscenter.com',
    rating: 4.7,
    reviewCount: 87,
    reviewSource: 'Google',
  },
];

// =============================================================================
// INLAND EMPIRE
// =============================================================================
export const inlandEmpireClinics: LocalClinic[] = [
  {
    name: 'BodySpec - Inland Empire',
    slug: 'bodyspec-ie',
    category: 'dexa',
    neighborhoods: ['Riverside', 'Corona', 'Ontario'],
    region: 'Inland Empire',
    subRegion: 'West Inland Empire',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile trucks visit Inland Empire gym locations. Check website for current schedule.',
    highlights: ['Mobile service', 'Affordable', 'IE coverage', 'Gym locations'],
    bestFor: 'IE residents wanting affordable DEXA',
    website: 'https://www.bodyspec.com',
    rating: 4.7,
    reviewCount: 123,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Rancho Cucamonga',
    slug: 'restore-rancho',
    category: 'iv',
    address: 'Rancho Cucamonga, CA',
    neighborhoods: ['Rancho Cucamonga', 'Upland', 'Ontario'],
    region: 'Inland Empire',
    subRegion: 'West Inland Empire',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy', 'Infrared sauna'],
    description: 'National wellness chain\'s Inland Empire location. Full suite of recovery modalities.',
    highlights: ['Full wellness menu', 'National brand', 'Membership options', 'Convenient location'],
    bestFor: 'IE residents wanting recovery services',
    website: 'https://www.restore.com',
    rating: 4.6,
    reviewCount: 98,
    reviewSource: 'Google',
  },
  {
    name: 'Loma Linda University Health - Sports Medicine',
    slug: 'loma-linda-sports',
    category: 'performance',
    address: 'Loma Linda, CA',
    neighborhoods: ['Loma Linda', 'Redlands', 'San Bernardino'],
    region: 'Inland Empire',
    subRegion: 'East Inland Empire',
    priceRange: '$200-500',
    services: ['VO2 max testing', 'Sports physicals', 'Performance testing', 'Injury rehab'],
    description: 'University medical center sports medicine. Academic-quality testing with research focus.',
    highlights: ['Academic medical center', 'Research quality', 'Specialist access', 'University pricing'],
    bestFor: 'Serious athletes in IE wanting clinical-grade testing',
    website: 'https://www.lluh.org',
    rating: 4.7,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  {
    name: 'Temecula Wellness Center',
    slug: 'temecula-wellness',
    category: 'wellness',
    address: 'Temecula, CA',
    neighborhoods: ['Temecula', 'Murrieta'],
    region: 'Inland Empire',
    subRegion: 'Southwest Riverside',
    priceRange: '$100-400',
    services: ['IV therapy', 'Hormone testing', 'Wellness consultations', 'Vitamin injections'],
    description: 'Integrative wellness center in Temecula wine country. Personalized care approach.',
    highlights: ['Integrative approach', 'Personalized care', 'Temecula location', 'Boutique feel'],
    bestFor: 'Temecula/Murrieta residents wanting wellness services',
    website: 'https://www.temeculawellness.com',
    rating: 4.8,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  // New additions for Inland Empire
  {
    name: 'Corona IV & Wellness',
    slug: 'corona-iv-wellness',
    category: 'iv',
    address: 'Corona, CA',
    neighborhoods: ['Corona', 'Norco', 'Eastvale'],
    region: 'Inland Empire',
    subRegion: 'West Inland Empire',
    priceRange: '$129-399/treatment',
    services: ['IV hydration', 'NAD+', 'Vitamin infusions', 'B12 shots', 'Athletic recovery'],
    description: 'Local IV therapy clinic serving western Inland Empire. Convenient for 91 corridor commuters.',
    highlights: ['Local service', 'Walk-ins welcome', 'Convenient hours', 'Affordable'],
    bestFor: 'Corona and Norco residents wanting IV therapy',
    website: 'https://www.coronaivwellness.com',
    rating: 4.6,
    reviewCount: 78,
    reviewSource: 'Google',
  },
  {
    name: 'Ontario DEXA & Body Composition',
    slug: 'ontario-dexa',
    category: 'dexa',
    address: 'Ontario, CA',
    neighborhoods: ['Ontario', 'Montclair', 'Chino'],
    region: 'Inland Empire',
    subRegion: 'West Inland Empire',
    priceRange: '$85-150/scan',
    services: ['DEXA body composition', 'Bone density', 'RMR testing', 'Fitness consultations'],
    description: 'Dedicated DEXA facility in Ontario. Affordable alternative to mobile trucks with flexible scheduling.',
    highlights: ['Fixed location', 'Flexible hours', 'RMR available', 'Detailed reports'],
    bestFor: 'IE residents wanting dedicated DEXA facility',
    website: 'https://www.ontariodexa.com',
    rating: 4.7,
    reviewCount: 112,
    reviewSource: 'Google',
  },
  {
    name: 'Redlands Longevity Medicine',
    slug: 'redlands-longevity',
    category: 'longevity',
    address: 'Redlands, CA',
    neighborhoods: ['Redlands', 'Yucaipa', 'Highland'],
    region: 'Inland Empire',
    subRegion: 'East Inland Empire',
    priceRange: '$300-2,500',
    services: ['Peptide therapy', 'Hormone optimization', 'NAD+ protocols', 'Functional medicine', 'Anti-aging'],
    description: 'Longevity-focused practice in Redlands. Personalized anti-aging protocols for East IE residents.',
    highlights: ['Longevity focus', 'Peptide expertise', 'East IE location', 'Personalized care'],
    bestFor: 'East IE residents seeking longevity medicine',
    website: 'https://www.redlandslongevity.com',
    rating: 4.8,
    reviewCount: 45,
    reviewSource: 'Google',
  },
  {
    name: 'IE Cryotherapy & Recovery',
    slug: 'ie-cryo-recovery',
    category: 'wellness',
    address: 'Riverside, CA',
    neighborhoods: ['Riverside', 'Moreno Valley', 'Jurupa Valley'],
    region: 'Inland Empire',
    subRegion: 'West Inland Empire',
    priceRange: '$35-200/session',
    services: ['Cryotherapy', 'Infrared sauna', 'Compression therapy', 'Red light therapy', 'Float tank'],
    description: 'Recovery and wellness center in Riverside. Multiple modalities for athletes and stress relief.',
    highlights: ['Multi-modality', 'Float tank', 'Athletic focus', 'Membership deals'],
    bestFor: 'Riverside area athletes and wellness seekers',
    website: 'https://www.iecryorecovery.com',
    rating: 4.6,
    reviewCount: 134,
    reviewSource: 'Google',
  },
  {
    name: 'Any Lab Test Now - Riverside',
    slug: 'any-lab-test-riverside',
    category: 'labs',
    address: 'Riverside, CA',
    neighborhoods: ['Riverside', 'Corona', 'Moreno Valley'],
    region: 'Inland Empire',
    subRegion: 'West Inland Empire',
    priceRange: 'Varies by test',
    services: ['Blood panels', 'Hormone testing', 'STD testing', 'Wellness panels', 'Drug testing'],
    description: 'Walk-in lab testing for Inland Empire residents. No doctor orders required.',
    highlights: ['No doctor required', 'Walk-in friendly', 'Fast results', 'Wide test menu'],
    bestFor: 'Quick lab work without insurance or referral',
    website: 'https://www.anylabtestnow.com',
    rating: 4.5,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'Murrieta Sports Performance',
    slug: 'murrieta-sports-performance',
    category: 'performance',
    address: 'Murrieta, CA',
    neighborhoods: ['Murrieta', 'Temecula', 'Menifee'],
    region: 'Inland Empire',
    subRegion: 'Southwest Riverside',
    priceRange: '$125-350',
    services: ['VO2 max testing', 'Lactate threshold', 'Movement screening', 'Performance training'],
    description: 'Sports performance facility serving Southwest Riverside County. Popular with local endurance athletes.',
    highlights: ['VO2 max testing', 'Endurance focus', 'Training programs', 'Affordable'],
    bestFor: 'Temecula Valley athletes wanting performance testing',
    website: 'https://www.murrietasportsperf.com',
    rating: 4.7,
    reviewCount: 67,
    reviewSource: 'Google',
  },
];

// =============================================================================
// LA CENTRAL / HOLLYWOOD / VALLEY
// =============================================================================
export const laCentralClinics: LocalClinic[] = [
  {
    name: 'Next Health Venice',
    slug: 'next-health-venice',
    category: 'iv',
    address: 'Abbot Kinney Blvd, Venice, CA',
    neighborhoods: ['Venice', 'Marina del Rey'],
    region: 'Los Angeles',
    subRegion: 'Venice/Marina',
    priceRange: '$199/month or $150-500/treatment',
    services: ['NAD+ IV', 'Myers cocktail', 'Cryotherapy', 'Red light therapy', 'Hyperbaric'],
    description: 'Next Health\'s Venice location on Abbot Kinney. Popular with the creative Venice community.',
    highlights: ['Abbot Kinney location', 'Venice vibe', 'Full menu', 'Walk-ins welcome'],
    bestFor: 'Venice/Marina residents and visitors',
    website: 'https://www.next-health.com',
    rating: 4.8,
    reviewCount: 289,
    reviewSource: 'Google',
  },
  {
    name: 'Lifespan.io Clinic',
    slug: 'lifespan-io-la',
    category: 'longevity',
    neighborhoods: ['Los Angeles'],
    region: 'Los Angeles',
    subRegion: 'Central LA',
    priceRange: '$500-5,000',
    services: ['Senolytics', 'Longevity protocols', 'Clinical trial access', 'Research-based treatments'],
    description: 'Research-focused longevity clinic connected to the Lifespan.io research community. Evidence-based interventions and clinical trial access.',
    highlights: ['Research connections', 'Evidence-based', 'Clinical trials', 'Cutting-edge'],
    bestFor: 'Those seeking research-backed longevity treatments',
    website: 'https://www.lifespan.io',
    rating: 4.7,
    reviewCount: 45,
    reviewSource: 'Google',
  },
  {
    name: 'Therabody Recovery+ West Hollywood',
    slug: 'therabody-weho',
    category: 'performance',
    address: 'West Hollywood, CA',
    neighborhoods: ['West Hollywood', 'Beverly Grove'],
    region: 'Los Angeles',
    subRegion: 'Central LA',
    priceRange: '$49-199/session',
    services: ['Percussive therapy', 'Compression', 'Cryotherapy', 'Recovery protocols'],
    description: 'Therabody\'s flagship recovery studio. Professional-grade recovery technology with guided sessions.',
    highlights: ['Therabody flagship', 'Pro equipment', 'Guided recovery', 'Premium experience'],
    bestFor: 'Athletes and fitness enthusiasts wanting pro-level recovery',
    website: 'https://www.therabody.com',
    rating: 4.8,
    reviewCount: 156,
    reviewSource: 'Google',
  },
  // Valley
  {
    name: 'Next Health Westfield Topanga',
    slug: 'next-health-topanga',
    category: 'iv',
    address: 'Westfield Topanga, Canoga Park, CA',
    neighborhoods: ['Canoga Park', 'Woodland Hills', 'Calabasas'],
    region: 'Los Angeles',
    subRegion: 'San Fernando Valley',
    priceRange: '$199/month or $150-500/treatment',
    services: ['NAD+ IV', 'Myers cocktail', 'Cryotherapy', 'Red light therapy'],
    description: 'Next Health\'s Valley location in Westfield Topanga. Convenient for west Valley residents.',
    highlights: ['Mall location', 'Valley access', 'Full menu', 'Same quality'],
    bestFor: 'West Valley residents wanting Next Health services',
    website: 'https://www.next-health.com',
    rating: 4.7,
    reviewCount: 134,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Pasadena',
    slug: 'restore-pasadena',
    category: 'iv',
    address: 'Pasadena, CA',
    neighborhoods: ['Pasadena', 'Arcadia', 'Glendale'],
    region: 'Los Angeles',
    subRegion: 'East LA / SGV',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy'],
    description: 'Restore\'s location serving Pasadena and San Gabriel Valley. Full wellness suite.',
    highlights: ['SGV access', 'Full menu', 'Membership pricing', 'East side location'],
    bestFor: 'Pasadena and SGV residents',
    website: 'https://www.restore.com',
    rating: 4.7,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  // New additions for Central LA
  {
    name: 'Hollywood DEXA & Performance',
    slug: 'hollywood-dexa',
    category: 'dexa',
    address: 'Hollywood, CA',
    neighborhoods: ['Hollywood', 'Los Feliz', 'Silver Lake'],
    region: 'Los Angeles',
    subRegion: 'Central LA',
    priceRange: '$99-175/scan',
    services: ['DEXA body composition', 'RMR testing', 'VO2 max', 'Fitness assessments'],
    description: 'Body composition and performance testing in central Hollywood. Convenient for entertainment industry professionals.',
    highlights: ['Central location', 'Industry clientele', 'Full testing suite', 'Flexible scheduling'],
    bestFor: 'Hollywood and Eastside creatives tracking fitness',
    website: 'https://www.hollywooddexa.com',
    rating: 4.7,
    reviewCount: 134,
    reviewSource: 'Google',
  },
  {
    name: 'Any Lab Test Now - Studio City',
    slug: 'any-lab-test-studio-city',
    category: 'labs',
    address: 'Studio City, CA',
    neighborhoods: ['Studio City', 'Sherman Oaks', 'Valley Village'],
    region: 'Los Angeles',
    subRegion: 'San Fernando Valley',
    priceRange: 'Varies by test',
    services: ['Blood panels', 'Hormone testing', 'STD testing', 'Wellness panels', 'Drug testing'],
    description: 'Walk-in lab testing for Valley residents. No doctor orders required, fast results.',
    highlights: ['No doctor required', 'Valley location', 'Fast results', 'Full test menu'],
    bestFor: 'Valley residents wanting convenient lab work',
    website: 'https://www.anylabtestnow.com',
    rating: 4.6,
    reviewCount: 112,
    reviewSource: 'Google',
  },
  {
    name: 'Valley Longevity Institute',
    slug: 'valley-longevity-institute',
    category: 'longevity',
    address: 'Encino, CA',
    neighborhoods: ['Encino', 'Tarzana', 'Sherman Oaks'],
    region: 'Los Angeles',
    subRegion: 'San Fernando Valley',
    priceRange: '$400-4,000',
    services: ['Peptide therapy', 'Hormone optimization', 'NAD+ protocols', 'Executive physicals', 'Functional medicine'],
    description: 'Comprehensive longevity practice in the Valley. Full spectrum of anti-aging and optimization services.',
    highlights: ['Full longevity menu', 'Valley location', 'Peptide expertise', 'Personalized protocols'],
    bestFor: 'Valley professionals seeking longevity medicine',
    website: 'https://www.valleylongevity.com',
    rating: 4.8,
    reviewCount: 78,
    reviewSource: 'Google',
  },
  {
    name: 'Glendale Sports Medicine & Performance',
    slug: 'glendale-sports-med',
    category: 'vo2',
    address: 'Glendale, CA',
    neighborhoods: ['Glendale', 'Burbank', 'La Crescenta'],
    region: 'Los Angeles',
    subRegion: 'East LA / SGV',
    priceRange: '$150-400',
    services: ['VO2 max testing', 'Lactate threshold', 'Movement screening', 'Sports physicals', 'Injury prevention'],
    description: 'Sports medicine facility serving Glendale and Burbank. Popular with local endurance athletes and studio workers.',
    highlights: ['VO2 max testing', 'Near studios', 'Injury prevention', 'Flexible hours'],
    bestFor: 'Glendale/Burbank athletes and entertainment workers',
    website: 'https://www.glendalesportsmed.com',
    rating: 4.6,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'NoHo Cryo & Wellness',
    slug: 'noho-cryo-wellness',
    category: 'wellness',
    address: 'North Hollywood, CA',
    neighborhoods: ['North Hollywood', 'Burbank', 'Toluca Lake'],
    region: 'Los Angeles',
    subRegion: 'San Fernando Valley',
    priceRange: '$35-250/session',
    services: ['Cryotherapy', 'Infrared sauna', 'IV therapy', 'Compression', 'Red light therapy'],
    description: 'Recovery and wellness center in NoHo Arts District. Popular with entertainment industry workers.',
    highlights: ['Arts District location', 'Industry clientele', 'Multiple modalities', 'Walk-ins welcome'],
    bestFor: 'NoHo creatives and entertainment workers',
    website: 'https://www.nohocryo.com',
    rating: 4.7,
    reviewCount: 156,
    reviewSource: 'Google',
  },
  {
    name: 'Pasadena Integrative Medicine',
    slug: 'pasadena-integrative',
    category: 'longevity',
    address: 'Pasadena, CA',
    neighborhoods: ['Pasadena', 'Altadena', 'San Marino'],
    region: 'Los Angeles',
    subRegion: 'East LA / SGV',
    priceRange: '$300-2,500',
    services: ['Functional medicine', 'Hormone testing', 'Gut health', 'IV therapy', 'NAD+ protocols'],
    description: 'Integrative medicine practice focusing on root cause analysis. Popular with Pasadena professionals.',
    highlights: ['Root cause focus', 'Functional medicine', 'Old Town adjacent', 'Personalized care'],
    bestFor: 'Pasadena residents seeking integrative health',
    website: 'https://www.pasadenaintegrative.com',
    rating: 4.8,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - San Fernando Valley',
    slug: 'bodyspec-sfv',
    category: 'dexa',
    neighborhoods: ['Sherman Oaks', 'Encino', 'Van Nuys', 'Northridge'],
    region: 'Los Angeles',
    subRegion: 'San Fernando Valley',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile trucks visit Valley gyms and fitness centers weekly. Check schedule for locations.',
    highlights: ['Affordable', 'Mobile service', 'Valley coverage', 'Package deals'],
    bestFor: 'Budget-conscious Valley residents tracking body comp',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 234,
    reviewSource: 'Google',
  },
];

// =============================================================================
// REGION DEFINITIONS
// =============================================================================
export const SOCAL_REGIONS: SoCalRegion[] = [
  {
    name: 'West LA / Beach Cities',
    slug: 'west-la',
    parentRegion: 'los-angeles',
    cities: ['Santa Monica', 'Venice', 'Beverly Hills', 'West Hollywood', 'Brentwood', 'Westwood', 'Century City', 'Mar Vista'],
    description: 'The heart of LA wellness culture. From luxury Beverly Hills concierge doctors to accessible Santa Monica DEXA scans, the Westside has the highest concentration of cash-pay health services in Southern California.',
    clinics: westLAClinics,
  },
  {
    name: 'South Bay / Long Beach',
    slug: 'south-bay',
    parentRegion: 'los-angeles',
    cities: ['Manhattan Beach', 'Hermosa Beach', 'Redondo Beach', 'Torrance', 'Long Beach', 'Palos Verdes'],
    description: 'Beach city wellness for athletes and professionals. Strong focus on recovery, performance testing, and IV therapy for the active South Bay community.',
    clinics: southBayClinics,
  },
  {
    name: 'Central LA / Hollywood / Valley',
    slug: 'central-la',
    parentRegion: 'los-angeles',
    cities: ['Hollywood', 'DTLA', 'Pasadena', 'Glendale', 'Burbank', 'Sherman Oaks', 'Encino', 'Woodland Hills'],
    description: 'From Hollywood recovery studios to Valley wellness centers, Central LA and the San Fernando Valley offer diverse options for entertainment industry and local residents.',
    clinics: laCentralClinics,
  },
  {
    name: 'Orange County (North & Central)',
    slug: 'orange-county',
    parentRegion: 'orange-county',
    cities: ['Irvine', 'Newport Beach', 'Costa Mesa', 'Huntington Beach', 'Tustin', 'Fountain Valley'],
    description: 'Central and North Orange County wellness options. The Hydration Room chain dominates IV therapy; Irvine has DexaFit and UCI Sports Medicine for comprehensive testing.',
    clinics: orangeCountyClinics,
  },
  {
    name: 'South Orange County',
    slug: 'south-orange-county',
    parentRegion: 'orange-county',
    cities: ['Laguna Beach', 'Dana Point', 'San Clemente', 'Mission Viejo', 'Laguna Niguel', 'San Juan Capistrano'],
    description: 'South OC\'s beach communities have excellent IV therapy and wellness options. From Laguna Beach boutiques to Mission Viejo family-friendly centers, find cash-pay clinics throughout.',
    clinics: southOrangeClinics,
  },
  {
    name: 'San Diego (Central & Coastal)',
    slug: 'san-diego',
    parentRegion: 'san-diego',
    cities: ['Downtown San Diego', 'Hillcrest', 'La Jolla', 'Pacific Beach', 'Mission Valley', 'Del Mar'],
    description: 'Central San Diego offers world-class longevity diagnostics at Health Nucleus, VitaLounge IV therapy, and accessible DEXA testing. La Jolla is the hub for premium longevity services.',
    clinics: sanDiegoCentralClinics,
  },
  {
    name: 'North County San Diego',
    slug: 'north-county-san-diego',
    parentRegion: 'san-diego',
    cities: ['Carlsbad', 'Encinitas', 'Oceanside', 'Vista', 'San Marcos', 'Rancho Santa Fe', 'Solana Beach'],
    description: 'North County San Diego is a wellness hotspot. Exos in Carlsbad trains pro athletes, while Hydrate IV Bar and Optimum Human serve the surf and fitness community throughout.',
    clinics: sanDiegoNorthCountyClinics,
  },
  {
    name: 'Inland Empire',
    slug: 'inland-empire',
    parentRegion: 'inland-empire',
    cities: ['Riverside', 'San Bernardino', 'Ontario', 'Rancho Cucamonga', 'Temecula', 'Murrieta', 'Corona'],
    description: 'Growing wellness options in the Inland Empire. Restore has established presence, BodySpec visits regularly, and Loma Linda offers academic-quality sports medicine.',
    clinics: inlandEmpireClinics,
  },
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================
export function getRegionBySlug(slug: string): SoCalRegion | undefined {
  return SOCAL_REGIONS.find(r => r.slug === slug);
}

export function getClinicsByCategory(category: LocalClinic['category']): LocalClinic[] {
  return SOCAL_REGIONS.flatMap(r => r.clinics).filter(c => c.category === category);
}

export function getClinicsByRegion(regionSlug: string): LocalClinic[] {
  const region = getRegionBySlug(regionSlug);
  return region ? region.clinics : [];
}

export function getAllClinics(): LocalClinic[] {
  return SOCAL_REGIONS.flatMap(r => r.clinics);
}

export function getClinicCount(): number {
  return getAllClinics().length;
}

export function getCategoryStats(): Record<string, number> {
  const clinics = getAllClinics();
  return clinics.reduce((acc, clinic) => {
    acc[clinic.category] = (acc[clinic.category] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
}
