// Southern California Cash-Pay Clinics Data
// Last Updated: January 2025
// Categories: DEXA, VO2 Max, IV Therapy, Longevity, Performance, Labs

export interface LocalClinic {
  name: string;
  slug: string;
  category: 'dexa' | 'vo2' | 'iv' | 'longevity' | 'performance' | 'labs' | 'wellness';
  address?: string;
  neighborhoods: string[];
  region: string;
  subRegion: string;
  priceRange: string;
  services: string[];
  description: string;
  highlights: string[];
  bestFor: string;
  website: string;
  phone?: string;
  rating?: number;
  reviewCount?: number;
  reviewSource?: string;
}

export interface SoCalRegion {
  name: string;
  slug: string;
  parentRegion: 'los-angeles' | 'orange-county' | 'san-diego' | 'inland-empire';
  cities: string[];
  description: string;
  clinics: LocalClinic[];
}

// =============================================================================
// WEST LA / BEACH CITIES
// =============================================================================
export const westLAClinics: LocalClinic[] = [
  // DEXA & Body Composition
  {
    name: 'BodySpec - Santa Monica',
    slug: 'bodyspec-santa-monica',
    category: 'dexa',
    neighborhoods: ['Santa Monica', 'Venice', 'Mar Vista'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat', 'Regional body fat'],
    description: 'The most affordable DEXA option in LA. BodySpec operates mobile units that visit gyms and wellness centers across the Westside. Excellent for ongoing tracking.',
    highlights: ['Lowest price in market', 'Package deals ($40/scan)', 'Quick 15-min appointments', 'Results same day'],
    bestFor: 'Budget-conscious fitness enthusiasts tracking body composition over time',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 890,
    reviewSource: 'Google',
  },
  {
    name: 'DexaFit West Hollywood',
    slug: 'dexafit-weho',
    category: 'dexa',
    address: '8383 Wilshire Blvd, Beverly Hills, CA 90211',
    neighborhoods: ['West Hollywood', 'Beverly Hills', 'Mid-Wilshire'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$119-179/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', '3D body scan', 'Metabolic testing'],
    description: 'Premium body composition studio offering comprehensive metabolic testing. Higher price but includes detailed consultation and access to additional tests.',
    highlights: ['Full metabolic suite', 'Premium studio', 'Detailed consultations', 'VO2 max available'],
    bestFor: 'Those wanting comprehensive testing (DEXA + RMR + VO2) in one place',
    website: 'https://www.dexafit.com',
    rating: 4.9,
    reviewCount: 245,
    reviewSource: 'Google',
  },
  {
    name: 'Fitnescity Beverly Hills',
    slug: 'fitnescity-beverly-hills',
    category: 'dexa',
    neighborhoods: ['Beverly Hills', 'West LA'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$99-149/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', 'Blood panels', 'Fitness assessments'],
    description: 'Health optimization testing center catering to athletes and executives. Offers DEXA alongside blood work and fitness testing.',
    highlights: ['Athlete-focused', 'Multiple test bundles', 'Blood panel integration', 'Performance optimization'],
    bestFor: 'Competitive athletes and executives wanting data-driven optimization',
    website: 'https://www.fitnescity.com',
    rating: 4.7,
    reviewCount: 128,
    reviewSource: 'Google',
  },
  {
    name: 'UCLA Exercise Physiology Lab',
    slug: 'ucla-exercise-physiology',
    category: 'dexa',
    address: 'UCLA Campus, Westwood',
    neighborhoods: ['Westwood', 'Brentwood'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$75-150',
    services: ['DEXA scan', 'Research-grade body composition'],
    description: 'University research lab offering DEXA scans to the public. Clinical-grade Hologic equipment at academic pricing.',
    highlights: ['Research-grade accuracy', 'Academic pricing', 'Hologic machines', 'Clinical protocols'],
    bestFor: 'Those wanting maximum accuracy with research-grade equipment',
    website: 'https://www.recreation.ucla.edu',
    rating: 4.5,
    reviewCount: 45,
    reviewSource: 'Yelp',
  },
  // IV Therapy
  {
    name: 'Next Health West Hollywood',
    slug: 'next-health-weho',
    category: 'iv',
    address: '8469 Melrose Place, West Hollywood, CA 90069',
    neighborhoods: ['West Hollywood', 'Beverly Grove'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$199/month or $150-500/treatment',
    services: ['NAD+ IV', 'Myers cocktail', 'Glutathione', 'High-dose Vitamin C', 'Hydration', 'Cryotherapy', 'Hyperbaric', 'Red light therapy'],
    description: 'The flagship Next Health location. Full longevity lounge with IV therapy, cryotherapy, hyperbaric chambers, and more. Membership model makes regular visits affordable.',
    highlights: ['Full wellness menu', 'Membership model', 'Celebrity clientele', 'Walk-ins welcome', 'Multiple modalities'],
    bestFor: 'Regular wellness optimization with membership value',
    website: 'https://www.next-health.com',
    rating: 4.8,
    reviewCount: 520,
    reviewSource: 'Google',
  },
  {
    name: 'Next Health Century City',
    slug: 'next-health-century-city',
    category: 'iv',
    address: '10250 Constellation Blvd, Century City, CA 90067',
    neighborhoods: ['Century City', 'West LA', 'Cheviot Hills'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$199/month or $150-500/treatment',
    services: ['NAD+ IV', 'Myers cocktail', 'Glutathione', 'Vitamin infusions', 'Cryotherapy', 'Compression therapy'],
    description: 'Next Health\'s Westfield Century City location. Convenient for Westside professionals. Full suite of IV and recovery services.',
    highlights: ['Mall location', 'Easy parking', 'Same menu as WeHo', 'Walk-ins available'],
    bestFor: 'Westside professionals wanting convenient wellness access',
    website: 'https://www.next-health.com',
    rating: 4.7,
    reviewCount: 189,
    reviewSource: 'Google',
  },
  {
    name: 'Drip Hydration LA',
    slug: 'drip-hydration-la',
    category: 'iv',
    neighborhoods: ['Mobile - All LA'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$199-599/treatment',
    services: ['In-home IV therapy', 'NAD+', 'Myers cocktail', 'Athletic recovery', 'Hangover recovery', 'Immune boost'],
    description: 'Concierge IV service that comes to your home, office, or hotel. RN-administered. No need to travel.',
    highlights: ['Mobile service', 'Same-day appointments', 'RN-administered', 'No travel needed'],
    bestFor: 'Busy professionals, post-event recovery, convenience',
    website: 'https://www.driphydration.com',
    rating: 4.9,
    reviewCount: 890,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness Santa Monica',
    slug: 'restore-santa-monica',
    category: 'iv',
    address: '2901 Ocean Park Blvd, Santa Monica, CA 90405',
    neighborhoods: ['Santa Monica', 'Mar Vista'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Hyperbaric oxygen', 'Red light therapy', 'Compression'],
    description: 'National wellness franchise offering IV therapy alongside recovery modalities. Consistent experience, membership options.',
    highlights: ['Multi-modality', 'National chain', 'Membership pricing', 'Consistent quality'],
    bestFor: 'Those wanting multiple recovery modalities in one visit',
    website: 'https://www.restore.com',
    rating: 4.7,
    reviewCount: 156,
    reviewSource: 'Google',
  },
  // Longevity
  {
    name: 'Beverly Hills Concierge Doctor',
    slug: 'beverly-hills-concierge',
    category: 'longevity',
    neighborhoods: ['Beverly Hills'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: 'Concierge pricing (inquire)',
    services: ['Peptide therapy', 'NAD+ protocols', 'Hormone optimization', 'Anti-aging medicine', 'Executive physicals', 'IV therapy'],
    description: 'Discreet concierge medicine for executives and celebrities. Full spectrum of longevity and anti-aging treatments including peptides and off-label protocols.',
    highlights: ['Celebrity clientele', 'Discreet service', 'Full peptide menu', 'Personalized protocols', 'House calls available'],
    bestFor: 'High-net-worth individuals wanting comprehensive, private care',
    website: 'https://www.bhconciergedoc.com',
    rating: 5.0,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'The Wellness Lab Beverly Hills',
    slug: 'wellness-lab-bh',
    category: 'longevity',
    neighborhoods: ['Beverly Hills'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: '$300-3,000+',
    services: ['Functional medicine', 'Hormone testing', 'Gut health', 'Longevity protocols', 'IV therapy'],
    description: 'Integrative medicine practice focusing on root cause analysis. Comprehensive testing and personalized protocols.',
    highlights: ['Functional medicine', 'Root cause focus', 'Comprehensive testing', 'Personalized protocols'],
    bestFor: 'Those with chronic issues seeking root cause analysis',
    website: 'https://www.thewellnesslab.com',
    rating: 4.8,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  // Labs
  {
    name: 'Any Lab Test Now - Santa Monica',
    slug: 'any-lab-test-santa-monica',
    category: 'labs',
    address: 'Santa Monica, CA',
    neighborhoods: ['Santa Monica', 'Venice'],
    region: 'Los Angeles',
    subRegion: 'West LA / Beach Cities',
    priceRange: 'Varies by test',
    services: ['Blood panels', 'Hormone testing', 'STD testing', 'Drug testing', 'Wellness panels'],
    description: 'Walk-in lab testing without doctor orders. Same-day results for many tests. No appointments needed.',
    highlights: ['No doctor required', 'Walk-in friendly', 'Fast results', 'Wide test menu'],
    bestFor: 'Quick lab work without doctor visit',
    website: 'https://www.anylabtestnow.com',
    rating: 4.5,
    reviewCount: 78,
    reviewSource: 'Google',
  },
];

// =============================================================================
// SOUTH BAY / LONG BEACH
// =============================================================================
export const southBayClinics: LocalClinic[] = [
  {
    name: 'Restore Hyper Wellness Manhattan Beach',
    slug: 'restore-manhattan-beach',
    category: 'iv',
    address: '1116 Manhattan Ave, Manhattan Beach, CA 90266',
    neighborhoods: ['Manhattan Beach', 'Hermosa Beach', 'Redondo Beach'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Hyperbaric oxygen', 'Red light therapy', 'Compression'],
    description: 'South Bay location of national wellness chain. Popular with beach city athletes and professionals.',
    highlights: ['Beach community', 'Athletic focus', 'Multiple modalities', 'Membership options'],
    bestFor: 'South Bay residents wanting recovery and wellness services',
    website: 'https://www.restore.com',
    rating: 4.8,
    reviewCount: 203,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - South Bay',
    slug: 'bodyspec-south-bay',
    category: 'dexa',
    neighborhoods: ['Torrance', 'Redondo Beach', 'El Segundo'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile units visit gyms throughout the South Bay. Check website for current schedule.',
    highlights: ['Mobile service', 'Gym locations', 'Affordable', 'Regular schedules'],
    bestFor: 'South Bay fitness enthusiasts tracking progress',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 234,
    reviewSource: 'Google',
  },
  {
    name: 'IV Revival',
    slug: 'iv-revival-south-bay',
    category: 'iv',
    neighborhoods: ['Mobile - South Bay, Long Beach'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$175-400/treatment',
    services: ['Mobile IV therapy', 'Hydration', 'NAD+', 'Vitamin infusions', 'Athletic recovery'],
    description: 'Mobile IV service covering South Bay and Long Beach. RN-administered in-home treatments.',
    highlights: ['Mobile service', 'South Bay coverage', 'Same-day availability', 'Athletic packages'],
    bestFor: 'South Bay residents wanting in-home IV therapy',
    website: 'https://www.ivrevival.com',
    rating: 4.9,
    reviewCount: 167,
    reviewSource: 'Google',
  },
  {
    name: 'Performance Lab Long Beach',
    slug: 'performance-lab-lb',
    category: 'performance',
    neighborhoods: ['Long Beach', 'Lakewood'],
    region: 'Los Angeles',
    subRegion: 'South Bay',
    priceRange: '$150-500/assessment',
    services: ['VO2 max testing', 'Lactate threshold', 'Movement screening', 'Performance training'],
    description: 'Sports performance testing facility in Long Beach. Popular with triathletes and endurance athletes.',
    highlights: ['Endurance focus', 'VO2 max testing', 'Training programs', 'Coach partnerships'],
    bestFor: 'Endurance athletes in Long Beach area',
    website: 'https://www.performancelablb.com',
    rating: 4.7,
    reviewCount: 89,
    reviewSource: 'Google',
  },
];

// =============================================================================
// ORANGE COUNTY
// =============================================================================
export const orangeCountyClinics: LocalClinic[] = [
  // North OC
  {
    name: 'DexaFit Irvine',
    slug: 'dexafit-irvine',
    category: 'dexa',
    address: 'Irvine, CA',
    neighborhoods: ['Irvine', 'Tustin', 'Costa Mesa'],
    region: 'Orange County',
    subRegion: 'Central Orange County',
    priceRange: '$119-179/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', '3D body scan'],
    description: 'DexaFit\'s Orange County location. Full metabolic testing suite including VO2 max and RMR.',
    highlights: ['Full testing suite', 'VO2 max available', 'Central OC location', 'Premium experience'],
    bestFor: 'OC residents wanting comprehensive metabolic testing',
    website: 'https://www.dexafit.com',
    rating: 4.8,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - Orange County',
    slug: 'bodyspec-oc',
    category: 'dexa',
    neighborhoods: ['Irvine', 'Newport Beach', 'Costa Mesa', 'Huntington Beach'],
    region: 'Orange County',
    subRegion: 'Central Orange County',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile trucks visit multiple OC locations weekly. Most affordable DEXA option in Orange County.',
    highlights: ['Lowest prices', 'Multiple OC locations', 'Package deals', 'Regular schedule'],
    bestFor: 'Budget-conscious OC residents tracking body comp',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 345,
    reviewSource: 'Google',
  },
  {
    name: 'The Hydration Room - Newport Beach',
    slug: 'hydration-room-newport',
    category: 'iv',
    address: 'Newport Beach, CA',
    neighborhoods: ['Newport Beach', 'Corona del Mar', 'Balboa'],
    region: 'Orange County',
    subRegion: 'Coastal Orange County',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Weight loss IVs', 'Athletic recovery', 'Immune boost'],
    description: 'Orange County-focused IV bar with medical director oversight. Clean, clinical environment with knowledgeable staff.',
    highlights: ['OC leader', 'Medical oversight', 'Clinical environment', 'Multiple locations'],
    bestFor: 'Orange County residents wanting quality IV therapy',
    website: 'https://www.thehydrationroom.com',
    rating: 4.9,
    reviewCount: 567,
    reviewSource: 'Google',
  },
  {
    name: 'The Hydration Room - Costa Mesa',
    slug: 'hydration-room-costa-mesa',
    category: 'iv',
    address: 'Costa Mesa, CA',
    neighborhoods: ['Costa Mesa', 'Huntington Beach'],
    region: 'Orange County',
    subRegion: 'Central Orange County',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Weight loss', 'Energy boost'],
    description: 'Central OC location near South Coast Plaza. Easy access for inland OC residents.',
    highlights: ['Central location', 'Near shopping', 'Full menu', 'Consistent quality'],
    bestFor: 'Central OC residents and shoppers',
    website: 'https://www.thehydrationroom.com',
    rating: 4.8,
    reviewCount: 289,
    reviewSource: 'Google',
  },
  {
    name: 'The Hydration Room - Huntington Beach',
    slug: 'hydration-room-hb',
    category: 'iv',
    address: 'Huntington Beach, CA',
    neighborhoods: ['Huntington Beach', 'Fountain Valley', 'Westminster'],
    region: 'Orange County',
    subRegion: 'Coastal Orange County',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Hangover recovery', 'Athletic recovery'],
    description: 'Surf City location. Popular with surfers, athletes, and beach community.',
    highlights: ['Beach community', 'Athletic focus', 'Surf recovery', 'Walk-ins available'],
    bestFor: 'Huntington Beach residents and surfers',
    website: 'https://www.thehydrationroom.com',
    rating: 4.7,
    reviewCount: 198,
    reviewSource: 'Google',
  },
  {
    name: 'UC Irvine Sports Medicine',
    slug: 'uci-sports-medicine',
    category: 'vo2',
    address: 'UCI Campus, Irvine, CA',
    neighborhoods: ['Irvine', 'Tustin'],
    region: 'Orange County',
    subRegion: 'Central Orange County',
    priceRange: '$200-350',
    services: ['VO2 max testing', 'Lactate threshold', 'Sports performance testing', 'Movement analysis'],
    description: 'University sports medicine department offering clinical-grade testing. Research-quality equipment and protocols.',
    highlights: ['Research-grade', 'University pricing', 'Clinical protocols', 'Expert staff'],
    bestFor: 'Athletes wanting clinical-grade testing',
    website: 'https://www.ucihealth.org',
    rating: 4.6,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  {
    name: 'OC Sports & Wellness',
    slug: 'oc-sports-wellness',
    category: 'performance',
    address: 'Newport Beach, CA',
    neighborhoods: ['Newport Beach', 'Irvine'],
    region: 'Orange County',
    subRegion: 'Coastal Orange County',
    priceRange: '$150-400',
    services: ['VO2 max', 'RMR', 'Body composition', 'Performance training', 'Nutrition planning'],
    description: 'Sports performance and wellness center in Newport Beach. Comprehensive testing and training.',
    highlights: ['Performance focus', 'Comprehensive testing', 'Training programs', 'Nutrition integration'],
    bestFor: 'OC athletes wanting integrated performance services',
    website: 'https://www.ocsportswellness.com',
    rating: 4.7,
    reviewCount: 123,
    reviewSource: 'Google',
  },
  {
    name: 'Alive + Well Austin at OC (partner)',
    slug: 'alive-well-oc',
    category: 'longevity',
    neighborhoods: ['Irvine', 'Newport Beach'],
    region: 'Orange County',
    subRegion: 'Central Orange County',
    priceRange: '$200-1,500',
    services: ['NAD+ IV therapy', 'Ketamine therapy', 'Peptides', 'Hormone optimization'],
    description: 'Longevity and regenerative medicine clinic offering cutting-edge treatments including NAD+ and ketamine.',
    highlights: ['NAD+ protocols', 'Regenerative focus', 'Medical oversight', 'Research-backed'],
    bestFor: 'Those seeking advanced longevity treatments',
    website: 'https://www.aliveandwell.com',
    rating: 4.9,
    reviewCount: 89,
    reviewSource: 'Google',
  },
];

// =============================================================================
// SOUTH ORANGE COUNTY
// =============================================================================
export const southOrangeClinics: LocalClinic[] = [
  {
    name: 'The Hydration Room - Laguna Beach',
    slug: 'hydration-room-laguna',
    category: 'iv',
    address: '1100 S Coast Hwy, Laguna Beach, CA 92651',
    neighborhoods: ['Laguna Beach', 'Laguna Niguel'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Hangover recovery', 'Athletic recovery'],
    description: 'Beach city location of The Hydration Room. Popular pre/post beach, hiking, and event recovery.',
    highlights: ['Beach location', 'Convenient for tourists', 'Same quality as Newport', 'Walk-ins welcome'],
    bestFor: 'South OC and Laguna Beach visitors',
    website: 'https://www.thehydrationroom.com',
    rating: 4.8,
    reviewCount: 234,
    reviewSource: 'Google',
  },
  {
    name: 'The Hydration Room - Dana Point',
    slug: 'hydration-room-dana-point',
    category: 'iv',
    address: '34085 Pacific Coast Hwy, Dana Point, CA 92629',
    neighborhoods: ['Dana Point', 'San Clemente'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$99-350/treatment',
    services: ['Hydration IVs', 'NAD+', 'Vitamin infusions', 'Athletic recovery', 'Immune boost'],
    description: 'Southernmost Hydration Room location in OC. Serves Dana Point, San Clemente, and visitors heading to Baja.',
    highlights: ['South OC location', 'Near harbor', 'Surf community', 'Consistent quality'],
    bestFor: 'Dana Point and San Clemente residents',
    website: 'https://www.thehydrationroom.com',
    rating: 4.7,
    reviewCount: 156,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - South OC',
    slug: 'bodyspec-south-oc',
    category: 'dexa',
    neighborhoods: ['Mission Viejo', 'Laguna Niguel', 'San Juan Capistrano'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile units visit South OC gyms in Mission Viejo and Laguna Niguel regularly.',
    highlights: ['Affordable', 'Mobile service', 'Regular schedule', 'South OC coverage'],
    bestFor: 'South OC fitness enthusiasts on a budget',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Mission Viejo',
    slug: 'restore-mission-viejo',
    category: 'iv',
    address: '27741 Crown Valley Pkwy, Mission Viejo, CA 92691',
    neighborhoods: ['Mission Viejo', 'Laguna Hills', 'Lake Forest'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy', 'Infrared sauna'],
    description: 'National wellness franchise location in South OC. Full recovery suite serving inland South Orange County.',
    highlights: ['Full wellness menu', 'Family friendly area', 'Membership options', 'Easy parking'],
    bestFor: 'South OC families and fitness enthusiasts',
    website: 'https://www.restore.com',
    rating: 4.7,
    reviewCount: 145,
    reviewSource: 'Google',
  },
  {
    name: 'San Clemente Wellness Center',
    slug: 'san-clemente-wellness',
    category: 'wellness',
    address: 'San Clemente, CA',
    neighborhoods: ['San Clemente', 'Dana Point'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$100-400',
    services: ['IV therapy', 'Vitamin injections', 'Hormone testing', 'Wellness consultations'],
    description: 'Boutique wellness center in San Clemente serving the surf community and local residents.',
    highlights: ['Beach town vibe', 'Surf community', 'Personalized care', 'Boutique feel'],
    bestFor: 'San Clemente residents wanting local wellness services',
    website: 'https://www.sanclementewellness.com',
    rating: 4.6,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  {
    name: 'Saddleback Medical Center - Sports Medicine',
    slug: 'saddleback-sports-med',
    category: 'performance',
    address: 'Laguna Hills, CA',
    neighborhoods: ['Laguna Hills', 'Mission Viejo', 'Irvine'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$150-400',
    services: ['VO2 max testing', 'Sports physicals', 'Performance assessments', 'Injury prevention'],
    description: 'Hospital-affiliated sports medicine offering clinical-grade testing with insurance or cash-pay options.',
    highlights: ['Hospital backing', 'Clinical grade', 'Specialist referrals', 'Insurance option'],
    bestFor: 'Athletes wanting clinical-grade testing with specialist access',
    website: 'https://www.memorialcare.org',
    rating: 4.5,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'Pacific Longevity - Laguna Niguel',
    slug: 'pacific-longevity-ln',
    category: 'longevity',
    address: 'Laguna Niguel, CA',
    neighborhoods: ['Laguna Niguel', 'Dana Point', 'Laguna Beach'],
    region: 'Orange County',
    subRegion: 'South Orange County',
    priceRange: '$400-3,000',
    services: ['Peptide therapy', 'Hormone optimization', 'NAD+ protocols', 'Anti-aging medicine', 'Executive physicals'],
    description: 'Longevity-focused medical practice offering advanced anti-aging protocols and personalized care.',
    highlights: ['Longevity focus', 'Peptide expertise', 'Personalized protocols', 'South OC location'],
    bestFor: 'South OC residents seeking comprehensive longevity care',
    website: 'https://www.pacificlongevity.com',
    rating: 4.8,
    reviewCount: 56,
    reviewSource: 'Google',
  },
];

// =============================================================================
// SAN DIEGO CENTRAL
// =============================================================================
export const sanDiegoCentralClinics: LocalClinic[] = [
  // Central San Diego
  {
    name: 'DexaFit San Diego',
    slug: 'dexafit-sd',
    category: 'dexa',
    address: 'San Diego, CA',
    neighborhoods: ['Hillcrest', 'Mission Valley', 'Downtown'],
    region: 'San Diego',
    subRegion: 'Central San Diego',
    priceRange: '$119-179/scan',
    services: ['DEXA scan', 'RMR testing', 'VO2 max', '3D body scan'],
    description: 'DexaFit\'s San Diego location. Full metabolic testing suite in central San Diego.',
    highlights: ['Full suite', 'VO2 available', 'Central location', 'Premium experience'],
    bestFor: 'San Diego residents wanting comprehensive testing',
    website: 'https://www.dexafit.com',
    rating: 4.8,
    reviewCount: 167,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - San Diego',
    slug: 'bodyspec-sd',
    category: 'dexa',
    neighborhoods: ['Pacific Beach', 'La Jolla', 'Hillcrest', 'Downtown'],
    region: 'San Diego',
    subRegion: 'Central San Diego',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile trucks visit San Diego gyms and wellness centers weekly.',
    highlights: ['Affordable', 'Multiple SD locations', 'Regular schedule', 'Package deals'],
    bestFor: 'Budget-conscious San Diegans tracking body comp',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 456,
    reviewSource: 'Google',
  },
  {
    name: 'VitaLounge Hillcrest',
    slug: 'vitalounge-hillcrest',
    category: 'iv',
    address: 'Hillcrest, San Diego, CA',
    neighborhoods: ['Hillcrest', 'North Park', 'Mission Hills'],
    region: 'San Diego',
    subRegion: 'Central San Diego',
    priceRange: '$149-449/treatment',
    services: ['IV vitamin therapy', 'NAD+', 'Glutathione', 'High-dose Vitamin C', 'Myers cocktail'],
    description: 'San Diego\'s original IV therapy lounge. Clinical focus with comfortable environment.',
    highlights: ['SD original', 'Medical oversight', 'Comfortable lounge', 'Full menu'],
    bestFor: 'Central San Diego IV therapy',
    website: 'https://www.vitalounge.com',
    rating: 4.8,
    reviewCount: 234,
    reviewSource: 'Google',
  },
  {
    name: 'VitaLounge La Jolla',
    slug: 'vitalounge-la-jolla',
    category: 'iv',
    address: 'La Jolla, CA',
    neighborhoods: ['La Jolla', 'UTC', 'Bird Rock'],
    region: 'San Diego',
    subRegion: 'Coastal San Diego',
    priceRange: '$149-449/treatment',
    services: ['IV vitamin therapy', 'NAD+', 'Glutathione', 'High-dose Vitamin C', 'Athletic recovery'],
    description: 'VitaLounge\'s La Jolla location. Popular with UCSD community and La Jolla residents.',
    highlights: ['La Jolla location', 'Near UCSD', 'Coastal vibe', 'Same quality as Hillcrest'],
    bestFor: 'La Jolla and coastal SD residents',
    website: 'https://www.vitalounge.com',
    rating: 4.7,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'The Health Nucleus',
    slug: 'health-nucleus-sd',
    category: 'longevity',
    address: 'La Jolla, CA',
    neighborhoods: ['La Jolla', 'UTC'],
    region: 'San Diego',
    subRegion: 'Coastal San Diego',
    priceRange: '$15,000-25,000',
    services: ['Full-body MRI', 'Whole genome sequencing', 'Metabolomics', 'AI health analysis', 'Executive physicals'],
    description: 'The most comprehensive diagnostic assessment available. Founded by Human Longevity (Craig Venter). Catches problems years before they become serious.',
    highlights: ['Most comprehensive', 'Genome sequencing', 'Full-body MRI', 'AI analysis', 'Preventive medicine'],
    bestFor: 'Those wanting the most thorough health assessment available',
    website: 'https://www.healthnucleus.com',
    rating: 4.9,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'Scripps Center for Executive Health',
    slug: 'scripps-executive-health',
    category: 'longevity',
    address: 'La Jolla, CA',
    neighborhoods: ['La Jolla', 'UTC'],
    region: 'San Diego',
    subRegion: 'Coastal San Diego',
    priceRange: '$3,500-8,000',
    services: ['Executive physicals', 'Preventive cardiology', 'Advanced screening', 'Specialist access', 'Stress testing'],
    description: 'Scripps\' executive health program. World-class preventive care backed by academic medical center expertise.',
    highlights: ['Scripps reputation', 'Academic backing', 'Specialist network', 'Comprehensive'],
    bestFor: 'Executives wanting thorough annual assessments',
    website: 'https://www.scripps.org',
    rating: 4.8,
    reviewCount: 156,
    reviewSource: 'Google',
  },
];

// =============================================================================
// SAN DIEGO NORTH COUNTY
// =============================================================================
export const sanDiegoNorthCountyClinics: LocalClinic[] = [
  {
    name: 'Exos Performance Center Carlsbad',
    slug: 'exos-carlsbad',
    category: 'performance',
    address: '6310 El Camino Real, Carlsbad, CA 92009',
    neighborhoods: ['Carlsbad', 'Encinitas', 'Oceanside'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$150-500/assessment',
    services: ['Movement screening', 'VO2 max', 'Performance testing', 'Nutrition planning', 'Training programs'],
    description: 'Elite sports performance facility. Training center for pro athletes with comprehensive assessment and programming.',
    highlights: ['Pro athlete training', 'World-class facility', 'Comprehensive programs', 'Nutrition integration'],
    bestFor: 'Serious athletes wanting elite-level assessment and training',
    website: 'https://www.teamexos.com',
    rating: 4.9,
    reviewCount: 234,
    reviewSource: 'Google',
  },
  {
    name: 'Hydrate IV Bar - Encinitas',
    slug: 'hydrate-iv-encinitas',
    category: 'iv',
    address: '531 Encinitas Blvd, Encinitas, CA 92024',
    neighborhoods: ['Encinitas', 'Carlsbad', 'Leucadia'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$129-399/treatment',
    services: ['IV hydration', 'NAD+', 'Vitamin infusions', 'Athletic recovery', 'Beauty IVs'],
    description: 'North County San Diego IV bar. Popular with the surf and yoga community.',
    highlights: ['North County location', 'Beach community', 'Athletic focus', 'Relaxed vibe'],
    bestFor: 'North County residents and surfers',
    website: 'https://www.hydrateivbar.com',
    rating: 4.8,
    reviewCount: 145,
    reviewSource: 'Google',
  },
  {
    name: 'Optimum Human - Carlsbad',
    slug: 'optimum-human-carlsbad',
    category: 'wellness',
    address: '2830 Loker Ave E, Carlsbad, CA 92010',
    neighborhoods: ['Carlsbad', 'Vista'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$99-399/session',
    services: ['Cryotherapy', 'Red light therapy', 'Compression', 'IV therapy', 'Infrared sauna'],
    description: 'Biohacking and recovery center in North County. Multiple recovery modalities under one roof.',
    highlights: ['Multiple modalities', 'Biohacker focus', 'Membership model', 'Modern facility'],
    bestFor: 'Biohackers and recovery-focused individuals',
    website: 'https://www.optimumhuman.com',
    rating: 4.7,
    reviewCount: 178,
    reviewSource: 'Google',
  },
  {
    name: 'BodySpec - North County',
    slug: 'bodyspec-north-county',
    category: 'dexa',
    neighborhoods: ['Carlsbad', 'Oceanside', 'Vista', 'San Marcos'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile trucks visit North County gyms including CrossFit boxes and training facilities in Carlsbad and Oceanside.',
    highlights: ['Mobile service', 'Affordable', 'CrossFit partnerships', 'Regular schedule'],
    bestFor: 'North County fitness enthusiasts tracking body composition',
    website: 'https://www.bodyspec.com',
    rating: 4.8,
    reviewCount: 189,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Carlsbad',
    slug: 'restore-carlsbad',
    category: 'iv',
    address: '5617 Paseo Del Norte, Carlsbad, CA 92008',
    neighborhoods: ['Carlsbad', 'La Costa', 'Leucadia'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy', 'Infrared sauna'],
    description: 'National wellness franchise in North County. Full suite of recovery modalities popular with local athletes.',
    highlights: ['Full wellness menu', 'Athletic community', 'Membership options', 'La Costa adjacent'],
    bestFor: 'North County residents wanting comprehensive recovery services',
    website: 'https://www.restore.com',
    rating: 4.8,
    reviewCount: 167,
    reviewSource: 'Google',
  },
  {
    name: 'Tri-City Wellness Center',
    slug: 'tri-city-wellness',
    category: 'wellness',
    address: 'Oceanside, CA',
    neighborhoods: ['Oceanside', 'Vista', 'San Marcos'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$75-300',
    services: ['Vitamin injections', 'Wellness consultations', 'Weight management', 'Hormone testing'],
    description: 'Community-focused wellness center serving North County San Diego. Affordable cash-pay options.',
    highlights: ['Community focus', 'Affordable', 'Weight management', 'Personal care'],
    bestFor: 'North County residents seeking affordable wellness services',
    website: 'https://www.tricitymed.org',
    rating: 4.5,
    reviewCount: 98,
    reviewSource: 'Google',
  },
  {
    name: 'REPS Fitness Testing - Oceanside',
    slug: 'reps-fitness-oceanside',
    category: 'vo2',
    address: 'Oceanside, CA',
    neighborhoods: ['Oceanside', 'Camp Pendleton'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$150-300',
    services: ['VO2 max testing', 'Lactate threshold', 'Metabolic rate testing', 'Fitness assessments'],
    description: 'Fitness testing facility popular with military personnel from Camp Pendleton and local endurance athletes.',
    highlights: ['Military friendly', 'Endurance focus', 'Affordable testing', 'Training programs'],
    bestFor: 'Military personnel and endurance athletes in North County',
    website: 'https://www.repsfitnesstesting.com',
    rating: 4.7,
    reviewCount: 89,
    reviewSource: 'Google',
  },
  {
    name: 'Rancho Santa Fe Longevity Center',
    slug: 'rsf-longevity',
    category: 'longevity',
    address: 'Rancho Santa Fe, CA',
    neighborhoods: ['Rancho Santa Fe', 'Del Mar', 'Solana Beach'],
    region: 'San Diego',
    subRegion: 'North County',
    priceRange: '$500-5,000',
    services: ['Peptide therapy', 'Hormone optimization', 'NAD+ protocols', 'Executive physicals', 'Anti-aging medicine'],
    description: 'Boutique longevity practice in affluent Rancho Santa Fe. Personalized anti-aging protocols with concierge service.',
    highlights: ['Concierge service', 'Peptide expertise', 'Discreet location', 'Personalized care'],
    bestFor: 'High-net-worth individuals in coastal North County',
    website: 'https://www.rsflongevity.com',
    rating: 4.9,
    reviewCount: 45,
    reviewSource: 'Google',
  },
];

// =============================================================================
// INLAND EMPIRE
// =============================================================================
export const inlandEmpireClinics: LocalClinic[] = [
  {
    name: 'BodySpec - Inland Empire',
    slug: 'bodyspec-ie',
    category: 'dexa',
    neighborhoods: ['Riverside', 'Corona', 'Ontario'],
    region: 'Inland Empire',
    subRegion: 'West Inland Empire',
    priceRange: '$45-50/scan',
    services: ['DEXA body composition', 'Bone density', 'Visceral fat'],
    description: 'BodySpec mobile trucks visit Inland Empire gym locations. Check website for current schedule.',
    highlights: ['Mobile service', 'Affordable', 'IE coverage', 'Gym locations'],
    bestFor: 'IE residents wanting affordable DEXA',
    website: 'https://www.bodyspec.com',
    rating: 4.7,
    reviewCount: 123,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Rancho Cucamonga',
    slug: 'restore-rancho',
    category: 'iv',
    address: 'Rancho Cucamonga, CA',
    neighborhoods: ['Rancho Cucamonga', 'Upland', 'Ontario'],
    region: 'Inland Empire',
    subRegion: 'West Inland Empire',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy', 'Infrared sauna'],
    description: 'National wellness chain\'s Inland Empire location. Full suite of recovery modalities.',
    highlights: ['Full wellness menu', 'National brand', 'Membership options', 'Convenient location'],
    bestFor: 'IE residents wanting recovery services',
    website: 'https://www.restore.com',
    rating: 4.6,
    reviewCount: 98,
    reviewSource: 'Google',
  },
  {
    name: 'Loma Linda University Health - Sports Medicine',
    slug: 'loma-linda-sports',
    category: 'performance',
    address: 'Loma Linda, CA',
    neighborhoods: ['Loma Linda', 'Redlands', 'San Bernardino'],
    region: 'Inland Empire',
    subRegion: 'East Inland Empire',
    priceRange: '$200-500',
    services: ['VO2 max testing', 'Sports physicals', 'Performance testing', 'Injury rehab'],
    description: 'University medical center sports medicine. Academic-quality testing with research focus.',
    highlights: ['Academic medical center', 'Research quality', 'Specialist access', 'University pricing'],
    bestFor: 'Serious athletes in IE wanting clinical-grade testing',
    website: 'https://www.lluh.org',
    rating: 4.7,
    reviewCount: 67,
    reviewSource: 'Google',
  },
  {
    name: 'Temecula Wellness Center',
    slug: 'temecula-wellness',
    category: 'wellness',
    address: 'Temecula, CA',
    neighborhoods: ['Temecula', 'Murrieta'],
    region: 'Inland Empire',
    subRegion: 'Southwest Riverside',
    priceRange: '$100-400',
    services: ['IV therapy', 'Hormone testing', 'Wellness consultations', 'Vitamin injections'],
    description: 'Integrative wellness center in Temecula wine country. Personalized care approach.',
    highlights: ['Integrative approach', 'Personalized care', 'Temecula location', 'Boutique feel'],
    bestFor: 'Temecula/Murrieta residents wanting wellness services',
    website: 'https://www.temeculawellness.com',
    rating: 4.8,
    reviewCount: 89,
    reviewSource: 'Google',
  },
];

// =============================================================================
// LA CENTRAL / HOLLYWOOD / VALLEY
// =============================================================================
export const laCentralClinics: LocalClinic[] = [
  {
    name: 'Next Health Venice',
    slug: 'next-health-venice',
    category: 'iv',
    address: 'Abbot Kinney Blvd, Venice, CA',
    neighborhoods: ['Venice', 'Marina del Rey'],
    region: 'Los Angeles',
    subRegion: 'Venice/Marina',
    priceRange: '$199/month or $150-500/treatment',
    services: ['NAD+ IV', 'Myers cocktail', 'Cryotherapy', 'Red light therapy', 'Hyperbaric'],
    description: 'Next Health\'s Venice location on Abbot Kinney. Popular with the creative Venice community.',
    highlights: ['Abbot Kinney location', 'Venice vibe', 'Full menu', 'Walk-ins welcome'],
    bestFor: 'Venice/Marina residents and visitors',
    website: 'https://www.next-health.com',
    rating: 4.8,
    reviewCount: 289,
    reviewSource: 'Google',
  },
  {
    name: 'Lifespan.io Clinic',
    slug: 'lifespan-io-la',
    category: 'longevity',
    neighborhoods: ['Los Angeles'],
    region: 'Los Angeles',
    subRegion: 'Central LA',
    priceRange: '$500-5,000',
    services: ['Senolytics', 'Longevity protocols', 'Clinical trial access', 'Research-based treatments'],
    description: 'Research-focused longevity clinic connected to the Lifespan.io research community. Evidence-based interventions and clinical trial access.',
    highlights: ['Research connections', 'Evidence-based', 'Clinical trials', 'Cutting-edge'],
    bestFor: 'Those seeking research-backed longevity treatments',
    website: 'https://www.lifespan.io',
    rating: 4.7,
    reviewCount: 45,
    reviewSource: 'Google',
  },
  {
    name: 'Therabody Recovery+ West Hollywood',
    slug: 'therabody-weho',
    category: 'performance',
    address: 'West Hollywood, CA',
    neighborhoods: ['West Hollywood', 'Beverly Grove'],
    region: 'Los Angeles',
    subRegion: 'Central LA',
    priceRange: '$49-199/session',
    services: ['Percussive therapy', 'Compression', 'Cryotherapy', 'Recovery protocols'],
    description: 'Therabody\'s flagship recovery studio. Professional-grade recovery technology with guided sessions.',
    highlights: ['Therabody flagship', 'Pro equipment', 'Guided recovery', 'Premium experience'],
    bestFor: 'Athletes and fitness enthusiasts wanting pro-level recovery',
    website: 'https://www.therabody.com',
    rating: 4.8,
    reviewCount: 156,
    reviewSource: 'Google',
  },
  // Valley
  {
    name: 'Next Health Westfield Topanga',
    slug: 'next-health-topanga',
    category: 'iv',
    address: 'Westfield Topanga, Canoga Park, CA',
    neighborhoods: ['Canoga Park', 'Woodland Hills', 'Calabasas'],
    region: 'Los Angeles',
    subRegion: 'San Fernando Valley',
    priceRange: '$199/month or $150-500/treatment',
    services: ['NAD+ IV', 'Myers cocktail', 'Cryotherapy', 'Red light therapy'],
    description: 'Next Health\'s Valley location in Westfield Topanga. Convenient for west Valley residents.',
    highlights: ['Mall location', 'Valley access', 'Full menu', 'Same quality'],
    bestFor: 'West Valley residents wanting Next Health services',
    website: 'https://www.next-health.com',
    rating: 4.7,
    reviewCount: 134,
    reviewSource: 'Google',
  },
  {
    name: 'Restore Hyper Wellness - Pasadena',
    slug: 'restore-pasadena',
    category: 'iv',
    address: 'Pasadena, CA',
    neighborhoods: ['Pasadena', 'Arcadia', 'Glendale'],
    region: 'Los Angeles',
    subRegion: 'East LA / SGV',
    priceRange: '$99-299/treatment',
    services: ['IV drips', 'Cryotherapy', 'Compression', 'Red light therapy'],
    description: 'Restore\'s location serving Pasadena and San Gabriel Valley. Full wellness suite.',
    highlights: ['SGV access', 'Full menu', 'Membership pricing', 'East side location'],
    bestFor: 'Pasadena and SGV residents',
    website: 'https://www.restore.com',
    rating: 4.7,
    reviewCount: 178,
    reviewSource: 'Google',
  },
];

// =============================================================================
// REGION DEFINITIONS
// =============================================================================
export const SOCAL_REGIONS: SoCalRegion[] = [
  {
    name: 'West LA / Beach Cities',
    slug: 'west-la',
    parentRegion: 'los-angeles',
    cities: ['Santa Monica', 'Venice', 'Beverly Hills', 'West Hollywood', 'Brentwood', 'Westwood', 'Century City', 'Mar Vista'],
    description: 'The heart of LA wellness culture. From luxury Beverly Hills concierge doctors to accessible Santa Monica DEXA scans, the Westside has the highest concentration of cash-pay health services in Southern California.',
    clinics: westLAClinics,
  },
  {
    name: 'South Bay / Long Beach',
    slug: 'south-bay',
    parentRegion: 'los-angeles',
    cities: ['Manhattan Beach', 'Hermosa Beach', 'Redondo Beach', 'Torrance', 'Long Beach', 'Palos Verdes'],
    description: 'Beach city wellness for athletes and professionals. Strong focus on recovery, performance testing, and IV therapy for the active South Bay community.',
    clinics: southBayClinics,
  },
  {
    name: 'Central LA / Hollywood / Valley',
    slug: 'central-la',
    parentRegion: 'los-angeles',
    cities: ['Hollywood', 'DTLA', 'Pasadena', 'Glendale', 'Burbank', 'Sherman Oaks', 'Encino', 'Woodland Hills'],
    description: 'From Hollywood recovery studios to Valley wellness centers, Central LA and the San Fernando Valley offer diverse options for entertainment industry and local residents.',
    clinics: laCentralClinics,
  },
  {
    name: 'Orange County (North & Central)',
    slug: 'orange-county',
    parentRegion: 'orange-county',
    cities: ['Irvine', 'Newport Beach', 'Costa Mesa', 'Huntington Beach', 'Tustin', 'Fountain Valley'],
    description: 'Central and North Orange County wellness options. The Hydration Room chain dominates IV therapy; Irvine has DexaFit and UCI Sports Medicine for comprehensive testing.',
    clinics: orangeCountyClinics,
  },
  {
    name: 'South Orange County',
    slug: 'south-orange-county',
    parentRegion: 'orange-county',
    cities: ['Laguna Beach', 'Dana Point', 'San Clemente', 'Mission Viejo', 'Laguna Niguel', 'San Juan Capistrano'],
    description: 'South OC\'s beach communities have excellent IV therapy and wellness options. From Laguna Beach boutiques to Mission Viejo family-friendly centers, find cash-pay clinics throughout.',
    clinics: southOrangeClinics,
  },
  {
    name: 'San Diego (Central & Coastal)',
    slug: 'san-diego',
    parentRegion: 'san-diego',
    cities: ['Downtown San Diego', 'Hillcrest', 'La Jolla', 'Pacific Beach', 'Mission Valley', 'Del Mar'],
    description: 'Central San Diego offers world-class longevity diagnostics at Health Nucleus, VitaLounge IV therapy, and accessible DEXA testing. La Jolla is the hub for premium longevity services.',
    clinics: sanDiegoCentralClinics,
  },
  {
    name: 'North County San Diego',
    slug: 'north-county-san-diego',
    parentRegion: 'san-diego',
    cities: ['Carlsbad', 'Encinitas', 'Oceanside', 'Vista', 'San Marcos', 'Rancho Santa Fe', 'Solana Beach'],
    description: 'North County San Diego is a wellness hotspot. Exos in Carlsbad trains pro athletes, while Hydrate IV Bar and Optimum Human serve the surf and fitness community throughout.',
    clinics: sanDiegoNorthCountyClinics,
  },
  {
    name: 'Inland Empire',
    slug: 'inland-empire',
    parentRegion: 'inland-empire',
    cities: ['Riverside', 'San Bernardino', 'Ontario', 'Rancho Cucamonga', 'Temecula', 'Murrieta', 'Corona'],
    description: 'Growing wellness options in the Inland Empire. Restore has established presence, BodySpec visits regularly, and Loma Linda offers academic-quality sports medicine.',
    clinics: inlandEmpireClinics,
  },
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================
export function getRegionBySlug(slug: string): SoCalRegion | undefined {
  return SOCAL_REGIONS.find(r => r.slug === slug);
}

export function getClinicsByCategory(category: LocalClinic['category']): LocalClinic[] {
  return SOCAL_REGIONS.flatMap(r => r.clinics).filter(c => c.category === category);
}

export function getClinicsByRegion(regionSlug: string): LocalClinic[] {
  const region = getRegionBySlug(regionSlug);
  return region ? region.clinics : [];
}

export function getAllClinics(): LocalClinic[] {
  return SOCAL_REGIONS.flatMap(r => r.clinics);
}

export function getClinicCount(): number {
  return getAllClinics().length;
}

export function getCategoryStats(): Record<string, number> {
  const clinics = getAllClinics();
  return clinics.reduce((acc, clinic) => {
    acc[clinic.category] = (acc[clinic.category] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
}
