// North Carolina Dexa Clinics
// Generated by seo-page-factory/convert.py — verified+enriched data only

import { DexaClinic } from '@/lib/dexa-clinic-types';

export const northCarolinaDexaClinics: DexaClinic[] = [
  {
    id: "c_794d95f87b",
    name: "Triangle Wellness & Anti-Aging",
    slug: "triangle-wellness-anti-aging",
    address: "9104 Falls of Neuse Road, Suite 206",
    city: "Raleigh",
    state: "North Carolina",
    stateSlug: "north-carolina",
    citySlug: "raleigh",
    scanTypes: ["InBody"],
    priceRange: "$30/scan ($145 for a 6-pack)",
    membership: "Per-scan, no membership; 6-scan package at ~$24/scan",
    byAppointment: true,
    mobile: false,
    website: "https://trianglewellnessandantiaging.com/inbody/",
    phone: "(919) 703-0174",
    description: "North Raleigh wellness and anti-aging clinic offering InBody 770 body-composition analysis on a cash-pay basis. Single scans are $30, or $145 for a package of six to track muscle mass, body fat, and water distribution over time.",
    highlights: ["InBody 770 (research-grade BIA)", "$30 single scan", "6-scan package ~$24/scan", "Progress-tracking focus"],
    bestFor: "Budget-conscious clients who want repeatable InBody body-fat and muscle-mass tracking",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_b8737fdc9f",
    name: "Chain Effect",
    slug: "chain-effect",
    address: "2501 Blue Ridge Road, Suite G130",
    city: "Raleigh",
    state: "North Carolina",
    stateSlug: "north-carolina",
    citySlug: "raleigh",
    scanTypes: ["3D-scan", "VO2max"],
    priceRange: "$40-150/scan",
    membership: "Pricing bundled with PT/training; assessments included in transparent packages",
    byAppointment: true,
    mobile: false,
    website: "https://chaineffect.com/",
    phone: "(919) 594-1885",
    description: "Independent multidisciplinary performance and wellness studio in West Raleigh combining physical therapy, dietitians, and personal training with objective testing. Body-composition tracking uses Fit3D 3D body scanning alongside VO2 Max testing, velocity-based training, and CGM.",
    highlights: ["Fit3D 3D body-composition scanning", "VO2 Max testing", "DPT + dietitian + coach on staff", "Same-day appointments", "Cash-pay (out-of-network)"],
    bestFor: "Active clients who want 3D body-comp and VO2 Max paired with hands-on coaching",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_add3f628ab",
    name: "Gameday Men's Health Raleigh (Glenwood)",
    slug: "gameday-mens-health-raleigh-glenwood",
    address: "2626 Glenwood Avenue, Suite 170",
    city: "Raleigh",
    state: "North Carolina",
    stateSlug: "north-carolina",
    citySlug: "raleigh",
    scanTypes: ["InBody"],
    priceRange: "$40-150/scan",
    membership: "Per-visit; often bundled with weight-loss/TRT programs",
    byAppointment: true,
    mobile: false,
    website: "https://gamedaymenshealth.com/glenwood-nc",
    phone: "(919) 268-8886",
    description: "Men's health clinic on Glenwood Avenue in Raleigh offering clinician-guided InBody body-composition scans as part of its weight-loss and optimization services. Scans break down muscle mass, body fat, and hydration with a licensed provider reviewing results.",
    highlights: ["Clinician-guided InBody scan", "Weight-loss program context", "Provider result review", "Glenwood Avenue location"],
    bestFor: "Men pairing a body-comp scan with weight-loss or testosterone optimization care",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_d07a0297b7",
    name: "Fitnescity Raleigh",
    slug: "fitnescity-raleigh",
    address: "1107 Capital Blvd",
    city: "Raleigh",
    state: "North Carolina",
    stateSlug: "north-carolina",
    citySlug: "raleigh",
    scanTypes: ["DEXA", "RMR", "VO2max"],
    priceRange: "$215-285/test (DEXA from $230; VO2 Max $285; RMR+VO2 $405)",
    membership: "Insurance-free direct-pay; multi-scan and combo packages",
    byAppointment: true,
    mobile: false,
    website: "https://www.fitnescity.com/dexa-scan-in-raleigh-nc",
    phone: "(888) 348-6372",
    description: "National cash-pay testing network with a Raleigh booking on Capital Boulevard for VO2 Max and RMR metabolic testing; full-body DEXA body-composition scans are run through its partner facility about 15 minutes away in Cary. Online booking, no insurance, with an included results review.",
    highlights: ["Insurance-free / direct-pay", "VO2 Max + RMR in Raleigh", "DEXA via Cary partner", "Instant online booking", "Included physician/results review"],
    bestFor: "Clients wanting DEXA plus metabolic (RMR/VO2 Max) testing with transparent online booking",
    lastVerified: "2026-06-11",
  },
];

export function getNorthCarolinaDexaClinicsByCity(citySlug: string): DexaClinic[] {
  return northCarolinaDexaClinics.filter(c => c.citySlug === citySlug);
}

export function getNorthCarolinaDexaCitiesWithClinics(): { city: string; citySlug: string; count: number }[] {
  const map = new Map<string, { city: string; citySlug: string; count: number }>();
  for (const c of northCarolinaDexaClinics) {
    const e = map.get(c.citySlug) || { city: c.city, citySlug: c.citySlug, count: 0 };
    e.count++; map.set(c.citySlug, e);
  }
  return Array.from(map.values());
}
