// Georgia Dexa Clinics
// Generated by seo-page-factory/convert.py — verified+enriched data only

import { DexaClinic } from '@/lib/dexa-clinic-types';

export const georgiaDexaClinics: DexaClinic[] = [
  {
    id: "c_e697f36b92",
    name: "DexaFit Atlanta",
    slug: "dexafit-atlanta",
    address: "5553 Peachtree Rd Ste 180, Chamblee, GA 30341",
    city: "Atlanta",
    state: "Georgia",
    stateSlug: "georgia",
    citySlug: "atlanta",
    scanTypes: ["DEXA", "VO2max", "RMR"],
    priceRange: "$40-150/scan",
    membership: "Per-scan, no membership; HSA/FSA eligible",
    byAppointment: true,
    mobile: false,
    website: "https://www.atlanta.dexafit.com/",
    phone: "(404) 996-7129",
    description: "A dedicated body-composition studio in Chamblee (north Atlanta) that pairs a clinical DEXA scan with AI-enhanced digital reports rather than static paper printouts. Beyond DEXA, the studio also runs VO2 Max fitness tests and RMR metabolic analysis for clients tracking fat loss, muscle gain, and longevity markers.",
    highlights: ["AI-enhanced DEXA with an interactive digital report (visceral fat, ALMI, regional composition, bone density, biological age)", "Scan completed in roughly 5-7 minutes with instant results review", "Also offers VO2 Max and Resting Metabolic Rate testing on site", "HSA/FSA accepted for body-composition testing"],
    bestFor: "Longevity-minded clients who want an AI-enhanced DEXA plus metabolic and cardio fitness testing in one visit",
    rating: 4.9,
    reviewCount: 259,
    reviewSource: "Google",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_31d8745bb5",
    name: "Dexa Body Atlanta",
    slug: "dexa-body-atlanta",
    address: "3355 Lenox Rd Ste 750, Atlanta, GA 30326",
    city: "Atlanta",
    state: "Georgia",
    stateSlug: "georgia",
    citySlug: "atlanta",
    scanTypes: ["DEXA", "VO2max", "RMR"],
    priceRange: "$40-150/scan",
    membership: "Per-scan, no membership; all services HSA/FSA eligible",
    byAppointment: true,
    mobile: true,
    website: "https://dexabody.com/",
    phone: "(678) 585-2000",
    description: "A Buckhead-based testing studio (3355 Lenox Rd) that bundles DEXA body-composition analysis with an in-house registered dietitian and health coaching rather than a scan-and-go model. Dexa Body also runs a mobile testing unit and corporate-wellness programs, so it can bring DEXA, VO2 Max, and RMR testing on site for groups.",
    highlights: ["In-house registered dietitian and health coaching included with results", "Mobile testing unit available for corporate-wellness and group bookings", "Offers DEXA body composition, VO2 Max fitness, and Resting Metabolic Rate testing", "All services HSA/FSA eligible"],
    bestFor: "Clients who want DEXA results paired with dietitian-led coaching, or employers wanting on-site group testing",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_7279c5328d",
    name: "Live Lean Rx Atlanta",
    slug: "live-lean-rx-atlanta",
    address: "6100 Lake Forrest Dr Ste 125, Atlanta, GA 30328",
    city: "Atlanta",
    state: "Georgia",
    stateSlug: "georgia",
    citySlug: "atlanta",
    scanTypes: ["DEXA", "RMR", "VO2max"],
    priceRange: "$75/scan",
    membership: "Per-scan; package deals available (Longevity $275, Starting Line $425, 15% off 4+ tests)",
    byAppointment: true,
    mobile: false,
    website: "https://liveleanrx.com/locations/atlanta-georgia",
    phone: "(404) 884-5942",
    description: "A Sandy Springs (north Atlanta) performance-testing clinic with transparent a-la-carte pricing: DEXA at $75, RMR at $105, and VO2 Max at $125. It leans toward physique and athletic clients, completing the DEXA scan in under six minutes and emailing the raw data within hours, with optional multi-test longevity and performance packages.",
    highlights: ["Transparent per-scan pricing: DEXA $75, RMR $105, VO2 Max $125", "DEXA completed in under six minutes with same-day emailed data", "Multi-test packages (Longevity, Starting Line, Performance) plus 15% off 4+ tests", "Also offers food-sensitivity panels alongside body-composition testing"],
    bestFor: "Bulk/cut and athletic clients who want low-cost, repeatable DEXA tracking with package discounts",
    lastVerified: "2026-06-11",
  },
];

export function getGeorgiaDexaClinicsByCity(citySlug: string): DexaClinic[] {
  return georgiaDexaClinics.filter(c => c.citySlug === citySlug);
}

export function getGeorgiaDexaCitiesWithClinics(): { city: string; citySlug: string; count: number }[] {
  const map = new Map<string, { city: string; citySlug: string; count: number }>();
  for (const c of georgiaDexaClinics) {
    const e = map.get(c.citySlug) || { city: c.city, citySlug: c.citySlug, count: 0 };
    e.count++; map.set(c.citySlug, e);
  }
  return Array.from(map.values());
}
