// Massachusetts Dexa Clinics
// Generated by seo-page-factory/convert.py — verified+enriched data only

import { DexaClinic } from '@/lib/dexa-clinic-types';

export const massachusettsDexaClinics: DexaClinic[] = [
  {
    id: "c_084e292f1f",
    name: "DEXA Scan Boston",
    slug: "dexa-scan-boston",
    address: "1101 Beacon Street, Suite 8W-3, Brookline, MA 02446",
    city: "Boston",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    citySlug: "boston",
    scanTypes: ["DEXA"],
    priceRange: "$40-150/scan",
    membership: "Per-scan, no membership (first-scan 40% off with code FIRST40)",
    byAppointment: true,
    mobile: false,
    website: "https://www.dexascanboston.com/",
    description: "An independent, physician-run DEXA body-composition clinic in the Brookline/Beacon Street corridor, led by Harvard Medical School-trained clinicians. Focuses purely on DEXA for body fat percentage, lean mass, visceral fat, and regional composition rather than a multi-test menu.",
    highlights: ["Independent, physician-owned clinic (not a chain)", "Harvard Medical School-trained medical expertise", "DEXA-only focus: fat %, lean mass, visceral fat, bone density", "First-scan 40% off promotion with code FIRST40"],
    bestFor: "People who want a doctor-supervised, DEXA-only body-composition read",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_24a7819bff",
    name: "DexaFit Boston",
    slug: "dexafit-boston",
    address: "799 Concord Ave, Cambridge, MA 02138",
    city: "Boston",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    citySlug: "boston",
    scanTypes: ["DEXA", "RMR", "VO2max"],
    priceRange: "$40-150/scan",
    membership: "Per-scan, no membership",
    byAppointment: true,
    mobile: false,
    website: "https://www.boston.dexafit.com/",
    phone: "(339) 330-4131",
    description: "The Boston-area studio of the DexaFit chain, located in Cambridge and serving the greater Boston metro with clinical-grade DEXA, direct VO2 Max, and breath-analysis RMR metabolism testing. DEXA results are quoted at roughly +/-1% precision and benchmarked against age- and sex-matched reference data spanning four continents.",
    highlights: ["DEXA, VO2 Max, and RMR metabolism testing under one roof", "DEXA precision quoted at approximately +/-1%", "Direct VO2 Max measurement, not wearable estimation", "Online appointment booking, no membership required"],
    bestFor: "Athletes who want DEXA plus direct VO2 Max and metabolic testing",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_fd406fc63e",
    name: "Fitnescity (Boston)",
    slug: "fitnescity-boston",
    address: "1101 Beacon St, Brookline, MA 02446",
    city: "Boston",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    citySlug: "boston",
    scanTypes: ["DEXA", "BodPod", "RMR", "VO2max"],
    priceRange: "$155-180/scan",
    membership: "Per-scan; 4-scan DEXA bundle at $155/scan, single DEXA $180",
    byAppointment: true,
    mobile: false,
    website: "https://www.fitnescity.com/dexa-scan-in-boston-ma",
    phone: "+1 888-348-6372",
    description: "An insurance-free booking marketplace that routes Boston-area clients to partner hospitals, academic centers, and diagnostic facilities for DEXA, Bod Pod, RMR, and VO2 Max testing. Pricing is transparent and packaged, with a Brookline DEXA partner location and bundle discounts for repeat scans.",
    highlights: ["Marketplace across hospital, academic, and diagnostic partners", "Transparent posted pricing: single DEXA $180, 4-pack $155/scan", "Also offers Bod Pod, RMR, and VO2 Max booking", "DEXA + RMR combo packages available ($320)"],
    bestFor: "Comparison shoppers who want transparent, packaged scan pricing",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_5daa27dacc",
    name: "BodySpec",
    slug: "bodyspec-boston",
    city: "Boston",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    citySlug: "boston",
    scanTypes: ["DEXA"],
    priceRange: "$39.95/scan",
    membership: "Per-scan, no membership; flat pricing with no added fees",
    byAppointment: true,
    mobile: true,
    website: "https://www.bodyspec.com/dexa-scan-boston",
    description: "A national DEXA chain that serves Boston through a mix of dedicated storefronts, mobile van clinics, and neighborhood pop-up events rather than a single fixed lab. Known for low flat per-scan pricing and a fast in-and-out visit, with results delivered alongside an AI agent for interpreting body-fat, lean-mass, and visceral-fat numbers.",
    highlights: ["Mobile-van and pop-up model across Boston neighborhoods", "Flat $39.95/scan with no surprise fees", "In-and-out scan in under 15 minutes", "Over 300,000 clients served, 4.9-star average"],
    bestFor: "Budget-conscious scanners who want a quick, low-cost DEXA near them",
    rating: 4.9,
    reviewSource: "BodySpec (company-reported)",
    lastVerified: "2026-06-11",
  },
];

export function getMassachusettsDexaClinicsByCity(citySlug: string): DexaClinic[] {
  return massachusettsDexaClinics.filter(c => c.citySlug === citySlug);
}

export function getMassachusettsDexaCitiesWithClinics(): { city: string; citySlug: string; count: number }[] {
  const map = new Map<string, { city: string; citySlug: string; count: number }>();
  for (const c of massachusettsDexaClinics) {
    const e = map.get(c.citySlug) || { city: c.city, citySlug: c.citySlug, count: 0 };
    e.count++; map.set(c.citySlug, e);
  }
  return Array.from(map.values());
}
