// Tennessee Dexa Clinics
// Generated by seo-page-factory/convert.py — verified+enriched data only

import { DexaClinic } from '@/lib/dexa-clinic-types';

export const tennesseeDexaClinics: DexaClinic[] = [
  {
    name: "Transformat10n Lab",
    slug: "transformat10n-lab",
    address: "3228 Clarksville Pike, Nashville, TN 37218",
    city: "Nashville",
    state: "Tennessee",
    stateSlug: "tennessee",
    citySlug: "nashville",
    scanTypes: ["DEXA", "RMR", "VO2max", "BodPod", "3D-scan"],
    priceRange: "$159/DEXA scan",
    membership: "Per-scan cash-pay; FUS10N membership adds yearly test credits, consults, and quarterly reviews",
    byAppointment: true,
    mobile: false,
    website: "https://transformat10n.com/services/nashville-dexa-scan/",
    phone: "(615) 669-8220",
    description: "Independent Nashville exercise-physiology and performance lab offering whole-body DEXA composition (lean/bone/fat mass, ALMI, visceral fat) minutes from downtown. Cash-pay only with no insurance taken; HSA/FSA accepted, and a physician order is issued in-house per Tennessee state law.",
    highlights: ["Independent local physiology lab, not a chain", "Full performance menu: DEXA, RMR, VO2 max, BOD POD, Fit3D", "In-house physician order handles Tennessee prescription requirement", "Weekday and some weekend availability near downtown"],
    bestFor: "Athletes and health-optimizers who want DEXA bundled with metabolic and cardiorespiratory testing in one local lab",
    lastVerified: "2026-06-11",
  },
  {
    name: "Live Lean Rx Nashville",
    slug: "live-lean-rx-nashville",
    address: "4633 Trousdale Drive, Suite 210, Nashville, TN 37204",
    city: "Nashville",
    state: "Tennessee",
    stateSlug: "tennessee",
    citySlug: "nashville",
    scanTypes: ["DEXA", "RMR", "VO2max"],
    priceRange: "$150/DEXA scan",
    membership: "Per-scan; mix-and-match 4/6/12-pack bundles from $280",
    byAppointment: true,
    mobile: false,
    website: "https://liveleanrx.com/locations/nashville-tn",
    phone: "(615) 392-0858",
    description: "Independent metabolic-testing and body-composition clinic in south Nashville offering a 5-10 minute head-to-toe whole-body DEXA scan. Cash-pay single scans and discounted multi-scan bundles, with RMR and VO2 max testing available alongside.",
    highlights: ["Independent clinic with a dedicated metabolic-testing focus", "Quick 5-10 minute whole-body DXA composition scan", "Discounted 4/6/12-scan progress-tracking bundles", "Pairs DEXA with RMR and VO2 max under one roof"],
    bestFor: "People tracking body-composition progress over time who want bundled repeat scans plus metabolic testing",
    lastVerified: "2026-06-11",
  },
  {
    name: "Fitnescity (Nashville)",
    slug: "fitnescity-nashville",
    address: "3228 Clarksville Pike, Nashville, TN 37218",
    city: "Nashville",
    state: "Tennessee",
    stateSlug: "tennessee",
    citySlug: "nashville",
    scanTypes: ["DEXA", "RMR", "VO2max"],
    priceRange: "$215/DEXA scan",
    membership: "Per-scan; volume packages ($200-215/scan for 2-4 scans)",
    byAppointment: true,
    mobile: false,
    website: "https://www.fitnescity.com/dexa-scan-in-nashville-tn",
    phone: "(888) 348-6372",
    description: "National cash-pay booking platform that schedules DEXA body-composition scans into vetted fixed Nashville-area facilities, never mobile units. Coordinates the Tennessee-required physician order remotely through a national network of board-certified doctors.",
    highlights: ["Online booking with remote physician-order coordination", "Scans run only in fixed, high-quality facilities", "Volume discounts on 2-4 scan packages", "Reports cover fat, lean, visceral fat, and bone density"],
    bestFor: "Buyers who want a turnkey online booking that handles the Tennessee prescription requirement for them",
    lastVerified: "2026-06-11",
  },
  {
    name: "BodySpec",
    slug: "bodyspec-nashville",
    city: "Nashville",
    state: "Tennessee",
    stateSlug: "tennessee",
    citySlug: "nashville",
    scanTypes: ["DEXA"],
    priceRange: "$39.95-79/scan",
    membership: "Per-scan, no membership",
    byAppointment: true,
    mobile: true,
    website: "https://www.bodyspec.com/dexa-scan-nashville",
    description: "National mobile-DEXA provider that runs medical-grade body-composition scans from vans at neighborhood pop-up events rather than a fixed clinic. Known for the lowest cash-pay pricing in the category; Nashville is on a launch waitlist as of June 2026 (verify current availability before booking).",
    highlights: ["Lowest published cash-pay DEXA pricing (from $39.95)", "Mobile van and pop-up event model", "Over 400,000 scans performed nationally", "No membership required; per-scan booking"],
    bestFor: "Budget-focused scanners who can catch a mobile pop-up once BodySpec launches in Nashville",
    lastVerified: "2026-06-11",
  },
];

export function getTennesseeDexaClinicsByCity(citySlug: string): DexaClinic[] {
  return tennesseeDexaClinics.filter(c => c.citySlug === citySlug);
}

export function getTennesseeDexaCitiesWithClinics(): { city: string; citySlug: string; count: number }[] {
  const map = new Map<string, { city: string; citySlug: string; count: number }>();
  for (const c of tennesseeDexaClinics) {
    const e = map.get(c.citySlug) || { city: c.city, citySlug: c.citySlug, count: 0 };
    e.count++; map.set(c.citySlug, e);
  }
  return Array.from(map.values());
}
