// Nevada Dexa Clinics
// Generated by seo-page-factory/convert.py — verified+enriched data only

import { DexaClinic } from '@/lib/dexa-clinic-types';

export const nevadaDexaClinics: DexaClinic[] = [
  {
    id: "c_cd41220e5f",
    name: "Project Wellbeing",
    slug: "project-wellbeing",
    address: "7155 S. Buffalo Dr., Suite 165, Las Vegas, NV 89113",
    city: "Las Vegas",
    state: "Nevada",
    stateSlug: "nevada",
    citySlug: "las-vegas",
    scanTypes: ["DEXA", "VO2max"],
    priceRange: "$40-150/scan",
    membership: "Per-scan, no membership; repeat-friendly package pricing",
    byAppointment: true,
    mobile: false,
    website: "https://www.projectwellbeing.co/dexa-scan-las-vegas",
    phone: "(702) 525-7791",
    description: "An independent cash-pay sports-science and wellness clinic near the 215 Beltway on S. Buffalo Dr., positioning DEXA as the gold standard over InBody and bioimpedance. Scans come with an optional one-on-one medical consult to interpret fat, lean, and bone results and build a nutrition and training plan.",
    highlights: ["Cash-pay with no insurance roadblock to results", "Same-day scheduling available; most clients scanned within a week", "Optional 1-on-1 with medical team to interpret results", "Also offers VO2 max testing, bloodwork, and movement screening"],
    bestFor: "Cash-pay athletes wanting DEXA plus a clinician walkthrough",
    rating: 5.0,
    reviewCount: 81,
    reviewSource: "Google",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_de67f226aa",
    name: "DexaFit Las Vegas",
    slug: "dexafit-las-vegas",
    address: "6883 W. Charleston Blvd, Suite A, Las Vegas, NV 89117",
    city: "Las Vegas",
    state: "Nevada",
    stateSlug: "nevada",
    citySlug: "las-vegas",
    scanTypes: ["DEXA", "RMR", "VO2max", "3D-scan"],
    priceRange: "$139/scan",
    membership: "Per-scan ($139 DEXA) or bundles; Premium DEXA+RMR $269, MAX DEXA+VO2 $289, Elite $419",
    byAppointment: true,
    mobile: false,
    website: "https://www.dexafitlv.com",
    phone: "(702) 833-0430",
    description: "The Las Vegas franchise of the national DexaFit chain on W. Charleston Blvd, bundling DEXA with metabolic and cardio testing under one roof. A single DEXA scan is $139, with Styku 3D body scans and red-light therapy available alongside multi-test health packages.",
    highlights: ["DEXA $139, RMR $149, VO2 max $179, Styku 3D $65 a la carte", "Bundle packages from $269 (Premium) to $419 (Elite)", "Styku 3D body scan included free with packages", "Red Light Therapy unlimited membership $199/mo, no contract"],
    bestFor: "One-stop DEXA plus RMR and VO2 max metabolic workup",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_b2069b81a7",
    name: "Las Vegas Medical Institute",
    slug: "las-vegas-medical-institute",
    address: "851 S Rampart Blvd #220, Las Vegas, NV 89145",
    city: "Las Vegas",
    state: "Nevada",
    stateSlug: "nevada",
    citySlug: "las-vegas",
    scanTypes: ["DEXA"],
    priceRange: "$40-150/scan",
    membership: "Per-scan, or included in age-management / BHRT membership programs",
    byAppointment: true,
    mobile: false,
    equipment: "GE Lunar",
    website: "https://lasvegasmedicalinstitute.com/las-vegas-nv/body-composition-analysis-dxa/",
    phone: "(725) 258-5864",
    description: "A physician-staffed independent age-management and BHRT clinic on S. Rampart Blvd that runs total-body composition analysis on a research-grade GE Lunar iDXA scanner. The 6-8 minute scan is offered standalone or folded into its comprehensive age-management and hormone programs.",
    highlights: ["Research-grade GE Lunar iDXA scanner", "Typical scan time only 6-8 minutes", "MD-staffed clinic (anti-aging / hormone focus)", "DEXA available standalone or in membership programs"],
    bestFor: "Research-grade GE Lunar DXA inside a physician-led clinic",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_ddb5a1c918",
    name: "Fitnescity (Las Vegas Network)",
    slug: "fitnescity-las-vegas",
    address: "Spring Valley, Las Vegas, NV",
    city: "Las Vegas",
    state: "Nevada",
    stateSlug: "nevada",
    citySlug: "las-vegas",
    scanTypes: ["DEXA", "RMR", "VO2max"],
    priceRange: "$40-150/scan",
    membership: "Per-test booking, no membership; physician order coordinated when needed",
    byAppointment: true,
    mobile: false,
    website: "https://www.fitnescity.com/dexa-scan-in-las-vegas-nv",
    description: "Fitnescity is a national insurance-free booking platform that schedules DEXA, RMR, and VO2 max tests through partner facilities in the Spring Valley area of Las Vegas. It coordinates any required physician order remotely and delivers results to an online dashboard within two business days, conducting tests only in fixed facilities, never mobile units.",
    highlights: ["Insurance-free marketplace; partners with hospitals and diagnostic centers", "Coordinates required physician order remotely, no doctor visit", "Results to online dashboard within two business days", "Tests run in fixed facilities only, never mobile units"],
    bestFor: "Booking DEXA plus metabolic tests with an order handled for you",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_2cd3e93fb6",
    name: "SDMI (Steinberg Diagnostic Medical Imaging)",
    slug: "sdmi-las-vegas",
    address: "2950 S Maryland Pkwy, Las Vegas, NV 89109",
    city: "Las Vegas",
    state: "Nevada",
    stateSlug: "nevada",
    citySlug: "las-vegas",
    scanTypes: ["DEXA"],
    priceRange: "$90-200/scan",
    membership: "Per-scan; doctor's order required before scheduling",
    byAppointment: true,
    mobile: false,
    website: "https://www.sdmi-lv.com/services/dexa-scan",
    phone: "(702) 732-6000",
    description: "An ACR-accredited independent diagnostic imaging group with roughly a dozen locations across the Las Vegas Valley, including Summerlin, Centennial Hills, and Henderson. Its DEXA scans report both bone mineral density and total body composition and fat content, though a physician's order is required before scheduling.",
    highlights: ["ACR-accredited (American College of Radiology)", "~12 locations across the Las Vegas Valley and Henderson", "Reports body composition and fat content, not bone density alone", "Requires a doctor's order to book"],
    bestFor: "Accredited imaging-grade DEXA with valley-wide locations",
    lastVerified: "2026-06-11",
  },
];

export function getNevadaDexaClinicsByCity(citySlug: string): DexaClinic[] {
  return nevadaDexaClinics.filter(c => c.citySlug === citySlug);
}

export function getNevadaDexaCitiesWithClinics(): { city: string; citySlug: string; count: number }[] {
  const map = new Map<string, { city: string; citySlug: string; count: number }>();
  for (const c of nevadaDexaClinics) {
    const e = map.get(c.citySlug) || { city: c.city, citySlug: c.citySlug, count: 0 };
    e.count++; map.set(c.citySlug, e);
  }
  return Array.from(map.values());
}
