// Colorado Dexa Clinics
// Generated by seo-page-factory/convert.py — verified+enriched data only

import { DexaClinic } from '@/lib/dexa-clinic-types';

export const coloradoDexaClinics: DexaClinic[] = [
  {
    name: "Body Fat USA",
    slug: "body-fat-usa",
    address: "1776 S Jackson St #1111, Denver, CO 80210",
    city: "Denver",
    state: "Colorado",
    stateSlug: "colorado",
    citySlug: "denver",
    scanTypes: ["DEXA", "RMR"],
    priceRange: "$85/scan",
    membership: "Per-scan, no membership (DEXA $85, RMR $100, DEXA+RMR combo $175)",
    byAppointment: true,
    mobile: false,
    equipment: "GE Lunar",
    website: "https://www.bodyfatusa.com/",
    phone: "(303) 758-9552",
    description: "An independent, locally owned body-composition testing center in Denver's University neighborhood that explicitly positions itself as a testing facility rather than a coaching program or supplement company. Scans run on a GE Lunar Prodigy densitometer with results delivered within minutes of the appointment.",
    highlights: ["Independent local business, not a chain", "GE Lunar Prodigy densitometer (research-grade reference method)", "DEXA $85, RMR $100, combo $175 with no upsell on coaching or supplements", "Results within ~5 minutes; scan takes 6-10 minutes"],
    bestFor: "Objective, no-upsell body-fat and lean-mass testing on research-grade hardware",
    lastVerified: "2026-06-11",
  },
  {
    name: "Live Lean Rx Denver South",
    slug: "live-lean-rx-denver-south",
    address: "9350 E Arapahoe Rd, Suite 205, Greenwood Village, CO 80112",
    city: "Denver",
    state: "Colorado",
    stateSlug: "colorado",
    citySlug: "denver",
    scanTypes: ["DEXA", "RMR", "VO2max"],
    priceRange: "$75/scan",
    membership: "Per-scan ($75 DEXA); bundled packages (Starting Line, Performance, Live Leaner, Longevity) combine scans with nutrition consulting",
    byAppointment: true,
    mobile: false,
    website: "https://liveleanrx.com/locations/denver-south-colorado",
    phone: "(303) 335-0784",
    description: "A metabolic-testing studio in the Denver South / Greenwood Village area offering a 5-10 minute whole-body DXA alongside VO2 Max, RMR, and food-sensitivity panels. Part of a 20+ location regional chain that bundles scans with optional nutrition coaching.",
    highlights: ["DEXA, VO2 Max, RMR, and food-sensitivity testing under one roof", "$75 single DEXA body-composition scan", "5-10 minute whole-body DXA with segmental breakdown", "Tiered packages pairing tests with nutrition consults"],
    bestFor: "Pairing a DEXA scan with VO2 Max and RMR metabolic testing in one visit",
    lastVerified: "2026-06-11",
  },
  {
    name: "BodySpec",
    slug: "bodyspec",
    address: "250 Steele St, Suite 350, Denver, CO 80206",
    city: "Denver",
    state: "Colorado",
    stateSlug: "colorado",
    citySlug: "denver",
    scanTypes: ["DEXA"],
    priceRange: "$39.95/scan",
    membership: "Per-scan from $39.95, no doctor referral; package/multi-scan pricing available",
    byAppointment: true,
    mobile: true,
    website: "https://www.bodyspec.com/dexa-scan-denver",
    phone: "(310) 601-8184",
    description: "A high-volume DEXA chain that reaches Denver through a dedicated storefront plus mobile van clinics and neighborhood pop-up events, making it the most accessible low-cost option in the metro. Every scan includes AI-driven analysis and results in under 15 minutes with no doctor referral required.",
    highlights: ["Starting at $39.95/scan, among the cheapest DEXA in Denver", "Storefront plus mobile vans and pop-up events across the metro", "No doctor referral needed; book directly online", "In and out in under 15 minutes; 600,000+ scans performed company-wide"],
    bestFor: "Lowest-cost DEXA and mobile/pop-up convenience without a referral",
    lastVerified: "2026-06-11",
  },
  {
    name: "DexaFit Denver",
    slug: "dexafit-denver",
    address: "1143 Auraria Parkway #204, Denver, CO 80204",
    city: "Denver",
    state: "Colorado",
    stateSlug: "colorado",
    citySlug: "denver",
    scanTypes: ["DEXA", "VO2max", "RMR"],
    priceRange: "$40-150/scan",
    membership: "Per-scan; HSA/FSA eligible",
    byAppointment: true,
    mobile: false,
    equipment: "GE Lunar",
    website: "https://www.denver.dexafit.com/",
    phone: "(720) 730-4004",
    description: "The Denver franchise of the DexaFit chain, located on Auraria Parkway near downtown, offering AI-enhanced DEXA body-composition scans alongside VO2 Max and RMR testing. Every assessment pairs a 5-minute scan with a one-on-one consultation and access to dietitians and health coaches.",
    highlights: ["DEXA, VO2 Max, and RMR metabolism testing at one location", "5-minute scan with one-on-one results consultation", "HSA/FSA eligible, no insurance billing", "Access to registered dietitians and board-certified health coaches"],
    bestFor: "Guided body-composition testing with a consultation and coaching add-ons",
    lastVerified: "2026-06-11",
  },
  {
    name: "Fitnescity (Denver)",
    slug: "fitnescity-denver",
    address: "8560 Northfield Blvd, Denver, CO 80238",
    city: "Denver",
    state: "Colorado",
    stateSlug: "colorado",
    citySlug: "denver",
    scanTypes: ["DEXA", "RMR", "VO2max"],
    priceRange: "$235/scan",
    membership: "Per-scan ($235 single, $210-225/scan in multi-scan packages; DEXA + bone density comprehensive $435)",
    byAppointment: true,
    mobile: false,
    equipment: "GE Lunar",
    website: "https://www.fitnescity.com/dexa-scan-in-denver-co",
    phone: "(888) 348-6372",
    description: "A booking marketplace rather than its own clinic, Fitnescity routes Denver clients to a partner imaging center on Northfield Blvd for DEXA body-composition scans with physician review included. Results are returned within two business days through a secure online dashboard.",
    highlights: ["Marketplace booking into a partner imaging center, not a standalone studio", "Physician's order included when needed", "Results within two business days via secure dashboard", "Also books RMR and VO2 Max; comprehensive DEXA + bone-density option at $435"],
    bestFor: "Clinical-grade DEXA at a partner imaging center with included physician review",
    lastVerified: "2026-06-11",
  },
];

export function getColoradoDexaClinicsByCity(citySlug: string): DexaClinic[] {
  return coloradoDexaClinics.filter(c => c.citySlug === citySlug);
}

export function getColoradoDexaCitiesWithClinics(): { city: string; citySlug: string; count: number }[] {
  const map = new Map<string, { city: string; citySlug: string; count: number }>();
  for (const c of coloradoDexaClinics) {
    const e = map.get(c.citySlug) || { city: c.city, citySlug: c.citySlug, count: 0 };
    e.count++; map.set(c.citySlug, e);
  }
  return Array.from(map.values());
}
