// Washington Dexa Clinics
// Generated by seo-page-factory/convert.py — verified+enriched data only

import { DexaClinic } from '@/lib/dexa-clinic-types';

export const washingtonDexaClinics: DexaClinic[] = [
  {
    id: "c_c62fb447b8",
    name: "Seattle Performance Medicine",
    slug: "seattle-performance-medicine",
    address: "19930 Ballinger Way NE, Second Floor, Shoreline, WA 98155",
    city: "Seattle",
    state: "Washington",
    stateSlug: "washington",
    citySlug: "seattle",
    scanTypes: ["DEXA", "VO2max", "RMR"],
    priceRange: "$40-150/scan",
    membership: "Per-scan, no membership; bookable by the public via the SPM app without being a patient",
    byAppointment: true,
    mobile: false,
    website: "https://coopermetabolic.com/seattle-performance-medicine/",
    phone: "(206) 632-4575",
    description: "An independent performance-medicine clinic (part of the Cooper Center for Metabolism) in Shoreline, just north of Seattle, that opens its physiology lab to the general public. Members of the public can self-book DEXA body-composition, VO2max, and resting metabolic rate testing through the SPM app without needing to be an existing patient.",
    highlights: ["Independent physician-led clinic, not a national scan chain", "DEXA body composition paired with Cosmed VO2max and RMR testing under one roof", "Self-scheduling for the public through the SPM app", "Staffed by an exercise physiologist for coaching follow-up"],
    bestFor: "Athletes wanting DEXA alongside clinical VO2max and metabolic testing",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_3f77cd47c0",
    name: "Nomad Fit Lab",
    slug: "nomad-fit-lab",
    city: "Seattle",
    state: "Washington",
    stateSlug: "washington",
    citySlug: "seattle",
    scanTypes: ["DEXA"],
    priceRange: "$59.95/scan",
    membership: "Per-scan $59.95; 3-pack $149.95 (~$50/scan); annual monthly plan $39.95/mo with rollover scans",
    byAppointment: true,
    mobile: true,
    website: "https://www.nomadfitlab.com/seattle-dexa-scans/",
    phone: "(360) 488-9870",
    description: "An independent mobile DEXA operator serving Seattle and King County (with additional coverage in Washington and Arizona), bringing the scanner to partner gyms and pop-up locations rather than a single fixed studio. A full-body scan takes under 15 minutes and reports body fat, lean muscle mass, and bone mineral density with results emailed within minutes.",
    highlights: ["Independent mobile unit serving Seattle / King County", "One-time scan $59.95; 3-pack $149.95; $39.95/mo membership with rollover", "Full-body scan in under 15 minutes, results within minutes", "Reports body fat, lean mass, and bone mineral density"],
    bestFor: "Convenient per-scan body-fat and lean-mass tracking near you",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_3976848746",
    name: "DexaFit Seattle",
    slug: "dexafit-seattle",
    address: "111 W John St, Ste 203A, Seattle, WA 98119",
    city: "Seattle",
    state: "Washington",
    stateSlug: "washington",
    citySlug: "seattle",
    scanTypes: ["DEXA", "VO2max", "RMR", "3D-scan"],
    priceRange: "$150/scan",
    membership: "Per-scan, no membership; assessment bundles available",
    byAppointment: true,
    mobile: false,
    website: "https://www.seattle.dexafit.com/dexa-scan",
    phone: "(206) 268-0700",
    description: "The DexaFit franchise location for the Seattle area (operated locally as Body Science Coaching), running a stationary research-grade DEXA scanner in the Queen Anne / lower Queen Anne area, with a second DEXA-only site in Renton. Beyond DEXA body composition it layers on AI-enhanced reporting plus VO2max, RMR, Proteus 3D power, and grip-strength testing.",
    highlights: ["National DexaFit chain location; stationary fixed scanner", "DEXA body composition with AI-enhanced reporting at $150/scan", "Also offers VO2max, RMR, Proteus 3D power, and grip-strength testing", "Second DEXA-only location in Renton (332 Burnett Ave S)"],
    bestFor: "A full longevity testing suite at a fixed Seattle studio",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_2ae71134cd",
    name: "BodySpec - Seattle (South Lake Union)",
    slug: "bodyspec-seattle",
    address: "2300 7th Ave, Seattle, WA 98121",
    city: "Seattle",
    state: "Washington",
    stateSlug: "washington",
    citySlug: "seattle",
    scanTypes: ["DEXA"],
    priceRange: "$39/scan",
    membership: "Per-scan starting at $39; multi-scan packages and memberships available",
    byAppointment: true,
    mobile: true,
    website: "https://www.bodyspec.com/dexa-scan-seattle",
    description: "BodySpec runs the lowest-cost DEXA option in Seattle, with a fixed South Lake Union storefront plus a Bellevue location and mobile vans that pop up at gyms across the city. Scans start at $39, require no doctor's referral, and are HSA/FSA eligible.",
    highlights: ["Among the lowest DEXA prices in Seattle, starting at $39/scan", "Fixed South Lake Union storefront plus mobile vans across the metro", "No doctor's referral required to book", "HSA/FSA eligible"],
    bestFor: "Budget-friendly DEXA body-fat scans without a referral",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_7ca0761021",
    name: "Fitnescity - Seattle DEXA",
    slug: "fitnescity-seattle",
    address: "122 SW 156th St, Burien, WA 98166",
    city: "Seattle",
    state: "Washington",
    stateSlug: "washington",
    citySlug: "seattle",
    scanTypes: ["DEXA", "VO2max", "RMR", "BodPod"],
    priceRange: "$170-195/scan",
    membership: "Per-scan $195; 2 scans $370 ($185/scan); 3 scans $540 ($180/scan); 4 scans $680 ($170/scan)",
    byAppointment: true,
    mobile: false,
    website: "https://www.fitnescity.com/dexa-scan-in-seattle-wa",
    phone: "(888) 348-6372",
    description: "Fitnescity is a national testing marketplace that books cash-pay DEXA body-composition scans at partner facilities, with its Seattle-area DEXA site in Burien and additional Bellevue testing. It also brokers VO2max, RMR, BodPod, and calcium-score testing, and handles the prescription that Washington requires for a DEXA scan.",
    highlights: ["National marketplace booking at vetted partner labs", "DEXA from $195, dropping to $170/scan in 4-packs", "Also brokers VO2max, RMR, BodPod, and calcium-score tests", "Handles the Washington-required prescription on the client's behalf"],
    bestFor: "Booking DEXA plus add-on metabolic tests through one marketplace",
    lastVerified: "2026-06-11",
  },
];

export function getWashingtonDexaClinicsByCity(citySlug: string): DexaClinic[] {
  return washingtonDexaClinics.filter(c => c.citySlug === citySlug);
}

export function getWashingtonDexaCitiesWithClinics(): { city: string; citySlug: string; count: number }[] {
  const map = new Map<string, { city: string; citySlug: string; count: number }>();
  for (const c of washingtonDexaClinics) {
    const e = map.get(c.citySlug) || { city: c.city, citySlug: c.citySlug, count: 0 };
    e.count++; map.set(c.citySlug, e);
  }
  return Array.from(map.values());
}
