// Washington DC Dexa Clinics
// Generated by seo-page-factory/convert.py — verified+enriched data only

import { DexaClinic } from '@/lib/dexa-clinic-types';

export const washingtonDcDexaClinics: DexaClinic[] = [
  {
    id: "c_132f2380cc",
    name: "GWU Metabolism and Exercise Testing Laboratory",
    slug: "gwu-metabolism-exercise-testing-lab",
    address: "950 New Hampshire Avenue NW, Washington, DC 20037",
    city: "Washington",
    state: "Washington DC",
    stateSlug: "washington-dc",
    citySlug: "washington",
    scanTypes: ["DEXA", "RMR", "VO2max", "InBody"],
    priceRange: "$200/scan (DXA); $240 DXA+RMR package",
    membership: "Per-scan, no membership; military/first-responder/student discounts",
    byAppointment: true,
    mobile: false,
    website: "https://bodycomposition.gwu.edu/tests-services",
    phone: "(202) 994-2654",
    description: "A university exercise-physiology lab inside George Washington University's Milken Institute School of Public Health that opens its research-grade testing to the public. Beyond DXA body composition it runs RMR, VO2max, InBody and lactate-threshold testing, all cash-pay with no insurance accepted.",
    highlights: ["Academic exercise-physiology lab open to the general public", "Single DXA body-composition scan $200; DXA+RMR package $240", "Also offers VO2max ($165), RMR ($100) and InBody ($100) testing", "Discounts for military, first responders and students"],
    bestFor: "Research-grade body composition from a university lab",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_c85c5d9ba6",
    name: "Composition ID",
    slug: "composition-id-washington-dc",
    address: "760 N St NW, Washington, DC 20001",
    city: "Washington",
    state: "Washington DC",
    stateSlug: "washington-dc",
    citySlug: "washington",
    scanTypes: ["DEXA", "RMR", "VO2max"],
    priceRange: "$150/scan (single); bundle discounts available",
    membership: "Per-scan, no membership; value bundles for repeat scans",
    byAppointment: true,
    mobile: false,
    website: "https://www.compositionid.com/locations/washington-dc/services/dexa-scan/",
    phone: "(202) 813-3399",
    description: "A dedicated body-composition and performance-testing studio in the Shaw neighborhood, billed as DC's first exercise and sports-performance testing lab. The fixed studio pairs DEXA scans with RMR, VO2max and nutrition coaching, and also runs a 'Scan Van' mobile DEXA service across the DMV.",
    highlights: ["Fixed studio at 760 N St NW in Shaw", "Single DEXA scan $150 with discounts on multi-scan bundles", "Also offers RMR and VO2 Max testing plus nutrition coaching", "Operates a 'Scan Van' mobile DEXA option in addition to the studio"],
    bestFor: "Tracking body composition over time with coaching",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_5daa27dacc",
    name: "BodySpec",
    slug: "bodyspec-washington-dc",
    city: "Washington",
    state: "Washington DC",
    stateSlug: "washington-dc",
    citySlug: "washington",
    scanTypes: ["DEXA", "RMR"],
    priceRange: "$39.95/scan",
    membership: "Per-scan, no membership; no added fees",
    byAppointment: false,
    mobile: true,
    website: "https://www.bodyspec.com/dexa-scan-washington-dc",
    description: "A national mobile-DEXA chain that runs van clinics and neighborhood pop-up events rather than a fixed studio, with each scan completed in under 15 minutes. BodySpec is actively expanding into the Washington DC area via a waitlist and is among the most affordable body-composition options at $39.95 per scan.",
    highlights: ["Mobile van and pop-up DEXA model, no fixed DC address", "Scans start at $39.95 with no added fees", "Each scan completed in under 15 minutes", "Expanding into Washington DC via waitlist (pre-launch)"],
    bestFor: "Lowest-cost mobile DEXA via pop-up events",
    lastVerified: "2026-06-11",
  },
  {
    id: "c_8504d1de13",
    name: "Fitnescity",
    slug: "fitnescity-washington-dc",
    city: "Washington",
    state: "Washington DC",
    stateSlug: "washington-dc",
    citySlug: "washington",
    scanTypes: ["DEXA", "RMR", "VO2max", "BodPod"],
    priceRange: "$180-255/scan",
    membership: "Per-scan, no membership; insurance-free",
    byAppointment: true,
    mobile: false,
    website: "https://www.fitnescity.com/dexa-scan-in-washington-dc",
    description: "A booking marketplace that partners with hospitals, diagnostic centers and academic institutions to place cash-pay DEXA scans at fixed Washington DC-area facilities, never mobile units. For DC clients it also coordinates the physician order the District requires, then delivers results through a personalized dashboard with a follow-up call.",
    highlights: ["Marketplace routing to fixed partner facilities (no mobile units)", "Single DEXA scan $180-255 depending on location", "Coordinates the physician order DC requires for a DEXA scan", "Also brokers RMR, VO2max and Bod Pod testing"],
    bestFor: "Booking a DEXA scan plus the required physician order in one step",
    lastVerified: "2026-06-11",
  },
];

export function getWashingtonDcDexaClinicsByCity(citySlug: string): DexaClinic[] {
  return washingtonDcDexaClinics.filter(c => c.citySlug === citySlug);
}

export function getWashingtonDcDexaCitiesWithClinics(): { city: string; citySlug: string; count: number }[] {
  const map = new Map<string, { city: string; citySlug: string; count: number }>();
  for (const c of washingtonDcDexaClinics) {
    const e = map.get(c.citySlug) || { city: c.city, citySlug: c.citySlug, count: 0 };
    e.count++; map.set(c.citySlug, e);
  }
  return Array.from(map.values());
}
