// Florida Dexa Clinics
// Generated by seo-page-factory/convert.py — verified+enriched data only

import { DexaClinic } from '@/lib/dexa-clinic-types';

export const floridaDexaClinics: DexaClinic[] = [
  {
    name: "Infinity Sports Institute",
    slug: "infinity-sports-institute",
    address: "163 NE 24th St, Miami, FL 33137",
    city: "Miami",
    state: "Florida",
    stateSlug: "florida",
    citySlug: "miami",
    scanTypes: ["DEXA", "VO2max", "RMR"],
    priceRange: "$100-150/scan",
    membership: "Per-scan, no membership; packages valid 12 months",
    byAppointment: true,
    mobile: false,
    website: "https://infinitysi.com/",
    phone: "(786) 591-7586",
    description: "An independent Midtown Miami sports-science and sports-medicine lab that bills itself as the only true sport-science lab in the city, pairing DEXA body composition with VO2 max, RMR and DARI motion-capture testing. Geared toward athletes and performance-minded clients who want gold-standard diagnostics rather than a quick med-spa scan.",
    highlights: ["Full sport-science lab: DEXA, VO2 max, RMR and DARI motion capture under one roof", "DEXA reports body fat %, lean mass, visceral fat and bone density at 1-2% margin of error", "Located in Midtown/Edgewater Miami (163 NE 24th St) with extended weekday hours", "Results paired with sports-medicine and nutrition coaching"],
    bestFor: "Athletes wanting performance-grade body composition plus VO2/RMR testing",
    lastVerified: "2026-06-11",
  },
  {
    name: "PURE Executive Health & Wellness",
    slug: "pure-executive-health-wellness",
    address: "4100 Salzedo St, Suite 4, Coral Gables, FL 33146",
    city: "Miami",
    state: "Florida",
    stateSlug: "florida",
    citySlug: "miami",
    scanTypes: ["DEXA"],
    priceRange: "$40-150/scan",
    membership: "Per-scan; rescan recommended every 3-6 months",
    byAppointment: true,
    mobile: false,
    website: "https://purehealthmiami.com/body-composition-scan/",
    phone: "(786) 227-6811",
    description: "An independent concierge medicine and executive-health practice in Coral Gables that offers a quick, painless DEXA body-composition scan breaking weight down into bone, fat and muscle. The clinic positions the scan as a longitudinal tracking tool, recommending a repeat every three to six months to monitor trends.",
    highlights: ["Independent concierge / executive-health practice in Coral Gables", "DEXA breaks body weight into bone, fat and lean muscle", "Six-minute scan framed as a recurring health-tracking metric", "Same Coral Gables facility used by national booking networks for DEXA"],
    bestFor: "Executive-health clients tracking body composition over time",
    lastVerified: "2026-06-11",
  },
  {
    name: "My Health & Wellness Medical Group",
    slug: "my-health-wellness-medical-group",
    address: "1717 N Bayshore Dr, Suite R230, Miami, FL 33132",
    city: "Miami",
    state: "Florida",
    stateSlug: "florida",
    citySlug: "miami",
    scanTypes: ["DEXA"],
    priceRange: "$40-150/scan",
    membership: "Per-scan, no membership",
    byAppointment: true,
    mobile: false,
    website: "https://mhw-medicalgroup.com/services/dexa-body-composition-scan-in-miami/",
    phone: "(305) 720-2288",
    description: "An independent medical-wellness group in the Edgewater/Downtown Miami corridor offering DEXA body-composition scanning alongside direct primary care, medical weight loss and hormone therapy. The regional DEXA readout maps fat and muscle by body region and results are reviewed roughly ten minutes after the scan.",
    highlights: ["Independent physician-led wellness clinic on N Bayshore Dr", "Regional DEXA analysis of fat and muscle by body area", "DEXA pairs with medical weight-loss and primary-care programs", "Results available within about ten minutes of the scan"],
    bestFor: "Medical weight-loss patients wanting a physician-reviewed DEXA",
    lastVerified: "2026-06-11",
  },
  {
    name: "University of Miami Fitness Laboratory",
    slug: "university-of-miami-fitness-laboratory",
    address: "1241 Dickinson Dr, Coral Gables, FL 33146",
    city: "Miami",
    state: "Florida",
    stateSlug: "florida",
    citySlug: "miami",
    scanTypes: ["BodPod", "VO2max", "RMR"],
    priceRange: "$35-110/test",
    membership: "Per-test; non-member, member and student tiers",
    byAppointment: true,
    mobile: false,
    website: "https://wellness.studentaffairs.miami.edu/services-and-spaces/fitness-services/fitness-assessments/index.html",
    phone: "(305) 284-8500",
    description: "The University of Miami's exercise-physiology Fitness Laboratory in Coral Gables, open to the public as well as students and faculty, with transparent tiered pricing. It runs BOD POD body composition, VO2 max and resting-metabolic-rate testing rather than DEXA, making it the budget university-lab option for body-comp measurement.",
    highlights: ["University exercise-physiology lab open to the general public", "BOD POD body composition from $50 for non-members ($35 student-member)", "VO2 max and RMR testing also available with published price tiers", "Physician approval may be required based on health history"],
    bestFor: "Budget-minded body-comp testing via a university BOD POD lab",
    lastVerified: "2026-06-11",
  },
  {
    name: "Fitnescity",
    slug: "fitnescity-miami",
    city: "Miami",
    state: "Florida",
    stateSlug: "florida",
    citySlug: "miami",
    scanTypes: ["DEXA", "RMR", "VO2max"],
    priceRange: "$235-260/scan",
    membership: "Per-scan ($260) or 4-scan package ($235/scan); bundles available",
    byAppointment: true,
    mobile: false,
    website: "https://www.fitnescity.com/dexa-scan-body-composition-in-miami-fl",
    phone: "(888) 348-6372",
    description: "A national DEXA, VO2 max and RMR booking network that fulfills Miami scans through partner facilities in the Coral Gables area, with a physician order and a 1:1 MD results call included. As a chain aggregator it standardizes pricing and reporting across cities rather than running its own Miami storefront.",
    highlights: ["National DEXA / VO2 max / RMR network serving Miami via partner clinics", "Single DEXA $260; 4-scan package drops to $235/scan", "Physician order and 1:1 MD results review included", "Bundled DEXA + RMR + VO2 max testing available"],
    bestFor: "Cash-pay scans with a standardized report and MD review",
    lastVerified: "2026-06-11",
  },
];

export function getFloridaDexaClinicsByCity(citySlug: string): DexaClinic[] {
  return floridaDexaClinics.filter(c => c.citySlug === citySlug);
}

export function getFloridaDexaCitiesWithClinics(): { city: string; citySlug: string; count: number }[] {
  const map = new Map<string, { city: string; citySlug: string; count: number }>();
  for (const c of floridaDexaClinics) {
    const e = map.get(c.citySlug) || { city: c.city, citySlug: c.citySlug, count: 0 };
    e.count++; map.set(c.citySlug, e);
  }
  return Array.from(map.values());
}
