// Colorado WeightLoss Clinics
// Generated by seo-page-factory/convert.py — verified+enriched data only

import { WeightLossClinic } from '@/lib/weightloss-clinic-types';

export const coloradoWeightLossClinics: WeightLossClinic[] = [
  {
    name: "Aria Integrative Health",
    slug: "aria-integrative-health",
    address: "2500 18th St Suite B",
    city: "Denver",
    state: "Colorado",
    stateSlug: "colorado",
    citySlug: "denver",
    services: ["semaglutide", "glp1", "medical_supervision", "nutrition"],
    priceRange: "$300-600/month",
    website: "https://ariaintegrativehealth.com/services/medical-weight-loss-in-denver/",
    phone: "303-953-2899",
    description: "Aria Integrative Health runs a physician-guided semaglutide program out of its LoHi office on 18th Street, pairing weekly injections with holistic nutrition counseling and dose adjustments at regular check-ins. The clinic keeps extended hours including Saturdays and emphasizes individualized, sustainable plans over one-size-fits-all protocols.",
    highlights: ["Weekly in-person semaglutide injections", "Holistic nutrition counseling included", "Saturday and evening appointment hours"],
    bestFor: "Patients wanting closely supervised weekly semaglutide visits",
    telehealth: false,
    inPerson: true,
    medications: ["semaglutide"],
    lastVerified: "2026-06-11",
  },
  {
    name: "Vitalogy Health and Integrative Medicine",
    slug: "vitalogy-health-and-integrative-medicine",
    address: "90 Madison Street, Suite 101",
    city: "Denver",
    state: "Colorado",
    stateSlug: "colorado",
    citySlug: "denver",
    services: ["semaglutide", "tirzepatide", "phentermine", "glp1", "medical_supervision", "nutrition", "body_composition"],
    priceRange: "$300-600/month",
    website: "https://www.vitalogydenver.com/weight-loss/",
    phone: "720-805-1989",
    description: "Vitalogy is a Cherry Creek North integrative-medicine practice led by board-certified nurse practitioner Alison Brown, offering structured programs such as the 10-week Vitalogy 180 and the 90-day Program 90 built around semaglutide, tirzepatide, and phentermine. Its weight-loss visits combine prescription medication with body composition analysis, customized meal plans, and lipotropic and B12 injections.",
    highlights: ["Defined multi-week medical weight-loss programs", "Semaglutide, tirzepatide, and phentermine options", "Body composition analysis and meal planning"],
    bestFor: "Patients wanting a structured multi-week program with medication choice",
    rating: 4.4,
    reviewCount: 61,
    reviewSource: "Google",
    telehealth: true,
    inPerson: true,
    medications: ["semaglutide", "tirzepatide", "phentermine"],
    lastVerified: "2026-06-11",
  },
  {
    name: "Denver Regenerative Medicine",
    slug: "denver-regenerative-medicine",
    address: "455 Sherman Street, Suite 450",
    city: "Denver",
    state: "Colorado",
    stateSlug: "colorado",
    citySlug: "denver",
    services: ["semaglutide", "tirzepatide", "glp1", "medical_supervision", "body_composition"],
    priceRange: "$300-600/month",
    website: "https://denverregenerativemedicine.com/semaglutide/",
    phone: "720-583-1648",
    description: "Denver Regenerative Medicine offers physician-supervised semaglutide and tirzepatide programs from its Sherman Street office, with weekly monitoring during the first month and protocols the clinic describes as altitude-adjusted for Denver's mile-high elevation. The practice integrates GLP-1 weight management with body composition tracking and its broader regenerative and joint-support services.",
    highlights: ["Brand-name and compounded GLP-1 options", "Weekly monitoring in the first month", "Integrates with regenerative medicine services"],
    bestFor: "Patients wanting GLP-1 care alongside regenerative medicine",
    telehealth: false,
    inPerson: true,
    medications: ["semaglutide", "tirzepatide"],
    lastVerified: "2026-06-11",
  },
  {
    name: "Juicy Face Medical Esthetics",
    slug: "juicy-face-medical-esthetics",
    address: "3000 E 1st Ave Unit 114",
    city: "Denver",
    state: "Colorado",
    stateSlug: "colorado",
    citySlug: "denver",
    services: ["semaglutide", "tirzepatide", "glp1"],
    priceRange: "$300-600/month",
    website: "https://juicyfacemedspa.com/tirzepatide",
    description: "Juicy Face Medical Esthetics is a Cherry Creek medical spa run by nurse practitioner Purnima Balla that adds tirzepatide and semaglutide weight-loss injections to its injectable and skincare menu. Patients start with an in-person consultation and the clinic frames GLP-1 treatment as part of a broader weight-management plan rather than a standalone fix.",
    highlights: ["Tirzepatide and semaglutide injections", "NP-led personalized consultations", "Six-days-a-week appointment availability"],
    bestFor: "Med-spa clients adding GLP-1 weight-loss injections",
    telehealth: false,
    inPerson: true,
    medications: ["tirzepatide", "semaglutide"],
    lastVerified: "2026-06-11",
  },
  {
    name: "MedNOW Clinics",
    slug: "mednow-clinics",
    address: "1485 S Colorado Blvd, Suite 100",
    city: "Denver",
    state: "Colorado",
    stateSlug: "colorado",
    citySlug: "denver",
    services: ["semaglutide", "glp1", "medical_supervision"],
    priceRange: "$300-600/month",
    website: "https://www.mednowclinics.com/semaglutide-therapy",
    phone: "303-722-7222",
    description: "MedNOW Clinics is a Colorado clinic network offering semaglutide-based weight management across multiple Denver-area locations, with both in-person visits and telehealth options. Patients receive instruction on self-administering weekly subcutaneous injections as part of a physician-supervised GLP-1 program.",
    highlights: ["Multiple Denver-metro locations", "In-person and telehealth visits", "Physician-supervised weekly GLP-1 dosing"],
    bestFor: "Patients wanting a multi-location network with telehealth flexibility",
    telehealth: true,
    inPerson: true,
    medications: ["semaglutide"],
    lastVerified: "2026-06-11",
  },
];

export function getColoradoWeightLossClinicsByCity(citySlug: string): WeightLossClinic[] {
  return coloradoWeightLossClinics.filter(c => c.citySlug === citySlug);
}

export function getColoradoWeightLossCitiesWithClinics(): { city: string; citySlug: string; count: number }[] {
  const map = new Map<string, { city: string; citySlug: string; count: number }>();
  for (const c of coloradoWeightLossClinics) {
    const e = map.get(c.citySlug) || { city: c.city, citySlug: c.citySlug, count: 0 };
    e.count++; map.set(c.citySlug, e);
  }
  return Array.from(map.values());
}
